/-  GENERATED by scripts/split_statements.py from Workspace/Statements/S09.lean -- one numbered statement
    of the paper per module.  The theorem below, its doc-comment and its
    signature are byte-identical to the source module; only the surrounding
    file was mechanically re-cut.  See PROVING_PLAN.md.  -/
import Mathlib
import Workspace.Types.Core
import Workspace.Types.Tracks
import Workspace.Types.Appearances
import Workspace.Types.Overshadowed
import Workspace.Types.Knots
import Workspace.Types.BasicClasses
import Workspace.Types.Decompositions
import Workspace.ProofLemmas.Thm93Proof

/-!
# Section 9 — Double split graphs

The seven numbered statements 9.1–9.7 of Chudnovsky–Robertson–Seymour–Thomas,
*The Strong Perfect Graph Theorem* (published/Annals version, printed pages 47–56),
transcribed from `paper/pdf/S09_Double_split_graphs.md`.

All defined terms are imported and never restated: *knot*, *the knot induces `K`*, *local* and
*resolves* with respect to a knot, *strip*, *rung*, *antistrip*, *parallel*, *co-parallel*,
*twist*, *striation*, *`V(L)`*, *local* and *resolves* with respect to a striation, *maximal
striation* from `Workspace.Types.Knots`; *Berge*, *path*, *antipath*, *length*, *interior*,
*anticomplete*, *connected set* from `Workspace.Types.Core`; *appearance*, *(non)degenerate
appearance*, *`J`-enlargement*, *`J` appears in `G`*, *saturates `L(H)`*, *local with respect
to `L(H)`*, *attachments* from `Workspace.Types.Appearances`; *overshadowed appearance* from
`Workspace.Types.Overshadowed`; *double split graph* from `Workspace.Types.BasicClasses`;
*proper 2-join* and *balanced skew partition* from `Workspace.Types.Decompositions`.

Encoding conventions (see `paper/spec/CONVENTIONS.md`):

* paths and antipaths are the lists of their vertices in order, so `V(P)` is `{v | v ∈ P}`,
  and `P \ a` is `{v | v ∈ P} \ {a}`;
* `K₄` is `(⊤ : SimpleGraph (Fin 4))`, `K₃,₃` is `completeBipartiteGraph (Fin 3) (Fin 3)`, and
  the paper's `Ḡ` is `Gᶜ`;
* an *appearance* `L(H)` of `J` in `G` is the pair `(H, K)` of a bipartite subdivision `H` of
  `J` and the induced subgraph `G|K` that `L(H)` is isomorphic to, together (where a notion
  has to cross between the two sides) with the identification `φ : H.lineGraph ≃g G.induce K`;
* "there is a graph `X` such that …" is `∃ (n : ℕ) (X : SimpleGraph (Fin n)), …`.

**Naming the ends of a knot.**  `Knots.IsKnot` existentially quantifies the eight end labels
`a₁,b₁,a₂,b₂,x₁,y₁,x₂,y₂`, as the paper does (*"we can label the ends … such that"*).  Those
labels are nevertheless *uniquely determined* by the four lists, since `IsKnot` fixes them by
`IsPathFrom G P₁ a₁ b₁`, …, i.e. as the heads and last entries of the lists.  Statements 9.2
and 9.3, whose text refers to the labels, therefore name them by the extra hypotheses
`IsPathFrom G P₁ a₁ b₁` etc.; this is the paper's own *"Define `aᵢ, bᵢ, xᵢ, yᵢ` `(i = 1,2)` as
usual"* (the opening sentence of the proofs of 9.1 and 9.3) and adds no content.
-/

set_option autoImplicit false

namespace Workspace.Statements.S09

open Workspace.Types.Core Workspace.Types.Core.SPGT
open Workspace.Types.Tracks Workspace.Types.Tracks.SPGT
open Workspace.Types.Appearances Workspace.Types.Appearances.SPGT
open Workspace.Types.Overshadowed Workspace.Types.Overshadowed.SPGT
open Workspace.Types.Knots Workspace.Types.Knots.SPGT
open Workspace.Types.BasicClasses Workspace.Types.BasicClasses.SPGT
open Workspace.Types.Decompositions Workspace.Types.Decompositions.SPGT

namespace SPGT

variable {V : Type*} [Fintype V] [DecidableEq V]


/-- **9.3** (printed p. 48)

PAPER: *"Let `(P₁,P₂,Q₁,Q₂)` be a knot in a Berge graph `G`, inducing `K`.  Assume that there
is no appearance in `G` or in `Ḡ` of any `K₄`-enlargement, and there is no overshadowed
appearance of `K₄` in `G` or in `Ḡ`.  Let `F` be a connected subset of `V(G) \ V(K)`, such
that its set of attachments in `K` is not local.  Then either:*

*1. there is a vertex in `F` such that its neighbour set in `K` resolves the knot, or*

*2. (up to symmetry) there is a path `R` in `F` with ends `r₁,r₂` such that `r₁,a₁` have the
same neighbours in `V(P₂) ∪ V(Q₁) ∪ V(Q₂)`, and there are no edges between `R \ r₁` and
`V(P₂) ∪ V(Q₁) ∪ V(Q₂)`, and `r₂` has a neighbour in `P₁ \ a₁`, and there are no edges between
`R \ r₂` and `P₁ \ a₁`, or*

*3. (up to symmetry) there is an odd path `R` in `F` with ends `r₁,r₂` such that `r₁,a₁` have
the same neighbours in `V(P₂) ∪ V(Q₁) ∪ V(Q₂)`, and `r₂,b₁` have the same neighbours in
`V(P₂) ∪ V(Q₁) ∪ V(Q₂)`, and there are no edges between `V(R*)` and
`V(P₂) ∪ V(Q₁) ∪ V(Q₂)`, and no edges between `R` and `P₁` except possibly `r₁a₁` and `r₂b₁`,
or*

*4. there is a vertex `f ∈ F` such that (up to symmetry) `f,x₁` have the same neighbours in
`V(P₁) ∪ V(P₂) ∪ V(Q₂)` and `f` is not adjacent to `y₁`."*

The four outcomes are cited elsewhere as 9.3.1–9.3.4 (in the proofs of 9.4 and 9.5); they are
transcribed below in the printed order, as the four disjuncts of the conclusion.

**How "up to symmetry" is discharged.**  PAPER (printed p. 48): *"(The expression 'up to
symmetry' means here 'possibly after exchanging `P₁` and `P₂` and exchanging `Q₁` and `Q₂`,
and renaming the ends of `P₁,P₂,Q₁,Q₂` accordingly.')"*  Writing `V(K)` as the union of the
four vertex sets, the eight ends form an 8-cycle of adjacencies,
`a₁-x₁-a₂-y₂-b₁-y₁-b₂-x₂-a₁` (this is forced by the third and fourth bullets of the
definition of a knot), in which `{a₁,b₁}`, `{a₂,b₂}`, `{x₁,y₁}`, `{x₂,y₂}` are the four
antipodal pairs.  A relabelling of the kind the paper describes is exactly a symmetry of that
8-cycle preserving the path/antipath classes, and the group generated by the two exchanges is
the resulting dihedral group of order 8 (it contains, for instance, the relabelling that
reverses all four of `P₁,P₂,Q₁,Q₂` simultaneously, being the composite of the two exchanges
performed in the two possible orders).  Since each outcome mentions only some of the labels,
the orbit of each outcome under that group is small, and is written out below as an explicit
choice of the labels involved:

* outcome 2 uses one path `P` with a distinguished end `a` (`P'` being the other path, so
  that `V(P') ∪ V(Q₁) ∪ V(Q₂) = V(K) \ V(P)`), and the orbit is
  `(a,P,P') ∈ {(a₁,P₁,P₂), (b₁,P₁,P₂), (a₂,P₂,P₁), (b₂,P₂,P₁)}`;
* outcome 3 uses one path `P` with *both* its ends `a,b` (matched with `r₁,r₂`), and the orbit
  is `(a,b,P,P') ∈ {(a₁,b₁,P₁,P₂), (b₁,a₁,P₁,P₂), (a₂,b₂,P₂,P₁), (b₂,a₂,P₂,P₁)}`;
* outcome 4 uses one antipath with its two ends in a *fixed order* (`f` copies the
  neighbours of the first and is nonadjacent to the second), together with the other antipath
  `Q'`, and the orbit is
  `(x,y,Q') ∈ {(x₁,y₁,Q₂), (y₁,x₁,Q₂), (x₂,y₂,Q₁), (y₂,x₂,Q₁)}`.

Further notes on the transcription.

* *"There is a path `R` in `F`"*: `R` is a path of `G` (the paper's induced notion) all of
  whose vertices lie in `F`; *"odd path"* is `Odd (pathLength R)`; `V(R*)` is
  `Core.interior R`.
* *"`r₁,a₁` have the same neighbours in `W`"* is `∀ w ∈ W, (G.Adj r₁ w ↔ G.Adj a₁ w)`.
* *"There are no edges between `X` and `Y`"* is `Core.Anticomplete G X Y`; `R \ r₁` is
  `V(R) \ {r₁}` and `P₁ \ a₁` is `V(P₁) \ {a₁}`.
* *"No edges between `R` and `P₁` except possibly `r₁a₁` and `r₂b₁`"*: every edge of `G` with
  one end on `R` and the other on `P₁` is one of those two.
* *"Its set of attachments in `K` is not local"* uses `Appearances.attachments` and the §9
  notion `Knots.LocalForKnot` (`local` *with respect to the knot*), which is the notion in
  force throughout this statement. -/
theorem thm_9_3 (G : SimpleGraph V) (hG : Berge G)
    (P₁ P₂ Q₁ Q₂ : List V) (a₁ b₁ a₂ b₂ x₁ y₁ x₂ y₂ : V)
    (hknot : IsKnot G P₁ P₂ Q₁ Q₂)
    (hP₁ : IsPathFrom G P₁ a₁ b₁) (hP₂ : IsPathFrom G P₂ a₂ b₂)
    (hQ₁ : IsAntipathFrom G Q₁ x₁ y₁) (hQ₂ : IsAntipathFrom G Q₂ x₂ y₂)
    (K : Set V) (hK : KnotInduces P₁ P₂ Q₁ Q₂ K)
    (hnoenl : ¬ ∃ (m : ℕ) (J' : SimpleGraph (Fin m)),
      IsJEnlargement (⊤ : SimpleGraph (Fin 4)) J' ∧ (Appears G J' ∨ Appears Gᶜ J'))
    (hnoover : ¬ ∃ (n : ℕ) (H : SimpleGraph (Fin n)) (K' : Set V)
      (φ : H.lineGraph ≃g G.induce K'),
      IsAppearance G (⊤ : SimpleGraph (Fin 4)) H K' ∧ IsOvershadowedAppearance G H K' φ)
    (hnoovercompl : ¬ ∃ (n : ℕ) (H : SimpleGraph (Fin n)) (K' : Set V)
      (φ : H.lineGraph ≃g Gᶜ.induce K'),
      IsAppearance Gᶜ (⊤ : SimpleGraph (Fin 4)) H K' ∧ IsOvershadowedAppearance Gᶜ H K' φ)
    (F : Set V) (hFsub : F ⊆ Kᶜ) (hFconn : ConnectedSet G F)
    (hFattach : ¬ LocalForKnot G P₁ P₂ Q₁ Q₂ (attachments G F K)) :
    -- 9.3.1
    (∃ f ∈ F, ResolvesKnot G P₁ P₂ Q₁ Q₂ (G.neighborSet f ∩ K)) ∨
    -- 9.3.2
    (∃ (a : V) (P P' : List V),
      ((a, P, P') = (a₁, P₁, P₂) ∨ (a, P, P') = (b₁, P₁, P₂) ∨
        (a, P, P') = (a₂, P₂, P₁) ∨ (a, P, P') = (b₂, P₂, P₁)) ∧
      ∃ (R : List V) (r₁ r₂ : V),
        IsPathFrom G R r₁ r₂ ∧ (∀ v ∈ R, v ∈ F) ∧
        (∀ w ∈ ({v : V | v ∈ P'} ∪ {v : V | v ∈ Q₁} ∪ {v : V | v ∈ Q₂} : Set V),
          (G.Adj r₁ w ↔ G.Adj a w)) ∧
        Anticomplete G ({v : V | v ∈ R} \ {r₁})
          ({v : V | v ∈ P'} ∪ {v : V | v ∈ Q₁} ∪ {v : V | v ∈ Q₂}) ∧
        (∃ w ∈ ({v : V | v ∈ P} \ {a} : Set V), G.Adj r₂ w) ∧
        Anticomplete G ({v : V | v ∈ R} \ {r₂}) ({v : V | v ∈ P} \ {a})) ∨
    -- 9.3.3
    (∃ (a b : V) (P P' : List V),
      ((a, b, P, P') = (a₁, b₁, P₁, P₂) ∨ (a, b, P, P') = (b₁, a₁, P₁, P₂) ∨
        (a, b, P, P') = (a₂, b₂, P₂, P₁) ∨ (a, b, P, P') = (b₂, a₂, P₂, P₁)) ∧
      ∃ (R : List V) (r₁ r₂ : V),
        IsPathFrom G R r₁ r₂ ∧ (∀ v ∈ R, v ∈ F) ∧ Odd (pathLength R) ∧
        (∀ w ∈ ({v : V | v ∈ P'} ∪ {v : V | v ∈ Q₁} ∪ {v : V | v ∈ Q₂} : Set V),
          (G.Adj r₁ w ↔ G.Adj a w)) ∧
        (∀ w ∈ ({v : V | v ∈ P'} ∪ {v : V | v ∈ Q₁} ∪ {v : V | v ∈ Q₂} : Set V),
          (G.Adj r₂ w ↔ G.Adj b w)) ∧
        Anticomplete G {v : V | v ∈ SPGT.interior R}
          ({v : V | v ∈ P'} ∪ {v : V | v ∈ Q₁} ∪ {v : V | v ∈ Q₂}) ∧
        (∀ u ∈ R, ∀ w ∈ P, G.Adj u w → ((u = r₁ ∧ w = a) ∨ (u = r₂ ∧ w = b)))) ∨
    -- 9.3.4
    (∃ (x y : V) (Q' : List V),
      ((x, y, Q') = (x₁, y₁, Q₂) ∨ (x, y, Q') = (y₁, x₁, Q₂) ∨
        (x, y, Q') = (x₂, y₂, Q₁) ∨ (x, y, Q') = (y₂, x₂, Q₁)) ∧
      ∃ f ∈ F,
        (∀ w ∈ ({v : V | v ∈ P₁} ∪ {v : V | v ∈ P₂} ∪ {v : V | v ∈ Q'} : Set V),
          (G.Adj f w ↔ G.Adj x w)) ∧
        (∃ w, (w ∈ Q₁ ∨ w ∈ Q₂) ∧ w ∉ Q' ∧ w ≠ x ∧ ¬ G.Adj f w)) := by
  exact Workspace.ProofLemmas.Thm93Proof.thm_9_3_core G hG P₁ P₂ Q₁ Q₂
    a₁ b₁ a₂ b₂ x₁ y₁ x₂ y₂ hknot hP₁ hP₂ hQ₁ hQ₂ K hK hnoenl hnoover
    hnoovercompl F hFsub hFconn hFattach


end SPGT

end Workspace.Statements.S09
