/-  GENERATED by scripts/split_statements.py from Workspace/Statements/S07.lean -- one numbered statement
    of the paper per module.  The theorem below, its doc-comment and its
    signature are byte-identical to the source module; only the surrounding
    file was mechanically re-cut.  See PROVING_PLAN.md.  -/
import Mathlib
import Workspace.Types.Core
import Workspace.Types.Tracks
import Workspace.Types.Appearances
import Workspace.Types.Overshadowed
import Workspace.Types.Prisms
import Workspace.Types.Decompositions
import Workspace.ProofLemmas.Thm75Setup
import Workspace.ProofLemmas.Thm75Separation
import Workspace.ProofLemmas.Thm75DominantOfOvershadowed
import Workspace.ProofLemmas.Thm75DominantOutsideLineGraph
import Workspace.ProofLemmas.Thm75Claim2
import Workspace.ProofLemmas.Thm75Claim3Exact

/-!
# Section 7 — Rung replacement

The five numbered statements 7.1–7.5 of Chudnovsky–Robertson–Seymour–Thomas,
*The Strong Perfect Graph Theorem* (published/Annals version, printed pages 34–39),
transcribed from `paper/pdf/S07_Rung_replacement.md`.

All defined terms are imported and never restated: *track*, *`k`-connected* from
`Workspace.Types.Tracks`; *prism* / *form a prism* / *long* and the §10 notions
*saturates* and *major with respect to a prism* from `Workspace.Types.Prisms`;
*Berge*, *anticonnected*, *path*, *length*, *`Y`-complete* from `Workspace.Types.Core`;
*appearance*, *(non)degenerate appearance*, *`J`-enlargement* from
`Workspace.Types.Appearances`; *overshadowed appearance* from
`Workspace.Types.Overshadowed`; *balanced skew partition* from
`Workspace.Types.Decompositions`.

Encoding conventions (see `paper/spec/CONVENTIONS.md`):

* the paper's indices `1,2,3` are `0,1,2 : Fin 3`, so the triangles of a prism are
  `{a 0, a 1, a 2}` and `{b 0, b 1, b 2}` (this matches `Prisms.FormPrism`);
* a path (of the paper: an *induced* path) is the list of its vertices in order, and a
  track (a not-necessarily-induced path of a host graph) likewise;
* "a path in `G \ Y`" is a path of `G` none of whose vertices lies in `Y`.
-/

set_option autoImplicit false

namespace Workspace.Statements.S07

open Workspace.Types.Core Workspace.Types.Core.SPGT
open Workspace.Types.Tracks Workspace.Types.Tracks.SPGT
open Workspace.Types.Appearances Workspace.Types.Appearances.SPGT
open Workspace.Types.Overshadowed Workspace.Types.Overshadowed.SPGT
open Workspace.Types.Prisms Workspace.Types.Prisms.SPGT
open Workspace.Types.Decompositions Workspace.Types.Decompositions.SPGT

namespace SPGT

variable {V : Type*} [Fintype V] [DecidableEq V]


/-- **7.5** (printed p. 35)

PAPER: *"Let `G` be Berge, and let `L(H)` be an overshadowed appearance of `J` in `G`, where
`J` is 3-connected.  Then either:*

*• there is a `J`-enlargement with a nondegenerate appearance in `G`, or*

*• `G` admits a balanced skew partition."*

Notes on the transcription.

* An *appearance* `L(H)` of `J` in `G` is the pair `(H, K)` — a bipartite subdivision `H` of
  `J` and the induced subgraph `G|K` that `L(H)` is isomorphic to — together with the
  identification `φ : H.lineGraph ≃g G.induce K` (`Appearances.IsAppearance`); *overshadowed*
  is `Overshadowed.IsOvershadowedAppearance`, which needs the same `φ` because `δ_H(b)` is a
  set of vertices of `L(H)`.
* *"there is a `J`-enlargement with a nondegenerate appearance in `G`"*: some graph `J'` is a
  `J`-enlargement (`Appearances.IsJEnlargement`) and has an appearance in `G` that is
  nondegenerate.  Quantifying the enlargement and the subdivision witnessing its appearance
  over `SimpleGraph (Fin ·)` is this project's rendering of "there is a finite graph such
  that …".
* (The remark preceding 7.5 — *"We shall only need the following when `J = K₄` or `K₃,₃`, but
  we might as well prove it in general."* — is not part of the statement.) -/
theorem thm_7_5 {U W : Type*} [Fintype U] [Fintype W] (G : SimpleGraph V) (hG : Berge G)
    (J : SimpleGraph U) (hJ : IsKConnected J 3)
    (H : SimpleGraph W) (K : Set V) (φ : H.lineGraph ≃g G.induce K)
    (happ : IsAppearance G J H K)
    (hover : IsOvershadowedAppearance G H K φ) :
    (∃ (m : ℕ) (J' : SimpleGraph (Fin m)), IsJEnlargement J J' ∧
        ∃ (n : ℕ) (H' : SimpleGraph (Fin n)) (K' : Set V),
          IsAppearance G J' H' K' ∧ NondegenerateAppearance J' H') ∨
      AdmitsBalancedSkewPartition G := by
  classical
  by_contra hcon
  have hnoenl : ¬ (∃ (m : ℕ) (J' : SimpleGraph (Fin m)), IsJEnlargement J J' ∧
      ∃ (n : ℕ) (H' : SimpleGraph (Fin n)) (K' : Set V),
        IsAppearance G J' H' K' ∧ NondegenerateAppearance J' H') := fun h => hcon (Or.inl h)
  have hnobal : ¬ AdmitsBalancedSkewPartition G := fun h => hcon (Or.inr h)
  -- PAPER: *"There is an edge `c₁c₂` of `J` such that `Bc₁c₂` has odd length `≥ 3`, and some
  -- vertex of `G` is nonadjacent in `G` to at most one vertex of `Nc₁` and to at most one
  -- vertex of `Nc₂`.  We say such a vertex `v` is `Bc₁c₂`-dominant with respect to `L(H)`."*
  obtain ⟨B, c₁, c₂, hbranch, hfrom, hodd, hlen, v₀, hv₀₁, hv₀₂⟩ := hover
  set N₁ : Set V := Workspace.ProofLemmas.Thm75Setup.NSet G H K φ c₁ with hN₁
  set N₂ : Set V := Workspace.ProofLemmas.Thm75Setup.NSet G H K φ c₂ with hN₂
  have hdom₀ : Workspace.ProofLemmas.Thm75Setup.IsDominantFor G N₁ N₂ v₀ :=
    ⟨Workspace.ProofLemmas.Thm75DominantOfOvershadowed.thm75DominantOfOvershadowed
        G H K φ c₁ v₀ hv₀₁,
     Workspace.ProofLemmas.Thm75DominantOfOvershadowed.thm75DominantOfOvershadowed
        G H K φ c₂ v₀ hv₀₂⟩
  -- PAPER: *"Let `Y` be a maximal anticonnected set of vertices each with at most one
  -- non-neighbour in `Nc₁` and at most one non-neighbour in `Nc₂`."*
  obtain ⟨Y, hv₀Y, hYanti, hYdom, hYmax⟩ :=
    Workspace.ProofLemmas.Thm75Setup.exists_maximal_anticonnected (G := G)
      (fun v => Workspace.ProofLemmas.Thm75Setup.IsDominantFor G N₁ N₂ v) v₀ hdom₀
  have hYne : Y.Nonempty := ⟨v₀, hv₀Y⟩
  -- PAPER: *"Let `X` be the set of all `Y`-complete vertices in `G`."* and the sets
  -- `X₀, X₁, S, T` displayed on printed p. 36.
  set X : Set V := {x : V | VertexComplete G x Y} with hX
  set Rset : Set V := {x : V | ∃ (e : Sym2 W) (he : e ∈ H.edgeSet),
    e ∈ trackEdges B ∧ x = (↑(φ ⟨e, he⟩) : V)} with hRset
  set X₀ : Set V := X \ K with hX₀
  set X₁ : Set V := X ∩ (N₁ ∪ N₂) with hX₁
  set S : Set V := Rset \ X₁ with hS
  set T : Set V := (K \ Rset) \ X₁ with hT
  -- `V(Rc₁c₂) ⊆ V(L(H))`: the vertices of the rung are values of `φ`, hence lie in `K`.
  have hRK : Rset ⊆ K := by
    rintro x ⟨e, he, -, rfl⟩
    exact Subtype.coe_prop _
  -- No vertex of `L(H)` is `Bc₁c₂`-dominant, so `Y` is disjoint from `V(L(H))`.
  have hYK : ∀ y ∈ Y, y ∉ K := fun y hy =>
    Workspace.ProofLemmas.Thm75DominantOutsideLineGraph.thm75DominantOutsideLineGraph
      G J hJ H K φ happ B c₁ c₂ hbranch hfrom hlen y (hYdom y hy)
  -- `S` and `T` are disjoint from the cutset `X₀ ∪ X₁ ∪ Y`.
  have hSZ : ∀ x ∈ S, x ∉ (X₀ ∪ X₁ ∪ Y) := by
    rintro x ⟨hxR, hxX₁⟩ ((⟨-, hxK⟩ | hx₁) | hxY)
    · exact hxK (hRK hxR)
    · exact hxX₁ hx₁
    · exact hYK x hxY (hRK hxR)
  have hTZ : ∀ x ∈ T, x ∉ (X₀ ∪ X₁ ∪ Y) := by
    rintro x ⟨⟨hxK, -⟩, hxX₁⟩ ((⟨-, hxK'⟩ | hx₁) | hxY)
    · exact hxK' hxK
    · exact hxX₁ hx₁
    · exact hYK x hxY hxK
  have hSTdisj : Disjoint S T := by
    refine Set.disjoint_left.2 ?_
    rintro x ⟨hxR, -⟩ ⟨⟨-, hxR'⟩, -⟩
    exact hxR' hxR
  -- PAPER (claim (2)): under the standing assumption that the theorem fails, there is no
  -- connected `F` disjoint from `X₀ ∪ X₁ ∪ Y` with a neighbour of `S` and a neighbour of `T`.
  have hno : ∀ F : Set V, ConnectedSet G F → (∀ x ∈ F, x ∉ (X₀ ∪ X₁ ∪ Y)) →
      (∃ s ∈ S, ∃ f ∈ F, G.Adj s f) → (∃ t ∈ T, ∃ f ∈ F, G.Adj t f) → False := by
    intro F hFconn hFdisj hSF hTF
    exact hcon (Workspace.ProofLemmas.Thm75Claim2.thm75Claim2 G hG J hJ H K φ happ B c₁ c₂
      hbranch hfrom hodd hlen Y hYne hYanti hYdom hYmax X X₀ X₁ Rset S T hX hRset hX₀ hX₁ hS hT
      F hFconn hFdisj hSF hTF)
  -- PAPER: *"It follows from (2) that there is a partition of `V(G) \ (X₀ ∪ X₁ ∪ Y)` into two
  -- sets `L` and `M` say, where there is no edge between `L` and `M`, and `S ⊆ L` and
  -- `T ⊆ M`."*
  obtain ⟨L, M, hLM, hLMdisj, hLManti, hSL, hTM⟩ :=
    Workspace.ProofLemmas.Thm75Separation.thm75Separation G (X₀ ∪ X₁ ∪ Y) S T hSZ hTZ hSTdisj hno
  -- PAPER: the last two paragraphs — the skew partition, the 4.2 step, claim (3), the kernel
  -- `W = (Nc₁ \ {r₁}) ∪ (Nc₂ \ {r₂})`, and 4.6.
  exact hnobal (Workspace.ProofLemmas.Thm75Claim3Exact.thm75EndgameExact G hG J hJ H K φ happ B c₁ c₂
    hbranch hfrom hodd hlen Y hYne hYanti hYdom hYmax X X₀ X₁ Rset S T hX hRset hX₀ hX₁ hS hT
    L M hLM hLMdisj hLManti hSL hTM)


end SPGT

end Workspace.Statements.S07
