/-  GENERATED by scripts/split_statements.py from Workspace/Statements/S06.lean -- one numbered statement
    of the paper per module.  The theorem below, its doc-comment and its
    signature are byte-identical to the source module; only the surrounding
    file was mechanically re-cut.  See PROVING_PLAN.md.  -/
import Mathlib
import Workspace.Types.Core
import Workspace.Types.Tracks
import Workspace.Types.Appearances
import Workspace.Types.Overshadowed
import Workspace.Types.Decompositions
import Workspace.ProofLemmas.Thm61Conclusion
import Workspace.ProofLemmas.Thm61MinimalY
import Workspace.ProofLemmas.Thm61YIsAntipath
import Workspace.ProofLemmas.Thm61OddCase
import Workspace.ProofLemmas.Thm61EvenCase

/-!
# Section 6 — Major attachments to a line graph

Assembly of the printed proof of 6.1 (Chudnovsky–Robertson–Seymour–Thomas, *The Strong Perfect
Graph Theorem*, printed pp. 28–33) from its four pieces:

1. *"We may assume that `Y` is minimal such that it is anticonnected and its common neighbours
   do not saturate `L(H)`"* — `Thm61MinimalY.exists_minimal_anticonnected_nonsaturating`,
   legitimised by the monotonicity of the conclusion in `Y`
   (`Thm61Conclusion.Thm61Concl_mono`).
2. *"Consequently, `Y` is the vertex set of an antipath with ends `y₁, y₂`, say … so `y₁, y₂`
   are distinct"* — `Thm61YIsAntipath.minimal_Y_is_vertex_set_of_antipath`.
3. *"We recall that `Y` is the vertex set of an antipath between `y₁, y₂`; let `Q` be this
   antipath.  There are two cases, depending whether `Q` is odd or even."*
   * `Q` odd: claim (7), *"If `Q` is odd then the theorem holds"* —
     `Thm61OddCase.thm_6_1_odd_case`.
   * `Q` even: *"In view of (7) we may henceforth assume that `Q` is even"* and claims
     (8)–(13) — `Thm61EvenCase.thm_6_1_even_case`.
-/

set_option autoImplicit false

namespace Workspace.Statements.S06

open Workspace.Types.Core Workspace.Types.Core.SPGT
open Workspace.Types.Tracks Workspace.Types.Tracks.SPGT
open Workspace.Types.Appearances Workspace.Types.Appearances.SPGT
open Workspace.Types.Overshadowed Workspace.Types.Overshadowed.SPGT
open Workspace.Types.Decompositions Workspace.Types.Decompositions.SPGT

open Workspace.ProofLemmas.Thm61Conclusion
open Workspace.ProofLemmas.Thm61MinimalY
open Workspace.ProofLemmas.Thm61YIsAntipath
open Workspace.ProofLemmas.Thm61OddCase
open Workspace.ProofLemmas.Thm61EvenCase

namespace SPGT

variable {V : Type*} [Fintype V] [DecidableEq V]


/-- **6.1** (printed p. 28)

PAPER: *"Let `G` be Berge, let `L(H)` be an appearance in `G` of a 3-connected graph `J`, and
let `Y` be an anticonnected set of major vertices.  Assume that the set of all `Y`-complete
vertices in `L(H)` does not saturate `L(H)`.  Then either*

*• `J = K₃,₃` or `K₄`, and there is an overshadowed appearance of `J` in `G`, or*

*• `J = K₃,₃` or `K₄`, `L(H)` is degenerate, and there is an overshadowed appearance of `J` in
`Ḡ`, or*

*• `J = K₃,₃`, `L(H)` is degenerate, and there is a `J`-enlargement that appears in `Ḡ`, or*

*• `J = K₄` and `|V(H)| = 6`, or*

*• `J = K₄` and `L(H)` is degenerate, and there exist nonadjacent `y, y' ∈ Y` with the
following property.  Let the 4-cycle in `H` formed by the branch-vertices of `H` have edges
`a`-`b`-`c`-`d` in order.  Let `p` be the third edge of `H` such that `a, b, p` have a common
end, and similarly let `b, c, q` have a common end, and `c, d, r` and `d, a, s`.  Then (up to
symmetry) the neighbours of `y` in `L(H)` are `a, b, d, q, r` and possibly `c`, and the
neighbours of `y'` in `L(H)` are `b, c, d, p, s` and possibly `a`."*

Transcription notes.

* The appearance is given by the bipartite subdivision `H` of `J` (`hsub`), the vertex set `K`
  of the induced subgraph of `G`, and the isomorphism `φ : L(H) ≃g G|K`; together `hsub` and
  `φ` are `IsAppearance G J H K`.
* *"a set of major vertices"* is `∀ y ∈ Y, MajorForLineGraph G H K φ y`; that definition
  already contains `y ∉ K`, i.e. the paper's implicit `Y ⊆ V(G) \ V(L(H))`.
* The four vertices of the 4-cycle of bullet 5 are `v₁,v₂,v₃,v₄`; *"the 4-cycle in `H` formed
  by the branch-vertices of `H`"* is that they are distinct, are exactly the branch-vertices
  of `H`, and are cyclically adjacent.  Its edges *in order* are then
  `a = v₁v₂`, `b = v₂v₃`, `c = v₃v₄`, `d = v₄v₁`.
* *"the third edge of `H` such that `a, b, p` have a common end"*: `a` and `b` meet at `v₂`,
  and `p` is an edge incident with `v₂` other than `a` and `b`.  (`v₂` is a branch-vertex of a
  subdivision of `K₄`, hence has degree exactly `3`, which is what makes such a `p` unique;
  uniqueness is a consequence and is not asserted.)  Likewise `q` at `v₃`, `r` at `v₄` and `s`
  at `v₁`.
* *"the neighbours of `y` in `L(H)` are `a, b, d, q, r` and possibly `c`"* is the pair of
  inclusions `{a,b,d,q,r} ⊆ N(y) ∩ V(L(H)) ⊆ {a,b,c,d,q,r}`, with the neighbour set read back
  as a set of edges of `H`; likewise for `y'` with `{b,c,d,p,s}` and `{a,b,c,d,p,s}`.
* *"(up to symmetry)"* is absorbed by the existential quantifiers: the labelling `v₁,…,v₄` of
  the 4-cycle (hence of `a,b,c,d`) and the choice of which of the two vertices of `Y` is `y`
  are both existentially bound.
* The five alternatives appear in the order printed, with exactly the printed hypotheses on
  `J` and on degeneracy — in particular bullet 1 puts no degeneracy condition on `L(H)`,
  bullet 2 allows `J = K₃,₃` **or** `K₄`, and bullet 3 allows only `J = K₃,₃`. -/
theorem thm_6_1 (G : SimpleGraph V) (hG : Berge G)
    (m : ℕ) (J : SimpleGraph (Fin m)) (hJ : IsKConnected J 3)
    (n : ℕ) (H : SimpleGraph (Fin n)) (K : Set V)
    (hsub : IsBipartiteSubdivision J H)
    (φ : H.lineGraph ≃g G.induce K)
    (Y : Set V) (hYanti : AnticonnectedSet G Y)
    (hYmajor : ∀ y ∈ Y, MajorForLineGraph G H K φ y)
    (hnotsat : ¬ SaturatesLineGraph H
      {e : Sym2 (Fin n) | ∃ he : e ∈ H.edgeSet,
        VertexComplete G (↑(φ ⟨e, he⟩) : V) Y}) :
    ((Nonempty (J ≃g completeBipartiteGraph (Fin 3) (Fin 3)) ∨
        Nonempty (J ≃g (⊤ : SimpleGraph (Fin 4)))) ∧
      (∃ (n' : ℕ) (H' : SimpleGraph (Fin n')) (K' : Set V)
          (φ' : H'.lineGraph ≃g G.induce K'),
        IsAppearance G J H' K' ∧ IsOvershadowedAppearance G H' K' φ')) ∨
    ((Nonempty (J ≃g completeBipartiteGraph (Fin 3) (Fin 3)) ∨
        Nonempty (J ≃g (⊤ : SimpleGraph (Fin 4)))) ∧
      DegenerateAppearance J H ∧
      (∃ (n' : ℕ) (H' : SimpleGraph (Fin n')) (K' : Set V)
          (φ' : H'.lineGraph ≃g Gᶜ.induce K'),
        IsAppearance Gᶜ J H' K' ∧ IsOvershadowedAppearance Gᶜ H' K' φ')) ∨
    (Nonempty (J ≃g completeBipartiteGraph (Fin 3) (Fin 3)) ∧
      DegenerateAppearance J H ∧
      (∃ (m' : ℕ) (J' : SimpleGraph (Fin m')), IsJEnlargement J J' ∧ Appears Gᶜ J')) ∨
    (Nonempty (J ≃g (⊤ : SimpleGraph (Fin 4))) ∧ Fintype.card (Fin n) = 6) ∨
    (Nonempty (J ≃g (⊤ : SimpleGraph (Fin 4))) ∧ DegenerateAppearance J H ∧
      ∃ y ∈ Y, ∃ y' ∈ Y, ¬ G.Adj y y' ∧
        ∃ (v₁ v₂ v₃ v₄ : Fin n) (a b c d p q r s : Sym2 (Fin n)),
          [v₁, v₂, v₃, v₄].Nodup ∧
          branchVertices H = ({v₁, v₂, v₃, v₄} : Set (Fin n)) ∧
          H.Adj v₁ v₂ ∧ H.Adj v₂ v₃ ∧ H.Adj v₃ v₄ ∧ H.Adj v₄ v₁ ∧
          a = s(v₁, v₂) ∧ b = s(v₂, v₃) ∧ c = s(v₃, v₄) ∧ d = s(v₄, v₁) ∧
          p ∈ incidentEdges H v₂ ∧ p ≠ a ∧ p ≠ b ∧
          q ∈ incidentEdges H v₃ ∧ q ≠ b ∧ q ≠ c ∧
          r ∈ incidentEdges H v₄ ∧ r ≠ c ∧ r ≠ d ∧
          s ∈ incidentEdges H v₁ ∧ s ≠ d ∧ s ≠ a ∧
          ({a, b, d, q, r} : Set (Sym2 (Fin n))) ⊆
            {e : Sym2 (Fin n) | ∃ he : e ∈ H.edgeSet, G.Adj y (↑(φ ⟨e, he⟩) : V)} ∧
          {e : Sym2 (Fin n) | ∃ he : e ∈ H.edgeSet, G.Adj y (↑(φ ⟨e, he⟩) : V)} ⊆
            ({a, b, c, d, q, r} : Set (Sym2 (Fin n))) ∧
          ({b, c, d, p, s} : Set (Sym2 (Fin n))) ⊆
            {e : Sym2 (Fin n) | ∃ he : e ∈ H.edgeSet, G.Adj y' (↑(φ ⟨e, he⟩) : V)} ∧
          {e : Sym2 (Fin n) | ∃ he : e ∈ H.edgeSet, G.Adj y' (↑(φ ⟨e, he⟩) : V)} ⊆
            ({a, b, c, d, p, s} : Set (Sym2 (Fin n)))) := by
  -- *"We may assume that `Y` is minimal such that it is anticonnected and its common
  -- neighbours do not saturate `L(H)`."*
  obtain ⟨Y₀, hY₀sub, hY₀anti, hY₀notsat, hY₀min⟩ :=
    exists_minimal_anticonnected_nonsaturating G H K φ Y hYanti hnotsat
  have hY₀major : ∀ y ∈ Y₀, MajorForLineGraph G H K φ y := fun y hy => hYmajor y (hY₀sub hy)
  -- *"Consequently, `Y` is the vertex set of an antipath with ends `y₁, y₂`, say … so
  -- `y₁, y₂` are distinct."*
  obtain ⟨y₁, y₂, Q, hQ, hQY, hyne⟩ :=
    minimal_Y_is_vertex_set_of_antipath G H K φ Y₀ hY₀anti hY₀major hY₀notsat hY₀min
  -- *"There are two cases, depending whether `Q` is odd or even."*
  have hres : Thm61Concl G m J n H K φ Y₀ := by
    rcases Nat.even_or_odd (pathLength Q) with he | ho
    · exact thm_6_1_even_case G hG m J hJ n H K hsub φ Y₀ hY₀anti hY₀major hY₀notsat hY₀min
        y₁ y₂ Q hQ hQY hyne he
    · exact thm_6_1_odd_case G hG m J hJ n H K hsub φ Y₀ hY₀anti hY₀major hY₀notsat hY₀min
        y₁ y₂ Q hQ hQY hyne ho
  -- The conclusion is monotone in `Y`, so it transports from `Y₀` back to `Y`.
  exact Thm61Concl_mono G m J n H K φ Y₀ Y hY₀sub hres


end SPGT

end Workspace.Statements.S06
