/-  GENERATED by scripts/split_statements.py from Workspace/Statements/S13.lean -- one numbered statement
    of the paper per module.  The theorem below, its doc-comment and its
    signature are byte-identical to the source module; only the surrounding
    file was mechanically re-cut.  See PROVING_PLAN.md.  -/
import Mathlib
import Workspace.Types.Core
import Workspace.Types.Prisms
import Workspace.Types.Staircases
import Workspace.Types.LongOddPrism
import Workspace.Types.Classes
import Workspace.Types.Decompositions
import Workspace.Types.Appearances
import Workspace.Types.SkewTools
import Workspace.ProofLemmas.PathBasics
import Workspace.ProofLemmas.HoleBasics
import Workspace.ProofLemmas.ClassLemmas
import Workspace.ProofLemmas.Thm133Setup
import Workspace.ProofLemmas.Thm133Claim1
import Workspace.ProofLemmas.Thm133SkewSetup
import Workspace.ProofLemmas.Thm133EvenPath
import Workspace.ProofLemmas.Thm133EvenAntipath
import Workspace.Statements.S04.Thm_4_6

/-!
# Section 13 — The long odd prism

The seven numbered statements 13.1–13.7 of Chudnovsky–Robertson–Seymour–Thomas, *The Strong
Perfect Graph Theorem* (published/Annals version, printed pages 78–86), transcribed from
`paper/pdf/S13_The_long_odd_prism.md`.

Every defined term used here is imported and never restated:

* *right-sequence*, *earlier*, *predecessor*, *trajectory*, *birth*, *`b`-optimal banister*,
  *3-breaker* and *recalcitrant* come from `Workspace.Types.LongOddPrism`;
* *strongly maximal staircase*, *right-star*, *banister*, *1-breaker* and *2-breaker* from
  `Workspace.Types.Staircases`;
* *even prism*, *long prism*, *odd prism* from `Workspace.Types.Prisms`;
* *appearance* from `Workspace.Types.Appearances`;
* the class `F₅` from `Workspace.Types.Classes`;
* *proper 2-join*, *proper homogeneous pair*, *balanced skew partition* from
  `Workspace.Types.Decompositions`;
* *Berge*, *path*, *antipath*, *length*, *interior*, *`X`-complete*, *`X`-complete edge*,
  *complete to*, *anticonnected* from `Workspace.Types.Core`.

Encoding conventions (see `paper/spec/CONVENTIONS.md`):

* a path/antipath is the list of its vertices in order; `V(P)` for such a list `P` is
  `{v | v ∈ P}`, `P*` is `SPGT.interior P` and the length of `P` is `pathLength P`;
* a staircase `K = (S = (A, C, B), a₀`-`R₀`-`b₀)` is carried by the seven pieces of data
  `A C B : Set V`, `a₀ : V`, `R₀ : List V`, `b₀ : V`, and `V(K)` is `staircaseVertices`;
* the paper's right-sequence `x₁, …, x_t` is the list `x : List V`, and the set
  `X = {x₁, …, x_t}` is `{v | v ∈ x}`;
* *"there is no appearance of `K₄` in `G`"* is `¬ Appears G (⊤ : SimpleGraph (Fin 4))`;
* *"there is no even prism in `G`"* is: no three paths of `G` form an even prism;
* *"there is no 1-breaker in `G`"*, *"no 2-breaker"*, *"there is a 3-breaker"* existentially
  quantify the data carried by `IsOneBreaker`, `IsTwoBreaker`, `IsThreeBreaker`.

Published-vs-draft notes (see the transcription file for the full list):

* **13.4** is the *published* form: its 2-joins are **proper** 2-joins and its third outcome is
  *"`G` admits a **proper homogeneous pair**"* (the arXiv draft said *"an M-join"*).  Its
  hypothesis is transcribed literally — *"`G` is Berge, there is no appearance of `K₄` in
  either `G` or `Ḡ`, and `G` contains a long odd prism as an induced subgraph"* — and **not**
  as *"`G, Ḡ ∈ F₄`"*, which is how the statement 1.8.5 that 13.4 restates is phrased; the two
  agree only modulo the elsewhere-proved disposal of long *even* prisms.
* **13.6** carries the published hypothesis `X ⊆ V(G) \ V(P)` (the draft had `X ⊆ V(G)`).
-/

set_option autoImplicit false

namespace Workspace.Statements.S13

open Workspace.Types.Core Workspace.Types.Core.SPGT
open Workspace.Types.Prisms Workspace.Types.Prisms.SPGT
open Workspace.Types.Staircases Workspace.Types.Staircases.SPGT
open Workspace.Types.LongOddPrism Workspace.Types.LongOddPrism.SPGT
open Workspace.Types.Classes Workspace.Types.Classes.SPGT
open Workspace.Types.Decompositions Workspace.Types.Decompositions.SPGT
open Workspace.Types.Appearances Workspace.Types.Appearances.SPGT

namespace SPGT

variable {V : Type*} [Fintype V] [DecidableEq V]


/-- **13.3** (printed p. 83)

PAPER: *"Let `G` be Berge, containing no appearance of `K₄`, no even prism, no 1-breaker and
no 2-breaker.  Suppose that there is a 3-breaker in `G`; then `G` admits a balanced skew
partition."*

A 3-breaker is a pair `(K, x)` with `K = (S = (A, C, B), a₀`-`R₀`-`b₀)`, so *"there is a
3-breaker in `G`"* existentially quantifies the six pieces of staircase data together with the
vertex `x`. -/
theorem thm_13_3 (G : SimpleGraph V) (hG : Berge G)
    (hK4 : ¬ Appears G (⊤ : SimpleGraph (Fin 4)))
    (heven : ¬ ∃ (s t : Fin 3 → V) (R₁ R₂ R₃ : List V), IsEvenPrism G s t R₁ R₂ R₃)
    (h1br : ¬ ∃ A' C' B' F Q : Set V, IsOneBreaker G A' C' B' F Q)
    (h2br : ¬ ∃ (A' C' B' : Set V) (a' : V) (R' : List V) (b' : V) (Q : Set V),
      IsTwoBreaker G A' C' B' a' R' b' Q)
    (h3br : ∃ (A C B : Set V) (a₀ : V) (R₀ : List V) (b₀ x : V),
      IsThreeBreaker G A C B a₀ R₀ b₀ x) :
    AdmitsBalancedSkewPartition G := by
  classical
  obtain ⟨A, C, B, a₀, R₀, b₀, x₁, hbreaker⟩ := h3br
  have hsingle : IsRightSequence G A C B [x₁] := by
    refine ⟨⟨by simp, ?_⟩, ?_, ?_⟩
    · intro z hz
      have hzx : z = x₁ := by simpa using hz
      exact hzx ▸ hbreaker.2.2.1
    · intro i hi hcomp
      have hi0 : i = 0 := by simpa using hi
      subst i
      exact False.elim (hbreaker.2.2.2.1 (by simpa using hcomp))
    · intro i hi hanti
      have hi0 : i = 0 := by simpa using hi
      subst i
      exact False.elim (hbreaker.2.2.2.2 (by simpa using hanti))
  obtain ⟨x, hx, hxlen, hxmax⟩ :=
    Workspace.ProofLemmas.Thm133Setup.exists_max_rightSequence hsingle
  have hxne : x ≠ [] := by
    intro he
    rw [he] at hxlen
    simp at hxlen
  let c : Workspace.ProofLemmas.Thm133Setup.Ctx G A C B a₀ b₀ R₀ x :=
    { berge := hG
      noK4 := hK4
      noPrism := heven
      no1br := h1br
      no2br := h2br
      strongMax := hbreaker.1
      rseq := hx
      maximal := hxmax
      nonempty := hxne }
  by_cases hno : ¬ AdmitsBalancedSkewPartition G
  · have hclaim : ∀ (u : V) (P : List V), u ∈ A ∪ C → IsPathFrom G P u b₀ →
        ∃ w ∈ SPGT.interior P,
          w ∈ Workspace.ProofLemmas.Thm133Setup.Ws G A C B x := by
      intro u P hu hP
      exact Workspace.ProofLemmas.Thm133Claim1.thm133_claim1 c hu hP
    obtain ⟨A₁, hskewc, hkernel, hA₁, hA₁sub⟩ :=
      Workspace.ProofLemmas.Thm133SkewSetup.thm133_skew_setup c hclaim
    have hskew : IsSkewPartition G
        (Workspace.ProofLemmas.Thm133Setup.Ws G A C B x)ᶜ
        (Workspace.ProofLemmas.Thm133Setup.Ws G A C B x) :=
      Workspace.ProofLemmas.ClassLemmas.isSkewPartition_compl.mp hskewc
    have hcompResult : AdmitsBalancedSkewPartition Gᶜ :=
      _root_.Workspace.Statements.S04.SPGT.thm_4_6 Gᶜ
        (Workspace.ProofLemmas.HoleBasics.berge_compl.mpr hG)
        (Workspace.ProofLemmas.Thm133Setup.Ws G A C B x)
        (Workspace.ProofLemmas.Thm133Setup.Ws G A C B x)ᶜ (A ∪ C) A₁
        hskewc hkernel hA₁
        (by
          intro u hu v hv huv _ _
          by_cases huvEq : u = v
          · subst v
            refine ⟨[u], ⟨Workspace.ProofLemmas.PathBasics.isPathList_singleton Gᶜ u,
              by simp, by simp⟩,
              ?_, ⟨0, by rfl⟩⟩
            simp [SPGT.interior]
          · have huvG : G.Adj u v := by
              by_contra hn
              exact huv ((G.compl_adj u v).mpr ⟨huvEq, hn⟩)
            obtain ⟨q, hq, hqint, hqeven⟩ :=
              Workspace.ProofLemmas.Thm133EvenAntipath.thm133_even_antipath
                c hskew hno hu hv huvG
            exact ⟨q, hq, hqint, hqeven⟩)
        (by
          intro u hu v hv huv _ _
          have hu' : u ∈ Workspace.ProofLemmas.Thm133Setup.Ys G A C B x ∪ B :=
            hA₁sub hu
          have hv' : v ∈ Workspace.ProofLemmas.Thm133Setup.Ys G A C B x ∪ B :=
            hA₁sub hv
          obtain ⟨p, hp, hpint, hpeven⟩ :=
            Workspace.ProofLemmas.Thm133EvenPath.thm133_even_path c hu' hv' huv.2 huv.1
          refine ⟨p, ?_, ?_, hpeven⟩
          · change IsPathFrom (Gᶜ)ᶜ p u v
            simpa only [compl_compl] using hp
          · intro z hz
            exact c.AC_disjoint_W z (hpint z hz))
    exact Workspace.ProofLemmas.ClassLemmas.admitsBalancedSkewPartition_compl.mp hcompResult
  · exact Classical.byContradiction hno


end SPGT

end Workspace.Statements.S13
