/-  GENERATED by scripts/split_statements.py from Workspace/Statements/S13.lean -- one numbered statement
    of the paper per module.  The theorem below, its doc-comment and its
    signature are byte-identical to the source module; only the surrounding
    file was mechanically re-cut.  See PROVING_PLAN.md.  -/
import Mathlib
import Workspace.Types.Core
import Workspace.Types.Prisms
import Workspace.Types.Staircases
import Workspace.Types.LongOddPrism
import Workspace.Types.Classes
import Workspace.Types.Decompositions
import Workspace.Types.Appearances
import Workspace.ProofLemmas.Thm131LastMiss
import Workspace.ProofLemmas.Thm131SingletonEdge

/-!
# Section 13 — The long odd prism

The seven numbered statements 13.1–13.7 of Chudnovsky–Robertson–Seymour–Thomas, *The Strong
Perfect Graph Theorem* (published/Annals version, printed pages 78–86), transcribed from
`paper/pdf/S13_The_long_odd_prism.md`.

Every defined term used here is imported and never restated:

* *right-sequence*, *earlier*, *predecessor*, *trajectory*, *birth*, *`b`-optimal banister*,
  *3-breaker* and *recalcitrant* come from `Workspace.Types.LongOddPrism`;
* *strongly maximal staircase*, *right-star*, *banister*, *1-breaker* and *2-breaker* from
  `Workspace.Types.Staircases`;
* *even prism*, *long prism*, *odd prism* from `Workspace.Types.Prisms`;
* *appearance* from `Workspace.Types.Appearances`;
* the class `F₅` from `Workspace.Types.Classes`;
* *proper 2-join*, *proper homogeneous pair*, *balanced skew partition* from
  `Workspace.Types.Decompositions`;
* *Berge*, *path*, *antipath*, *length*, *interior*, *`X`-complete*, *`X`-complete edge*,
  *complete to*, *anticonnected* from `Workspace.Types.Core`.

Encoding conventions (see `paper/spec/CONVENTIONS.md`):

* a path/antipath is the list of its vertices in order; `V(P)` for such a list `P` is
  `{v | v ∈ P}`, `P*` is `SPGT.interior P` and the length of `P` is `pathLength P`;
* a staircase `K = (S = (A, C, B), a₀`-`R₀`-`b₀)` is carried by the seven pieces of data
  `A C B : Set V`, `a₀ : V`, `R₀ : List V`, `b₀ : V`, and `V(K)` is `staircaseVertices`;
* the paper's right-sequence `x₁, …, x_t` is the list `x : List V`, and the set
  `X = {x₁, …, x_t}` is `{v | v ∈ x}`;
* *"there is no appearance of `K₄` in `G`"* is `¬ Appears G (⊤ : SimpleGraph (Fin 4))`;
* *"there is no even prism in `G`"* is: no three paths of `G` form an even prism;
* *"there is no 1-breaker in `G`"*, *"no 2-breaker"*, *"there is a 3-breaker"* existentially
  quantify the data carried by `IsOneBreaker`, `IsTwoBreaker`, `IsThreeBreaker`.

Published-vs-draft notes (see the transcription file for the full list):

* **13.4** is the *published* form: its 2-joins are **proper** 2-joins and its third outcome is
  *"`G` admits a **proper homogeneous pair**"* (the arXiv draft said *"an M-join"*).  Its
  hypothesis is transcribed literally — *"`G` is Berge, there is no appearance of `K₄` in
  either `G` or `Ḡ`, and `G` contains a long odd prism as an induced subgraph"* — and **not**
  as *"`G, Ḡ ∈ F₄`"*, which is how the statement 1.8.5 that 13.4 restates is phrased; the two
  agree only modulo the elsewhere-proved disposal of long *even* prisms.
* **13.6** carries the published hypothesis `X ⊆ V(G) \ V(P)` (the draft had `X ⊆ V(G)`).
-/

set_option autoImplicit false

namespace Workspace.Statements.S13

open Workspace.Types.Core Workspace.Types.Core.SPGT
open Workspace.Types.Prisms Workspace.Types.Prisms.SPGT
open Workspace.Types.Staircases Workspace.Types.Staircases.SPGT
open Workspace.Types.LongOddPrism Workspace.Types.LongOddPrism.SPGT
open Workspace.Types.Classes Workspace.Types.Classes.SPGT
open Workspace.Types.Decompositions Workspace.Types.Decompositions.SPGT
open Workspace.Types.Appearances Workspace.Types.Appearances.SPGT
open Workspace.ProofLemmas.Thm131Trajectory
open Workspace.ProofLemmas.Thm131OptimalLength
open Workspace.ProofLemmas.Thm131EdgeCases
open Workspace.ProofLemmas.Thm131LastMiss
open Workspace.ProofLemmas.Thm131SingletonEdge
open Workspace.ProofLemmas.Thm132Infrastructure

namespace SPGT

variable {V : Type*} [Fintype V] [DecidableEq V]


/-- **13.1** (printed pp. 79–80)

PAPER: *"Let `G` be Berge, containing no appearance of `K₄`, no even prism, no 1-breaker and
no 2-breaker.  Let `K = (S = (A, C, B), a₀`-`R₀`-`b₀)` be a strongly maximal staircase in `G`,
and let `x₁, …, x_t` be a right-sequence.  Let `b` be a right-star, and let `a`-`R`-`b` be a
`b`-optimal banister.  Let `a`-`w₁`-`⋯`-`w_n` be the trajectory of `a`.  Then `n` is odd, and
either:*

*• `b` is the unique vertex of `R` which is `{w₁, …, w_n}`-complete, or*

*• `R` has length 1, and there exists some even `m` with `1 ≤ m < n` such that
`a`-`w₁`-`⋯`-`w_m`-`b` is an antipath."*

Notes on the transcription.

* *"the trajectory of `a`"* is the second of the section's two `trajectory` notions (the one
  for a general vertex, printed p. 79), which produces the antipath `a`-`w₁`-`⋯`-`w_n`
  **including** its first vertex `a`; so the trajectory is the list `a :: w` with
  `w = [w₁, …, w_n]`, and the paper's `n` is `w.length`.
* `{w₁, …, w_n}` is `{u | u ∈ w}`, and *"`b` is the unique vertex of `R` which is
  `{w₁, …, w_n}`-complete"* is: a vertex of `R` is `{w₁, …, w_n}`-complete exactly when it is
  `b` (`b` is a vertex of `R`, being one of its ends).
* `a`-`w₁`-`⋯`-`w_m`-`b` is the list `a :: (w.take m ++ [b])`, since `w.take m` is
  `[w₁, …, w_m]`. -/
theorem thm_13_1 (G : SimpleGraph V) (hG : Berge G)
    (hK4 : ¬ Appears G (⊤ : SimpleGraph (Fin 4)))
    (heven : ¬ ∃ (s t : Fin 3 → V) (R₁ R₂ R₃ : List V), IsEvenPrism G s t R₁ R₂ R₃)
    (h1br : ¬ ∃ A' C' B' F Q : Set V, IsOneBreaker G A' C' B' F Q)
    (h2br : ¬ ∃ (A' C' B' : Set V) (a' : V) (R' : List V) (b' : V) (Q : Set V),
      IsTwoBreaker G A' C' B' a' R' b' Q)
    (A C B : Set V) (a₀ b₀ : V) (R₀ : List V)
    (hK : StronglyMaximalStaircase G A C B a₀ R₀ b₀)
    (x : List V) (hx : IsRightSequence G A C B x)
    (b : V) (hb : IsRightStar G A C B b)
    (a : V) (R : List V) (hopt : BOptimalBanister G A C B x a R b)
    (w : List V) (htraj : trajectoryOfVertex G A x a (a :: w)) :
    Odd w.length ∧
      ((∀ r ∈ R, (VertexComplete G r {u : V | u ∈ w} ↔ r = b)) ∨
        (pathLength R = 1 ∧
          ∃ m : ℕ, Even m ∧ 1 ≤ m ∧ m < w.length ∧
            IsAntipathList G (a :: (w.take m ++ [b])))) := by
  classical
  have claim : ∀ n : ℕ, ∀ (y : List V), y.length = n →
      IsRightSequence G A C B y →
      ∀ (d : V), IsRightStar G A C B d →
      ∀ (c : V) (P : List V), BOptimalBanister G A C B y c P d →
      ∀ (z : List V), trajectoryOfVertex G A y c (c :: z) →
        TrajectoryConclusion G c P d z := by
    intro n
    induction n using Nat.strong_induction_on with
    | h n ih =>
      intro y hylen hy d hd c P hP z hz
      have hS : StepConnected G A C B := hK.1.1.1
      have hIH : ∀ (q : List V), q.length < y.length →
          IsRightSequence G A C B q →
          ∀ (d' : V), IsRightStar G A C B d' →
          ∀ (c' : V) (Q : List V), BOptimalBanister G A C B q c' Q d' →
          ∀ (z' : List V), trajectoryOfVertex G A q c' (c' :: z') →
            TrajectoryConclusion G c' Q d' z' := by
        intro q hq hqseq d' hd' c' Q hQ z' hz'
        exact ih q.length (by omega) q rfl hqseq d' hd' c' Q hQ z' hz'
      have hodd : Odd z.length := trajectory_tail_odd hG hS hy hP.1.2.2.1 hz
      have hPone : pathLength P = 1 :=
        optimal_banister_length_one hG hK4 heven h1br h2br hK hy hIH hP
      have hPeq : P = [c, d] := path_eq_pair_of_length_one hP.1.1 hPone
      have hcd : G.Adj c d :=
        Workspace.ProofLemmas.PathBasics.isPathFrom_ends_adj_of_length_one hP.1.1 hPone
      obtain ⟨i, hi, j, hj, hcbirth, hantiData, hidx⟩ :=
        trajectoryOfVertex_data hS hy hP.1.2.2.1 hz
      let last : V := y[j]
      have hanti : IsAntipathFrom G (c :: z) c last := by
        simpa [last] using hantiData
      have hbeforeA : ∀ u ∈ z, u ≠ last → VertexComplete G u A :=
        trajectory_before_last_left_complete hz hanti
      have hzB : ∀ u ∈ z, VertexComplete G u B :=
        trajectory_tail_right_complete hS hy hP.1.2.2.1 hz hanti
      have hdnotz : d ∉ z := optimal_right_end_not_mem_trajectory hS hy hd hP hz
      have hzpos : 0 < z.length := by
        obtain ⟨k, hk⟩ := hodd
        omega
      have hz0 : z[0]'hzpos ∈ z := List.getElem_mem hzpos
      have hcNotComplete : ¬ VertexComplete G c {u : V | u ∈ z} := by
        intro hccomp
        have hadjC : Gᶜ.Adj c z[0] := by
          have hp := Workspace.ProofLemmas.PathBasics.path_adj_succ hanti.1 (i := 0)
            (by simp; omega)
          simpa using hp
        exact hadjC.2 (hccomp z[0] hz0)

      refine ⟨hodd, ?_⟩
      by_cases hdcomp : VertexComplete G d {u : V | u ∈ z}
      · left
        intro r hr
        rw [hPeq] at hr
        simp at hr
        rcases hr with hrc | hrd
        · subst r
          exact iff_of_false hcNotComplete hcd.ne
        · subst r
          exact iff_of_true hdcomp rfl
      · have hex : ∃ k : ℕ, ∃ hk : k < z.length, ¬ G.Adj d z[k] := by
          rw [VertexComplete] at hdcomp
          push Not at hdcomp
          obtain ⟨u, huz, hdu⟩ := hdcomp
          obtain ⟨k, hk, hku⟩ := List.mem_iff_getElem.mp huz
          exact ⟨k, hk, by simpa [hku] using hdu⟩
        let k : ℕ := Nat.find hex
        obtain ⟨hk, hdk⟩ := Nat.find_spec hex
        have hdprev : ∀ (ell : ℕ) (hell : ell < k),
            G.Adj d (z[ell]'(by omega)) := by
          intro ell hell
          by_contra hn
          exact Nat.find_min hex hell ⟨by omega, hn⟩
        by_cases hkearly : k + 1 < z.length
        · right
          obtain ⟨hkeven, hantiPrefix⟩ := early_miss_gives_second_outcome
            hG hS hP.1.2.2.1 hd hcd hanti hbeforeA hzB hdnotz
            k hk hdk hdprev hkearly
          exact ⟨hPone, k + 1, hkeven, by omega, hkearly, hantiPrefix⟩
        · have hklast : k = z.length - 1 := by omega
          have hlastZ : z.getLast? = some last := by
            have hz_ne : z ≠ [] := List.ne_nil_of_length_pos hzpos
            simpa [List.getLast?_cons_of_ne_nil hz_ne] using hanti.2.2
          have hzlastElem : z[z.length - 1]'(by omega) = last :=
            Workspace.ProofLemmas.PathBasics.getElem_last_of_getLast? hlastZ hzpos
          have hzklast : z[k]'hk = last := by
            have hidxeq : z[k]'hk = z[z.length - 1]'(by omega) :=
              getElem_congr rfl hklast hk
            exact hidxeq.trans hzlastElem
          have hdmissLast : ¬ G.Adj d last := by
            intro hdlast
            exact hdk (hzklast.symm ▸ hdlast)
          have hdBefore : ∀ u ∈ z, u ≠ last → G.Adj d u := by
            intro u huz hulast
            obtain ⟨ell, hell, hellu⟩ := List.mem_iff_getElem.mp huz
            have hellk : ell < k := by
              have hellle : ell ≤ k := by omega
              rcases lt_or_eq_of_le hellle with hlt | heq
              · exact hlt
              · subst ell
                exact absurd (hellu.symm.trans hzklast) hulast
            simpa [hellu] using hdprev ell hellk
          obtain ⟨aMiss, haMissA, hlastMiss⟩ :=
            trajectory_last_misses_left hz hanti
          have hlastAntiA : VertexAnticomplete G last A := by
            intro u huA
            by_contra hlu
            exact terminal_miss_neighbor_absurd hG hS hP.1.2.2.1 hd hcd
              hanti hodd hbeforeA hzB hdnotz hdBefore hdmissLast
              huA (by simpa using hlu) haMissA hlastMiss
          have hlastB : VertexComplete G last B := hzB last
            (Workspace.ProofLemmas.PathBasics.getLast_mem hlastZ)
          have hlastStar : IsRightStar G A C B last := by
            by_cases heq : last = b₀
            · simpa [heq] using hK.1.1.2.1.2.2.2.1
            · have hout : last ∉ staircaseVertices A C B R₀ :=
                bComplete_not_mem_staircase hK.1.1 hlastB heq
              rcases bComplete_rightStar_or_major hG hK4 heven h1br hK.1 hout hlastB with
                hs | hm
              · exact hs
              · obtain ⟨u, huA, hlu⟩ := hm.2.1
                exact absurd hlu (hlastAntiA u huA)
          by_cases hzone : z.length = 1
          · exact False.elim (singleton_edge_terminal_miss_absurd
              hG hK4 heven h1br h2br hK hy hd hlastStar hP hz hIH
              hPone hanti hzone hdnotz hdmissLast)
          · have hzlong : 1 < z.length := by
              obtain ⟨ko, hko⟩ := hodd
              omega
            exact False.elim (terminal_miss_absurd hG hK4 heven h1br h2br hK hy
              hd hP hz hIH hPone hanti hodd hzlong hbeforeA hzB hdnotz
              hdBefore hdmissLast hlastStar)
  exact claim x.length x rfl hx b hb a R hopt w htraj


end SPGT

end Workspace.Statements.S13
