/-  GENERATED by scripts/split_statements.py from Workspace/Statements/S08.lean -- one numbered statement
    of the paper per module.  The theorem below, its doc-comment and its
    signature are byte-identical to the source module; only the surrounding
    file was mechanically re-cut.  See PROVING_PLAN.md.  -/
import Mathlib
import Workspace.Types.Core
import Workspace.Types.Tracks
import Workspace.Types.Appearances
import Workspace.Types.StripSystems
import Workspace.Types.Overshadowed
import Workspace.Types.Decompositions
import Workspace.Statements.S08.Thm_8_2
import Workspace.ProofLemmas.Thm83MixedRungs

/-!
# Section 8 — Generalized line graphs

The six numbered statements 8.1–8.6 of Chudnovsky–Robertson–Seymour–Thomas,
*The Strong Perfect Graph Theorem* (published/Annals version, printed pages 39–47),
transcribed from `paper/pdf/S08_Generalized_line_graphs.md`.

All defined terms are imported and never restated: *`J`-strip system*, *`uv`-rung*,
*a choice of rungs forms `L(H)`*, *nondegenerate strip system*, *`V(S,N)`*, *saturates the
strip system*, *major* and *local* with respect to the strip system, *maximal strip system*
from `Workspace.Types.StripSystems`; *Berge*, *path*, *length*, *connected set* from
`Workspace.Types.Core`; *`k`-connected* from `Workspace.Types.Tracks`; *appearance*,
*(non)degenerate appearance*, *`J`-enlargement*, *saturates `L(H)`*, *attachments* from
`Workspace.Types.Appearances`; *overshadowed appearance* from `Workspace.Types.Overshadowed`;
*proper 2-join* and *balanced skew partition* from `Workspace.Types.Decompositions`.

Encoding conventions (see `paper/spec/CONVENTIONS.md`):

* an *appearance* `L(H)` of `J` in `G` is the pair `(H, K)` of a bipartite subdivision `H` of
  `J` and the induced subgraph `G|K` that `L(H)` is isomorphic to; the notions that have to
  cross between the two sides (`saturates L(H)`, *overshadowed*) additionally take the
  identification `φ : H.lineGraph ≃g G.induce K`, which is the paper's silent "equality
  convention" of printed p. 20 made explicit;
* "there is a graph `X` such that …" is `∃ (n : ℕ) (X : SimpleGraph (Fin n)), …`;
* `K₄` is `(⊤ : SimpleGraph (Fin 4))`, `K₃,₃` is `completeBipartiteGraph (Fin 3) (Fin 3)`, and
  "`J = K₄`" is `Nonempty (J ≃g (⊤ : SimpleGraph (Fin 4)))`;
* the paper's `Ḡ` is `Gᶜ`.

Statement 8.6 is the restatement of 5.4 (*"We are now ready to prove 5.4, which we restate:"*),
and is transcribed here in exactly the same form as `Workspace.Statements.S05.SPGT.thm_5_4`.
-/

set_option autoImplicit false

namespace Workspace.Statements.S08

open Workspace.Types.Core Workspace.Types.Core.SPGT
open Workspace.Types.Tracks Workspace.Types.Tracks.SPGT
open Workspace.Types.Appearances Workspace.Types.Appearances.SPGT
open Workspace.Types.StripSystems Workspace.Types.StripSystems.SPGT
open Workspace.Types.Overshadowed Workspace.Types.Overshadowed.SPGT
open Workspace.Types.Decompositions Workspace.Types.Decompositions.SPGT

namespace SPGT

variable {V : Type*} [Fintype V] [DecidableEq V]


/-- **8.3** (printed p. 40)

PAPER: *"Let `(S,N)` be a nondegenerate `J`-strip system in a Berge graph `G`, where `J` is
3-connected.  If there is no overshadowed appearance of `J` in `G`, then for every choice of
rungs, the line graph they form is a nondegenerate appearance of `J` in `G`."*

Notes on the transcription.

* *"Nondegenerate `J`-strip system"* is `StripSystems.NondegenerateStripSystem` (printed
  p. 40: *"A `J`-strip system is nondegenerate if there is some choice of rungs such that the
  line graph `L(H)` they form is a nondegenerate appearance of `J`"*).
* *"For every choice of rungs, the line graph they form is a nondegenerate appearance of `J`
  in `G`"*: `StripSystems.FormsLineGraph G J S N R H` says that the family `R` is a choice of
  rungs whose union induces an appearance of `J` in `G` via the subdivision `H`; so the
  conclusion is that every such `H` is nondegenerate.  That the formed line graph *exists*
  for every choice of rungs is the paper's remark immediately after the proof of 8.1
  (*"It follows from 8.1 and the final axiom above that the subgraph of `G` induced on the
  union of the vertex sets of these rungs is a line graph of a bipartite subdivision `H` of
  `J`"*), not part of 8.3, and so is not asserted here. -/
theorem thm_8_3 {U : Type*} [Fintype U] (G : SimpleGraph V) (hG : Berge G)
    (J : SimpleGraph U) (hJ : IsKConnected J 3)
    (S : U → U → Set V) (N : U → Set V) (hSN : IsJStripSystem G J S N)
    (hnd : NondegenerateStripSystem G J S N)
    (hnoover : ¬ ∃ (n : ℕ) (H : SimpleGraph (Fin n)) (K' : Set V)
        (φ : H.lineGraph ≃g G.induce K'),
        IsAppearance G J H K' ∧ IsOvershadowedAppearance G H K' φ) :
    ∀ (n : ℕ) (H : SimpleGraph (Fin n)) (R : U → U → List V),
      FormsLineGraph G J S N R H → NondegenerateAppearance J H := by
  -- PAPER: *"Take a choice of rungs `R_ij` (`ij ∈ E(J)`), forming `L(H)` say, where `L(H)` is
  -- nondegenerate"* — this is exactly the hypothesis that the strip system is nondegenerate.
  obtain ⟨n₀, H₀, R₀, hForms₀, hnd₀⟩ := hnd
  -- PAPER: *"and suppose there is another choice, `R'_ij` (`ij ∈ E(J)`), forming `L(H')` say,
  -- where `L(H')` is degenerate."*
  intro n H R hForms hdeg
  -- PAPER: *"Then for some `ij ∈ E(J)`, `R_ij` has nonzero length and `R'_ij` has length 0."*
  obtain ⟨u, v, huv, hzero, hpos⟩ :=
    Workspace.ProofLemmas.Thm83MixedRungs.thm83MixedRungs G J hJ S N hSN
      hForms₀ hnd₀ hForms hdeg
  -- PAPER: *"By 8.2 there is an overshadowed appearance of `J` in `G`."* — contrary to the
  -- hypothesis.  This proves 8.3.
  exact hnoover
    (thm_8_2 G hG J hJ S N hSN
      ⟨u, v, huv, R u v, R₀ u v, hForms.1 u v huv, hzero, hForms₀.1 u v huv, hpos⟩)


end SPGT

end Workspace.Statements.S08
