/-  GENERATED by scripts/split_statements.py from Workspace/Statements/S16.lean -- one numbered statement
    of the paper per module.  The theorem below, its doc-comment and its
    signature are byte-identical to the source module; only the surrounding
    file was mechanically re-cut.  See PROVING_PLAN.md.  -/
import Mathlib
import Workspace.Types.Core
import Workspace.Types.Decompositions
import Workspace.Types.Wheels
import Workspace.Types.LongOddPrism
import Workspace.Types.Classes
import Workspace.Types.Appearances
import Workspace.Statements.S14.Thm_14_3_recalcitrant
import Workspace.Statements.S16.Thm_16_3
import Workspace.ProofLemmas.ClassLemmas

/-!
# Section 16 — Odd wheels

The three numbered statements 16.1 – 16.3 of Chudnovsky–Robertson–Seymour–Thomas,
*The Strong Perfect Graph Theorem* (published / *Annals* version; printed pages 96–102).
Every definition used here is imported, never restated:

* `Workspace.Types.Core` — `IsPathList`, `IsPathFrom`, `SPGT.interior`, `VertexComplete`,
  `EdgeComplete`, `ConnectedSet`
* `Workspace.Types.Wheels` — `IsWheel` (*rim* `C`, *hub* `Y`), `IsSegment`, `IsOddWheel`,
  `SameWheelParity`, `OppositeWheelParity` — the whole wheel vocabulary of the section
  preamble (printed p. 96)
* `Workspace.Types.Appearances` — `attachments` (printed p. 20: *"a vertex in `V(K)` is said
  to be an attachment of `F` … if it has a neighbour in `V(F)`"*)
* `Workspace.Types.Decompositions` — `AdmitsBalancedSkewPartition`
* `Workspace.Types.Classes` — `InF6`, `InF7`
* `Workspace.Types.LongOddPrism` — `Recalcitrant`

The section's own vocabulary is exactly *rim*, *hub*, *segment* / *`Y`-segment*, *odd wheel*
and *wheel-parity* (same / opposite); all of it lives in `Workspace.Types.Wheels`.  The two
further terms of the section — *"line"* and the *"optimality"* of `(C,Y)` — are introduced
inside the proof of 16.3 and are used nowhere else, so they are not part of any statement.

## Encoding conventions specific to this section

* The rim `C` is the list of the vertices of the hole in cyclic order; the paper's numbering
  *"`C` has vertices `p₁, …, pₙ` in order"* is that list, so `p_k` is `C[k-1]` and `V(C)` is
  `{w | w ∈ C}`.
* *"a path of `C`"* / *"a 3-vertex path `p₁-p₂-p₃` in `C`"* is a path of `G` whose vertices
  form a cyclically consecutive block of `C`, in either orientation, i.e.
  `∃ k, S <+: C.rotate k ∨ S.reverse <+: C.rotate k`; this is the convention of
  `Workspace.Types.Wheels.SPGT.IsSegment` for *"a path in a path or hole `H`"*.
* Because a hole is induced, an *edge* of a path or hole listed as `P` is exactly a pair of
  adjacent vertices of `P`; so *"there is a `Z`-complete edge in `P`"* is
  `∃ x ∈ P, ∃ y ∈ P, EdgeComplete G Z x y` (`EdgeComplete` already contains `G.Adj x y`).
* *"the neighbours of `v` in `C`"* is `{u | u ∈ C ∧ G.Adj v u}`, equivalently
  `G.neighborSet v ∩ {u | u ∈ C}`.
* `SPGT.interior` is always written with its `SPGT.` prefix (Mathlib's topological `interior`
  otherwise captures the bare name).

## Published vs. arXiv v1

* **16.2, third bullet** — the arXiv draft's bullet is ill-formed: it speaks of
  `{p₄, …, pₙ}` although no numbering of `C` has been fixed anywhere in the statement.  The
  published version repairs this by opening the bullet with *"we can number the vertices of `C`
  as `p₁, …, pₙ` in order, such that `p₁, p₂, p₃` are all `Y`-complete, and …"*.  **The
  published form is what is transcribed here**: naming a cyclically consecutive triple
  `p₁, p₂, p₃` of `C` *is* the numbering, and `{p₄, …, pₙ}` is then exactly the set of vertices
  of `C` other than `p₁, p₂, p₃`.  (A numbering "in order" may run either way round the cycle;
  both orientations are allowed, as they must be.  The two readings are in fact equivalent,
  since reversing a numbering reverses the path `p₁-f₁-⋯-f_k-p₃` as well.)
* **16.1** and **16.3** are word-for-word identical in the two versions (up to
  *"so that"* → *"such that"*).
-/

set_option autoImplicit false

namespace Workspace.Statements.S16

open Workspace.Types.Core Workspace.Types.Core.SPGT
open Workspace.Types.Decompositions Workspace.Types.Decompositions.SPGT
open Workspace.Types.Wheels Workspace.Types.Wheels.SPGT
open Workspace.Types.Appearances Workspace.Types.Appearances.SPGT
open Workspace.Types.LongOddPrism Workspace.Types.LongOddPrism.SPGT
open Workspace.Types.Classes Workspace.Types.Classes.SPGT

namespace SPGT

variable {V : Type*} [Fintype V] [DecidableEq V]


/-- **16.3**, final sentence (printed p. 101) — the closing corollary of 16.3, stated on its own
because the paper asserts it of *every* recalcitrant graph, under no hypothesis.

PAPER: *"In particular, every recalcitrant graph belongs to `F₇`."*

`G` here is an arbitrary finite graph (unrelated to the `G ∈ F₆` of `thm_16_3`); *recalcitrant*
is the four-bullet notion of §13. -/
theorem thm_16_3_recalcitrant (G : SimpleGraph V) (hG : SPGT.Recalcitrant G) : SPGT.InF7 G := by
  -- Printed p. 91 (the closing sentence of 14.3): every recalcitrant graph is in `F₆`.
  have hF6 : SPGT.InF6 G :=
    _root_.Workspace.Statements.S14.SPGT.thm_14_3_recalcitrant G hG
  -- `F₆` is complement-closed, so `Ḡ ∈ F₆` as well; 16.3 is stated for `G` only, and
  -- `F₇` asks for the absence of odd wheels in `G` *and* in `Ḡ`.
  have hF6c : SPGT.InF6 Gᶜ :=
    _root_.Workspace.ProofLemmas.ClassLemmas.inF6_compl.mpr hF6
  -- The last bullet of *recalcitrant*: `G` admits no balanced skew partition — and
  -- neither does `Ḡ`, since balanced skew partitions are complement-invariant.
  have hbsp : ¬ SPGT.AdmitsBalancedSkewPartition G := hG.2.2.2.2
  have hbspc : ¬ SPGT.AdmitsBalancedSkewPartition Gᶜ := fun h =>
    hbsp (_root_.Workspace.ProofLemmas.ClassLemmas.admitsBalancedSkewPartition_compl.mp h)
  -- 16.3: *"If there is an odd wheel in `G` then `G` admits a balanced skew partition."*
  exact ⟨hF6, fun h => hbsp (thm_16_3 G hF6 h), fun h => hbspc (thm_16_3 Gᶜ hF6c h)⟩


end SPGT

end Workspace.Statements.S16
