/-  GENERATED by scripts/split_statements.py from Workspace/Statements/S23.lean -- one numbered statement
    of the paper per module.  The theorem below, its doc-comment and its
    signature are byte-identical to the source module; only the surrounding
    file was mechanically re-cut.  See PROVING_PLAN.md.  -/
import Mathlib
import Workspace.Types.Core
import Workspace.Types.BasicClasses
import Workspace.Types.Decompositions
import Workspace.Types.SkewTools
import Workspace.Types.Wheels
import Workspace.Types.WheelSystems
import Workspace.Types.Classes
import Workspace.Types.LongOddPrism
import Workspace.Statements.S23.Thm_23_4_recalcitrant
import Workspace.Statements.S23.Thm_23_5
import Workspace.ProofLemmas.ClassLemmas
import Workspace.ProofLemmas.HoleBasics

/-!
# Section 23 — The end of wheels

The six numbered statements 23.1 … 23.6 of Chudnovsky–Robertson–Seymour–Thomas,
*The Strong Perfect Graph Theorem* (published/Annals version, printed pages
139–143).  Source of the verbatim quotations: `paper/pdf/S23_The_end_of_wheels.md`,
`## Numbered statements`.

**Three of the twelve main steps of the proof of 1.3 live here**: 23.2 discharges
1.8.9, 23.4 discharges 1.8.10 and 23.5 discharges 1.8.11 (see printed p. 13:
*"The twelve statements of 1.8 are proved in 5.1, 5.2, 9.6, 10.6, 13.4, 14.3,
16.3, 18.7, 23.2, 23.4, 23.5, and 24.1 respectively."*).

**23.6 is not a result of this paper.**  It is quoted by the authors from
reference [12] — M. Conforti, G. Cornuéjols and G. Zambelli, *"Decomposing Berge
graphs containing no proper wheels, long prisms or their complements"*,
*Combinatorica*, to appear — as a possible *alternative* to Section 24
(*"Let us mention a theorem of [12], which could be applied at this stage as an
alternative to the next section, the following (and see also [8] for some related
material):"*), and the authors explicitly decline to use it (*"The method we give
below is somewhat shorter than the proof of 23.6 in [12], however."*).  It is
transcribed here like every other numbered statement of the section; see its own
doc-comment.

Section 23 **defines no new term**.  The only definitional material inside it is
an in-proof gloss of the §2 notion *hat* (*"So `Y` contains a hat, that is, there
exists `y' ∈ Y` with no neighbour in `C'` except `z, x₀`"*, inside the proof of
23.2), which occurs in no numbered statement; accordingly
`Workspace.Types.RousselRubio` (where `IsHatForHole` lives) is not imported.
The word *triad* does not occur anywhere in the section.

Every defined term used below is imported and never restated:

* `Workspace.Types.Core` — `IsPathFrom`, `SPGT.interior`, `IsHoleList`,
  `IsAntiholeList`, `holeLength`, `VertexComplete`;
* `Workspace.Types.Wheels` — `IsWheel` (§16's *wheel*);
* `Workspace.Types.WheelSystems` — `OptimalWheel` (§22), `IsFrame`,
  `IsWheelSystem`, `wheelSystemX` (`Xᵢ`), `wheelSystemA` (`Aᵢ`) (all §19);
* `Workspace.Types.Classes` — the classes `F₅, F₈, F₉, F₁₀, F₁₁` of §1;
* `Workspace.Types.Decompositions` — `AdmitsBalancedSkewPartition`;
* `Workspace.Types.SkewTools` — `AdmitsLooseSkewPartition` (§4), used by 23.6;
* `Workspace.Types.BasicClasses` — `IsLineGraphOfBipartite` (§1), used by 23.6;
* `Workspace.Types.LongOddPrism` — `Recalcitrant` (§13).

Encoding conventions (see `paper/spec/CONVENTIONS.md`):

* a hole is the list `C : List V` of its vertices in cyclic order, its length is
  `holeLength C`, and `V(C)` is `{w : V | w ∈ C}` (so *"`v ∉ V(C)`"* is `v ∉ C`);
* a **cyclically consecutive block** of the hole `C` — the paper's *subpath
  `c₁-c₂-c₃` of `C`*, and its *three consecutive neighbours* — is a prefix of
  some rotation of `C`, `∃ k : ℕ, [c₁, c₂, c₃] <+: C.rotate k`; this is the
  convention already used by `Classes.InF10` and `WheelSystems.IsKite`;
* a path is the list of its vertices in order; `SPGT.interior P` is the paper's
  `P*` (always written qualified — a bare `interior` is Mathlib's topological
  one);
* *"the set of neighbours of `v` in `V(C)`"* is
  `G.neighborSet v ∩ {w : V | w ∈ C}`;
* `Gᶜ` is the paper's `Ḡ`.

**Placement of the "In particular, …" sentences.**  Following the house rule
(`CONVENTIONS.md` §3.7) and the precedent of `Workspace.Statements.S14`
(statement 14.3), the closing sentence of 23.2, 23.4 and 23.5 is genuine
mathematical content and is formalized — as a *separate theorem* in each case
(`thm_23_2_recalcitrant`, `thm_23_4_recalcitrant`, `thm_23_5_recalcitrant`).  It
speaks about every recalcitrant graph, not about the ambient `G`, and the paper
asserts it under **no** hypothesis; making it a conjunct of the conclusion of the
  theorem proper would assert it only for those graphs satisfying that theorem's
hypotheses (`G ∈ F₈` and admitting no balanced skew partition, etc.), so that the
corollary would not be asserted at all were those hypotheses unsatisfiable.  Each
companion theorem therefore carries only the ambient finite graph `G` and the
hypothesis that `G` is recalcitrant.
-/

set_option autoImplicit false

namespace Workspace.Statements.S23

open Workspace.Types.Core Workspace.Types.Core.SPGT
open Workspace.Types.BasicClasses Workspace.Types.BasicClasses.SPGT
open Workspace.Types.Decompositions Workspace.Types.Decompositions.SPGT
open Workspace.Types.SkewTools Workspace.Types.SkewTools.SPGT
open Workspace.Types.Wheels Workspace.Types.Wheels.SPGT
open Workspace.Types.WheelSystems Workspace.Types.WheelSystems.SPGT
open Workspace.Types.Classes Workspace.Types.Classes.SPGT
open Workspace.Types.LongOddPrism Workspace.Types.LongOddPrism.SPGT

namespace SPGT

variable {V : Type*} [Fintype V] [DecidableEq V]


/-- **23.5**, final sentence (printed p. 143) — the closing corollary of 23.5,
stated on its own because the paper asserts it of *every* recalcitrant graph,
under no hypothesis.

PAPER: *"In particular, for every recalcitrant graph `G`, one of `G, Ḡ` belongs to
`F₁₁`."*

The `G` of this sentence is a fresh variable, unrelated to the `G ∈ F₁₀` of
`thm_23_5`; *"one of `G, Ḡ`"* is the disjunction `InF11 G ∨ InF11 Gᶜ`, and
*recalcitrant* is the four-bullet notion of §13. -/
theorem thm_23_5_recalcitrant (G : SimpleGraph V) (hG : SPGT.Recalcitrant G) :
    SPGT.InF11 G ∨ SPGT.InF11 Gᶜ := by
  -- Printed p. 142 (the closing sentence of 23.4): every recalcitrant graph is in `F₁₀`.
  have hF10 : SPGT.InF10 G :=
    _root_.Workspace.Statements.S23.SPGT.thm_23_4_recalcitrant G hG
  -- The first bullet of *recalcitrant*: `G` is Berge, so every hole of `G` and every
  -- hole of `Ḡ` has even length.
  have hB : SPGT.Berge G := hG.1
  -- 23.5: *"`G` does not contain both a hole of length ≥ 6 and an antihole of length ≥ 6."*
  have h23 := thm_23_5 G hF10
  rw [not_and_or] at h23
  rcases h23 with hP | hQ
  · -- No hole of `G` has length ≥ 6.  A hole is even and has length ≥ 4, so every hole of
    -- `G` has length exactly 4 — i.e. every antihole of `Ḡ` has length 4; with `Ḡ ∈ F₁₀`
    -- (`F₁₀` is complement-closed) this is `Ḡ ∈ F₁₁`.
    refine Or.inr (_root_.Workspace.ProofLemmas.ClassLemmas.inF11_compl_iff.mpr ⟨hF10, ?_⟩)
    intro c hc
    have h4 : 4 ≤ c.length :=
      _root_.Workspace.ProofLemmas.HoleBasics.hole_length_ge_four hc
    have h6 : ¬ (6 ≤ c.length) := fun h => hP ⟨c, hc, h⟩
    have hev : c.length % 2 = 0 := Nat.even_iff.mp (hB.1 c hc)
    show c.length = 4
    omega
  · -- No antihole of `G` has length ≥ 6, so every antihole of `G` has length exactly 4;
    -- with `G ∈ F₁₀` this is `G ∈ F₁₁`.
    refine Or.inl ⟨hF10, ?_⟩
    intro c hc
    have hc' : SPGT.IsHoleList Gᶜ c :=
      _root_.Workspace.ProofLemmas.HoleBasics.isAntiholeList_iff.mp hc
    have h4 : 4 ≤ c.length :=
      _root_.Workspace.ProofLemmas.HoleBasics.hole_length_ge_four hc'
    have h6 : ¬ (6 ≤ c.length) := fun h => hQ ⟨c, hc, h⟩
    have hev : c.length % 2 = 0 := Nat.even_iff.mp (hB.2 c hc')
    show c.length = 4
    omega


end SPGT

end Workspace.Statements.S23
