/-  GENERATED by scripts/split_statements.py from Workspace/Statements/S23.lean -- one numbered statement
    of the paper per module.  The theorem below, its doc-comment and its
    signature are byte-identical to the source module; only the surrounding
    file was mechanically re-cut.  See PROVING_PLAN.md.  -/
import Mathlib
import Workspace.Types.Core
import Workspace.Types.BasicClasses
import Workspace.Types.Decompositions
import Workspace.Types.SkewTools
import Workspace.Types.Wheels
import Workspace.Types.WheelSystems
import Workspace.Types.Classes
import Workspace.Types.LongOddPrism
import Workspace.Statements.S23.Thm_23_2_recalcitrant
import Workspace.Statements.S23.Thm_23_4
import Workspace.ProofLemmas.ClassLemmas
import Workspace.ProofLemmas.HoleBasics

/-!
# Section 23 — The end of wheels

The six numbered statements 23.1 … 23.6 of Chudnovsky–Robertson–Seymour–Thomas,
*The Strong Perfect Graph Theorem* (published/Annals version, printed pages
139–143).  Source of the verbatim quotations: `paper/pdf/S23_The_end_of_wheels.md`,
`## Numbered statements`.

**Three of the twelve main steps of the proof of 1.3 live here**: 23.2 discharges
1.8.9, 23.4 discharges 1.8.10 and 23.5 discharges 1.8.11 (see printed p. 13:
*"The twelve statements of 1.8 are proved in 5.1, 5.2, 9.6, 10.6, 13.4, 14.3,
16.3, 18.7, 23.2, 23.4, 23.5, and 24.1 respectively."*).

**23.6 is not a result of this paper.**  It is quoted by the authors from
reference [12] — M. Conforti, G. Cornuéjols and G. Zambelli, *"Decomposing Berge
graphs containing no proper wheels, long prisms or their complements"*,
*Combinatorica*, to appear — as a possible *alternative* to Section 24
(*"Let us mention a theorem of [12], which could be applied at this stage as an
alternative to the next section, the following (and see also [8] for some related
material):"*), and the authors explicitly decline to use it (*"The method we give
below is somewhat shorter than the proof of 23.6 in [12], however."*).  It is
transcribed here like every other numbered statement of the section; see its own
doc-comment.

Section 23 **defines no new term**.  The only definitional material inside it is
an in-proof gloss of the §2 notion *hat* (*"So `Y` contains a hat, that is, there
exists `y' ∈ Y` with no neighbour in `C'` except `z, x₀`"*, inside the proof of
23.2), which occurs in no numbered statement; accordingly
`Workspace.Types.RousselRubio` (where `IsHatForHole` lives) is not imported.
The word *triad* does not occur anywhere in the section.

Every defined term used below is imported and never restated:

* `Workspace.Types.Core` — `IsPathFrom`, `SPGT.interior`, `IsHoleList`,
  `IsAntiholeList`, `holeLength`, `VertexComplete`;
* `Workspace.Types.Wheels` — `IsWheel` (§16's *wheel*);
* `Workspace.Types.WheelSystems` — `OptimalWheel` (§22), `IsFrame`,
  `IsWheelSystem`, `wheelSystemX` (`Xᵢ`), `wheelSystemA` (`Aᵢ`) (all §19);
* `Workspace.Types.Classes` — the classes `F₅, F₈, F₉, F₁₀, F₁₁` of §1;
* `Workspace.Types.Decompositions` — `AdmitsBalancedSkewPartition`;
* `Workspace.Types.SkewTools` — `AdmitsLooseSkewPartition` (§4), used by 23.6;
* `Workspace.Types.BasicClasses` — `IsLineGraphOfBipartite` (§1), used by 23.6;
* `Workspace.Types.LongOddPrism` — `Recalcitrant` (§13).

Encoding conventions (see `paper/spec/CONVENTIONS.md`):

* a hole is the list `C : List V` of its vertices in cyclic order, its length is
  `holeLength C`, and `V(C)` is `{w : V | w ∈ C}` (so *"`v ∉ V(C)`"* is `v ∉ C`);
* a **cyclically consecutive block** of the hole `C` — the paper's *subpath
  `c₁-c₂-c₃` of `C`*, and its *three consecutive neighbours* — is a prefix of
  some rotation of `C`, `∃ k : ℕ, [c₁, c₂, c₃] <+: C.rotate k`; this is the
  convention already used by `Classes.InF10` and `WheelSystems.IsKite`;
* a path is the list of its vertices in order; `SPGT.interior P` is the paper's
  `P*` (always written qualified — a bare `interior` is Mathlib's topological
  one);
* *"the set of neighbours of `v` in `V(C)`"* is
  `G.neighborSet v ∩ {w : V | w ∈ C}`;
* `Gᶜ` is the paper's `Ḡ`.

**Placement of the "In particular, …" sentences.**  Following the house rule
(`CONVENTIONS.md` §3.7) and the precedent of `Workspace.Statements.S14`
(statement 14.3), the closing sentence of 23.2, 23.4 and 23.5 is genuine
mathematical content and is formalized — as a *separate theorem* in each case
(`thm_23_2_recalcitrant`, `thm_23_4_recalcitrant`, `thm_23_5_recalcitrant`).  It
speaks about every recalcitrant graph, not about the ambient `G`, and the paper
asserts it under **no** hypothesis; making it a conjunct of the conclusion of the
  theorem proper would assert it only for those graphs satisfying that theorem's
hypotheses (`G ∈ F₈` and admitting no balanced skew partition, etc.), so that the
corollary would not be asserted at all were those hypotheses unsatisfiable.  Each
companion theorem therefore carries only the ambient finite graph `G` and the
hypothesis that `G` is recalcitrant.
-/

set_option autoImplicit false

namespace Workspace.Statements.S23

open Workspace.Types.Core Workspace.Types.Core.SPGT
open Workspace.Types.BasicClasses Workspace.Types.BasicClasses.SPGT
open Workspace.Types.Decompositions Workspace.Types.Decompositions.SPGT
open Workspace.Types.SkewTools Workspace.Types.SkewTools.SPGT
open Workspace.Types.Wheels Workspace.Types.Wheels.SPGT
open Workspace.Types.WheelSystems Workspace.Types.WheelSystems.SPGT
open Workspace.Types.Classes Workspace.Types.Classes.SPGT
open Workspace.Types.LongOddPrism Workspace.Types.LongOddPrism.SPGT

namespace SPGT

variable {V : Type*} [Fintype V] [DecidableEq V]


/-- **23.4**, final sentence (printed p. 142) — the closing corollary of 23.4,
stated on its own because the paper asserts it of *every* recalcitrant graph,
under no hypothesis.

PAPER: *"In particular, every recalcitrant graph belongs to `F₁₀`."*

`G` is an arbitrary finite graph, unrelated to the `G ∈ F₉` of `thm_23_4`;
*recalcitrant* is the four-bullet notion of §13. -/
theorem thm_23_4_recalcitrant (G : SimpleGraph V) (hG : SPGT.Recalcitrant G) :
    SPGT.InF10 G := by
  -- 23.4 excludes only vertices of `G \ V(C)`; `F₁₀` quantifies over all vertices.  The
  -- gap is the remark in the `InF10` doc-comment: *"no vertex of the hole itself can
  -- qualify, since a hole is induced and so each of its vertices has exactly two
  -- neighbours on it"*.  (Same argument as the `private` lemma
  -- `hole_no_three_consecutive_neighbours` of the proved `Workspace.Statements.S01.Thm_1_8_10`;
  -- it is `private` there, so it is repeated here as a local `have`.)
  have hole_no3 : ∀ (H : SimpleGraph V) (C : List V), SPGT.IsHoleList H C →
      6 ≤ SPGT.holeLength C → ∀ v : V, v ∈ C →
      ¬ ∃ x y z : V, (∃ k : ℕ, [x, y, z] <+: C.rotate k) ∧
        H.Adj v x ∧ H.Adj v y ∧ H.Adj v z := by
    rintro H C hC h6 v hv ⟨x, y, z, ⟨k, t, ht⟩, hvx, hvy, -⟩
    -- `ht : [x, y, z] ++ t = C.rotate k`, i.e. the rotated hole is `x :: y :: z :: t`.
    have hrot : (x :: y :: z :: t) = C.rotate k := ht
    have hD : SPGT.IsHoleList H (x :: y :: z :: t) := by
      rw [hrot]; exact _root_.Workspace.ProofLemmas.HoleBasics.isHoleList_rotate hC k
    have hlen : (x :: y :: z :: t).length = C.length := by
      rw [hrot, List.length_rotate]
    have h6C : 6 ≤ C.length := h6
    have hn6 : 6 ≤ (x :: y :: z :: t).length := by omega
    have hvD : v ∈ (x :: y :: z :: t) := by
      rw [hrot]; exact List.mem_rotate.mpr hv
    obtain ⟨i, hi, hvi⟩ := List.getElem_of_mem hvD
    have h0 : 0 < (x :: y :: z :: t).length := by omega
    have h1 : 1 < (x :: y :: z :: t).length := by omega
    have hx0 : (x :: y :: z :: t)[0]'h0 = x := by simp
    have hy1 : (x :: y :: z :: t)[1]'h1 = y := by simp
    have hax : H.Adj ((x :: y :: z :: t)[i]'hi) ((x :: y :: z :: t)[0]'h0) := by
      rw [hvi, hx0]; exact hvx
    have hay : H.Adj ((x :: y :: z :: t)[i]'hi) ((x :: y :: z :: t)[1]'h1) := by
      rw [hvi, hy1]; exact hvy
    have hix := (_root_.Workspace.ProofLemmas.HoleBasics.hole_adj_iff hD hi h0).mp hax
    have hiy := (_root_.Workspace.ProofLemmas.HoleBasics.hole_adj_iff hD hi h1).mp hay
    have e2 : (0 + 1) % (x :: y :: z :: t).length = 1 := Nat.mod_eq_of_lt (by omega)
    have e3 : (1 + 1) % (x :: y :: z :: t).length = 2 := Nat.mod_eq_of_lt (by omega)
    by_cases hc : i + 1 = (x :: y :: z :: t).length
    · have e1 : (i + 1) % (x :: y :: z :: t).length = 0 := by rw [hc]; simp
      rw [e1, e2] at hix
      rw [e1, e3] at hiy
      omega
    · have e1 : (i + 1) % (x :: y :: z :: t).length = i + 1 :=
        Nat.mod_eq_of_lt (by omega)
      rw [e1, e2] at hix
      rw [e1, e3] at hiy
      omega
  -- Printed p. 139 (the closing sentence of 23.2): every recalcitrant graph is in `F₉`.
  have hF9 : SPGT.InF9 G :=
    _root_.Workspace.Statements.S23.SPGT.thm_23_2_recalcitrant G hG
  -- `F₉` is complement-closed; 23.4 is stated for `G` only, and `F₁₀` asks for the
  -- condition in `G` *and* in `Ḡ`.
  have hF9c : SPGT.InF9 Gᶜ :=
    _root_.Workspace.ProofLemmas.ClassLemmas.inF9_compl.mpr hF9
  have hbsp : ¬ SPGT.AdmitsBalancedSkewPartition G := hG.2.2.2.2
  have hbspc : ¬ SPGT.AdmitsBalancedSkewPartition Gᶜ := fun h =>
    hbsp (_root_.Workspace.ProofLemmas.ClassLemmas.admitsBalancedSkewPartition_compl.mp h)
  -- 23.4: *"Let `G ∈ F₉`, admitting no balanced skew partition, and let `C` be a hole in
  -- `G` of length ≥ 6.  Then there is no vertex of `G \ V(C)` with three consecutive
  -- neighbours in `C`."*
  have h23G := thm_23_4 G hF9 hbsp
  have h23Gc := thm_23_4 Gᶜ hF9c hbspc
  refine ⟨hF9, ?_, ?_⟩
  · intro C hC h6
    rintro ⟨v, x, y, z, hpre, hvx, hvy, hvz⟩
    by_cases hv : v ∈ C
    · exact hole_no3 G C hC h6 v hv ⟨x, y, z, hpre, hvx, hvy, hvz⟩
    · exact h23G C hC h6 ⟨v, hv, x, y, z, hpre, hvx, hvy, hvz⟩
  · intro C hC h6
    rintro ⟨v, x, y, z, hpre, hvx, hvy, hvz⟩
    by_cases hv : v ∈ C
    · exact hole_no3 Gᶜ C hC h6 v hv ⟨x, y, z, hpre, hvx, hvy, hvz⟩
    · exact h23Gc C hC h6 ⟨v, hv, x, y, z, hpre, hvx, hvy, hvz⟩


end SPGT

end Workspace.Statements.S23
