/-  GENERATED by scripts/split_statements.py from Workspace/Statements/S23.lean -- one numbered statement
    of the paper per module.  The theorem below, its doc-comment and its
    signature are byte-identical to the source module; only the surrounding
    file was mechanically re-cut.  See PROVING_PLAN.md.  -/
import Mathlib
import Workspace.Types.Core
import Workspace.Types.BasicClasses
import Workspace.Types.Decompositions
import Workspace.Types.SkewTools
import Workspace.Types.Wheels
import Workspace.Types.WheelSystems
import Workspace.Types.Classes
import Workspace.Types.LongOddPrism
import Workspace.Statements.S18.Thm_18_7_recalcitrant
import Workspace.Statements.S23.Thm_23_2
import Workspace.ProofLemmas.ClassLemmas

/-!
# Section 23 — The end of wheels

The six numbered statements 23.1 … 23.6 of Chudnovsky–Robertson–Seymour–Thomas,
*The Strong Perfect Graph Theorem* (published/Annals version, printed pages
139–143).  Source of the verbatim quotations: `paper/pdf/S23_The_end_of_wheels.md`,
`## Numbered statements`.

**Three of the twelve main steps of the proof of 1.3 live here**: 23.2 discharges
1.8.9, 23.4 discharges 1.8.10 and 23.5 discharges 1.8.11 (see printed p. 13:
*"The twelve statements of 1.8 are proved in 5.1, 5.2, 9.6, 10.6, 13.4, 14.3,
16.3, 18.7, 23.2, 23.4, 23.5, and 24.1 respectively."*).

**23.6 is not a result of this paper.**  It is quoted by the authors from
reference [12] — M. Conforti, G. Cornuéjols and G. Zambelli, *"Decomposing Berge
graphs containing no proper wheels, long prisms or their complements"*,
*Combinatorica*, to appear — as a possible *alternative* to Section 24
(*"Let us mention a theorem of [12], which could be applied at this stage as an
alternative to the next section, the following (and see also [8] for some related
material):"*), and the authors explicitly decline to use it (*"The method we give
below is somewhat shorter than the proof of 23.6 in [12], however."*).  It is
transcribed here like every other numbered statement of the section; see its own
doc-comment.

Section 23 **defines no new term**.  The only definitional material inside it is
an in-proof gloss of the §2 notion *hat* (*"So `Y` contains a hat, that is, there
exists `y' ∈ Y` with no neighbour in `C'` except `z, x₀`"*, inside the proof of
23.2), which occurs in no numbered statement; accordingly
`Workspace.Types.RousselRubio` (where `IsHatForHole` lives) is not imported.
The word *triad* does not occur anywhere in the section.

Every defined term used below is imported and never restated:

* `Workspace.Types.Core` — `IsPathFrom`, `SPGT.interior`, `IsHoleList`,
  `IsAntiholeList`, `holeLength`, `VertexComplete`;
* `Workspace.Types.Wheels` — `IsWheel` (§16's *wheel*);
* `Workspace.Types.WheelSystems` — `OptimalWheel` (§22), `IsFrame`,
  `IsWheelSystem`, `wheelSystemX` (`Xᵢ`), `wheelSystemA` (`Aᵢ`) (all §19);
* `Workspace.Types.Classes` — the classes `F₅, F₈, F₉, F₁₀, F₁₁` of §1;
* `Workspace.Types.Decompositions` — `AdmitsBalancedSkewPartition`;
* `Workspace.Types.SkewTools` — `AdmitsLooseSkewPartition` (§4), used by 23.6;
* `Workspace.Types.BasicClasses` — `IsLineGraphOfBipartite` (§1), used by 23.6;
* `Workspace.Types.LongOddPrism` — `Recalcitrant` (§13).

Encoding conventions (see `paper/spec/CONVENTIONS.md`):

* a hole is the list `C : List V` of its vertices in cyclic order, its length is
  `holeLength C`, and `V(C)` is `{w : V | w ∈ C}` (so *"`v ∉ V(C)`"* is `v ∉ C`);
* a **cyclically consecutive block** of the hole `C` — the paper's *subpath
  `c₁-c₂-c₃` of `C`*, and its *three consecutive neighbours* — is a prefix of
  some rotation of `C`, `∃ k : ℕ, [c₁, c₂, c₃] <+: C.rotate k`; this is the
  convention already used by `Classes.InF10` and `WheelSystems.IsKite`;
* a path is the list of its vertices in order; `SPGT.interior P` is the paper's
  `P*` (always written qualified — a bare `interior` is Mathlib's topological
  one);
* *"the set of neighbours of `v` in `V(C)`"* is
  `G.neighborSet v ∩ {w : V | w ∈ C}`;
* `Gᶜ` is the paper's `Ḡ`.

**Placement of the "In particular, …" sentences.**  Following the house rule
(`CONVENTIONS.md` §3.7) and the precedent of `Workspace.Statements.S14`
(statement 14.3), the closing sentence of 23.2, 23.4 and 23.5 is genuine
mathematical content and is formalized — as a *separate theorem* in each case
(`thm_23_2_recalcitrant`, `thm_23_4_recalcitrant`, `thm_23_5_recalcitrant`).  It
speaks about every recalcitrant graph, not about the ambient `G`, and the paper
asserts it under **no** hypothesis; making it a conjunct of the conclusion of the
  theorem proper would assert it only for those graphs satisfying that theorem's
hypotheses (`G ∈ F₈` and admitting no balanced skew partition, etc.), so that the
corollary would not be asserted at all were those hypotheses unsatisfiable.  Each
companion theorem therefore carries only the ambient finite graph `G` and the
hypothesis that `G` is recalcitrant.
-/

set_option autoImplicit false

namespace Workspace.Statements.S23

open Workspace.Types.Core Workspace.Types.Core.SPGT
open Workspace.Types.BasicClasses Workspace.Types.BasicClasses.SPGT
open Workspace.Types.Decompositions Workspace.Types.Decompositions.SPGT
open Workspace.Types.SkewTools Workspace.Types.SkewTools.SPGT
open Workspace.Types.Wheels Workspace.Types.Wheels.SPGT
open Workspace.Types.WheelSystems Workspace.Types.WheelSystems.SPGT
open Workspace.Types.Classes Workspace.Types.Classes.SPGT
open Workspace.Types.LongOddPrism Workspace.Types.LongOddPrism.SPGT

namespace SPGT

variable {V : Type*} [Fintype V] [DecidableEq V]


/-- **23.2**, final sentence (printed p. 139) — the closing corollary of 23.2,
stated on its own because the paper asserts it of *every* recalcitrant graph,
under no hypothesis.

PAPER: *"In particular, every recalcitrant graph belongs to `F₉`."*

`G` is an arbitrary finite graph, unrelated to the `G ∈ F₈` of `thm_23_2`;
*recalcitrant* is the four-bullet notion of §13. -/
theorem thm_23_2_recalcitrant (G : SimpleGraph V) (hG : SPGT.Recalcitrant G) :
    SPGT.InF9 G := by
  -- Printed p. 115 (the closing sentence of 18.7): every recalcitrant graph is in `F₈`.
  have hF8 : SPGT.InF8 G :=
    _root_.Workspace.Statements.S18.SPGT.thm_18_7_recalcitrant G hG
  -- `F₈` is complement-closed; 23.2 is stated for `G` only, and `F₉` asks for the
  -- absence of wheels in `G` *and* in `Ḡ`.
  have hF8c : SPGT.InF8 Gᶜ :=
    _root_.Workspace.ProofLemmas.ClassLemmas.inF8_compl.mpr hF8
  -- The last bullet of *recalcitrant*, and its complement form: this is exactly the
  -- second hypothesis of 23.2.
  have hbsp : ¬ SPGT.AdmitsBalancedSkewPartition G := hG.2.2.2.2
  have hbspc : ¬ SPGT.AdmitsBalancedSkewPartition Gᶜ := fun h =>
    hbsp (_root_.Workspace.ProofLemmas.ClassLemmas.admitsBalancedSkewPartition_compl.mp h)
  -- 23.2: *"Let `G ∈ F₈`, not admitting a balanced skew partition; then there is no
  -- wheel in `G`."*
  exact ⟨hF8, thm_23_2 G hF8 hbsp, thm_23_2 Gᶜ hF8c hbspc⟩


end SPGT

end Workspace.Statements.S23
