import Mathlib
import Workspace.Types.AdmissibleDatum
import Workspace.Types.CMAdjoinI

open Polynomial
open scoped NumberField
open scoped ComplexConjugate

open Workspace.Types.AdmissibleDatum Workspace.Types.CMAdjoinI

/-- **Local split generator.**

For an admissible datum `d` with base field `L = d.L`, CM field `K = d.K`, and
`d.h_adjoin : IsAdjoinI L K` (there is `iota ∈ K` with `iota² = -1` generating `K`
over `L`), there exists an element `ω` of the ring of integers `𝓞 K` whose image in
`K` squares to `-1`, that is integral over `𝓞 L` (under the scalar tower
`𝓞 L ⊆ 𝓞 K`), whose minimal polynomial over `𝓞 L` is `X² + 1`, and whose image in
`K` generates `K` over `L` (the `L`-intermediate field generated by it is `⊤`). Thus
`𝓞 L[ω]` is an order in `𝓞 K` with `[K : L] = 2` realized by the monic integral
generator `ω` with `ω² = -1`. -/
theorem LocalSplitGenerator (d : Workspace.Types.AdmissibleDatum.AdmissibleDatum) :
    ∃ ω : 𝓞 d.K,
      (algebraMap (𝓞 d.K) d.K ω) ^ 2 = -1 ∧
      IsIntegral (𝓞 d.L) ω ∧
      minpoly (𝓞 d.L) ω = X ^ 2 + 1 ∧
      IntermediateField.adjoin d.L {algebraMap (𝓞 d.K) d.K ω} = ⊤ := by
  classical
  obtain ⟨iota, hsq, hadj⟩ := d.h_adjoin
  have hintZ : IsIntegral ℤ iota := by
    refine ⟨X ^ 2 + 1, ?_, ?_⟩
    · monicity!
    · simp [hsq]
  set ω : 𝓞 d.K :=
    NumberField.RingOfIntegers.restrict (fun _ : Unit => iota) (fun _ => hintZ) () with hω
  have hcoe : (algebraMap (𝓞 d.K) d.K ω) = iota := rfl
  -- `iota` is integral over `L`, being a root of the monic polynomial `X ^ 2 + 1`.
  have hint : IsIntegral d.L iota := by
    refine ⟨X ^ 2 + 1, ?_, ?_⟩
    · monicity!
    · simp [hsq]
  -- `iota ∉ L` because `L` is totally real, so `-1` is not a square in `L`.
  have hne : iota ∉ (algebraMap d.L d.K).range := by
    rintro ⟨a, ha⟩
    have ha2 : a ^ 2 = -1 := by
      apply (algebraMap d.L d.K).injective
      rw [map_pow, ha, hsq, map_neg, map_one]
    obtain ⟨φ⟩ := (inferInstance : Nonempty (d.L →+* ℂ))
    have hreal : NumberField.ComplexEmbedding.IsReal φ :=
      NumberField.IsTotallyReal.complexEmbedding_isReal φ
    have hconj : conj (φ a) = φ a := by
      have h1 : NumberField.ComplexEmbedding.conjugate φ = φ :=
        NumberField.ComplexEmbedding.isReal_iff.mp hreal
      have h2 := RingHom.congr_fun h1 a
      rwa [NumberField.ComplexEmbedding.conjugate_coe_eq] at h2
    have hsq2 : (φ a) ^ 2 = -1 := by rw [← map_pow, ha2, map_neg, map_one]
    have key : ((Complex.normSq (φ a) : ℝ) : ℂ) = -1 := by
      rw [← Complex.mul_conj, hconj, ← pow_two]; exact hsq2
    have hcast : Complex.normSq (φ a) = -1 := by exact_mod_cast key
    have hnn := Complex.normSq_nonneg (φ a)
    linarith
  -- Hence the minimal polynomial of `iota` over `L` is exactly `X ^ 2 + 1`.
  have hmin : minpoly d.L iota = X ^ 2 + 1 := by
    have hdvd : minpoly d.L iota ∣ (X ^ 2 + 1 : d.L[X]) := by
      apply minpoly.dvd
      simp [hsq]
    have hmonic : (X ^ 2 + 1 : d.L[X]).Monic := by monicity!
    have hdeg : (X ^ 2 + 1 : d.L[X]).natDegree ≤ (minpoly d.L iota).natDegree := by
      have h2 : 2 ≤ (minpoly d.L iota).natDegree :=
        (minpoly.two_le_natDegree_iff hint).mpr hne
      have hnd : (X ^ 2 + 1 : d.L[X]).natDegree = 2 := by compute_degree!
      omega
    exact (Polynomial.eq_of_monic_of_dvd_of_natDegree_le (minpoly.monic hint) hmonic hdvd hdeg).symm
  -- `ω` is integral over `𝓞 L` since it is integral over `ℤ`.
  have hωint : IsIntegral (𝓞 d.L) ω := (NumberField.RingOfIntegers.isIntegral ω).tower_top
  refine ⟨ω, ?_, hωint, ?_, ?_⟩
  · rw [hcoe]; exact hsq
  · -- Transfer `minpoly d.L iota = X² + 1` down to `minpoly (𝓞 L) ω = X² + 1`.
    have hfield :
        minpoly d.L ((algebraMap (𝓞 d.K) d.K) ω) =
          map (algebraMap (𝓞 d.L) d.L) (minpoly (𝓞 d.L) ω) :=
      minpoly.isIntegrallyClosed_eq_field_fractions d.L d.K hωint
    have h1 : map (algebraMap (𝓞 d.L) d.L) (minpoly (𝓞 d.L) ω) = X ^ 2 + 1 := by
      rw [← hfield, hcoe, hmin]
    have hmapinj : Function.Injective (Polynomial.map (algebraMap (𝓞 d.L) d.L)) :=
      Polynomial.map_injective _ (IsFractionRing.injective (𝓞 d.L) d.L)
    apply hmapinj
    rw [h1]
    simp
  · rw [hcoe]; exact hadj
