/-  GENERATED by scripts/split_statements.py from Workspace/Statements/S14.lean -- one numbered statement
    of the paper per module.  The theorem below, its doc-comment and its
    signature are byte-identical to the source module; only the surrounding
    file was mechanically re-cut.  See PROVING_PLAN.md.  -/
import Mathlib
import Workspace.Types.Core
import Workspace.Types.DoubleDiamond
import Workspace.Types.LongOddPrism
import Workspace.Types.Classes
import Workspace.Types.Decompositions
import Workspace.Types.Appearances
import Workspace.ProofLemmas.CubeMinorAttachmentContainment
import Workspace.ProofLemmas.CubeAttachmentsCDComplete
import Workspace.ProofLemmas.Thm142ABComplete

/-!
# Section 14 — The double diamond

The three numbered statements 14.1–14.3 of Chudnovsky–Robertson–Seymour–Thomas, *The Strong
Perfect Graph Theorem* (published/Annals version, printed pages 87–91), transcribed from
`paper/pdf/S14_The_double_diamond.md`.

Every defined term used here is imported and never restated:

* *double diamond*, *cube*, *maximal cube*, *the graph formed by a cube*, *minor* and *major*
  (with respect to a maximal cube) come from `Workspace.Types.DoubleDiamond`;
* *attachment* from `Workspace.Types.Appearances`;
* the classes `F₅`, `F₆` from `Workspace.Types.Classes`;
* *recalcitrant* from `Workspace.Types.LongOddPrism` (it is defined in §13);
* *proper 2-join* and *balanced skew partition* from `Workspace.Types.Decompositions`;
* *connected*, *complete to*, *anticomplete to* from `Workspace.Types.Core`.

Encoding conventions (see `paper/spec/CONVENTIONS.md`):

* a cube is the quadruple of vertex sets `(A, B, C, D)`, and the vertex set `V(K)` of the
  graph `K = G|(A ∪ B ∪ C ∪ D)` that it forms is `A ∪ B ∪ C ∪ D`;
* *"the set of neighbours of `v` in `V(K)`"* is `G.neighborSet v ∩ (A ∪ B ∪ C ∪ D)`, and
  *"the set of attachments of `F` in `V(K)`"* is `attachments G F (A ∪ B ∪ C ∪ D)`;
* *"`X` includes `S`"* is `S ⊆ X`;
* quantification over all finite graphs is `∀ (n : ℕ) (H : SimpleGraph (Fin n))`.

Published-vs-draft note: **14.3** is the published form, *"either one of `G, Ḡ` admits a
**proper** 2-join"* (the arXiv draft says *"a 2-join"*).

The closing sentence of 14.3, *"In particular, every recalcitrant graph belongs to `F₆`"*, has
no free `G` and is asserted by the paper outright, so it is a **separate, hypothesis-free**
 theorem `thm_14_3_recalcitrant` rather than a conjunct sitting under 14.3's hypotheses.
-/

set_option autoImplicit false
set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

namespace Workspace.Statements.S14

open Workspace.Types.Core Workspace.Types.Core.SPGT
open Workspace.Types.DoubleDiamond Workspace.Types.DoubleDiamond.SPGT
open Workspace.Types.LongOddPrism Workspace.Types.LongOddPrism.SPGT
open Workspace.Types.Classes Workspace.Types.Classes.SPGT
open Workspace.Types.Decompositions Workspace.Types.Decompositions.SPGT
open Workspace.Types.Appearances Workspace.Types.Appearances.SPGT

namespace SPGT

variable {V : Type*} [Fintype V] [DecidableEq V]


/-- **14.2** (printed p. 88)

PAPER: *"Let `G ∈ F₅`.  Let `(A, B, C, D)` be a maximal cube in `G`, forming `K`, let
`F ⊆ V(G) \ V(K)` be a connected set of minor vertices, and let `X` be the set of attachments
of `F` in `V(K)`.  Then `X` is a subset of one of `A ∪ B`, `C ∪ D`, `A ∪ C`, `B ∪ D`.
Moreover, `X ∩ (A ∪ C)` is complete to `X ∩ (B ∪ D)`."*

Notes on the transcription.

* *"a connected set of minor vertices"*: `F` is connected (`ConnectedSet`) and every vertex of
  `F` is minor with respect to the maximal cube (`MinorForCube`, printed p. 88).
* *"the set of attachments of `F` in `V(K)`"* is `attachments G F (A ∪ B ∪ C ∪ D)` — the
  vertices of `V(K)` having a neighbour in `F` (printed p. 20).
* The *"Moreover"* sentence is part of the statement, so the conclusion is the conjunction of
  the two sentences. -/
theorem thm_14_2 (G : SimpleGraph V) (hG : InF5 G)
    (A B C D : Set V) (hcube : MaximalCube G A B C D)
    (F : Set V) (hF : F ⊆ (A ∪ B ∪ C ∪ D)ᶜ) (hFconn : ConnectedSet G F)
    (hFminor : ∀ v ∈ F, MinorForCube G A B C D v)
    (X : Set V) (hX : X = attachments G F (A ∪ B ∪ C ∪ D)) :
    (X ⊆ A ∪ B ∨ X ⊆ C ∪ D ∨ X ⊆ A ∪ C ∨ X ⊆ B ∪ D) ∧
      Complete G (X ∩ (A ∪ C)) (X ∩ (B ∪ D)) := by
  -- *"From (1)-(4), the first assertion of the theorem follows."*
  have hfirst :=
    Workspace.ProofLemmas.CubeMinorAttachmentContainment.CubeMinorAttachmentContainment
      G hG A B C D hcube F hF hFconn hFminor X hX
  refine ⟨hfirst, ?_⟩
  obtain ⟨⟨⟨dAB, dAC, dAD, dBC, dBD, dCD⟩, -⟩, -, -⟩ := hcube.1
  -- *"We may assume `X` meets both `A ∪ C` and `B ∪ D`, and so from what we just proved,
  -- either `X ⊆ C ∪ D` or `X ⊆ A ∪ B`."*  The two remaining cases are vacuous.
  rcases hfirst with h | h | h | h
  · -- *"Now assume that `X ⊆ A ∪ B`."*
    have key := Workspace.ProofLemmas.Thm142ABComplete
      G hG A B C D hcube F hF hFconn hFminor X hX h
    intro p hp q hq
    have hpA : p ∈ A := by
      rcases hp.2 with hp' | hp'
      · exact hp'
      · exact absurd hp' (by
          rcases h hp.1 with hA | hB
          · exact Set.disjoint_left.mp dAC hA
          · exact Set.disjoint_left.mp dBC hB)
    have hqB : q ∈ B := by
      rcases hq.2 with hq' | hq'
      · exact hq'
      · exact absurd hq' (by
          rcases h hq.1 with hA | hB
          · exact Set.disjoint_left.mp dAD hA
          · exact Set.disjoint_left.mp dBD hB)
    exact key p ⟨hp.1, hpA⟩ q ⟨hq.1, hqB⟩
  · -- *"Suppose first that `X ⊆ C ∪ D`."*
    have key := Workspace.ProofLemmas.CubeAttachmentsCDComplete
      G hG A B C D hcube.1 F hF hFconn X hX h
    intro p hp q hq
    have hpC : p ∈ C := by
      rcases hp.2 with hp' | hp'
      · exact absurd hp' (by
          rcases h hp.1 with hC | hD
          · exact fun hA => Set.disjoint_left.mp dAC hA hC
          · exact fun hA => Set.disjoint_left.mp dAD hA hD)
      · exact hp'
    have hqD : q ∈ D := by
      rcases hq.2 with hq' | hq'
      · exact absurd hq' (by
          rcases h hq.1 with hC | hD
          · exact fun hB => Set.disjoint_left.mp dBC hB hC
          · exact fun hB => Set.disjoint_left.mp dBD hB hD)
      · exact hq'
    exact key p ⟨hp.1, hpC⟩ q ⟨hq.1, hqD⟩
  · -- `X ⊆ A ∪ C`: `X ∩ (B ∪ D)` is empty
    intro p hp q hq
    exact absurd (h hq.1) (by
      rcases hq.2 with hq' | hq'
      · rintro (hA | hC)
        · exact Set.disjoint_left.mp dAB hA hq'
        · exact Set.disjoint_left.mp dBC hq' hC
      · rintro (hA | hC)
        · exact Set.disjoint_left.mp dAD hA hq'
        · exact Set.disjoint_left.mp dCD hC hq')
  · -- `X ⊆ B ∪ D`: `X ∩ (A ∪ C)` is empty
    intro p hp q hq
    exact absurd (h hp.1) (by
      rcases hp.2 with hp' | hp'
      · rintro (hB | hD)
        · exact Set.disjoint_left.mp dAB hp' hB
        · exact Set.disjoint_left.mp dAD hp' hD
      · rintro (hB | hD)
        · exact Set.disjoint_left.mp dBC hB hp'
        · exact Set.disjoint_left.mp dCD hp' hD)


end SPGT

end Workspace.Statements.S14
