/-  GENERATED by scripts/split_statements.py from Workspace/Statements/S14.lean -- one numbered statement
    of the paper per module.  The theorem below, its doc-comment and its
    signature are byte-identical to the source module; only the surrounding
    file was mechanically re-cut.  See PROVING_PLAN.md.  -/
import Mathlib
import Workspace.Types.Core
import Workspace.Types.DoubleDiamond
import Workspace.Types.LongOddPrism
import Workspace.Types.Classes
import Workspace.Types.Decompositions
import Workspace.Types.Appearances
import Workspace.ProofLemmas.HoleBasics
import Workspace.ProofLemmas.CubeComplement
import Workspace.ProofLemmas.CubeNeighbourSideComplete
import Workspace.ProofLemmas.CubeMajorCoreContradiction

/-!
# Section 14 — The double diamond

The three numbered statements 14.1–14.3 of Chudnovsky–Robertson–Seymour–Thomas, *The Strong
Perfect Graph Theorem* (published/Annals version, printed pages 87–91), transcribed from
`paper/pdf/S14_The_double_diamond.md`.

Every defined term used here is imported and never restated:

* *double diamond*, *cube*, *maximal cube*, *the graph formed by a cube*, *minor* and *major*
  (with respect to a maximal cube) come from `Workspace.Types.DoubleDiamond`;
* *attachment* from `Workspace.Types.Appearances`;
* the classes `F₅`, `F₆` from `Workspace.Types.Classes`;
* *recalcitrant* from `Workspace.Types.LongOddPrism` (it is defined in §13);
* *proper 2-join* and *balanced skew partition* from `Workspace.Types.Decompositions`;
* *connected*, *complete to*, *anticomplete to* from `Workspace.Types.Core`.

Encoding conventions (see `paper/spec/CONVENTIONS.md`):

* a cube is the quadruple of vertex sets `(A, B, C, D)`, and the vertex set `V(K)` of the
  graph `K = G|(A ∪ B ∪ C ∪ D)` that it forms is `A ∪ B ∪ C ∪ D`;
* *"the set of neighbours of `v` in `V(K)`"* is `G.neighborSet v ∩ (A ∪ B ∪ C ∪ D)`, and
  *"the set of attachments of `F` in `V(K)`"* is `attachments G F (A ∪ B ∪ C ∪ D)`;
* *"`X` includes `S`"* is `S ⊆ X`;
* quantification over all finite graphs is `∀ (n : ℕ) (H : SimpleGraph (Fin n))`.

Published-vs-draft note: **14.3** is the published form, *"either one of `G, Ḡ` admits a
**proper** 2-join"* (the arXiv draft says *"a 2-join"*).

The closing sentence of 14.3, *"In particular, every recalcitrant graph belongs to `F₆`"*, has
no free `G` and is asserted by the paper outright, so it is a **separate, hypothesis-free**
 theorem `thm_14_3_recalcitrant` rather than a conjunct sitting under 14.3's hypotheses.
-/

set_option autoImplicit false
set_option linter.unusedVariables false
set_option maxHeartbeats 4000000

namespace Workspace.Statements.S14

open Workspace.Types.Core Workspace.Types.Core.SPGT
open Workspace.Types.DoubleDiamond Workspace.Types.DoubleDiamond.SPGT
open Workspace.Types.LongOddPrism Workspace.Types.LongOddPrism.SPGT
open Workspace.Types.Classes Workspace.Types.Classes.SPGT
open Workspace.Types.Decompositions Workspace.Types.Decompositions.SPGT
open Workspace.Types.Appearances Workspace.Types.Appearances.SPGT

namespace SPGT

variable {V : Type*} [Fintype V] [DecidableEq V]

/-- `V(K)` written in the order the complementary cube `(D, C, A, B)` uses. -/
private theorem union4_DCAB (A B C D : Set V) : D ∪ C ∪ A ∪ B = A ∪ B ∪ C ∪ D := by
  ext u; simp only [Set.mem_union]; tauto

/-- `V(K)` written in the order the swapped cube `(B, A, D, C)` uses. -/
private theorem union4_BADC (A B C D : Set V) : B ∪ A ∪ D ∪ C = A ∪ B ∪ C ∪ D := by
  ext u; simp only [Set.mem_union]; tauto

/-- `V(K)` written in the order the swapped complementary cube `(C, D, B, A)` uses. -/
private theorem union4_CDBA (A B C D : Set V) : C ∪ D ∪ B ∪ A = D ∪ C ∪ A ∪ B := by
  ext u; simp only [Set.mem_union]; tauto

/-- The `(A,B,C,D) ↦ (B,A,D,C)` symmetry of a cube preserves maximality.  This is the symmetry
that lets the printed proof say *"So we may assume that `X` meets both `A` and `D`"* after having
disposed of the four `X ⊆ …` cases. -/
private theorem maximalCube_swap' {G : SimpleGraph V} {A B C D : Set V}
    (h : MaximalCube G A B C D) : MaximalCube G B A D C := by
  refine ⟨Workspace.ProofLemmas.CubeComplement.isCube_swap h.1, ?_⟩
  intro A' B' C' D' hcube hBA' hAB' hDC' hCD'
  obtain ⟨e1, e2, e3, e4⟩ := h.2 B' A' D' C'
    (Workspace.ProofLemmas.CubeComplement.isCube_swap hcube) hAB' hBA' hCD' hDC'
  exact ⟨e2, e1, e4, e3⟩

/-- **14.1** (printed pp. 87–88)

PAPER: *"Let `G ∈ F₅`.  Let `(A, B, C, D)` be a maximal cube in `G`, forming `K`, let
`v ∈ V(G) \ V(K)`, and let `X` be the set of neighbours of `v` in `V(K)`.  Then either*

*• `X` is a subset of one of `A ∪ B`, `C ∪ D`, `A ∪ C`, `B ∪ D`, and `X ∩ (A ∪ C)` is complete
to `X ∩ (B ∪ D)`, or*

*• `X` includes one of `A ∪ B`, `C ∪ D`, `A ∪ D`, `B ∪ C`, and `(A ∪ D) \ X` is anticomplete
to `(B ∪ C) \ X`."*

The two cases are stated in the printed order, and the paper names them immediately
afterwards: *"Say a vertex `v ∈ V(G) \ V(K)` is minor if the first case of 14.1 applies to it,
and major if the second case applies."*  So the first disjunct below is
`DoubleDiamond.SPGT.MinorForCube G A B C D v` and the second is `MajorForCube G A B C D v`,
each with its `v ∉ V(K)` conjunct removed (that conjunct is the hypothesis `hv` here); they
are written out in full so that the statement reproduces the printed text without appealing to
notions whose definition refers back to 14.1 itself.

`V(K)` is `A ∪ B ∪ C ∪ D` and `X` is `G.neighborSet v ∩ (A ∪ B ∪ C ∪ D)`. -/
theorem thm_14_1 (G : SimpleGraph V) (hG : InF5 G)
    (A B C D : Set V) (hcube : MaximalCube G A B C D)
    (v : V) (hv : v ∉ A ∪ B ∪ C ∪ D)
    (X : Set V) (hX : X = G.neighborSet v ∩ (A ∪ B ∪ C ∪ D)) :
    ((X ⊆ A ∪ B ∨ X ⊆ C ∪ D ∨ X ⊆ A ∪ C ∨ X ⊆ B ∪ D) ∧
        Complete G (X ∩ (A ∪ C)) (X ∩ (B ∪ D))) ∨
    ((A ∪ B ⊆ X ∨ C ∪ D ⊆ X ∨ A ∪ D ⊆ X ∨ B ∪ C ⊆ X) ∧
        Anticomplete G ((A ∪ D) \ X) ((B ∪ C) \ X)) := by
  classical
  have hBerge : Berge G := hG.1.1
  have hBergeC : Berge Gᶜ := Workspace.ProofLemmas.HoleBasics.berge_compl.mpr hBerge
  have hXsub : X ⊆ A ∪ B ∪ C ∪ D := by rw [hX]; exact Set.inter_subset_right
  -- ### The complementary picture: the cube `(D, C, A, B)` of `Gᶜ`, and `X' = V(K) \ X`
  have hKeq : D ∪ C ∪ A ∪ B = A ∪ B ∪ C ∪ D := union4_DCAB A B C D
  obtain ⟨X', hX'def⟩ : ∃ Y : Set V, Y = Gᶜ.neighborSet v ∩ (D ∪ C ∪ A ∪ B) := ⟨_, rfl⟩
  have hv' : v ∉ D ∪ C ∪ A ∪ B := by rw [hKeq]; exact hv
  have hX'mem : ∀ u : V, u ∈ A ∪ B ∪ C ∪ D → (u ∈ X' ↔ u ∉ X) := by
    intro u hu
    rw [hX'def]
    constructor
    · rintro ⟨hadj, -⟩ hcon
      rw [hX] at hcon
      exact hadj.2 hcon.1
    · intro hcon
      refine ⟨⟨fun he => hv (he ▸ hu), fun hadj => hcon (by rw [hX]; exact ⟨hadj, hu⟩)⟩, ?_⟩
      rw [hKeq]; exact hu
  have hX'sub : X' ⊆ A ∪ B ∪ C ∪ D := by
    intro u hu; rw [hX'def] at hu; rw [← hKeq]; exact hu.2
  -- a set of `V(K)` not included in `X` meets `X'`, and one meeting `X` is not included in `X'`
  have hmeetX' : ∀ S : Set V, S ⊆ A ∪ B ∪ C ∪ D → ¬ (S ⊆ X) → (S ∩ X').Nonempty := by
    intro S hSK hS
    by_contra hcon
    refine hS fun u hu => ?_
    by_contra hux
    exact hcon ⟨u, hu, (hX'mem u (hSK hu)).mpr hux⟩
  have hnotsubX' : ∀ S : Set V, (S ∩ X).Nonempty → ¬ (S ⊆ X') := by
    rintro S ⟨u, huS, huX⟩ hsub
    exact ((hX'mem u (hXsub huX)).mp (hsub huS)) huX
  -- ### Steps 1–3 of the printed proof
  by_cases h1 : X ⊆ A ∪ B ∨ X ⊆ C ∪ D ∨ X ⊆ A ∪ C ∨ X ⊆ B ∪ D
  · exact Or.inl ⟨h1,
      Workspace.ProofLemmas.CubeNeighbourSideComplete.CubeNeighbourSideComplete
        hBerge hcube.1 hv hX h1⟩
  -- ### Step 5: *"From the same argument in `Ḡ`"*
  by_cases h2 : A ∪ B ⊆ X ∨ C ∪ D ⊆ X ∨ A ∪ D ⊆ X ∨ B ∪ C ⊆ X
  · refine Or.inr ⟨h2, ?_⟩
    -- the four inclusions `S ⊆ X` become the four inclusions `X' ⊆ Sᶜ ∩ V(K)`
    have hsub' : X' ⊆ D ∪ C ∨ X' ⊆ A ∪ B ∨ X' ⊆ D ∪ A ∨ X' ⊆ C ∪ B := by
      have key : ∀ S T : Set V, (∀ u : V, u ∈ A ∪ B ∪ C ∪ D → u ∈ S ∨ u ∈ T) →
          S ⊆ X → X' ⊆ T := by
        intro S T hcov hSX u hu
        rcases hcov u (hX'sub hu) with h | h
        · exact absurd (hSX h) ((hX'mem u (hX'sub hu)).mp hu)
        · exact h
      rcases h2 with h | h | h | h
      · refine Or.inl (key (A ∪ B) (D ∪ C) ?_ h)
        rintro u (((hu | hu) | hu) | hu)
        exacts [Or.inl (Or.inl hu), Or.inl (Or.inr hu), Or.inr (Or.inr hu), Or.inr (Or.inl hu)]
      · refine Or.inr (Or.inl (key (C ∪ D) (A ∪ B) ?_ h))
        rintro u (((hu | hu) | hu) | hu)
        exacts [Or.inr (Or.inl hu), Or.inr (Or.inr hu), Or.inl (Or.inl hu), Or.inl (Or.inr hu)]
      · refine Or.inr (Or.inr (Or.inr (key (A ∪ D) (C ∪ B) ?_ h)))
        rintro u (((hu | hu) | hu) | hu)
        exacts [Or.inl (Or.inl hu), Or.inr (Or.inr hu), Or.inr (Or.inl hu), Or.inl (Or.inr hu)]
      · refine Or.inr (Or.inr (Or.inl (key (B ∪ C) (D ∪ A) ?_ h)))
        rintro u (((hu | hu) | hu) | hu)
        exacts [Or.inr (Or.inr hu), Or.inl (Or.inl hu), Or.inl (Or.inr hu), Or.inr (Or.inl hu)]
    have hcompl := Workspace.ProofLemmas.CubeNeighbourSideComplete.CubeNeighbourSideComplete
      (G := Gᶜ) hBergeC (Workspace.ProofLemmas.CubeComplement.isCube_compl hcube.1) hv'
      (X := X') hX'def hsub'
    intro p hp q hq hadj
    have hpK : p ∈ A ∪ B ∪ C ∪ D := by
      rcases hp.1 with h | h
      · exact Or.inl (Or.inl (Or.inl h))
      · exact Or.inr h
    have hqK : q ∈ A ∪ B ∪ C ∪ D := by
      rcases hq.1 with h | h
      · exact Or.inl (Or.inl (Or.inr h))
      · exact Or.inl (Or.inr h)
    have hpX' : p ∈ X' ∩ (D ∪ A) := by
      refine ⟨(hX'mem p hpK).mpr hp.2, ?_⟩
      rcases hp.1 with h | h
      · exact Or.inr h
      · exact Or.inl h
    have hqX' : q ∈ X' ∩ (C ∪ B) := by
      refine ⟨(hX'mem q hqK).mpr hq.2, ?_⟩
      rcases hq.1 with h | h
      · exact Or.inr h
      · exact Or.inl h
    exact (hcompl p hpX' q hqX').2 hadj
  -- ### The remaining case: neither disjunct's inclusion list holds — derive a contradiction
  push_neg at h1 h2
  obtain ⟨hn1, hn2, hn3, hn4⟩ := h1
  obtain ⟨hm1, hm2, hm3, hm4⟩ := h2
  exfalso
  -- *"So we may assume that `X` meets both `A` and `D`"* — the four failures of `X ⊆ …`
  have wit : ∀ S T : Set V, ¬ (X ⊆ S ∪ T) → ∃ u, u ∈ X ∧ u ∉ S ∧ u ∉ T := by
    intro S T h
    by_contra hcon
    push_neg at hcon
    exact h fun u hu => by
      by_cases hs : u ∈ S
      · exact Or.inl hs
      · exact Or.inr (hcon u hu hs)
  have mCD : (C ∩ X).Nonempty ∨ (D ∩ X).Nonempty := by
    obtain ⟨u, huX, ha, hb⟩ := wit A B hn1
    rcases hXsub huX with ((h | h) | h) | h
    · exact absurd h ha
    · exact absurd h hb
    · exact Or.inl ⟨u, h, huX⟩
    · exact Or.inr ⟨u, h, huX⟩
  have mAB : (A ∩ X).Nonempty ∨ (B ∩ X).Nonempty := by
    obtain ⟨u, huX, hc, hd⟩ := wit C D hn2
    rcases hXsub huX with ((h | h) | h) | h
    · exact Or.inl ⟨u, h, huX⟩
    · exact Or.inr ⟨u, h, huX⟩
    · exact absurd h hc
    · exact absurd h hd
  have mBD : (B ∩ X).Nonempty ∨ (D ∩ X).Nonempty := by
    obtain ⟨u, huX, ha, hc⟩ := wit A C hn3
    rcases hXsub huX with ((h | h) | h) | h
    · exact absurd h ha
    · exact Or.inl ⟨u, h, huX⟩
    · exact absurd h hc
    · exact Or.inr ⟨u, h, huX⟩
  have mAC : (A ∩ X).Nonempty ∨ (C ∩ X).Nonempty := by
    obtain ⟨u, huX, hb, hd⟩ := wit B D hn4
    rcases hXsub huX with ((h | h) | h) | h
    · exact Or.inl ⟨u, h, huX⟩
    · exact absurd h hb
    · exact Or.inr ⟨u, h, huX⟩
    · exact absurd h hd
  have hsplit1 : ((A ∩ X).Nonempty ∧ (D ∩ X).Nonempty) ∨
      ((B ∩ X).Nonempty ∧ (C ∩ X).Nonempty) := by
    by_cases hA : (A ∩ X).Nonempty
    · by_cases hD : (D ∩ X).Nonempty
      · exact Or.inl ⟨hA, hD⟩
      · exact Or.inr ⟨mBD.resolve_right hD, mCD.resolve_right hD⟩
    · exact Or.inr ⟨mAB.resolve_left hA, mAC.resolve_left hA⟩
  -- *"either `X` includes neither of `A, C` or it includes neither of `B, D`"*
  have k1 : ¬ (A ⊆ X ∧ B ⊆ X) := fun h => hm1 (Set.union_subset h.1 h.2)
  have k2 : ¬ (C ⊆ X ∧ D ⊆ X) := fun h => hm2 (Set.union_subset h.1 h.2)
  have k3 : ¬ (A ⊆ X ∧ D ⊆ X) := fun h => hm3 (Set.union_subset h.1 h.2)
  have k4 : ¬ (B ⊆ X ∧ C ⊆ X) := fun h => hm4 (Set.union_subset h.1 h.2)
  have hsplit2 : (¬ (A ⊆ X) ∧ ¬ (C ⊆ X)) ∨ (¬ (B ⊆ X) ∧ ¬ (D ⊆ X)) := by
    by_cases hA : A ⊆ X
    · exact Or.inr ⟨fun hb => k1 ⟨hA, hb⟩, fun hd => k3 ⟨hA, hd⟩⟩
    · by_cases hC : C ⊆ X
      · exact Or.inr ⟨fun hb => k4 ⟨hb, hC⟩, fun hd => k2 ⟨hC, hd⟩⟩
      · exact Or.inl ⟨hA, hC⟩
  -- subset shorthands
  have sA : A ⊆ A ∪ B ∪ C ∪ D := fun u hu => Or.inl (Or.inl (Or.inl hu))
  have sB : B ⊆ A ∪ B ∪ C ∪ D := fun u hu => Or.inl (Or.inl (Or.inr hu))
  have sC : C ⊆ A ∪ B ∪ C ∪ D := fun u hu => Or.inl (Or.inr hu)
  have sD : D ⊆ A ∪ B ∪ C ∪ D := fun u hu => Or.inr hu
  have hKeq2 : B ∪ A ∪ D ∪ C = A ∪ B ∪ C ∪ D := union4_BADC A B C D
  have hKeq3 : C ∪ D ∪ B ∪ A = D ∪ C ∪ A ∪ B := union4_CDBA A B C D
  rcases hsplit1 with ⟨hα, hδ⟩ | ⟨hβ, hγ⟩
  · rcases hsplit2 with ⟨hA2, hC2⟩ | ⟨hB2, hD2⟩
    · -- pass to the complement: the cube `(C, D, B, A)` of `Gᶜ` with `X'`
      exact Workspace.ProofLemmas.CubeMajorCoreContradiction.CubeMajorCoreContradiction
        hBergeC (maximalCube_swap' (Workspace.ProofLemmas.CubeComplement.maximalCube_compl hcube))
        (by rw [hKeq3, hKeq]; exact hv) (X := X') (by rw [hKeq3]; exact hX'def)
        (hmeetX' C sC hC2) (hmeetX' A sA hA2) (hnotsubX' D hδ) (hnotsubX' A hα)
    · -- the printed configuration, verbatim
      exact Workspace.ProofLemmas.CubeMajorCoreContradiction.CubeMajorCoreContradiction
        hBerge hcube hv hX hα hδ hB2 hD2
  · rcases hsplit2 with ⟨hA2, hC2⟩ | ⟨hB2, hD2⟩
    · -- the `(A,B,C,D) ↦ (B,A,D,C)` symmetry
      exact Workspace.ProofLemmas.CubeMajorCoreContradiction.CubeMajorCoreContradiction
        hBerge (maximalCube_swap' hcube) (by rw [hKeq2]; exact hv) (by rw [hKeq2]; exact hX)
        hβ hγ hA2 hC2
    · -- both: pass to the complement cube `(D, C, A, B)` of `Gᶜ`
      exact Workspace.ProofLemmas.CubeMajorCoreContradiction.CubeMajorCoreContradiction
        hBergeC (Workspace.ProofLemmas.CubeComplement.maximalCube_compl hcube) hv'
        (X := X') hX'def (hmeetX' D sD hD2) (hmeetX' B sB hB2)
        (hnotsubX' C hγ) (hnotsubX' B hβ)

end SPGT

end Workspace.Statements.S14
