/-  GENERATED by scripts/split_statements.py from Workspace/Statements/S14.lean -- one numbered statement
    of the paper per module.  The theorem below, its doc-comment and its
    signature are byte-identical to the source module; only the surrounding
    file was mechanically re-cut.  See PROVING_PLAN.md.  -/
import Mathlib
import Workspace.Types.Core
import Workspace.Types.DoubleDiamond
import Workspace.Types.LongOddPrism
import Workspace.Types.Classes
import Workspace.Types.Decompositions
import Workspace.Types.Appearances
import Workspace.Statements.S14.Thm_14_3
import Workspace.ProofLemmas.RecalcitrantInF5

/-!
# Section 14 — The double diamond

The three numbered statements 14.1–14.3 of Chudnovsky–Robertson–Seymour–Thomas, *The Strong
Perfect Graph Theorem* (published/Annals version, printed pages 87–91), transcribed from
`paper/pdf/S14_The_double_diamond.md`.

Every defined term used here is imported and never restated:

* *double diamond*, *cube*, *maximal cube*, *the graph formed by a cube*, *minor* and *major*
  (with respect to a maximal cube) come from `Workspace.Types.DoubleDiamond`;
* *attachment* from `Workspace.Types.Appearances`;
* the classes `F₅`, `F₆` from `Workspace.Types.Classes`;
* *recalcitrant* from `Workspace.Types.LongOddPrism` (it is defined in §13);
* *proper 2-join* and *balanced skew partition* from `Workspace.Types.Decompositions`;
* *connected*, *complete to*, *anticomplete to* from `Workspace.Types.Core`.

Encoding conventions (see `paper/spec/CONVENTIONS.md`):

* a cube is the quadruple of vertex sets `(A, B, C, D)`, and the vertex set `V(K)` of the
  graph `K = G|(A ∪ B ∪ C ∪ D)` that it forms is `A ∪ B ∪ C ∪ D`;
* *"the set of neighbours of `v` in `V(K)`"* is `G.neighborSet v ∩ (A ∪ B ∪ C ∪ D)`, and
  *"the set of attachments of `F` in `V(K)`"* is `attachments G F (A ∪ B ∪ C ∪ D)`;
* *"`X` includes `S`"* is `S ⊆ X`;
* quantification over all finite graphs is `∀ (n : ℕ) (H : SimpleGraph (Fin n))`.

Published-vs-draft note: **14.3** is the published form, *"either one of `G, Ḡ` admits a
**proper** 2-join"* (the arXiv draft says *"a 2-join"*).

The closing sentence of 14.3, *"In particular, every recalcitrant graph belongs to `F₆`"*, has
no free `G` and is asserted by the paper outright, so it is a **separate, hypothesis-free**
  theorem `thm_14_3_recalcitrant` rather than a conjunct sitting under 14.3's hypotheses.
-/

set_option autoImplicit false

namespace Workspace.Statements.S14

open Workspace.Types.Core Workspace.Types.Core.SPGT
open Workspace.Types.DoubleDiamond Workspace.Types.DoubleDiamond.SPGT
open Workspace.Types.LongOddPrism Workspace.Types.LongOddPrism.SPGT
open Workspace.Types.Classes Workspace.Types.Classes.SPGT
open Workspace.Types.Decompositions Workspace.Types.Decompositions.SPGT
open Workspace.Types.Appearances Workspace.Types.Appearances.SPGT

namespace SPGT

variable {V : Type*} [Fintype V] [DecidableEq V]


/-- **14.3**, final sentence (printed p. 91) — the closing corollary of 14.3, stated on its own
because the paper asserts it of *every* recalcitrant graph, under no hypothesis.

PAPER: *"In particular, every recalcitrant graph belongs to `F₆`."*

`G` here is an arbitrary finite graph (it is unrelated to the `G ∈ F₅` of `thm_14_3`);
*recalcitrant* is the four-bullet notion of §13. -/
theorem thm_14_3_recalcitrant (G : SimpleGraph V) (hG : SPGT.Recalcitrant G) : SPGT.InF6 G := by
  -- Printed p. 86: *"Certainly every recalcitrant graph belongs to `F₅`, by 10.6 and 9.7."*
  have hF5 : SPGT.InF5 G :=
    _root_.Workspace.ProofLemmas.RecalcitrantInF5.recalcitrant_inF5 G hG
  refine ⟨hF5, ?_⟩
  -- The remaining conjunct of `F₆`: `G` contains no double diamond.
  intro hdd
  -- 14.3 itself, applied to `G ∈ F₅`.
  rcases thm_14_3 G hF5 hdd with (h | h) | h
  · exact hG.2.2.1.1 h            -- `G` admits no proper 2-join
  · exact hG.2.2.1.2 h            -- nor does `Ḡ`
  · exact hG.2.2.2.2 h            -- `G` admits no balanced skew partition


end SPGT

end Workspace.Statements.S14
