/-  GENERATED by scripts/split_statements.py from Workspace/Statements/S17.lean -- one numbered statement
    of the paper per module.  The theorem below, its doc-comment and its
    signature are byte-identical to the source module; only the surrounding
    file was mechanically re-cut.  See PROVING_PLAN.md.  -/
import Mathlib
import Workspace.Types.Core
import Workspace.Types.RousselRubio
import Workspace.Types.TriangleCatching
import Workspace.Types.Classes
import Workspace.ProofLemmas.Thm174Main

/-!
# Section 17 — Another extension of the Roussel–Rubio lemma

The five numbered statements 17.1 … 17.5 of Chudnovsky–Robertson–Seymour–Thomas,
*The Strong Perfect Graph Theorem* (published/Annals version, printed pages
102–109).  Source of the verbatim quotations: `paper/pdf/S17_Another_extension_of_RR.md`,
`## Numbered statements`.

Every defined term used here already lives in an imported module; nothing is
restated:

* `Workspace.Types.Core` — `IsPathList`, `IsPathFrom`, `IsAntipathFrom`,
  `pathLength`, `SPGT.interior`, `VertexComplete`, `VertexAnticomplete`,
  `EdgeComplete`, `ConnectedSet`, `AnticonnectedSet`;
* `Workspace.Types.RousselRubio` — `IsTriangle` (§2's *triangle*);
* `Workspace.Types.TriangleCatching` — `IsReflectionOfTriangle` (§17's
  *reflection*), `Catches` (§17's *catch*);
* `Workspace.Types.Classes` — `InF7` (the class `F₇` of §1).

Encoding conventions (see `paper/spec/CONVENTIONS.md`):

* a *path* of the paper is the list `p : List V` of its vertices in order,
  together with `IsPathList G p`; its length is `pathLength p`, its interior `P*`
  is `SPGT.interior p` (always written qualified — a bare `interior` is Mathlib's
  topological one), and `V(P)` is `{w : V | w ∈ p}`;
* "`X ⊆ V(G) \ V(P)`" is `∀ w ∈ p, w ∉ X`;
* an "`X`-complete vertex" is `VertexComplete G v X` and an "`X`-complete edge" is
  `EdgeComplete G X u v`;
* **the number of `X`-complete edges of `P`.**  Paths of the paper are *induced*
  subgraphs, so the edges of `P` are exactly the adjacent pairs of vertices of
  `P`, and their number is
  `{e : Sym2 V | ∃ u ∈ p, ∃ v ∈ p, e = s(u, v) ∧ EdgeComplete G X u v}.ncard` —
  a set of *unordered* pairs, so each edge is counted exactly once (this is the
  convention already used in `Workspace.Statements.S02`);
* the paper's `pₙ₋₁` is written `pn1` (the subscript minus `₋` is not a Lean
  identifier character), pinned down by `p.dropLast.getLast? = some pn1`.
-/

set_option autoImplicit false

namespace Workspace.Statements.S17

open Workspace.Types.Core Workspace.Types.Core.SPGT
open Workspace.Types.RousselRubio Workspace.Types.RousselRubio.SPGT
open Workspace.Types.TriangleCatching Workspace.Types.TriangleCatching.SPGT
open Workspace.Types.Classes Workspace.Types.Classes.SPGT

namespace SPGT

variable {V : Type*} [Fintype V] [DecidableEq V]


/-- **17.4** (printed p. 105).

PAPER: *"Let `G ∈ F₇` and let `P` be a path in `G` with length `> 1`, with
vertices `p₁,…,pₙ` in order.  Let `X,Y ⊆ V(G) \ V(P)` be anticonnected sets, such
that `X ∪ Y` is anticonnected, `p₁` is `X`-complete, and `pₙ` is the unique
`Y`-complete vertex in `P`.  (Note that `X,Y` need not be disjoint.)  Let
`z ∈ V(G) \ (X ∪ Y ∪ V(P))`, complete to `X ∪ Y` and with no neighbours in `P`.
Assume that `pₙ` is not `X`-complete.  Let `pₙ`-`x₁`-`⋯`-`x_k`-`y` be an antipath
with interior in `X` from `pₙ` to some `y ∈ Y`.  Then `pₙ₋₁` is nonadjacent to
`x₁`."*

(Introduced by: *"The next result is just a technical lemma for use in proving the
main result of this section, which is 17.5."*)

Encoding notes.

* The antipath is the list `q` with `IsAntipathFrom G q pₙ y` and interior in `X`.
  The paper names its vertices `pₙ, x₁, …, x_k, y`, so `x₁` is the vertex right
  after `pₙ`, i.e. the *first interior vertex*:
  `(SPGT.interior q).head? = some x₁`.  This also records that the list of
  `x`'s is non-empty (`k ≥ 1`), which the paper's notation presupposes — without
  it the "antipath" could be the single edge `pₙ`-`y`, in which case there is no
  `x₁` at all.
* `pₙ₋₁` is written `pn1`, pinned by `p.dropLast.getLast? = some pn1`. -/
theorem thm_17_4 (G : SimpleGraph V) (hG : InF7 G)
    (p : List V) (p₁ pn1 pₙ : V) (hp : IsPathList G p) (hlen : 1 < pathLength p)
    (hhead : p.head? = some p₁) (hlast : p.getLast? = some pₙ)
    (hlast1 : p.dropLast.getLast? = some pn1)
    (X Y : Set V) (hXP : ∀ w ∈ p, w ∉ X) (hYP : ∀ w ∈ p, w ∉ Y)
    (hXa : AnticonnectedSet G X) (hYa : AnticonnectedSet G Y)
    (hXYa : AnticonnectedSet G (X ∪ Y))
    (hp₁X : VertexComplete G p₁ X)
    (hYuniq : ∀ w ∈ p, (VertexComplete G w Y ↔ w = pₙ))
    (z : V) (hz : z ∉ X ∪ Y) (hzP : z ∉ p)
    (hzXY : VertexComplete G z (X ∪ Y))
    (hznb : VertexAnticomplete G z {w : V | w ∈ p})
    (hpₙX : ¬ VertexComplete G pₙ X)
    (y x₁ : V) (hy : y ∈ Y) (q : List V) (hq : IsAntipathFrom G q pₙ y)
    (hqint : ∀ w ∈ SPGT.interior q, w ∈ X)
    (hx₁ : (SPGT.interior q).head? = some x₁) :
    ¬ G.Adj pn1 x₁ := by
  exact Workspace.ProofLemmas.Thm174Main.main G hG p p₁ pn1 pₙ hp hlen hhead hlast
    hlast1 X Y hXP hYP hXa hYa hXYa hp₁X hYuniq z hz hzP hzXY hznb hpₙX
    y x₁ hy q hq hqint hx₁


end SPGT

end Workspace.Statements.S17
