/-  GENERATED by scripts/split_statements.py from Workspace/Statements/S17.lean -- one numbered statement
    of the paper per module.  The theorem below, its doc-comment and its
    signature are byte-identical to the source module; only the surrounding
    file was mechanically re-cut.  See PROVING_PLAN.md.  -/
import Mathlib
import Workspace.Types.Core
import Workspace.Types.RousselRubio
import Workspace.Types.TriangleCatching
import Workspace.Types.Classes
import Workspace.ProofLemmas.Thm175Endgame

/-!
# Section 17 — Another extension of the Roussel–Rubio lemma

The five numbered statements 17.1 … 17.5 of Chudnovsky–Robertson–Seymour–Thomas,
*The Strong Perfect Graph Theorem* (published/Annals version, printed pages
102–109).  Source of the verbatim quotations: `paper/pdf/S17_Another_extension_of_RR.md`,
`## Numbered statements`.

Every defined term used here already lives in an imported module; nothing is
restated:

* `Workspace.Types.Core` — `IsPathList`, `IsPathFrom`, `IsAntipathFrom`,
  `pathLength`, `SPGT.interior`, `VertexComplete`, `VertexAnticomplete`,
  `EdgeComplete`, `ConnectedSet`, `AnticonnectedSet`;
* `Workspace.Types.RousselRubio` — `IsTriangle` (§2's *triangle*);
* `Workspace.Types.TriangleCatching` — `IsReflectionOfTriangle` (§17's
  *reflection*), `Catches` (§17's *catch*);
* `Workspace.Types.Classes` — `InF7` (the class `F₇` of §1).

Encoding conventions (see `paper/spec/CONVENTIONS.md`):

* a *path* of the paper is the list `p : List V` of its vertices in order,
  together with `IsPathList G p`; its length is `pathLength p`, its interior `P*`
  is `SPGT.interior p` (always written qualified — a bare `interior` is Mathlib's
  topological one), and `V(P)` is `{w : V | w ∈ p}`;
* "`X ⊆ V(G) \ V(P)`" is `∀ w ∈ p, w ∉ X`;
* an "`X`-complete vertex" is `VertexComplete G v X` and an "`X`-complete edge" is
  `EdgeComplete G X u v`;
* **the number of `X`-complete edges of `P`.**  Paths of the paper are *induced*
  subgraphs, so the edges of `P` are exactly the adjacent pairs of vertices of
  `P`, and their number is
  `{e : Sym2 V | ∃ u ∈ p, ∃ v ∈ p, e = s(u, v) ∧ EdgeComplete G X u v}.ncard` —
  a set of *unordered* pairs, so each edge is counted exactly once (this is the
  convention already used in `Workspace.Statements.S02`);
* the paper's `pₙ₋₁` is written `pn1` (the subscript minus `₋` is not a Lean
  identifier character), pinned down by `p.dropLast.getLast? = some pn1`.
-/

set_option autoImplicit false

namespace Workspace.Statements.S17

open Workspace.Types.Core Workspace.Types.Core.SPGT
open Workspace.Types.RousselRubio Workspace.Types.RousselRubio.SPGT
open Workspace.Types.TriangleCatching Workspace.Types.TriangleCatching.SPGT
open Workspace.Types.Classes Workspace.Types.Classes.SPGT

namespace SPGT

variable {V : Type*} [Fintype V] [DecidableEq V]


/-- **17.5** — the main result of Section 17 (printed p. 105).

PAPER: *"Let `G ∈ F₇` and let `P` be an odd path in `G` with length `> 1`, with
vertices `p₁,…,pₙ` in order.  Let `X,Y ⊆ V(G) \ V(P)` be anticonnected sets, such
that `X ∪ Y` is anticonnected, `p₁` is `X`-complete, and `pₙ` is the unique
`Y`-complete vertex in `P`.  (Note that `X,Y` need not be disjoint.)  Let
`z ∈ V(G) \ (X ∪ Y ∪ V(P))`, complete to `X ∪ Y` and with no neighbours in `P`.
Then an odd number of edges of `P` are `X`-complete."*

(Preceded by: *"… Incidentally, unlike 2.9, what we are going to prove here is not
true for general Berge graphs — we need the hypothesis that `G ∈ F₇`."*)

Note that, unlike 17.4, this statement does **not** assume that `pₙ` fails to be
`X`-complete.  For the edge-counting convention see the module docstring. -/
theorem thm_17_5 (G : SimpleGraph V) (hG : InF7 G)
    (p : List V) (p₁ pₙ : V) (hp : IsPathList G p)
    (hodd : Odd (pathLength p)) (hlen : 1 < pathLength p)
    (hhead : p.head? = some p₁) (hlast : p.getLast? = some pₙ)
    (X Y : Set V) (hXP : ∀ w ∈ p, w ∉ X) (hYP : ∀ w ∈ p, w ∉ Y)
    (hXa : AnticonnectedSet G X) (hYa : AnticonnectedSet G Y)
    (hXYa : AnticonnectedSet G (X ∪ Y))
    (hp₁X : VertexComplete G p₁ X)
    (hYuniq : ∀ w ∈ p, (VertexComplete G w Y ↔ w = pₙ))
    (z : V) (hz : z ∉ X ∪ Y) (hzP : z ∉ p)
    (hzXY : VertexComplete G z (X ∪ Y))
    (hznb : VertexAnticomplete G z {w : V | w ∈ p}) :
    Odd {e : Sym2 V | ∃ u ∈ p, ∃ v ∈ p, e = s(u, v) ∧ EdgeComplete G X u v}.ncard := by
  classical
  by_contra hnotOdd
  have heven : Even {e : Sym2 V | ∃ u ∈ p, ∃ v ∈ p,
      e = s(u, v) ∧ EdgeComplete G X u v}.ncard :=
    Nat.not_odd_iff_even.mp hnotOdd
  let c₀ : Workspace.ProofLemmas.Thm175Optimal.Counterexample G z :=
    { X := X
      Y := Y
      core :=
        { p := p
          p₁ := p₁
          pₙ := pₙ
          hp := ⟨hp, hhead, hlast⟩
          hodd := hodd
          hlong := hlen
          houtX := hXP
          houtY := hYP
          hp₁X := hp₁X
          hYuniq := hYuniq
          hzP := hzP
          hzanti := hznb
          heven := heven }
      hXa := hXa
      hYa := hYa
      hXYa := hXYa
      hz := hz
      hzXY := hzXY }
  obtain ⟨c, hopt⟩ :=
    Workspace.ProofLemmas.Thm175Optimal.exists_optimal c₀
  exact Workspace.ProofLemmas.Thm175Endgame.optimal_counterexample_absurd
    G hG z c hopt


end SPGT

end Workspace.Statements.S17
