/-  GENERATED by scripts/split_statements.py from Workspace/Statements/S17.lean -- one numbered statement
    of the paper per module.  The theorem below, its doc-comment and its
    signature are byte-identical to the source module; only the surrounding
    file was mechanically re-cut.  See PROVING_PLAN.md.  -/
import Mathlib
import Workspace.Types.Core
import Workspace.Types.RousselRubio
import Workspace.Types.TriangleCatching
import Workspace.Types.Classes
import Workspace.ProofLemmas.Thm173Core

/-!
# Section 17 — Another extension of the Roussel–Rubio lemma

The five numbered statements 17.1 … 17.5 of Chudnovsky–Robertson–Seymour–Thomas,
*The Strong Perfect Graph Theorem* (published/Annals version, printed pages
102–109).  Source of the verbatim quotations: `paper/pdf/S17_Another_extension_of_RR.md`,
`## Numbered statements`.

Every defined term used here already lives in an imported module; nothing is
restated:

* `Workspace.Types.Core` — `IsPathList`, `IsPathFrom`, `IsAntipathFrom`,
  `pathLength`, `SPGT.interior`, `VertexComplete`, `VertexAnticomplete`,
  `EdgeComplete`, `ConnectedSet`, `AnticonnectedSet`;
* `Workspace.Types.RousselRubio` — `IsTriangle` (§2's *triangle*);
* `Workspace.Types.TriangleCatching` — `IsReflectionOfTriangle` (§17's
  *reflection*), `Catches` (§17's *catch*);
* `Workspace.Types.Classes` — `InF7` (the class `F₇` of §1).

Encoding conventions (see `paper/spec/CONVENTIONS.md`):

* a *path* of the paper is the list `p : List V` of its vertices in order,
  together with `IsPathList G p`; its length is `pathLength p`, its interior `P*`
  is `SPGT.interior p` (always written qualified — a bare `interior` is Mathlib's
  topological one), and `V(P)` is `{w : V | w ∈ p}`;
* "`X ⊆ V(G) \ V(P)`" is `∀ w ∈ p, w ∉ X`;
* an "`X`-complete vertex" is `VertexComplete G v X` and an "`X`-complete edge" is
  `EdgeComplete G X u v`;
* **the number of `X`-complete edges of `P`.**  Paths of the paper are *induced*
  subgraphs, so the edges of `P` are exactly the adjacent pairs of vertices of
  `P`, and their number is
  `{e : Sym2 V | ∃ u ∈ p, ∃ v ∈ p, e = s(u, v) ∧ EdgeComplete G X u v}.ncard` —
  a set of *unordered* pairs, so each edge is counted exactly once (this is the
  convention already used in `Workspace.Statements.S02`);
* the paper's `pₙ₋₁` is written `pn1` (the subscript minus `₋` is not a Lean
  identifier character), pinned down by `p.dropLast.getLast? = some pn1`.
-/

set_option autoImplicit false

namespace Workspace.Statements.S17

open Workspace.Types.Core Workspace.Types.Core.SPGT
open Workspace.Types.RousselRubio Workspace.Types.RousselRubio.SPGT
open Workspace.Types.TriangleCatching Workspace.Types.TriangleCatching.SPGT
open Workspace.Types.Classes Workspace.Types.Classes.SPGT

namespace SPGT

variable {V : Type*} [Fintype V] [DecidableEq V]


/-- **17.3** (printed p. 105).

PAPER: *"Let `G ∈ F₇`, and let `F,Y ⊆ V(G)` be disjoint, such that `F` is
connected and `Y` is anticonnected.  Let `a₀,b₀ ∈ V(G) \ (F ∪ Y)` and `a,b ∈ F`
such that `a`-`a₀`-`b₀`-`b` is a 3-edge path in `G`.  Suppose that:*

* *`a₀,b₀` are both `Y`-complete, and `a,b` are not `Y`-complete,*
* *the only neighbours of `a₀,b₀` in `F` are `a` and `b` respectively,*
* *`F \ {a}` is connected.*

*Then there is a vertex `y ∈ Y` with no neighbour in `F \ {a}`."*

(Introduced by: *"The following is a variant of 17.2, not so symmetrical, but more
useful."*  Note that only `F \ {a}` — not also `F \ {b}` — is assumed connected.)

Same encoding as 17.2; *"no neighbour in `F \ {a}`"* is
`VertexAnticomplete G y (F \ {a})`. -/
theorem thm_17_3 (G : SimpleGraph V) (hG : InF7 G) (F Y : Set V)
    (hFY : Disjoint F Y) (hF : ConnectedSet G F) (hY : AnticonnectedSet G Y)
    (a₀ b₀ a b : V) (ha₀ : a₀ ∉ F ∪ Y) (hb₀ : b₀ ∉ F ∪ Y)
    (ha : a ∈ F) (hb : b ∈ F)
    (hpath : IsPathList G [a, a₀, b₀, b])
    (ha₀Y : VertexComplete G a₀ Y) (hb₀Y : VertexComplete G b₀ Y)
    (haY : ¬ VertexComplete G a Y) (hbY : ¬ VertexComplete G b Y)
    (ha₀F : {f ∈ F | G.Adj a₀ f} = {a}) (hb₀F : {f ∈ F | G.Adj b₀ f} = {b})
    (hFa : ConnectedSet G (F \ {a})) :
    ∃ y ∈ Y, VertexAnticomplete G y (F \ {a}) := by
  exact Workspace.ProofLemmas.Thm173Core.main G hG F Y hFY hF hY a₀ b₀ a b
    ha₀ hb₀ ha hb hpath ha₀Y hb₀Y haY hbY ha₀F hb₀F hFa


end SPGT

end Workspace.Statements.S17
