/-  GENERATED by scripts/split_statements.py from Workspace/Statements/S17.lean -- one numbered statement
    of the paper per module.  The theorem below, its doc-comment and its
    signature are byte-identical to the source module; only the surrounding
    file was mechanically re-cut.  See PROVING_PLAN.md.  -/
import Mathlib
import Workspace.Types.Core
import Workspace.Types.RousselRubio
import Workspace.Types.TriangleCatching
import Workspace.Types.Classes
import Workspace.Statements.S02.Thm_2_3
import Workspace.Statements.S02.Thm_2_4
import Workspace.ProofLemmas.NoPathMeetsThreeCatchNeighborSets
import Workspace.ProofLemmas.MinimalCatchHasUniqueTriangleNeighbors
import Workspace.ProofLemmas.UniqueAttachmentForcesTwoTriangleNeighbors
import Workspace.ProofLemmas.DoubleAttachmentForcesTriangleReflection
import Workspace.ProofLemmas.InducedPathExtraction
import Workspace.ProofLemmas.PathBasics
import Workspace.ProofLemmas.NearestPathAttachment
import Workspace.ProofLemmas.AttachmentIndicesAreLocal
import Workspace.ProofLemmas.ConnectedSetUnionAttach

set_option linter.unusedVariables false

/-!
# Section 17 — Another extension of the Roussel–Rubio lemma

The five numbered statements 17.1 … 17.5 of Chudnovsky–Robertson–Seymour–Thomas,
*The Strong Perfect Graph Theorem* (published/Annals version, printed pages
102–109).  Source of the verbatim quotations: `paper/pdf/S17_Another_extension_of_RR.md`,
`## Numbered statements`.

Every defined term used here already lives in an imported module; nothing is
restated:

* `Workspace.Types.Core` — `IsPathList`, `IsPathFrom`, `IsAntipathFrom`,
  `pathLength`, `SPGT.interior`, `VertexComplete`, `VertexAnticomplete`,
  `EdgeComplete`, `ConnectedSet`, `AnticonnectedSet`;
* `Workspace.Types.RousselRubio` — `IsTriangle` (§2's *triangle*);
* `Workspace.Types.TriangleCatching` — `IsReflectionOfTriangle` (§17's
  *reflection*), `Catches` (§17's *catch*);
* `Workspace.Types.Classes` — `InF7` (the class `F₇` of §1).

Encoding conventions (see `paper/spec/CONVENTIONS.md`):

* a *path* of the paper is the list `p : List V` of its vertices in order,
  together with `IsPathList G p`; its length is `pathLength p`, its interior `P*`
  is `SPGT.interior p` (always written qualified — a bare `interior` is Mathlib's
  topological one), and `V(P)` is `{w : V | w ∈ p}`;
* "`X ⊆ V(G) \ V(P)`" is `∀ w ∈ p, w ∉ X`;
* an "`X`-complete vertex" is `VertexComplete G v X` and an "`X`-complete edge" is
  `EdgeComplete G X u v`;
* **the number of `X`-complete edges of `P`.**  Paths of the paper are *induced*
  subgraphs, so the edges of `P` are exactly the adjacent pairs of vertices of
  `P`, and their number is
  `{e : Sym2 V | ∃ u ∈ p, ∃ v ∈ p, e = s(u, v) ∧ EdgeComplete G X u v}.ncard` —
  a set of *unordered* pairs, so each edge is counted exactly once (this is the
  convention already used in `Workspace.Statements.S02`);
* the paper's `pₙ₋₁` is written `pn1` (the subscript minus `₋` is not a Lean
  identifier character), pinned down by `p.dropLast.getLast? = some pn1`.
-/

set_option autoImplicit false

namespace Workspace.Statements.S17

open Workspace.Types.Core Workspace.Types.Core.SPGT
open Workspace.Types.RousselRubio Workspace.Types.RousselRubio.SPGT
open Workspace.Types.TriangleCatching Workspace.Types.TriangleCatching.SPGT
open Workspace.Types.Classes Workspace.Types.Classes.SPGT

namespace SPGT

variable {V : Type*} [Fintype V] [DecidableEq V]


/-- **17.1** (printed p. 102).

PAPER: *"Let `A` be a triangle in a graph `G ∈ F₇`, and let `F ⊆ V(G) \ A` catch
`A`.  Then either `F` contains a reflection of `A`, or some vertex of `F` has
`≥ 2` neighbours in `A`."*

Encoding notes.

* *"`F ⊆ V(G) \ A`"* is `F ⊆ Aᶜ`.  (`Catches` already contains `Disjoint F A`, so
  this hypothesis is redundant; it is kept because the paper prints it.)
* *"`F` contains a reflection of `A`"*: a reflection of `A` is a triangle
  `{b₁,b₂,b₃}` matched vertex-by-vertex with `A = {a₁,a₂,a₃}`
  (`IsReflectionOfTriangle`), and *contains* means `{b₁,b₂,b₃} ⊆ F`.
* *"some vertex of `F` has `≥ 2` neighbours in `A`"* is
  `2 ≤ (G.neighborSet f ∩ A).ncard` for some `f ∈ F`; the set is a subset of the
  three-element set `A`, so its `ncard` is its genuine cardinality. -/
theorem thm_17_1 (G : SimpleGraph V) (hG : InF7 G) (A : Set V) (hA : IsTriangle G A)
    (F : Set V) (hFA : F ⊆ Aᶜ) (hcatch : Catches G F A) :
    (∃ a₁ a₂ a₃ b₁ b₂ b₃ : V, A = {a₁, a₂, a₃} ∧ ({b₁, b₂, b₃} : Set V) ⊆ F ∧
        IsReflectionOfTriangle G a₁ a₂ a₃ b₁ b₂ b₃) ∨
    (∃ f ∈ F, 2 ≤ (G.neighborSet f ∩ A).ncard) := by
  classical
  by_contra hconcl
  have hnoReflection : ¬ ∃ a₁ a₂ a₃ b₁ b₂ b₃ : V,
      A = {a₁, a₂, a₃} ∧ ({b₁, b₂, b₃} : Set V) ⊆ F ∧
        IsReflectionOfTriangle G a₁ a₂ a₃ b₁ b₂ b₃ := by
    intro href
    exact hconcl (Or.inl href)
  have hnoTwo : ¬ ∃ f ∈ F, 2 ≤ (G.neighborSet f ∩ A).ncard := by
    intro htwo
    exact hconcl (Or.inr htwo)
  have hex : ∃ n : ℕ, ∃ S : Set V,
      S ⊆ F ∧ Catches G S A ∧ S.ncard = n := by
    exact ⟨F.ncard, F, Set.Subset.rfl, hcatch, rfl⟩
  obtain ⟨Fm, hFmF, hcatchm, hFmcard⟩ := Nat.find_spec hex
  have hmin : ∀ S : Set V, S ⊆ Fm → Catches G S A → Fm.ncard ≤ S.ncard := by
    intro S hSFm hcatchS
    rw [hFmcard]
    exact Nat.find_min' hex ⟨S, hSFm.trans hFmF, hcatchS, rfl⟩
  have hatMostOne : ∀ f ∈ Fm, ¬ 2 ≤ (G.neighborSet f ∩ A).ncard := by
    intro f hf htwo
    exact hnoTwo ⟨f, hFmF hf, htwo⟩
  obtain ⟨a₁, a₂, a₃, ha₁₂, ha₁₃, ha₂₃, hAeq⟩ :=
    Set.ncard_eq_three.mp hA.1
  obtain ⟨b₁, b₂, b₃, hb₁F, hb₂F, hb₃F,
      hb₁₂, hb₁₃, hb₂₃, hadj, hcatch_iff, hterminal, hnoThreePath⟩ :=
    Workspace.Types.MinimalCatchHasUniqueTriangleNeighbors.minimalCatchHasUniqueTriangleNeighbors
      G hG A Fm a₁ a₂ a₃ hA hAeq
        ⟨ha₁₂, ha₁₃, ha₂₃⟩ hcatchm hatMostOne hmin
  obtain ⟨P, hP, hPF⟩ :=
    Workspace.ProofLemmas.InducedPathExtraction.exists_isPathFrom_of_connected
      hcatchm.2.1 hb₁F hb₂F
  have hb₁P : b₁ ∈ P := Workspace.ProofLemmas.PathBasics.head_mem hP.2.1
  have hb₂P : b₂ ∈ P := Workspace.ProofLemmas.PathBasics.getLast_mem hP.2.2
  have hb₃P : b₃ ∉ P := by
    intro hb₃P
    exact hnoThreePath ⟨P, hP.1, hPF, hb₁P, hb₂P, hb₃P⟩
  obtain ⟨R, w, hR, hRF, hwP, hRlen, hinter, hclean⟩ :=
    Workspace.Types.NearestPathAttachment.nearestPathAttachment
      G Fm P b₃ hcatchm.2.1 hP.1 hPF hb₃F hb₃P
  have hPconn : ConnectedSet G {x : V | x ∈ P} :=
    Workspace.ProofLemmas.InducedPathExtraction.connectedSet_setOf_mem_of_isPathList hP.1
  have hRconn : ConnectedSet G {x : V | x ∈ R} :=
    Workspace.ProofLemmas.InducedPathExtraction.connectedSet_setOf_mem_of_isPathList hR.1
  have hunionConn : ConnectedSet G ({x : V | x ∈ P} ∪ {x : V | x ∈ R}) :=
    Workspace.ProofLemmas.ConnectedSetUnionAttach.connectedSet_union hPconn hRconn
      (Or.inl ⟨w, hwP, Workspace.ProofLemmas.PathBasics.getLast_mem hR.2.2⟩)
  have hunionSub : ({x : V | x ∈ P} ∪ {x : V | x ∈ R}) ⊆ Fm := by
    intro x hx
    rcases hx with hxP | hxR
    · exact hPF x hxP
    · exact hRF x hxR
  have hb₁Union : b₁ ∈ ({x : V | x ∈ P} ∪ {x : V | x ∈ R}) := Or.inl hb₁P
  have hb₂Union : b₂ ∈ ({x : V | x ∈ P} ∪ {x : V | x ∈ R}) := Or.inl hb₂P
  have hb₃Union : b₃ ∈ ({x : V | x ∈ P} ∪ {x : V | x ∈ R}) :=
    Or.inr (Workspace.ProofLemmas.PathBasics.head_mem hR.2.1)
  have hcover : Fm = {x : V | x ∈ P} ∪ {x : V | x ∈ R} :=
    (hterminal _ hunionSub hunionConn hb₁Union hb₂Union hb₃Union).symm
  let v : Fin 3 → V := ![b₁, b₂, b₃]
  let N : Fin 3 → Set V := fun i => {v i}
  have hv : ∀ i : Fin 3, v i ∈ Fm ∧ v i ∈ N i := by
    intro i
    fin_cases i <;> simp [v, N, hb₁F, hb₂F, hb₃F]
  have hlocalMin : ∀ S : Set V, S ⊆ Fm → ConnectedSet G S →
      (∀ i : Fin 3, ∃ x ∈ S, x ∈ N i) → Fm.ncard ≤ S.ncard := by
    intro S hSFm hSconn hmeet
    have hvS : ∀ i : Fin 3, v i ∈ S := by
      intro i
      obtain ⟨x, hxS, hxN⟩ := hmeet i
      have hx : x = v i := by simpa [N] using hxN
      simpa [hx] using hxS
    have hSeq : S = Fm := by
      apply hterminal S hSFm hSconn
      · simpa [v] using hvS 0
      · simpa [v] using hvS 1
      · simpa [v] using hvS 2
    rw [hSeq]
  obtain ⟨s, hs, hcases⟩ :=
    Workspace.Types.AttachmentIndicesAreLocal.attachmentIndicesAreLocal
      G Fm N v hv hlocalMin P R w (by simpa [v] using hP) (by simpa [v] using hR)
        (by simpa [v] using hb₃P) hwP hRlen hinter hcover
  rcases hcases with ⟨hsingle, _⟩ | ⟨hdouble, _⟩
  · let y : V := P[s]'hs
    have hyP : y ∈ P := List.getElem_mem hs
    have hattach : ∀ p ∈ P,
        G.Adj (R[R.length - 2]'(by omega)) p ↔ p = y := by
      intro p hp
      obtain ⟨d, hd, hdp⟩ := List.getElem_of_mem hp
      subst p
      rw [hsingle d hd]
      constructor
      · intro hds
        subst d
        rfl
      · intro heq
        exact hP.1.2.1.getElem_inj_iff.mp heq
    have htwo :=
      Workspace.Types.UniqueAttachmentForcesTwoTriangleNeighbors.uniqueAttachmentForcesTwoTriangleNeighbors
        G hG.1.1.1.1 A Fm
          a₁ a₂ a₃ b₁ b₂ b₃ hA hAeq ⟨ha₁₂, ha₁₃, ha₂₃⟩
          ⟨hb₁₂, hb₁₃, hb₂₃⟩ ⟨hb₁F, hb₂F, hb₃F⟩ hcatchm.2.2.1 hadj
          P R w y hP hPF hR hRF hb₃P hwP hRlen hinter hclean hyP hattach
    exact hnoTwo ⟨y, hFmF (hPF y hyP), htwo⟩
  · obtain ⟨hsucc, hdouble⟩ := hdouble
    let y : V := P[s]'hs
    let z : V := P[s + 1]'hsucc
    have hattach : ∀ p ∈ P,
        G.Adj (R[R.length - 2]'(by omega)) p ↔ p = y ∨ p = z := by
      intro p hp
      obtain ⟨d, hd, hdp⟩ := List.getElem_of_mem hp
      subst p
      rw [hdouble d hd]
      constructor
      · rintro (hds | hds)
        · left
          subst d
          rfl
        · right
          subst d
          rfl
      · rintro (heq | heq)
        · exact Or.inl (hP.1.2.1.getElem_inj_iff.mp heq)
        · exact Or.inr (hP.1.2.1.getElem_inj_iff.mp heq)
    obtain ⟨hbSub, hreflection⟩ :=
      Workspace.Types.DoubleAttachmentForcesTriangleReflection.doubleAttachmentForcesTriangleReflection
        G hG A Fm
          a₁ a₂ a₃ b₁ b₂ b₃ hA hAeq ⟨ha₁₂, ha₁₃, ha₂₃⟩
          ⟨hb₁₂, hb₁₃, hb₂₃⟩ ⟨hb₁F, hb₂F, hb₃F⟩ hcatchm.2.2.1 hadj
          P R w hP hPF hR hRF hb₃P hwP hRlen hinter hclean s y z hsucc rfl rfl hattach
    exact hnoReflection ⟨a₁, a₂, a₃, b₁, b₂, b₃, hAeq,
      hbSub.trans hFmF, hreflection⟩


end SPGT

end Workspace.Statements.S17
