import Mathlib
import Workspace.Types.Core
import Workspace.Types.Tracks
import Workspace.Types.Prisms
import Workspace.ProofLemmas.Thm101ThetaOfPrism
import Workspace.ProofLemmas.Thm101ThetaAddBranch
import Workspace.ProofLemmas.SubdivisionCounting
import Workspace.ProofLemmas.SubdivisionCompose
import Workspace.ProofLemmas.PathBasics
import Workspace.ProofLemmas.PathGlue
import Workspace.ProofLemmas.TrackSlice
import Workspace.ProofLemmas.HyperprismFromPrism
import Workspace.ProofLemmas.PrismSymmetry

/-!
# The theta graph with an extra branch is bipartite

Fourth of the five modules decomposing
`Workspace.ProofLemmas.Thm101CaseOneK4AppearanceWitness`.

## What it discharges

The word **bipartite** in 10.1.1 (printed p. 56):

> *"… the line graph of a **bipartite** subdivision of `K₄`."*

## The four cycles

`H` is a subdivision of `K₄` on the branch-vertices `x, y, z, z'`, so its cycle space is
generated by the four cycles carried by the four triangles of `K₄`.  Writing
`ℓᵢ = trackLength (Q i) = (R i).length`, `s`/`s'` for the two pieces of `Q 0` split at `z`,
`t`/`t'` for the two pieces of `Q 1` split at `z'`, and `n = trackLength p = f.length`:

| triangle of `K₄` | cycle length in `H` | why it is even |
|---|---|---|
| `x y z`  | `ℓ₂ + ℓ₀` | **7.2** — `pathLength (R 0) ≡ pathLength (R 2)` |
| `x y z'` | `ℓ₂ + ℓ₁` | **7.2** — `pathLength (R 0) ≡ pathLength (R 1)` |
| `x z z'` | `s + n + t`    | **Berge** — it is the `G`-hole `a₀-⋯-u-f₁-⋯-fₙ-w-⋯-a₁-a₀` |
| `y z z'` | `s' + n + t'`  | **Berge** — it is the `G`-hole `b₀-⋯-u'-f₁-⋯-fₙ-w'-⋯-b₁-b₀` |

## Why `hfNonmajor` is in the binder list

The last two rows need the `G`-cycle to have length `≥ 4`, i.e. to be a *hole*; Berge says
nothing about triangles.  The two lengths sum to `ℓ₀ + ℓ₁ + 2n`, which 7.2 makes even, so if
exactly one of them is `3` the other is odd and `≥ 4`, contradicting Berge.  The one surviving
possibility is that **both** are `3`, i.e.

  `ℓ₀ = ℓ₁ = 2` (so `pathLength (R 0) = pathLength (R 1) = 1`)  and  `f.length = 1`,

and there `H` really does contain the triangle `x z z'` and is **not** bipartite.  That
configuration is excluded not by Berge but by `hfNonmajor`: with `ℓ₀ = ℓ₁ = 2` the rungs are
`R 0 = [a₀, b₀]` and `R 1 = [a₁, b₁]`, so `{u, u'} = {a₀, b₀}` and `{w, w'} = {a₁, b₁}`, and
with `f.length = 1` we have `f₁ = fₙ` adjacent to all four of `a₀, b₀, a₁, b₁` — i.e. `f₁` is
major with respect to the prism.

So the full 10.1 case-1 context is carried below, not just `Berge G` and 7.2.  A prover who
tries to get by on those two alone will be stuck on exactly this one configuration.

## Which `decide` in `NinePrismLineGraph` this generalises

`NinePrismLineGraph.theta_bipartite`, whose proof is

  `refine ⟨SimpleGraph.Coloring.mk ![0, 1, 1, 1, 1, 0, 0, 0] ?_⟩; intro u v h; revert h;`
  `revert u v; decide`

— an explicit two-colouring of the eight fixed vertices, checked by kernel evaluation.  In the
general case the colouring is *"the parity of the distance along its track from `x`"*, and the
`decide` is replaced by the four parity obligations tabulated above.
-/

set_option autoImplicit false

namespace Workspace.ProofLemmas

open Workspace.Types.Core.SPGT
open Workspace.Types.Tracks.SPGT
open Workspace.Types.Prisms.SPGT
open Workspace.ProofLemmas.ThetaData

private theorem pair_mem_iff_of_injective_pair {X : Type*} {a b c d : X}
    (hab : a ≠ b) (hcd : c ≠ d) (ha : a = c ∨ a = d) (hb : b = c ∨ b = d) :
    ∀ t : X, (t = a ∨ t = b) ↔ (t = c ∨ t = d) := by
  intro t
  rcases ha with ha | ha <;> rcases hb with hb | hb
  · exact (hab (ha.trans hb.symm)).elim
  · simp only [ha, hb]
  · simp only [ha, hb, or_comm]
  · exact (hab (ha.trans hb.symm)).elim

private theorem isPathFrom_slice_le {V : Type*} {G : SimpleGraph V} {q : List V}
    (hq : IsPathList G q) {i j : ℕ} (hij : i ≤ j) (hj : j < q.length) :
    IsPathFrom G (Workspace.ProofLemmas.TrackSlice.slice q i j)
      (q[i]'(by omega)) (q[j]'hj) := by
  refine ⟨?_, Workspace.ProofLemmas.PathBasics.head?_slice q hij hj,
    Workspace.ProofLemmas.PathBasics.getLast?_slice q hij hj⟩
  rcases eq_or_lt_of_le hij with heq | hlt
  · have hlen : (Workspace.ProofLemmas.TrackSlice.slice q i j).length = 1 := by
      rw [Workspace.ProofLemmas.TrackSlice.length_slice q hj hij]
      omega
    obtain ⟨v, hv⟩ := List.length_eq_one_iff.mp hlen
    rw [hv]
    exact Workspace.ProofLemmas.PathBasics.isPathList_singleton G v
  · exact Workspace.ProofLemmas.PathBasics.isPathList_slice hq hlt hj

private theorem mod_two_eq_of_even_iff {r s : ℕ} (h : Even r ↔ Even s) :
    r % 2 = s % 2 := by
  rw [Nat.even_iff, Nat.even_iff] at h
  have hr := Nat.mod_lt r (by decide : 0 < 2)
  have hs := Nat.mod_lt s (by decide : 0 < 2)
  omega

private theorem thetaExtension_isBipartite_of_parity {m m' : ℕ}
    (Θ : SimpleGraph (Fin m)) (x y : Fin m) (Q : Fin 3 → List (Fin m))
    (hΘ : IsThetaDatum Θ x y Q)
    (z z' : Fin m) (k0 k1 : ℕ)
    (hk0 : k0 < (Q 0).length) (hk1 : k1 < (Q 1).length)
    (hzpos : (Q 0)[k0]'hk0 = z) (hz'pos : (Q 1)[k1]'hk1 = z')
    (H : SimpleGraph (Fin m')) (ρ : Fin m → Fin m') (p : List (Fin m'))
    (hext : IsThetaBranchExtension Θ z z' H ρ p)
    (hQpar : ∀ i : Fin 3, trackLength (Q i) % 2 = trackLength (Q 0) % 2)
    (hpPar : (k0 + trackLength p) % 2 = k1 % 2) :
    H.IsBipartite := by
  classical
  have hQmem : ∀ v : Fin m, ∃ i : Fin 3, v ∈ Q i := by
    intro v
    rcases hΘ.2.2.2.2.2.1 v with rfl | rfl | ⟨i, hi⟩
    · refine ⟨0, List.mem_of_mem_head? ?_⟩
      exact (hΘ.2.1 0).2.1
    · refine ⟨0, List.mem_of_mem_getLast? ?_⟩
      exact (hΘ.2.1 0).2.2
    · exact ⟨i, Workspace.ProofLemmas.SubdivisionCompose.mem_of_mem_trackInterior hi⟩
  let RepΘ := Σ i : Fin 3, Fin ((Q i).length)
  have hRepΘ : ∀ v : Fin m, ∃ r : RepΘ, (Q r.1)[r.2.val]'r.2.isLt = v := by
    intro v
    obtain ⟨i, hi⟩ := hQmem v
    obtain ⟨k, hk, hkv⟩ := List.mem_iff_getElem.mp hi
    exact ⟨⟨i, ⟨k, hk⟩⟩, hkv⟩
  let repΘ : (v : Fin m) → RepΘ := fun v => Classical.choose (hRepΘ v)
  have hrepΘ : ∀ v : Fin m, (Q (repΘ v).1)[(repΘ v).2.val]'(repΘ v).2.isLt = v :=
    fun v => Classical.choose_spec (hRepΘ v)
  have hreprParity : ∀ {i j : Fin 3} {ki kj : ℕ}
      (hki : ki < (Q i).length) (hkj : kj < (Q j).length),
      (Q i)[ki]'hki = (Q j)[kj]'hkj → ki % 2 = kj % 2 := by
    intro i j ki kj hki hkj heq
    by_cases hij : i = j
    · subst j
      have hkij : ki = kj := (hΘ.2.1 i).1.2.1.getElem_inj_iff.mp heq
      omega
    · have hni : (Q i)[ki]'hki ∉ trackInterior (Q i) := by
        intro hint
        exact hΘ.2.2.2.1 i j hij _ hint
          (heq.symm ▸ List.getElem_mem hkj)
      have hnj : (Q j)[kj]'hkj ∉ trackInterior (Q j) := by
        intro hint
        exact hΘ.2.2.2.1 j i (Ne.symm hij) _ hint
          (heq ▸ List.getElem_mem hki)
      have hiEnds := Workspace.ProofLemmas.SubdivisionCompose.mem_ends_of_mem
        (hΘ.2.1 i).2.1 (hΘ.2.1 i).2.2 (List.getElem_mem hki) hni
      have hjEnds := Workspace.ProofLemmas.SubdivisionCompose.mem_ends_of_mem
        (hΘ.2.1 j).2.1 (hΘ.2.1 j).2.2 (List.getElem_mem hkj) hnj
      have hposi : 0 < (Q i).length := by have := hΘ.2.2.1 i; omega
      have hposj : 0 < (Q j).length := by have := hΘ.2.2.1 j; omega
      have hheadi : (Q i)[0]'hposi = x :=
        Workspace.ProofLemmas.SubdivisionCounting.track_head (hΘ.2.1 i) hposi
      have hheadj : (Q j)[0]'hposj = x :=
        Workspace.ProofLemmas.SubdivisionCounting.track_head (hΘ.2.1 j) hposj
      have hlasti : (Q i)[(Q i).length - 1]'(by omega) = y := by
        have h := (hΘ.2.1 i).2.2
        rw [List.getLast?_eq_getElem?, List.getElem?_eq_getElem (by omega)] at h
        exact Option.some_injective _ h
      have hlastj : (Q j)[(Q j).length - 1]'(by omega) = y := by
        have h := (hΘ.2.1 j).2.2
        rw [List.getLast?_eq_getElem?, List.getElem?_eq_getElem (by omega)] at h
        exact Option.some_injective _ h
      rcases hiEnds with hiX | hiY <;> rcases hjEnds with hjX | hjY
      · have eki : ki = 0 := (hΘ.2.1 i).1.2.1.getElem_inj_iff.mp
          (hiX.trans hheadi.symm)
        have ekj : kj = 0 := (hΘ.2.1 j).1.2.1.getElem_inj_iff.mp
          (hjX.trans hheadj.symm)
        omega
      · exact (hΘ.1 (hiX.symm.trans (heq.trans hjY))).elim
      · exact (hΘ.1 (hjX.symm.trans (heq.symm.trans hiY))).elim
      · have eki : ki = (Q i).length - 1 := (hΘ.2.1 i).1.2.1.getElem_inj_iff.mp
          (hiY.trans hlasti.symm)
        have ekj : kj = (Q j).length - 1 := (hΘ.2.1 j).1.2.1.getElem_inj_iff.mp
          (hjY.trans hlastj.symm)
        have hpij : trackLength (Q i) % 2 = trackLength (Q j) % 2 := by
          rw [hQpar i, hQpar j]
        simp only [trackLength] at hpij
        omega
  let cΘNat : Fin m → ℕ := fun v => (repΘ v).2.val % 2
  have hcΘ_at : ∀ (i : Fin 3) (k : ℕ) (hk : k < (Q i).length),
      cΘNat ((Q i)[k]'hk) = k % 2 := by
    intro i k hk
    dsimp only [cΘNat]
    exact hreprParity (repΘ ((Q i)[k]'hk)).2.isLt hk
      ((hrepΘ _).trans rfl)
  have hcΘ_valid : ∀ {c d : Fin m}, Θ.Adj c d → cΘNat c ≠ cΘNat d := by
    intro c d hcd
    have hedge : s(c, d) ∈ Θ.edgeSet := (SimpleGraph.mem_edgeSet Θ).mpr hcd
    rw [hΘ.2.2.2.2.2.2] at hedge
    simp only [Set.mem_iUnion] at hedge
    obtain ⟨i, k, hk, he⟩ := hedge
    rcases Sym2.eq_iff.mp he with h | h
    · rw [h.1, h.2, hcΘ_at i k (by omega), hcΘ_at i (k + 1) hk]
      omega
    · rw [h.1, h.2, hcΘ_at i (k + 1) hk, hcΘ_at i k (by omega)]
      omega
  have hpPos : 0 < p.length := by have := hext.2.2.2.1; omega
  let RepH := Fin m ⊕ Fin p.length
  let repVal : RepH → Fin m' := fun r => Sum.elim ρ (fun k => p[k.val]'k.isLt) r
  have hRepH : ∀ v : Fin m', ∃ r : RepH, repVal r = v := by
    intro v
    rcases hext.2.2.2.2.2.1 v with ⟨c, rfl⟩ | hv
    · exact ⟨Sum.inl c, rfl⟩
    · have hvp := Workspace.ProofLemmas.SubdivisionCompose.mem_of_mem_trackInterior hv
      obtain ⟨k, hk, hkv⟩ := List.mem_iff_getElem.mp hvp
      exact ⟨Sum.inr ⟨k, hk⟩, hkv⟩
  let repH : (v : Fin m') → RepH := fun v => Classical.choose (hRepH v)
  have hrepH : ∀ v : Fin m', repVal (repH v) = v := fun v =>
    Classical.choose_spec (hRepH v)
  let repColor : RepH → ℕ := fun r => Sum.elim cΘNat
    (fun k => (k0 + k.val) % 2) r
  have hcΘz : cΘNat z = k0 % 2 := by simpa only [hzpos] using hcΘ_at 0 k0 hk0
  have hcΘz' : cΘNat z' = k1 % 2 := by simpa only [hz'pos] using hcΘ_at 1 k1 hk1
  have hcrossColor : ∀ (c : Fin m) (j : Fin p.length),
      repVal (Sum.inl c) = repVal (Sum.inr j) →
        repColor (Sum.inl c) = repColor (Sum.inr j) := by
      intro c j hrs
      simp only [repVal, Sum.elim_inl, Sum.elim_inr] at hrs
      have hjmem : p[j.val]'j.isLt ∈ p := List.getElem_mem j.isLt
      have hjnot : p[j.val]'j.isLt ∉ trackInterior p := by
        intro hjint
        exact hext.2.2.2.2.1 _ hjint ⟨c, hrs⟩
      rcases Workspace.ProofLemmas.SubdivisionCompose.mem_ends_of_mem
          hext.2.2.1.2.1 hext.2.2.1.2.2 hjmem hjnot with hjz | hjz'
      · have hc : c = z := hext.1 (hrs.trans hjz)
        have hj0 : j.val = 0 := hext.2.2.1.1.2.1.getElem_inj_iff.mp (by
          rw [hjz]
          exact (Workspace.ProofLemmas.SubdivisionCounting.track_head hext.2.2.1 hpPos).symm)
        subst c
        simp only [repColor, Sum.elim_inl, Sum.elim_inr, hcΘz]
        omega
      · have hc : c = z' := hext.1 (hrs.trans hjz')
        have hjlast : j.val = p.length - 1 := hext.2.2.1.1.2.1.getElem_inj_iff.mp (by
          rw [hjz']
          have h := hext.2.2.1.2.2
          rw [List.getLast?_eq_getElem?, List.getElem?_eq_getElem (by omega)] at h
          exact (Option.some_injective _ h).symm)
        subst c
        simp only [repColor, Sum.elim_inl, Sum.elim_inr, hcΘz']
        simp only [trackLength] at hpPar
        omega
  have hrepColor : ∀ {r s : RepH}, repVal r = repVal s → repColor r = repColor s := by
    intro r s hrs
    rcases r with c | i <;> rcases s with d | j
    · simp only [repVal, Sum.elim_inl] at hrs
      have hcd : c = d := hext.1 hrs
      subst d
      rfl
    · exact hcrossColor c j hrs
    · exact (hcrossColor d i hrs.symm).symm
    · simp only [repVal, Sum.elim_inr] at hrs
      have hij : i.val = j.val := hext.2.2.1.1.2.1.getElem_inj_iff.mp hrs
      simp only [repColor, Sum.elim_inr]
      omega
  let colorNat : Fin m' → ℕ := fun v => repColor (repH v)
  have hcolor_at : ∀ (r : RepH), colorNat (repVal r) = repColor r := by
    intro r
    dsimp only [colorNat]
    exact hrepColor ((hrepH _).trans rfl)
  refine ⟨SimpleGraph.Coloring.mk
    (fun v => ⟨colorNat v, by
      dsimp only [colorNat, repColor]
      rcases hrv : repH v with c | i
      · simp only [hrv, Sum.elim_inl, cΘNat]
        exact Nat.mod_lt _ (by decide)
      · simp only [hrv, Sum.elim_inr]
        exact Nat.mod_lt _ (by decide)⟩) ?_⟩
  intro c d hcd
  intro hsame
  have hedge : s(c, d) ∈ H.edgeSet := (SimpleGraph.mem_edgeSet H).mpr hcd
  rw [hext.2.2.2.2.2.2] at hedge
  rcases hedge with ⟨e, he, hemap⟩ | hpedge
  · induction e using Sym2.inductionOn with
    | _ u v =>
      have huv : Θ.Adj u v := (SimpleGraph.mem_edgeSet Θ).mp he
      have hmap : s(ρ u, ρ v) = s(c, d) := by simpa using hemap
      rcases Sym2.eq_iff.mp hmap with h | h
      · rcases h with ⟨rfl, rfl⟩
        have hcu := hcolor_at (Sum.inl u)
        have hcv := hcolor_at (Sum.inl v)
        simp only [repVal, repColor, Sum.elim_inl] at hcu hcv
        exact hcΘ_valid huv (by simpa [hcu, hcv] using congrArg Fin.val hsame)
      · rcases h with ⟨rfl, rfl⟩
        have hcu := hcolor_at (Sum.inl u)
        have hcv := hcolor_at (Sum.inl v)
        simp only [repVal, repColor, Sum.elim_inl] at hcu hcv
        exact hcΘ_valid huv (by simpa [hcu, hcv] using (congrArg Fin.val hsame).symm)
  · obtain ⟨k, hk, he⟩ := hpedge
    have hk0' : k < p.length := by omega
    have hc0 := hcolor_at (Sum.inr (⟨k, hk0'⟩ : Fin p.length))
    have hc1 := hcolor_at (Sum.inr (⟨k + 1, hk⟩ : Fin p.length))
    simp only [repVal, repColor, Sum.elim_inr] at hc0 hc1
    rcases Sym2.eq_iff.mp he with h | h
    · rcases h with ⟨rfl, rfl⟩
      have hv := congrArg Fin.val hsame
      simp only [hc0, hc1] at hv
      omega
    · rcases h with ⟨rfl, rfl⟩
      have hv := congrArg Fin.val hsame
      simp only [hc0, hc1] at hv
      omega

/-- **The host graph of the 10.1 case-1 appearance is bipartite.**

`Θ` is the theta graph of the prism `R 0, R 1, R 2` (from `Thm101ThetaOfPrism`), `z` and `z'`
are the internal theta-vertices sitting on the rung edges `u u'` and `w w'` — this is what
`hzinc` / `hz'inc` say — and `H` is `Θ` with the extra `z`–`z'` branch of `f.length` edges
(from `Thm101ThetaAddBranch`).

`h72` is verbatim the conclusion of `Workspace.Statements.S07.SPGT.thm_7_2` applied to this
prism; it is passed as a hypothesis rather than imported so that this module stays inside
`ProofLemmas`.

Generalises `NinePrismLineGraph.theta_bipartite` (a `decide` on an explicit `Fin 8`
two-colouring).  See the module docstring for the four parity obligations that replace it, and
for why `hfNonmajor` cannot be dropped. -/
theorem Thm101ThetaBipartite {V : Type*} [Fintype V] [DecidableEq V]
    (G : SimpleGraph V) (hG : Berge G)
    (a b : Fin 3 → V) (R : Fin 3 → List V) (K : Set V)
    (hprism : FormPrism G a b (R 0) (R 1) (R 2))
    (hK : K = {v : V | v ∈ R 0} ∪ {v : V | v ∈ R 1} ∪ {v : V | v ∈ R 2})
    (h72 : (Even (pathLength (R 0)) ↔ Even (pathLength (R 1))) ∧
      (Even (pathLength (R 0)) ↔ Even (pathLength (R 2))))
    (m : ℕ) (Θ : SimpleGraph (Fin m)) (x y : Fin m) (Q : Fin 3 → List (Fin m))
    (φ : Θ.lineGraph ≃g G.induce K)
    (hΘ : IsPrismTheta G R K Θ x y Q φ)
    (z z' : Fin m) (hz : z ∈ trackInterior (Q 0)) (hz' : z' ∈ trackInterior (Q 1))
    (f : List V) (f₁ fn u u' w w' : V)
    (hf : IsPathFrom G f f₁ fn)
    (hfK : ∀ v ∈ f, v ∈ Kᶜ)
    (hfNonmajor : ∀ v ∈ f, ¬ MajorForPrism G a b v)
    (hu : u ∈ R 0) (hu' : u' ∈ R 0) (huu' : G.Adj u u')
    (hf₁u : G.Adj f₁ u) (hf₁u' : G.Adj f₁ u')
    (hw : w ∈ R 1) (hw' : w' ∈ R 1) (hww' : G.Adj w w')
    (hfnw : G.Adj fn w) (hfnw' : G.Adj fn w')
    (hother : ∀ v ∈ f, ∀ k ∈ K, G.Adj v k →
      (v = f₁ ∧ (k = u ∨ k = u')) ∨ (v = fn ∧ (k = w ∨ k = w')))
    (hzinc : ∀ e : Θ.edgeSet,
      z ∈ (e : Sym2 (Fin m)) ↔ ((↑(φ e) : V) = u ∨ (↑(φ e) : V) = u'))
    (hz'inc : ∀ e : Θ.edgeSet,
      z' ∈ (e : Sym2 (Fin m)) ↔ ((↑(φ e) : V) = w ∨ (↑(φ e) : V) = w'))
    (m' : ℕ) (H : SimpleGraph (Fin m')) (ρ : Fin m → Fin m') (p : List (Fin m'))
    (hext : IsThetaBranchExtension Θ z z' H ρ p)
    (hplen : p.length = f.length + 1) :
    H.IsBipartite := by
  classical
  obtain ⟨hA, hB, hAB, hR, hcross⟩ :=
    Workspace.ProofLemmas.PrismSymmetry.formPrism_family.mp hprism
  obtain ⟨j0, hj0, hzpos0⟩ :=
    (Workspace.ProofLemmas.SubdivisionCounting.mem_trackInterior_iff (Q 0) z).mp hz
  obtain ⟨j1, hj1, hzpos1⟩ :=
    (Workspace.ProofLemmas.SubdivisionCounting.mem_trackInterior_iff (Q 1) z').mp hz'
  let k0 := j0 + 1
  let k1 := j1 + 1
  have hk0 : k0 < (Q 0).length := by dsimp [k0]; omega
  have hk0next : k0 + 1 < (Q 0).length := by dsimp [k0]; omega
  have hk1 : k1 < (Q 1).length := by dsimp [k1]; omega
  have hk1next : k1 + 1 < (Q 1).length := by dsimp [k1]; omega
  have hk0pos : 0 < k0 := by dsimp [k0]; omega
  have hk1pos : 0 < k1 := by dsimp [k1]; omega
  have hzpos : (Q 0)[k0]'hk0 = z := by simpa only [k0] using hzpos0
  have hz'pos : (Q 1)[k1]'hk1 = z' := by simpa only [k1] using hzpos1
  have hR0len : (Q 0).length = (R 0).length + 1 := hΘ.2.1 0
  have hR1len : (Q 1).length = (R 1).length + 1 := hΘ.2.1 1
  have hR2len : (Q 2).length = (R 2).length + 1 := hΘ.2.1 2
  have hk0R : k0 < (R 0).length := by omega
  have hk1R : k1 < (R 1).length := by omega
  have hR0two : 2 ≤ (R 0).length :=
    Workspace.ProofLemmas.HyperprismFromPrism.formPrism_two_le_length hprism 0
  have hR1two : 2 ≤ (R 1).length :=
    Workspace.ProofLemmas.HyperprismFromPrism.formPrism_two_le_length hprism 1
  have hfpos : 0 < f.length := Workspace.ProofLemmas.PathBasics.path_length_pos hf.1
  have hu_ne : u ≠ u' := huu'.ne
  have hw_ne : w ≠ w' := hww'.ne
  have hr0_ne : (R 0)[k0 - 1]'(by omega) ≠ (R 0)[k0]'hk0R :=
    Workspace.ProofLemmas.PathBasics.path_ne_of_ne_index (hR 0).1 (by omega) hk0R (by omega)
  have hr1_ne : (R 1)[k1 - 1]'(by omega) ≠ (R 1)[k1]'hk1R :=
    Workspace.ProofLemmas.PathBasics.path_ne_of_ne_index (hR 1).1 (by omega) hk1R (by omega)
  obtain ⟨he0L, hphi0L⟩ := hΘ.2.2 0 (k0 - 1) (by omega)
  obtain ⟨he0R, hphi0R⟩ := hΘ.2.2 0 k0 hk0next
  obtain ⟨he1L, hphi1L⟩ := hΘ.2.2 1 (k1 - 1) (by omega)
  obtain ⟨he1R, hphi1R⟩ := hΘ.2.2 1 k1 hk1next
  have hzedge0L : z ∈ s((Q 0)[k0 - 1]'(by omega), (Q 0)[k0]'hk0) := by
    rw [hzpos]
    exact Sym2.mem_mk_right _ _
  have hzedge0R : z ∈ s((Q 0)[k0]'hk0, (Q 0)[k0 + 1]'hk0next) := by
    rw [hzpos]
    exact Sym2.mem_mk_left _ _
  have hzedge1L : z' ∈ s((Q 1)[k1 - 1]'(by omega), (Q 1)[k1]'hk1) := by
    rw [hz'pos]
    exact Sym2.mem_mk_right _ _
  have hzedge1R : z' ∈ s((Q 1)[k1]'hk1, (Q 1)[k1 + 1]'hk1next) := by
    rw [hz'pos]
    exact Sym2.mem_mk_left _ _
  have hmap0L : (↑(φ ⟨_, he0L⟩) : V) = (R 0)[k0 - 1]'(by omega) := by
    rw [List.getElem?_eq_getElem (by omega)] at hphi0L
    exact (Option.some_injective _ hphi0L).symm
  have hmap0R : (↑(φ ⟨_, he0R⟩) : V) = (R 0)[k0]'hk0R := by
    rw [List.getElem?_eq_getElem hk0R] at hphi0R
    exact (Option.some_injective _ hphi0R).symm
  have hmap1L : (↑(φ ⟨_, he1L⟩) : V) = (R 1)[k1 - 1]'(by omega) := by
    rw [List.getElem?_eq_getElem (by omega)] at hphi1L
    exact (Option.some_injective _ hphi1L).symm
  have hmap1R : (↑(φ ⟨_, he1R⟩) : V) = (R 1)[k1]'hk1R := by
    rw [List.getElem?_eq_getElem hk1R] at hphi1R
    exact (Option.some_injective _ hphi1R).symm
  have hpair0L : (R 0)[k0 - 1]'(by omega) = u ∨ (R 0)[k0 - 1]'(by omega) = u' := by
    rw [← hmap0L]
    exact (hzinc ⟨_, he0L⟩).mp hzedge0L
  have hpair0R : (R 0)[k0]'hk0R = u ∨ (R 0)[k0]'hk0R = u' := by
    rw [← hmap0R]
    exact (hzinc ⟨_, he0R⟩).mp hzedge0R
  have hpair1L : (R 1)[k1 - 1]'(by omega) = w ∨ (R 1)[k1 - 1]'(by omega) = w' := by
    rw [← hmap1L]
    exact (hz'inc ⟨_, he1L⟩).mp hzedge1L
  have hpair1R : (R 1)[k1]'hk1R = w ∨ (R 1)[k1]'hk1R = w' := by
    rw [← hmap1R]
    exact (hz'inc ⟨_, he1R⟩).mp hzedge1R
  have hpair0 : ∀ t : V,
      (t = (R 0)[k0 - 1]'(by omega) ∨ t = (R 0)[k0]'hk0R) ↔ (t = u ∨ t = u') :=
    pair_mem_iff_of_injective_pair hr0_ne hu_ne hpair0L hpair0R
  have hpair1 : ∀ t : V,
      (t = (R 1)[k1 - 1]'(by omega) ∨ t = (R 1)[k1]'hk1R) ↔ (t = w ∨ t = w') :=
    pair_mem_iff_of_injective_pair hr1_ne hw_ne hpair1L hpair1R
  let L0 := Workspace.ProofLemmas.TrackSlice.slice (R 0) 0 (k0 - 1)
  let U0 := Workspace.ProofLemmas.TrackSlice.slice (R 0) k0 ((R 0).length - 1)
  let L1 := Workspace.ProofLemmas.TrackSlice.slice (R 1) 0 (k1 - 1)
  let U1 := Workspace.ProofLemmas.TrackSlice.slice (R 1) k1 ((R 1).length - 1)
  have hL0len : L0.length = k0 := by
    simp only [L0, Workspace.ProofLemmas.TrackSlice.length_slice (R 0)
      (i := 0) (j := k0 - 1) (by omega) (by omega)]
    omega
  have hU0len : U0.length = (R 0).length - k0 := by
    simp only [U0, Workspace.ProofLemmas.TrackSlice.length_slice (R 0)
      (i := k0) (j := (R 0).length - 1) (by omega) (by omega)]
    omega
  have hL1len : L1.length = k1 := by
    simp only [L1, Workspace.ProofLemmas.TrackSlice.length_slice (R 1)
      (i := 0) (j := k1 - 1) (by omega) (by omega)]
    omega
  have hU1len : U1.length = (R 1).length - k1 := by
    simp only [U1, Workspace.ProofLemmas.TrackSlice.length_slice (R 1)
      (i := k1) (j := (R 1).length - 1) (by omega) (by omega)]
    omega
  have hL0 : IsPathFrom G L0 (a 0) ((R 0)[k0 - 1]'(by omega)) := by
    have hs := isPathFrom_slice_le (hR 0).1
      (i := 0) (j := k0 - 1) (by omega) (by omega)
    have hhead : (R 0)[0]'(by omega) = a 0 :=
      Workspace.ProofLemmas.PathBasics.getElem_zero_of_head? (hR 0).2.1 (by omega)
    simpa only [L0, Workspace.ProofLemmas.TrackSlice.slice, hhead] using hs
  have hU0 : IsPathFrom G U0 ((R 0)[k0]'hk0R) (b 0) := by
    have hs := isPathFrom_slice_le (hR 0).1
      (i := k0) (j := (R 0).length - 1) (by omega) (by omega)
    have hlast : (R 0)[(R 0).length - 1]'(by omega) = b 0 :=
      Workspace.ProofLemmas.PathBasics.getElem_last_of_getLast? (hR 0).2.2 (by omega)
    simpa only [U0, Workspace.ProofLemmas.TrackSlice.slice, hlast] using hs
  have hL1 : IsPathFrom G L1 (a 1) ((R 1)[k1 - 1]'(by omega)) := by
    have hs := isPathFrom_slice_le (hR 1).1
      (i := 0) (j := k1 - 1) (by omega) (by omega)
    have hhead : (R 1)[0]'(by omega) = a 1 :=
      Workspace.ProofLemmas.PathBasics.getElem_zero_of_head? (hR 1).2.1 (by omega)
    simpa only [L1, Workspace.ProofLemmas.TrackSlice.slice, hhead] using hs
  have hU1 : IsPathFrom G U1 ((R 1)[k1]'hk1R) (b 1) := by
    have hs := isPathFrom_slice_le (hR 1).1
      (i := k1) (j := (R 1).length - 1) (by omega) (by omega)
    have hlast : (R 1)[(R 1).length - 1]'(by omega) = b 1 :=
      Workspace.ProofLemmas.PathBasics.getElem_last_of_getLast? (hR 1).2.2 (by omega)
    simpa only [U1, Workspace.ProofLemmas.TrackSlice.slice, hlast] using hs
  have hdisj01 : ∀ q ∈ R 0, q ∉ R 1 :=
    Workspace.ProofLemmas.HyperprismFromPrism.formPrism_disjoint hprism (by decide)
  have hmemK0 : ∀ q ∈ R 0, q ∈ K := by
    intro q hq
    rw [hK]
    exact Or.inl (Or.inl hq)
  have hmemK1 : ∀ q ∈ R 1, q ∈ K := by
    intro q hq
    rw [hK]
    exact Or.inl (Or.inr hq)
  have hL0sub : ∀ q ∈ L0, q ∈ R 0 := fun q hq =>
    Workspace.ProofLemmas.TrackSlice.mem_of_mem_slice hq
  have hU0sub : ∀ q ∈ U0, q ∈ R 0 := fun q hq =>
    Workspace.ProofLemmas.TrackSlice.mem_of_mem_slice hq
  have hL1sub : ∀ q ∈ L1, q ∈ R 1 := fun q hq =>
    Workspace.ProofLemmas.TrackSlice.mem_of_mem_slice hq
  have hU1sub : ∀ q ∈ U1, q ∈ R 1 := fun q hq =>
    Workspace.ProofLemmas.TrackSlice.mem_of_mem_slice hq
  have hL0_no_right : (R 0)[k0]'hk0R ∉ L0 := by
    intro hc
    obtain ⟨t, ht, -, htle, heq⟩ :=
      (Workspace.ProofLemmas.TrackSlice.mem_slice_iff (R := R 0)
        (j := k0 - 1) (by omega) (by omega)).mp hc
    have := (hR 0).1.2.1.getElem_inj_iff.mp (heq.trans rfl)
    omega
  have hL1_no_right : (R 1)[k1]'hk1R ∉ L1 := by
    intro hc
    obtain ⟨t, ht, -, htle, heq⟩ :=
      (Workspace.ProofLemmas.TrackSlice.mem_slice_iff (R := R 1)
        (j := k1 - 1) (by omega) (by omega)).mp hc
    have := (hR 1).1.2.1.getElem_inj_iff.mp (heq.trans rfl)
    omega
  have hU0_no_left : (R 0)[k0 - 1]'(by omega) ∉ U0 := by
    intro hc
    obtain ⟨t, ht, hkle, -, heq⟩ :=
      (Workspace.ProofLemmas.TrackSlice.mem_slice_iff (R := R 0)
        (i := k0) (j := (R 0).length - 1) (by omega) (by omega)).mp hc
    have := (hR 0).1.2.1.getElem_inj_iff.mp (heq.trans rfl)
    omega
  have hU1_no_left : (R 1)[k1 - 1]'(by omega) ∉ U1 := by
    intro hc
    obtain ⟨t, ht, hkle, -, heq⟩ :=
      (Workspace.ProofLemmas.TrackSlice.mem_slice_iff (R := R 1)
        (i := k1) (j := (R 1).length - 1) (by omega) (by omega)).mp hc
    have := (hR 1).1.2.1.getElem_inj_iff.mp (heq.trans rfl)
    omega
  have hL0_no_b : b 0 ∉ L0 := by
    intro hc
    obtain ⟨t, ht, -, htle, heq⟩ :=
      (Workspace.ProofLemmas.TrackSlice.mem_slice_iff (R := R 0)
        (j := k0 - 1) (by omega) (by omega)).mp hc
    have hlast : (R 0)[(R 0).length - 1]'(by omega) = b 0 :=
      Workspace.ProofLemmas.PathBasics.getElem_last_of_getLast? (hR 0).2.2 (by omega)
    have := (hR 0).1.2.1.getElem_inj_iff.mp (heq.trans hlast.symm)
    omega
  have hL1_no_b : b 1 ∉ L1 := by
    intro hc
    obtain ⟨t, ht, -, htle, heq⟩ :=
      (Workspace.ProofLemmas.TrackSlice.mem_slice_iff (R := R 1)
        (j := k1 - 1) (by omega) (by omega)).mp hc
    have hlast : (R 1)[(R 1).length - 1]'(by omega) = b 1 :=
      Workspace.ProofLemmas.PathBasics.getElem_last_of_getLast? (hR 1).2.2 (by omega)
    have := (hR 1).1.2.1.getElem_inj_iff.mp (heq.trans hlast.symm)
    omega
  have hU0_no_a : a 0 ∉ U0 := by
    intro hc
    obtain ⟨t, ht, hkle, -, heq⟩ :=
      (Workspace.ProofLemmas.TrackSlice.mem_slice_iff (R := R 0)
        (i := k0) (j := (R 0).length - 1) (by omega) (by omega)).mp hc
    have hhead : (R 0)[0]'(by omega) = a 0 :=
      Workspace.ProofLemmas.PathBasics.getElem_zero_of_head? (hR 0).2.1 (by omega)
    have := (hR 0).1.2.1.getElem_inj_iff.mp (heq.trans hhead.symm)
    omega
  have hU1_no_a : a 1 ∉ U1 := by
    intro hc
    obtain ⟨t, ht, hkle, -, heq⟩ :=
      (Workspace.ProofLemmas.TrackSlice.mem_slice_iff (R := R 1)
        (i := k1) (j := (R 1).length - 1) (by omega) (by omega)).mp hc
    have hhead : (R 1)[0]'(by omega) = a 1 :=
      Workspace.ProofLemmas.PathBasics.getElem_zero_of_head? (hR 1).2.1 (by omega)
    have := (hR 1).1.2.1.getElem_inj_iff.mp (heq.trans hhead.symm)
    omega
  have hf1r0L : G.Adj f₁ ((R 0)[k0 - 1]'(by omega)) := by
    rcases hpair0L with h | h
    · simpa only [h] using hf₁u
    · simpa only [h] using hf₁u'
  have hf1r0R : G.Adj f₁ ((R 0)[k0]'hk0R) := by
    rcases hpair0R with h | h
    · simpa only [h] using hf₁u
    · simpa only [h] using hf₁u'
  have hfnr1L : G.Adj fn ((R 1)[k1 - 1]'(by omega)) := by
    rcases hpair1L with h | h
    · simpa only [h] using hfnw
    · simpa only [h] using hfnw'
  have hfnr1R : G.Adj fn ((R 1)[k1]'hk1R) := by
    rcases hpair1R with h | h
    · simpa only [h] using hfnw
    · simpa only [h] using hfnw'
  have hcross_f_L1 : ∀ v ∈ f, ∀ q ∈ L1,
      G.Adj v q ↔ v = fn ∧ q = (R 1)[k1 - 1]'(by omega) := by
    intro v hv q hq
    have hqR := hL1sub q hq
    constructor
    · intro hadj
      rcases hother v hv q (hmemK1 q hqR) hadj with
        ⟨hv1, hqu⟩ | ⟨hvn, hqw⟩
      · exfalso
        rcases hqu with hqu | hqu
        · exact hdisj01 u hu (hqu.symm ▸ hqR)
        · exact hdisj01 u' hu' (hqu.symm ▸ hqR)
      · refine ⟨hvn, ?_⟩
        rcases (hpair1 q).mpr hqw with hqL | hqR'
        · exact hqL
        · exact (hL1_no_right (hqR'.symm ▸ hq)).elim
    · rintro ⟨rfl, rfl⟩
      exact hfnr1L
  have hcross_f_U1 : ∀ v ∈ f, ∀ q ∈ U1,
      G.Adj v q ↔ v = fn ∧ q = (R 1)[k1]'hk1R := by
    intro v hv q hq
    have hqR := hU1sub q hq
    constructor
    · intro hadj
      rcases hother v hv q (hmemK1 q hqR) hadj with
        ⟨hv1, hqu⟩ | ⟨hvn, hqw⟩
      · exfalso
        rcases hqu with hqu | hqu
        · exact hdisj01 u hu (hqu.symm ▸ hqR)
        · exact hdisj01 u' hu' (hqu.symm ▸ hqR)
      · refine ⟨hvn, ?_⟩
        rcases (hpair1 q).mpr hqw with hqL | hqR'
        · exact (hU1_no_left (hqL.symm ▸ hq)).elim
        · exact hqR'
    · rintro ⟨rfl, rfl⟩
      exact hfnr1R
  have hcross_L0_f : ∀ q ∈ L0, ∀ v ∈ f,
      G.Adj q v ↔ q = (R 0)[k0 - 1]'(by omega) ∧ v = f₁ := by
    intro q hq v hv
    have hqR := hL0sub q hq
    rw [SimpleGraph.adj_comm]
    constructor
    · intro hadj
      rcases hother v hv q (hmemK0 q hqR) hadj with
        ⟨hv1, hqu⟩ | ⟨hvn, hqw⟩
      · refine ⟨?_, hv1⟩
        rcases (hpair0 q).mpr hqu with hqL | hqR'
        · exact hqL
        · exact (hL0_no_right (hqR'.symm ▸ hq)).elim
      · exfalso
        rcases hqw with rfl | rfl
        · exact hdisj01 q hqR hw
        · exact hdisj01 q hqR hw'
    · rintro ⟨rfl, rfl⟩
      exact hf1r0L
  have hcross_U0_f : ∀ q ∈ U0, ∀ v ∈ f,
      G.Adj q v ↔ q = (R 0)[k0]'hk0R ∧ v = f₁ := by
    intro q hq v hv
    have hqR := hU0sub q hq
    rw [SimpleGraph.adj_comm]
    constructor
    · intro hadj
      rcases hother v hv q (hmemK0 q hqR) hadj with
        ⟨hv1, hqu⟩ | ⟨hvn, hqw⟩
      · refine ⟨?_, hv1⟩
        rcases (hpair0 q).mpr hqu with hqL | hqR'
        · exact (hU0_no_left (hqL.symm ▸ hq)).elim
        · exact hqR'
      · exfalso
        rcases hqw with rfl | rfl
        · exact hdisj01 q hqR hw
        · exact hdisj01 q hqR hw'
    · rintro ⟨rfl, rfl⟩
      exact hf1r0R
  have hdisj_f_L1 : ∀ v ∈ f, v ∉ L1 := by
    intro v hv hvl
    exact (hfK v hv) (hmemK1 v (hL1sub v hvl))
  have hdisj_f_U1 : ∀ v ∈ f, v ∉ U1 := by
    intro v hv hvu
    exact (hfK v hv) (hmemK1 v (hU1sub v hvu))
  have hpath_fL1 : IsPathFrom G (f ++ L1.reverse) f₁ (a 1) := by
    apply Workspace.ProofLemmas.PathGlue.glue_path hf
      (Workspace.ProofLemmas.PathBasics.isPathFrom_reverse hL1)
    · intro v hv
      simpa only [List.mem_reverse] using hdisj_f_L1 v hv
    · intro v hv q hq
      rw [List.mem_reverse] at hq
      exact hcross_f_L1 v hv q hq
  have hpath_fU1 : IsPathFrom G (f ++ U1) f₁ (b 1) := by
    apply Workspace.ProofLemmas.PathGlue.glue_path hf hU1 hdisj_f_U1
    exact hcross_f_U1
  have hdisj_L0_fL1 : ∀ q ∈ L0, q ∉ f ++ L1.reverse := by
    intro q hq hc
    rw [List.mem_append, List.mem_reverse] at hc
    rcases hc with hqf | hq1
    · exact (hfK q hqf) (hmemK0 q (hL0sub q hq))
    · exact hdisj01 q (hL0sub q hq) (hL1sub q hq1)
  have hdisj_U0_fU1 : ∀ q ∈ U0, q ∉ f ++ U1 := by
    intro q hq hc
    rw [List.mem_append] at hc
    rcases hc with hqf | hq1
    · exact (hfK q hqf) (hmemK0 q (hU0sub q hq))
    · exact hdisj01 q (hU0sub q hq) (hU1sub q hq1)
  have hcross_L0_L1 : ∀ q ∈ L0, ∀ r ∈ L1,
      G.Adj q r ↔ q = a 0 ∧ r = a 1 := by
    intro q hq r hr
    rw [hcross 0 1 (by decide) q (hL0sub q hq) r (hL1sub r hr)]
    constructor
    · rintro (h | h)
      · exact h
      · exact (hL0_no_b (h.1.symm ▸ hq)).elim
    · exact Or.inl
  have hcross_U0_U1 : ∀ q ∈ U0, ∀ r ∈ U1,
      G.Adj q r ↔ q = b 0 ∧ r = b 1 := by
    intro q hq r hr
    rw [hcross 0 1 (by decide) q (hU0sub q hq) r (hU1sub r hr)]
    constructor
    · rintro (h | h)
      · exact (hU0_no_a (h.1.symm ▸ hq)).elim
      · exact h
    · exact Or.inr
  have hcross_left : ∀ q ∈ L0, ∀ v ∈ f ++ L1.reverse,
      G.Adj q v ↔
        (q = (R 0)[k0 - 1]'(by omega) ∧ v = f₁) ∨ (q = a 0 ∧ v = a 1) := by
    intro q hq v hv
    rw [List.mem_append, List.mem_reverse] at hv
    rcases hv with hvf | hv1
    · rw [hcross_L0_f q hq v hvf]
      constructor
      · exact Or.inl
      · rintro (h | h)
        · exact h
        · exfalso
          exact (hfK v hvf) (h.2 ▸ hmemK1 _ (List.mem_of_mem_head? (hR 1).2.1))
    · rw [hcross_L0_L1 q hq v hv1]
      constructor
      · exact Or.inr
      · rintro (h | h)
        · exfalso
          exact hdisj_f_L1 v (h.2 ▸ List.mem_of_mem_head? hf.2.1) hv1
        · exact h
  have hcross_right : ∀ q ∈ U0.reverse, ∀ v ∈ f ++ U1,
      G.Adj q v ↔
        (q = (R 0)[k0]'hk0R ∧ v = f₁) ∨ (q = b 0 ∧ v = b 1) := by
    intro q hq v hv
    rw [List.mem_reverse] at hq
    rw [List.mem_append] at hv
    rcases hv with hvf | hv1
    · rw [hcross_U0_f q hq v hvf]
      constructor
      · exact Or.inl
      · rintro (h | h)
        · exact h
        · exfalso
          exact (hfK v hvf) (h.2 ▸ hmemK1 _ (List.mem_of_mem_getLast? (hR 1).2.2))
    · rw [hcross_U0_U1 q hq v hv1]
      constructor
      · exact Or.inr
      · rintro (h | h)
        · exfalso
          exact hdisj_f_U1 v (h.2 ▸ List.mem_of_mem_head? hf.2.1) hv1
        · exact h
  let leftLen := k0 + f.length + k1
  let rightLen := ((R 0).length - k0) + f.length + ((R 1).length - k1)
  have hleftHole : 4 ≤ leftLen → IsHoleList G (L0 ++ (f ++ L1.reverse)) := by
    intro h4
    apply Workspace.ProofLemmas.PathGlue.glue_hole hL0 hpath_fL1 hdisj_L0_fL1 hcross_left
    simpa only [List.length_append, List.length_reverse, hL0len, hL1len, leftLen,
      add_assoc] using h4
  have hrightHole : 4 ≤ rightLen → IsHoleList G (U0.reverse ++ (f ++ U1)) := by
    intro h4
    apply Workspace.ProofLemmas.PathGlue.glue_hole
      (Workspace.ProofLemmas.PathBasics.isPathFrom_reverse hU0) hpath_fU1
    · intro q hq
      rw [List.mem_reverse] at hq
      exact hdisj_U0_fU1 q hq
    · exact hcross_right
    · simpa only [List.length_append, List.length_reverse, hU0len, hU1len, rightLen,
        add_assoc] using h4
  have hleftEven : 4 ≤ leftLen → Even leftLen := by
    intro h4
    have he := hG.1 _ (hleftHole h4)
    simpa only [holeLength, List.length_append, List.length_reverse, hL0len, hL1len,
      leftLen, add_assoc] using he
  have hrightEven : 4 ≤ rightLen → Even rightLen := by
    intro h4
    have he := hG.1 _ (hrightHole h4)
    simpa only [holeLength, List.length_append, List.length_reverse, hU0len, hU1len,
      rightLen, add_assoc] using he
  have hpathPar01 : pathLength (R 0) % 2 = pathLength (R 1) % 2 :=
    mod_two_eq_of_even_iff h72.1
  have hpathPar02 : pathLength (R 0) % 2 = pathLength (R 2) % 2 :=
    mod_two_eq_of_even_iff h72.2
  have hR2two : 2 ≤ (R 2).length :=
    Workspace.ProofLemmas.HyperprismFromPrism.formPrism_two_le_length hprism 2
  have hRlenPar01 : (R 0).length % 2 = (R 1).length % 2 := by
    simp only [pathLength] at hpathPar01
    omega
  have hRlenPar02 : (R 0).length % 2 = (R 2).length % 2 := by
    simp only [pathLength] at hpathPar02
    omega
  have htotalEven : Even ((R 0).length + (R 1).length + 2 * f.length) := by
    rw [Nat.even_iff]
    omega
  have hsum : leftLen + rightLen =
      (R 0).length + (R 1).length + 2 * f.length := by
    dsimp only [leftLen, rightLen]
    omega
  have hleft4 : 4 ≤ leftLen := by
    by_contra hnot
    have hleft3 : leftLen = 3 := by
      dsimp only [leftLen] at hnot ⊢
      omega
    by_cases hr4 : 4 ≤ rightLen
    · have hre := hrightEven hr4
      rw [Nat.even_iff] at hre htotalEven
      have htot : (leftLen + rightLen) % 2 = 0 := by rw [hsum]; exact htotalEven
      omega
    · have hright3 : rightLen = 3 := by
        dsimp only [rightLen] at hr4 ⊢
        omega
      have hk0one : k0 = 1 := by dsimp only [leftLen] at hleft3; omega
      have hk1one : k1 = 1 := by dsimp only [leftLen] at hleft3; omega
      have hfone : f.length = 1 := by dsimp only [leftLen] at hleft3; omega
      have hR0eq : (R 0).length = 2 := by
        dsimp only [rightLen] at hright3
        omega
      have hR1eq : (R 1).length = 2 := by
        dsimp only [rightLen] at hright3
        omega
      have hr0La : (R 0)[k0 - 1]'(by omega) = a 0 := by
        have hhead := Workspace.ProofLemmas.PathBasics.getElem_zero_of_head?
          (hR 0).2.1 (show 0 < (R 0).length by omega)
        simpa [hk0one] using hhead
      have hr0Rb : (R 0)[k0]'hk0R = b 0 := by
        have hlast := Workspace.ProofLemmas.PathBasics.getElem_last_of_getLast?
          (hR 0).2.2 (show 0 < (R 0).length by omega)
        simpa only [hk0one, hR0eq, Nat.reduceSub] using hlast
      have hr1La : (R 1)[k1 - 1]'(by omega) = a 1 := by
        have hhead := Workspace.ProofLemmas.PathBasics.getElem_zero_of_head?
          (hR 1).2.1 (show 0 < (R 1).length by omega)
        simpa [hk1one] using hhead
      have hr1Rb : (R 1)[k1]'hk1R = b 1 := by
        have hlast := Workspace.ProofLemmas.PathBasics.getElem_last_of_getLast?
          (hR 1).2.2 (show 0 < (R 1).length by omega)
        simpa only [hk1one, hR1eq, Nat.reduceSub] using hlast
      obtain ⟨c, hfc⟩ := List.length_eq_one_iff.mp hfone
      have hcf1 : c = f₁ := by
        apply Option.some_injective
        simpa only [hfc, List.head?_cons] using hf.2.1
      have hcfn : c = fn := by
        apply Option.some_injective
        simpa only [hfc, List.getLast?_singleton] using hf.2.2
      have hf1fn : f₁ = fn := hcf1.symm.trans hcfn
      have hfa0 : G.Adj f₁ (a 0) := by simpa only [hr0La] using hf1r0L
      have hfb0 : G.Adj f₁ (b 0) := by simpa only [hr0Rb] using hf1r0R
      have hfa1 : G.Adj f₁ (a 1) := by rw [hf1fn]; simpa only [hr1La] using hfnr1L
      have hfb1 : G.Adj f₁ (b 1) := by rw [hf1fn]; simpa only [hr1Rb] using hfnr1R
      have hmajor : MajorForPrism G a b f₁ := by
        unfold MajorForPrism SaturatesPrism
        constructor
        · have hsub : ({a 0, a 1} : Set V) ⊆
              ({a 0, a 1, a 2} : Set V) ∩ G.neighborSet f₁ := by
            intro q hq
            simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hq ⊢
            rcases hq with rfl | rfl
            · exact ⟨Or.inl rfl, (SimpleGraph.mem_neighborSet G f₁ (a 0)).mpr hfa0⟩
            · exact ⟨Or.inr (Or.inl rfl),
                (SimpleGraph.mem_neighborSet G f₁ (a 1)).mpr hfa1⟩
          calc
            2 = ({a 0, a 1} : Set V).ncard :=
              (Set.ncard_pair (hA 0 1 (by decide)).ne).symm
            _ ≤ (({a 0, a 1, a 2} : Set V) ∩ G.neighborSet f₁).ncard :=
              Set.ncard_le_ncard hsub
        · have hsub : ({b 0, b 1} : Set V) ⊆
              ({b 0, b 1, b 2} : Set V) ∩ G.neighborSet f₁ := by
            intro q hq
            simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hq ⊢
            rcases hq with rfl | rfl
            · exact ⟨Or.inl rfl, (SimpleGraph.mem_neighborSet G f₁ (b 0)).mpr hfb0⟩
            · exact ⟨Or.inr (Or.inl rfl),
                (SimpleGraph.mem_neighborSet G f₁ (b 1)).mpr hfb1⟩
          calc
            2 = ({b 0, b 1} : Set V).ncard :=
              (Set.ncard_pair (hB 0 1 (by decide)).ne).symm
            _ ≤ (({b 0, b 1, b 2} : Set V) ∩ G.neighborSet f₁).ncard :=
              Set.ncard_le_ncard hsub
      exact (hfNonmajor f₁ (List.mem_of_mem_head? hf.2.1)) hmajor
  have hleftE : Even leftLen := hleftEven hleft4
  have hright4 : 4 ≤ rightLen := by
    by_contra hnot
    have hright3 : rightLen = 3 := by
      dsimp only [rightLen] at hnot ⊢
      omega
    have htot : (leftLen + rightLen) % 2 = 0 := by
      rw [hsum, ← Nat.even_iff]
      exact htotalEven
    rw [Nat.even_iff] at hleftE
    omega
  have hrightE : Even rightLen := hrightEven hright4
  have hpTrack : trackLength p = f.length := by
    simp only [trackLength]
    omega
  have hpPar : (k0 + trackLength p) % 2 = k1 % 2 := by
    rw [Nat.even_iff] at hleftE
    dsimp only [leftLen] at hleftE
    rw [hpTrack]
    omega
  have htrackR : ∀ i : Fin 3, trackLength (Q i) = (R i).length := by
    intro i
    have hi := hΘ.2.1 i
    simp only [trackLength]
    omega
  have hQpar : ∀ i : Fin 3,
      trackLength (Q i) % 2 = trackLength (Q 0) % 2 := by
    intro i
    fin_cases i
    · rfl
    · change trackLength (Q 1) % 2 = trackLength (Q 0) % 2
      rw [htrackR 1, htrackR 0]
      exact hRlenPar01.symm
    · change trackLength (Q 2) % 2 = trackLength (Q 0) % 2
      rw [htrackR 2, htrackR 0]
      exact hRlenPar02.symm
  exact thetaExtension_isBipartite_of_parity Θ x y Q hΘ.1 z z' k0 k1 hk0 hk1 hzpos hz'pos
    H ρ p hext hQpar hpPar

/-- Public parity criterion for a theta branch extension.  This is the structural core used by
`Thm101ThetaBipartite`, exposed for later constructions whose theta is not obtained from a
prism. -/
theorem thetaExtensionIsBipartiteOfParity {m m' : ℕ}
    (Θ : SimpleGraph (Fin m)) (x y : Fin m) (Q : Fin 3 → List (Fin m))
    (hΘ : IsThetaDatum Θ x y Q)
    (z z' : Fin m) (k0 k1 : ℕ)
    (hk0 : k0 < (Q 0).length) (hk1 : k1 < (Q 1).length)
    (hzpos : (Q 0)[k0]'hk0 = z) (hz'pos : (Q 1)[k1]'hk1 = z')
    (H : SimpleGraph (Fin m')) (ρ : Fin m → Fin m') (p : List (Fin m'))
    (hext : IsThetaBranchExtension Θ z z' H ρ p)
    (hQpar : ∀ i : Fin 3, trackLength (Q i) % 2 = trackLength (Q 0) % 2)
    (hpPar : (k0 + trackLength p) % 2 = k1 % 2) :
    H.IsBipartite :=
  thetaExtension_isBipartite_of_parity Θ x y Q hΘ z z' k0 k1 hk0 hk1 hzpos hz'pos
    H ρ p hext hQpar hpPar

end Workspace.ProofLemmas
