/-  GENERATED by scripts/split_statements.py from Workspace/Statements/S10.lean -- one numbered statement
    of the paper per module.  The theorem below, its doc-comment and its
    signature are byte-identical to the source module; only the surrounding
    file was mechanically re-cut.  See PROVING_PLAN.md.  -/
import Mathlib
import Workspace.Types.Core
import Workspace.Types.Tracks
import Workspace.Types.Appearances
import Workspace.Types.Prisms
import Workspace.Types.Decompositions
import Workspace.ProofLemmas.Thm101CaseOneK4AppearanceWitness

/-!
# Section 10 — The even prism

The six numbered statements 10.1–10.6 of Chudnovsky–Robertson–Seymour–Thomas,
*The Strong Perfect Graph Theorem* (published/Annals version, printed pages 56–63),
transcribed from `paper/pdf/S10_The_even_prism.md`.

All the defined terms used here are imported and never restated: *prism* / *form a prism*,
*even prism*, *saturates*, *major*, *local* (with respect to a prism) come from
`Workspace.Types.Prisms`; *attachment* / *appearance* / *(non)degenerate appearance* from
`Workspace.Types.Appearances`; *Berge*, *connected set*, *path*, *length*, *interior* from
`Workspace.Types.Core`; *proper 2-join* and *balanced skew partition* from
`Workspace.Types.Decompositions`.

Encoding conventions (see `paper/spec/CONVENTIONS.md`):

* the paper's indices `1,2,3` are `0,1,2 : Fin 3`, so `R₁,R₂,R₃` is a family
  `R : Fin 3 → List V` and `a₁,a₂,a₃` is `a : Fin 3 → V` (this matches `Prisms`);
* a path is the list of its vertices in order, and `V(P)` for such a list `P` is
  `{v | v ∈ P}`; "a path in `F`" is a path of `G` all of whose vertices lie in `F`;
* `K` is the vertex set of the prism, i.e. `V(R₁) ∪ V(R₂) ∪ V(R₃)`, and
  `F ⊆ V(G) \ V(K)` is `F ⊆ Kᶜ`;
* "there is a nondegenerate appearance of `K₄` in `G`" is spelled out at each use as
  `∃ n (H : SimpleGraph (Fin n)) (K' : Set V), IsAppearance G K₄ H K' ∧
   NondegenerateAppearance K₄ H`, where `K₄` is `(⊤ : SimpleGraph (Fin 4))`;
* "the only edges between `X` and `Y` are …" is rendered as: every edge between `X` and `Y`
  is one of the listed ones (the listed ones being asserted separately as conjuncts).
-/

set_option autoImplicit false

namespace Workspace.Statements.S10

open Workspace.Types.Core Workspace.Types.Core.SPGT
open Workspace.Types.Tracks Workspace.Types.Tracks.SPGT
open Workspace.Types.Appearances Workspace.Types.Appearances.SPGT
open Workspace.Types.Prisms Workspace.Types.Prisms.SPGT
open Workspace.Types.Decompositions Workspace.Types.Decompositions.SPGT

namespace SPGT

variable {V : Type*} [Fintype V] [DecidableEq V]


/-- **10.2** (printed p. 58)

PAPER: *"Let `R₁, R₂, R₃, K, F` be as in 10.1, and suppose that 10.1.1 holds.  Then either
`R₁` and `R₂` both have length 1, or there is a nondegenerate appearance of `K₄` in `G`."*

The hypotheses inherited from 10.1 are written out in full: `G` is Berge, `R₁, R₂, R₃` form
the prism `K` with triangles `{a₁, a₂, a₃}` and `{b₁, b₂, b₃}`, `F ⊆ V(G) \ V(K)` is
connected, its set of attachments in `K` is not local, and no vertex of `F` is major with
respect to `K`.  *"10.1.1 holds"* is 10.1's first alternative for this very labelling of the
prism (`R₁` and `R₂` being the two paths named in its conclusion), including its final
"(therefore)" clause. -/
theorem thm_10_2 (G : SimpleGraph V) (hG : Berge G)
    (a b : Fin 3 → V) (R : Fin 3 → List V) (K F : Set V)
    (hprism : FormPrism G a b (R 0) (R 1) (R 2))
    (hK : K = {v : V | v ∈ R 0} ∪ {v : V | v ∈ R 1} ∪ {v : V | v ∈ R 2})
    (hFK : F ⊆ Kᶜ) (hFconn : ConnectedSet G F)
    (hFloc : ¬ LocalForPrism a b (R 0) (R 1) (R 2) (attachments G F K))
    (hFmaj : ∀ v ∈ F, ¬ MajorForPrism G a b v)
    (f : List V) (f₁ fn : V) (hf : IsPathFrom G f f₁ fn) (hfF : ∀ v ∈ f, v ∈ F)
    (hfn : 1 ≤ f.length)
    (u u' w w' : V)
    (hu : u ∈ R 0) (hu' : u' ∈ R 0) (huu' : G.Adj u u')
    (hf₁u : G.Adj f₁ u) (hf₁u' : G.Adj f₁ u')
    (hw : w ∈ R 1) (hw' : w' ∈ R 1) (hww' : G.Adj w w')
    (hfnw : G.Adj fn w) (hfnw' : G.Adj fn w')
    (hother : ∀ x ∈ f, ∀ k ∈ K, G.Adj x k →
      (x = f₁ ∧ (k = u ∨ k = u')) ∨ (x = fn ∧ (k = w ∨ k = w')))
    (hL : Appears G (⊤ : SimpleGraph (Fin 4))) :
    (pathLength (R 0) = 1 ∧ pathLength (R 1) = 1) ∨
      ∃ (n : ℕ) (H : SimpleGraph (Fin n)) (K' : Set V),
        IsAppearance G (⊤ : SimpleGraph (Fin 4)) H K' ∧
          NondegenerateAppearance (⊤ : SimpleGraph (Fin 4)) H := by
  have hfK : ∀ x ∈ f, x ∈ Kᶜ := by
    intro x hx
    exact hFK (hfF x hx)
  have hfNonmajor : ∀ x ∈ f, ¬ MajorForPrism G a b x := by
    intro x hx
    exact hFmaj x (hfF x hx)
  rcases Workspace.ProofLemmas.Thm101CaseOneK4AppearanceWitness
      G hG a b R K f f₁ fn u u' w w' hprism hK hf hfK hfNonmajor
      hu hu' huu' hf₁u hf₁u' hw hw' hww' hfnw hfnw' hother with
    ⟨m, H, K', hK', hAppearance, hCases⟩
  rcases hCases with hNondegenerate | hDegenerate
  · right
    exact ⟨m, H, K', hAppearance, hNondegenerate⟩
  · left
    exact ⟨hDegenerate.2.1, hDegenerate.2.2⟩


end SPGT

end Workspace.Statements.S10
