/-  GENERATED by scripts/split_statements.py from Workspace/MainTheorem.lean -- one numbered statement
    of the paper per module.  The theorem below, its doc-comment and its
    signature are byte-identical to the source module; only the surrounding
    file was mechanically re-cut.  See PROVING_PLAN.md.  -/
import Mathlib
import Workspace.Types.Core
import Workspace.Types.Decompositions
import Workspace.Types.BasicClasses
import Workspace.Types.Replication
import Workspace.Types.Classes
import Workspace.Types.Prisms
import Workspace.ProofLemmas.ProperHomogeneousPairColouringAssembly

/-!
# The Strong Perfect Graph Theorem — the main statement file

The numbered results of Section 1 of Chudnovsky, Robertson, Seymour and Thomas,
*The Strong Perfect Graph Theorem* (`perfect.pdf`, June 20 2002 / revised July 19 2005,
printed pages 1–4), together with the external results that the paper's deduction of
**1.2** from **1.3** relies on, and the two external results used inside its proof of
**1.5**.

The centrepiece is `thm_1_2`: *a graph is perfect if and only if it is Berge.*

Contents, in the order printed in the paper:

* `thm_1_1` — Lovász [16]: the complement of every perfect graph is perfect;
* `thm_1_2` — **the Strong Perfect Graph Theorem**;
* `thm_1_3` — the structure theorem for Berge graphs (the contents of sections 2–24);
* `thm_1_4` — the same with the proper-homogeneous-pair alternative removed
  (Chudnovsky's PhD thesis [3, 4]; stated but not proved in this paper);
* `thm_1_5` — no minimum imperfect graph admits a balanced skew partition;

and the external ingredients of the proof of 1.2, printed page 4:

* `thm_E2_no_proper_2_join_in_minimum_imperfect` — Cornuéjols and Cunningham [13];
* `thm_E3_no_proper_homogeneous_pair_in_minimum_imperfect` — Chvátal and Sbihi [7];
* `thm_E4_basic_implies_perfect` — König [15], Lovász [16], and "the reader";
* `thm_E5_perfect_implies_berge`;

and the two external ingredients of the proof of 1.5, printed pages 3–4:

* `thm_E6_no_star_cutset_in_minimum_imperfect` — Chvátal [6];
* `thm_E7_lovasz_replication` — Lovász [16].

and the twelve steps of the proof of 1.3, printed page 7:

* `thm_1_8_1`, …, `thm_1_8_12` — the twelve numbered statements of **1.8**
  *(The steps of the proof of 1.3)*, which the paper proves in 5.1, 5.2, 9.6, 10.6, 13.4,
  14.3, 16.3, 18.7, 23.2, 23.4, 23.5 and 24.1 respectively.  They quantify over the classes
  `F₁, …, F₁₁` of `Workspace.Types.Classes` (`InF1`, …, `InF11`), and 1.8(4) additionally
  uses `IsEvenPrism` of `Workspace.Types.Prisms`.
* `thm_1_8_4_F3` — **not printed in the paper**: the corrected form of 1.8(4), with hypothesis
  `G ∈ F₃` in place of the printed `G ∈ F₁` and the identical conclusion.  Printed 1.8(4) is
  false — see the erratum and countermodel in the doc-comment of `thm_1_8_4`, `AMBIGUITIES.md`
  §A2a and `FIXES.md` §F2 — while this form is what 10.6 proves and what the chain
  `1.8(3) → 1.8(4) → 1.8(5)` needs.  `thm_1_8_4` itself is left exactly as printed.

Every definition used below is imported: `Berge`, `IsPerfect`, `MinimumImperfect` from
`Workspace.Types.Core`; `AdmitsProper2Join`, `AdmitsProperHomogeneousPair`,
`AdmitsBalancedSkewPartition`, `AdmitsStarCutset` from `Workspace.Types.Decompositions`;
`IsBasic` from `Workspace.Types.BasicClasses`; `replicateVertex` from
`Workspace.Types.Replication`.  Nothing is restated here.

Ambient conventions (see `paper/spec/CONVENTIONS.md`): all graphs of the paper are finite
and simple, so the vertex type carries `[Fintype V]` (and `[DecidableEq V]`); the paper's
`Ḡ` is Mathlib's `Gᶜ`.
-/

namespace Workspace.MainTheorem

open Workspace.Types.Core Workspace.Types.Decompositions
open Workspace.Types.BasicClasses Workspace.Types.Replication
open Workspace.Types.Classes Workspace.Types.Prisms

namespace SPGT

variable {V : Type*} [Fintype V] [DecidableEq V]


/-- **E3**, due to Chvátal and Sbihi [7]; used in the proof of 1.2 from 1.3.

PAPER (printed p. 4): *"It is shown in [7] that `G` does not admit a proper homogeneous
pair."*

(The paper's *proper homogeneous pair* is *"a slight variation of the 'homogeneous pair' of
Chvátal and Sbihi [7]"*.) -/
theorem thm_E3_no_proper_homogeneous_pair_in_minimum_imperfect
    (G : SimpleGraph V) (hG : SPGT.MinimumImperfect G) :
    ¬ SPGT.AdmitsProperHomogeneousPair G := by
  rintro ⟨A, B, hAB⟩
  exact Workspace.ProofLemmas.ProperHomogeneousPairColouringAssembly G hG A B hAB


end SPGT

end Workspace.MainTheorem
