/-  GENERATED by scripts/split_statements.py from Workspace/Statements/S24.lean -- one numbered statement
    of the paper per module.  The theorem below, its doc-comment and its
    signature are byte-identical to the source module; only the surrounding
    file was mechanically re-cut.  See PROVING_PLAN.md.  -/
/- Proof promoted from `ProofAttempts/thm_24_5/Attempt_2.lean` after rollback
   against this frozen statement and targeted Numina diagnostics. -/
import Mathlib
import Workspace.Types.Core
import Workspace.Types.Decompositions
import Workspace.Types.Classes
import Workspace.ProofLemmas.PathBasics
import Workspace.ProofLemmas.Thm245MaximalAdmissibleSet
import Workspace.ProofLemmas.Thm245AuxiliaryPathFromFifteenTwo
import Workspace.ProofLemmas.Thm245YCompleteWitnessFromTwentyFourFour
import Workspace.ProofLemmas.Thm245MaximalityForcesQNonadjacent
import Workspace.ProofLemmas.Thm245NoNeighborCaseContradictsTwentyFourThree

/-!
# Section 24 — The end

The seven numbered statements 24.1 … 24.7 of Chudnovsky–Robertson–Seymour–Thomas,
*The Strong Perfect Graph Theorem* (published/Annals version, printed pages
143–146).  Source of the verbatim quotations: `paper/pdf/S24_The_end.md`,
`## Numbered statements`.

**24.1 is the last of the twelve main steps of the proof of 1.3**: it is statement
**1.8.12** (printed p. 13: *"The twelve statements of 1.8 are proved in 5.1, 5.2,
9.6, 10.6, 13.4, 14.3, 16.3, 18.7, 23.2, 23.4, 23.5, and 24.1 respectively."*),
and it is the terminal conclusion of the whole paper — the section preamble reads
*"We recall that we are trying to prove 13.5.  In view of 23.5, it suffices to show
the following, which is 1.8.12, and the objective of the remainder of the paper:"*,
and the section ends *"Now we can complete the proof of 24.1, and hence of 13.5 and
therefore of 1.3 and 1.2, as follows."*

Section 24 **defines no term** and **cites no external (prior-work) result**; every
citation in it (1.2, 1.3, 13.5, 13.6, 13.7, 15.2, 17.1, 23.5, 24.2–24.7) is
internal to the paper.  The §17 notions *reflection of a triangle* and *catch a
triangle* occur only inside the **proof** of 24.4 and in no numbered statement, so
`Workspace.Types.TriangleCatching` is not imported.  The words *triad* and *hat*
do not occur in the section at all.

Every defined term used below is imported and never restated:

* `Workspace.Types.Core` — `IsPathList`, `IsPathFrom`, `pathLength`,
  `SPGT.interior`, `IsHoleList`, `holeLength`, `IsAntipathList`,
  `VertexComplete`, `EdgeComplete`, `Complete`, `ConnectedSet`,
  `AnticonnectedSet`;
* `Workspace.Types.Classes` — `InF11` (the class `F₁₁` of §1);
* `Workspace.Types.Decompositions` — `AdmitsBalancedSkewPartition`.

Encoding conventions (see `paper/spec/CONVENTIONS.md`):

* a path of the paper is an *induced* subgraph, given by the list `p : List V` of
  its vertices in order; the paper's `p₁-⋯-pₙ` therefore has `n = p.length`
  vertices and length `pathLength p = n - 1`, its interior `p₂,…,pₙ₋₁` is
  `SPGT.interior p` (always written qualified — a bare `interior` is Mathlib's
  topological one), and `V(P)` is `{w : V | w ∈ p}` (so *"`z ∉ V(P)`"* is
  `z ∉ p`);
* the ends `p₁, pₙ` and the second vertex `p₂` are pinned down by the total
  functions `p.head?`, `p.getLast?`, `p.tail.head?` (no `getElem` bounds needed);
* *"an edge of `P`"*: since `P` is induced, the edges of `P` are exactly the
  adjacent pairs of vertices of `p`, so *"some edge of `P` is `X`-complete"* is
  `∃ a ∈ p, ∃ b ∈ p, EdgeComplete G X a b` (`EdgeComplete` already contains
  `G.Adj a b`);
* a hole is the list of its vertices in cyclic order, with length `holeLength`;
* *"`X` is complete to `Y`"* is `Complete G X Y`, *"`v` is `X`-complete"* is
  `VertexComplete G v X`;
* *"`G` is complete"* means every two distinct vertices of `G` are adjacent, and
  *"`G` is bipartite"* is Mathlib's `SimpleGraph.IsBipartite` (= `Colorable 2`).
-/

set_option autoImplicit false

namespace Workspace.Statements.S24

open Workspace.Types.Core Workspace.Types.Core.SPGT
open Workspace.Types.Decompositions Workspace.Types.Decompositions.SPGT
open Workspace.Types.Classes Workspace.Types.Classes.SPGT
open Workspace.ProofLemmas

namespace SPGT

variable {V : Type*} [Fintype V] [DecidableEq V]


/-- **24.5** (printed p. 145).

PAPER: *"Let `G ∈ F₁₁`, admitting no balanced skew partition.  Let `X, Y` be
disjoint anticonnected subsets of `V(G)`, complete to each other, and let
`p₁-⋯-pₙ` be a path of `G \ (X ∪ Y)`, with `n ≥ 2`, such that `p₁` is the unique
`X`-complete vertex in the path, and `pₙ` is the unique `Y`-complete vertex.  Then
there is no `z ∈ V(G) \ (X ∪ Y ∪ {p₁, …, pₙ})`, complete to `X ∪ Y` and nonadjacent
to `p₁, pₙ`."*

Transcription notes.

* `X` and `Y` are **not** assumed nonempty here (contrast 24.3 and 24.7).
* *"`n ≥ 2`"* is `2 ≤ p.length` — at least two vertices, so `p₁ ≠ pₙ`.
* *"`p₁` is the unique `X`-complete vertex in the path"* is the biconditional
  `∀ w ∈ p, (VertexComplete G w X ↔ w = p₁)`; together with `p₁ ∈ p` this already
  says that `p₁` *is* `X`-complete, and likewise for `pₙ` and `Y`.
* *"complete to `X ∪ Y`"* is `VertexComplete G z (X ∪ Y)`. -/
theorem thm_24_5 (G : SimpleGraph V) (hG : InF11 G)
    (hbsp : ¬ AdmitsBalancedSkewPartition G)
    (X Y : Set V) (hXY : Disjoint X Y)
    (hX : AnticonnectedSet G X) (hY : AnticonnectedSet G Y)
    (hcomp : Complete G X Y)
    (p : List V) (p₁ pₙ : V)
    (hp : IsPathList G p) (hpXY : ∀ w ∈ p, w ∉ X ∪ Y) (hn : 2 ≤ p.length)
    (hhead : p.head? = some p₁) (hlast : p.getLast? = some pₙ)
    (hXuniq : ∀ w ∈ p, (VertexComplete G w X ↔ w = p₁))
    (hYuniq : ∀ w ∈ p, (VertexComplete G w Y ↔ w = pₙ)) :
    ¬ ∃ z : V, z ∉ X ∧ z ∉ Y ∧ z ∉ p ∧ VertexComplete G z (X ∪ Y) ∧
        ¬ G.Adj z p₁ ∧ ¬ G.Adj z pₙ := by
  rintro ⟨z, hzX, hzY, hzp, hzcomp, hzp₁, hzpₙ⟩
  have hp₁mem : p₁ ∈ p := PathBasics.head_mem hhead
  have hpₙmem : pₙ ∈ p := PathBasics.getLast_mem hlast
  have hpos : 0 < p.length := by omega
  have hp₁val : p[0]'hpos = p₁ := PathBasics.getElem_zero_of_head? hhead hpos
  have hpₙval : p[p.length - 1]'(by omega) = pₙ :=
    PathBasics.getElem_last_of_getLast? hlast hpos
  have hp₁pₙ : p₁ ≠ pₙ := by
    intro heq
    have hlastlt : p.length - 1 < p.length := by omega
    have hidx : (0 : Nat) ≠ p.length - 1 := by omega
    have hdiff : p[0]'hpos ≠ p[p.length - 1]'hlastlt :=
      PathBasics.path_ne_of_ne_index hp hpos hlastlt hidx
    apply hdiff
    rw [hp₁val, hpₙval, heq]
  have hpₙnotX : ¬ VertexComplete G pₙ X := by
    intro hpₙX
    exact hp₁pₙ ((hXuniq pₙ hpₙmem).mp hpₙX).symm
  have hp₁notY : ¬ VertexComplete G p₁ Y := by
    intro hp₁Y
    exact hp₁pₙ ((hYuniq p₁ hp₁mem).mp hp₁Y)
  have hXne : X.Nonempty := by
    by_contra hne
    apply hpₙnotX
    intro x hx
    exact (hne ⟨x, hx⟩).elim
  have hYne : Y.Nonempty := by
    by_contra hne
    apply hp₁notY
    intro y hy
    exact (hne ⟨y, hy⟩).elim
  obtain ⟨S, hS, hSY, hScomp, hpSY, hSuniq, hzS, hzScomp, hSmax⟩ :=
    Workspace.Types.Thm245MaximalAdmissibleSet.thm245MaximalAdmissibleSet
      G X Y p p₁ z hX hXY hcomp hpXY hXuniq hzX hzcomp
  have hpₙnotS : ¬ VertexComplete G pₙ S := by
    intro hpₙS
    exact hp₁pₙ ((hSuniq pₙ hpₙmem).mp hpₙS).symm
  have hSne : S.Nonempty := by
    by_contra hne
    apply hpₙnotS
    intro s hs
    exact (hne ⟨s, hs⟩).elim
  have hp₁Scomp : VertexComplete G p₁ S := (hSuniq p₁ hp₁mem).mpr rfl
  have hpS : ∀ w ∈ p, w ∉ S := by
    intro w hw hwS
    exact hpSY w hw (Or.inl hwS)
  have hp₁Y : p₁ ∉ Y := by
    intro hp₁Ymem
    exact hpSY p₁ hp₁mem (Or.inr hp₁Ymem)
  have hzSonly : VertexComplete G z S := by
    intro s hs
    exact hzScomp s (Or.inl hs)
  have hzYcomp : VertexComplete G z Y := by
    intro y hy
    exact hzScomp y (Or.inr hy)
  obtain ⟨Q, q, hQ, hsnd, hQlen, hqint, hzq, hqS, hqnotcomp, hQint, hQcontain⟩ :=
    Workspace.Types.Thm245AuxiliaryPathFromFifteenTwo.thm245AuxiliaryPathFromFifteenTwo
      G hG.1.1.1.1.1 hbsp S hSne p p₁ pₙ z hp hn
        hpS hhead hlast hSuniq hzS hzp hzSonly hzp₁
  obtain ⟨f, hfF, hfY, hfz⟩ :=
    Workspace.Types.Thm245YCompleteWitnessFromTwentyFourFour.thm245YCompleteWitnessFromTwentyFourFour
      G hG S Y hSY hSne hYne hS hY hScomp
        p p₁ pₙ hp hn hhead hlast hpSY hSuniq hYuniq z hzS hzY hzp hzScomp hzp₁ Q q
        hQ hqint hzq hQint
  by_cases hsees : ∃ w ∈ p, G.Adj z w
  · have hfpmem : f ∈ p := by
      rcases hfF with hfQ | hfp
      · obtain ⟨hfQmem, hfne⟩ := hfQ
        rcases hQcontain hsees f hfQmem with rfl | hfpmem
        · exact False.elim (hfne rfl)
        · exact hfpmem
      · exact hfp
    have hfpₙ : f = pₙ := (hYuniq f hfpmem).mp hfY
    exact hzpₙ (hfpₙ ▸ hfz.symm)
  · have hznone : ∀ w ∈ p, ¬ G.Adj z w := by
      intro w hw hadj
      exact hsees ⟨w, hw, hadj⟩
    have hfq : f = q := by
      rcases hfF with hfQ | hfp
      · obtain ⟨hfQmem, _⟩ := hfQ
        obtain ⟨i, hi, hif⟩ := List.mem_iff_getElem.mp hfQmem
        have hQpos : 0 < Q.length := PathBasics.path_length_pos hQ.1
        have hQ0 : Q[0]'hQpos = z := PathBasics.getElem_zero_of_head? hQ.2.1 hQpos
        have hQ1 : Q[1]'(by omega) = q := by
          have h := hsnd
          rw [List.head?_eq_getElem?, List.getElem?_eq_getElem (by simp; omega)] at h
          have h' : Q.tail[0]'(by simp; omega) = q := Option.some_inj.mp h
          rw [← h']
          simp [List.getElem_tail]
        have hadj : G.Adj (Q[i]'hi) (Q[0]'hQpos) := by
          rw [hif, hQ0]
          exact hfz
        have hi1 : i = 1 := by
          rcases (PathBasics.path_adj_iff hQ.1 hi hQpos).mp hadj with h | h <;> omega
        have hQi : Q[i]'hi = q := by
          subst i
          simpa using hQ1
        exact hif.symm.trans hQi
      · exact False.elim (hznone f hfp hfz.symm)
    have hqY : VertexComplete G q Y := hfq ▸ hfY
    have hqp₁ : ¬ G.Adj q p₁ :=
      Workspace.Types.Thm245MaximalityForcesQNonadjacent.thm245MaximalityForcesQNonadjacent
        G S Y p p₁ z q hS hSY hScomp hpSY hp₁mem
          hSuniq hzS hzScomp hSmax hznone hzq hqS hqnotcomp hqY
    have hQoutside : ∀ w ∈ Q, w ∉ S := by
      intro w hwQ
      by_cases hwz : w = z
      · simpa [hwz] using hzS
      by_cases hwp₁ : w = p₁
      · subst w
        exact hpS p₁ hp₁mem
      · exact (hQint w ((PathBasics.mem_interior_iff_of_pathFrom hQ).mpr
          ⟨hwQ, hwz, hwp₁⟩)).1
    have hQnotcomp : ∀ w ∈ interior Q, ¬ VertexComplete G w S := by
      intro w hw
      exact (hQint w hw).2
    exact Workspace.Types.Thm245NoNeighborCaseContradictsTwentyFourThree.thm245NoNeighborCaseContradictsTwentyFourThree
      G hG S Y hSne hS hYne hSY hScomp
        Q z p₁ q hQ hsnd hQoutside hzSonly hp₁Scomp hQnotcomp hzY hp₁Y hzYcomp hqY
        hzp₁ hqp₁


end SPGT

end Workspace.Statements.S24
