/-  GENERATED by scripts/split_statements.py from Workspace/Statements/S24.lean -- one numbered statement
    of the paper per module.  The theorem below, its doc-comment and its
    signature are byte-identical to the source module; only the surrounding
    file was mechanically re-cut.  See PROVING_PLAN.md.  -/
import Mathlib
import Workspace.Types.Core
import Workspace.Types.Decompositions
import Workspace.Types.Classes
import Workspace.ProofLemmas.ExtremalChoice
import Workspace.ProofLemmas.Thm244Shapes
import Workspace.ProofLemmas.Thm244Trichotomy
import Workspace.ProofLemmas.Thm244Case1
import Workspace.ProofLemmas.Thm244Case2
import Workspace.ProofLemmas.Thm244Case3

/-!
# Section 24 — The end

The seven numbered statements 24.1 … 24.7 of Chudnovsky–Robertson–Seymour–Thomas,
*The Strong Perfect Graph Theorem* (published/Annals version, printed pages
143–146).  Source of the verbatim quotations: `paper/pdf/S24_The_end.md`,
`## Numbered statements`.

**24.1 is the last of the twelve main steps of the proof of 1.3**: it is statement
**1.8.12** (printed p. 13: *"The twelve statements of 1.8 are proved in 5.1, 5.2,
9.6, 10.6, 13.4, 14.3, 16.3, 18.7, 23.2, 23.4, 23.5, and 24.1 respectively."*),
and it is the terminal conclusion of the whole paper — the section preamble reads
*"We recall that we are trying to prove 13.5.  In view of 23.5, it suffices to show
the following, which is 1.8.12, and the objective of the remainder of the paper:"*,
and the section ends *"Now we can complete the proof of 24.1, and hence of 13.5 and
therefore of 1.3 and 1.2, as follows."*

Section 24 **defines no term** and **cites no external (prior-work) result**; every
citation in it (1.2, 1.3, 13.5, 13.6, 13.7, 15.2, 17.1, 23.5, 24.2–24.7) is
internal to the paper.  The §17 notions *reflection of a triangle* and *catch a
triangle* occur only inside the **proof** of 24.4 and in no numbered statement, so
`Workspace.Types.TriangleCatching` is not imported.  The words *triad* and *hat*
do not occur in the section at all.

Every defined term used below is imported and never restated:

* `Workspace.Types.Core` — `IsPathList`, `IsPathFrom`, `pathLength`,
  `SPGT.interior`, `IsHoleList`, `holeLength`, `IsAntipathList`,
  `VertexComplete`, `EdgeComplete`, `Complete`, `ConnectedSet`,
  `AnticonnectedSet`;
* `Workspace.Types.Classes` — `InF11` (the class `F₁₁` of §1);
* `Workspace.Types.Decompositions` — `AdmitsBalancedSkewPartition`.

Encoding conventions (see `paper/spec/CONVENTIONS.md`):

* a path of the paper is an *induced* subgraph, given by the list `p : List V` of
  its vertices in order; the paper's `p₁-⋯-pₙ` therefore has `n = p.length`
  vertices and length `pathLength p = n - 1`, its interior `p₂,…,pₙ₋₁` is
  `SPGT.interior p` (always written qualified — a bare `interior` is Mathlib's
  topological one), and `V(P)` is `{w : V | w ∈ p}` (so *"`z ∉ V(P)`"* is
  `z ∉ p`);
* the ends `p₁, pₙ` and the second vertex `p₂` are pinned down by the total
  functions `p.head?`, `p.getLast?`, `p.tail.head?` (no `getElem` bounds needed);
* *"an edge of `P`"*: since `P` is induced, the edges of `P` are exactly the
  adjacent pairs of vertices of `p`, so *"some edge of `P` is `X`-complete"* is
  `∃ a ∈ p, ∃ b ∈ p, EdgeComplete G X a b` (`EdgeComplete` already contains
  `G.Adj a b`);
* a hole is the list of its vertices in cyclic order, with length `holeLength`;
* *"`X` is complete to `Y`"* is `Complete G X Y`, *"`v` is `X`-complete"* is
  `VertexComplete G v X`;
* *"`G` is complete"* means every two distinct vertices of `G` are adjacent, and
  *"`G` is bipartite"* is Mathlib's `SimpleGraph.IsBipartite` (= `Colorable 2`).
-/

set_option autoImplicit false
set_option linter.unusedSectionVars false
set_option linter.unusedVariables false
set_option maxHeartbeats 1000000

namespace Workspace.Statements.S24

open Workspace.Types.Core Workspace.Types.Core.SPGT
open Workspace.Types.Decompositions Workspace.Types.Decompositions.SPGT
open Workspace.Types.Classes Workspace.Types.Classes.SPGT

namespace SPGT

variable {V : Type*} [Fintype V] [DecidableEq V]


/-- **24.4** (printed p. 144), introduced by *"The next is a strengthening of
17.1."*

PAPER: *"Let `G ∈ F₁₁`.  Let `X₁, X₂, X₃` be disjoint nonempty anticonnected sets,
complete to each other.  Let `F ⊆ V(G) \ (X₁ ∪ X₂ ∪ X₃)` be connected, such that for
`i = 1,2,3` there is an `Xᵢ`-complete vertex in `F`.  Then there is a vertex in `F`
complete to two of `X₁, X₂, X₃`."*

Transcription notes.

* *"disjoint"* for three sets is pairwise disjointness (spelled out as in 24.7,
  which prints *"pairwise disjoint"*).
* *"complete to each other"* is `Complete G Xᵢ Xⱼ` for the three pairs.
* *"`F ⊆ V(G) \ (X₁ ∪ X₂ ∪ X₃)`"* is `F ⊆ (X₁ ∪ X₂ ∪ X₃)ᶜ`, and *"connected"* is
  `ConnectedSet`.
* Note that 24.4, unlike 24.5 and 24.7, does **not** assume that `G` fails to
  admit a balanced skew partition.
* *"a vertex in `F` complete to two of `X₁, X₂, X₃`"* is the three-way disjunction
  over the pairs `{X₁,X₂}`, `{X₁,X₃}`, `{X₂,X₃}`. -/
theorem thm_24_4 (G : SimpleGraph V) (hG : InF11 G)
    (X₁ X₂ X₃ : Set V)
    (hd₁₂ : Disjoint X₁ X₂) (hd₁₃ : Disjoint X₁ X₃) (hd₂₃ : Disjoint X₂ X₃)
    (hne₁ : X₁.Nonempty) (hne₂ : X₂.Nonempty) (hne₃ : X₃.Nonempty)
    (ha₁ : AnticonnectedSet G X₁) (ha₂ : AnticonnectedSet G X₂)
    (ha₃ : AnticonnectedSet G X₃)
    (hc₁₂ : Complete G X₁ X₂) (hc₁₃ : Complete G X₁ X₃) (hc₂₃ : Complete G X₂ X₃)
    (F : Set V) (hF : F ⊆ (X₁ ∪ X₂ ∪ X₃)ᶜ) (hFconn : ConnectedSet G F)
    (hF₁ : ∃ f ∈ F, VertexComplete G f X₁)
    (hF₂ : ∃ f ∈ F, VertexComplete G f X₂)
    (hF₃ : ∃ f ∈ F, VertexComplete G f X₃) :
    ∃ f ∈ F,
      (VertexComplete G f X₁ ∧ VertexComplete G f X₂) ∨
      (VertexComplete G f X₁ ∧ VertexComplete G f X₃) ∨
      (VertexComplete G f X₂ ∧ VertexComplete G f X₃) := by
  classical
  by_contra hcon
  have hnotwo : ∀ f ∈ F, ¬ (VertexComplete G f X₁ ∧ VertexComplete G f X₂) ∧
      ¬ (VertexComplete G f X₁ ∧ VertexComplete G f X₃) ∧
      ¬ (VertexComplete G f X₂ ∧ VertexComplete G f X₃) := by
    intro f hf
    exact ⟨fun h => hcon ⟨f, hf, Or.inl h⟩, fun h => hcon ⟨f, hf, Or.inr (Or.inl h)⟩,
      fun h => hcon ⟨f, hf, Or.inr (Or.inr h)⟩⟩
  obtain ⟨X, hX0, hX1, hX2⟩ : ∃ X : Fin 3 → Set V, X 0 = X₁ ∧ X 1 = X₂ ∧ X 2 = X₃ :=
    ⟨![X₁, X₂, X₃], rfl, rfl, rfl⟩
  have hXcases : ∀ l : Fin 3,
      (l = 0 ∧ X l = X₁) ∨ (l = 1 ∧ X l = X₂) ∨ (l = 2 ∧ X l = X₃) := by
    intro l
    fin_cases l
    · exact Or.inl ⟨rfl, hX0⟩
    · exact Or.inr (Or.inl ⟨rfl, hX1⟩)
    · exact Or.inr (Or.inr ⟨rfl, hX2⟩)
  have hcompsymm : ∀ A B : Set V, Complete G A B → Complete G B A :=
    fun A B h b hb a ha => (h a ha b hb).symm
  have hXdisj : ∀ l₁ l₂ : Fin 3, l₁ ≠ l₂ → Disjoint (X l₁) (X l₂) := by
    intro l₁ l₂ hl
    rcases hXcases l₁ with ⟨e1, f1⟩ | ⟨e1, f1⟩ | ⟨e1, f1⟩ <;>
      rcases hXcases l₂ with ⟨e2, f2⟩ | ⟨e2, f2⟩ | ⟨e2, f2⟩ <;>
      rw [f1, f2] <;>
      first
        | exact absurd (e1.trans e2.symm) hl
        | exact hd₁₂ | exact hd₁₃ | exact hd₂₃
        | exact hd₁₂.symm | exact hd₁₃.symm | exact hd₂₃.symm
  have hXne : ∀ l : Fin 3, (X l).Nonempty := by
    intro l
    rcases hXcases l with ⟨-, f⟩ | ⟨-, f⟩ | ⟨-, f⟩ <;> rw [f]
    · exact hne₁
    · exact hne₂
    · exact hne₃
  have hXanti : ∀ l : Fin 3, AnticonnectedSet G (X l) := by
    intro l
    rcases hXcases l with ⟨-, f⟩ | ⟨-, f⟩ | ⟨-, f⟩ <;> rw [f]
    · exact ha₁
    · exact ha₂
    · exact ha₃
  have hXcomp : ∀ l₁ l₂ : Fin 3, l₁ ≠ l₂ → Complete G (X l₁) (X l₂) := by
    intro l₁ l₂ hl
    rcases hXcases l₁ with ⟨e1, f1⟩ | ⟨e1, f1⟩ | ⟨e1, f1⟩ <;>
      rcases hXcases l₂ with ⟨e2, f2⟩ | ⟨e2, f2⟩ | ⟨e2, f2⟩ <;>
      rw [f1, f2] <;>
      first
        | exact absurd (e1.trans e2.symm) hl
        | exact hc₁₂ | exact hc₁₃ | exact hc₂₃
        | exact hcompsymm _ _ hc₁₂ | exact hcompsymm _ _ hc₁₃ | exact hcompsymm _ _ hc₂₃
  have hmemF : (fun S : Set V => S ⊆ F ∧ ConnectedSet G S ∧
      ∀ l : Fin 3, ∃ w ∈ S, VertexComplete G w (X l)) F := by
    refine ⟨subset_rfl, hFconn, ?_⟩
    intro l
    rcases hXcases l with ⟨-, f⟩ | ⟨-, f⟩ | ⟨-, f⟩ <;> rw [f]
    · exact hF₁
    · exact hF₂
    · exact hF₃
  obtain ⟨S, ⟨hSF, hSconn, hSmeet⟩, hSmin⟩ :=
    Workspace.ProofLemmas.ExtremalChoice.exists_min_nat
      (fun S : Set V => S ⊆ F ∧ ConnectedSet G S ∧
        ∀ l : Fin 3, ∃ w ∈ S, VertexComplete G w (X l))
      Set.ncard ⟨F, hmemF⟩
  have hFXS : ∀ w ∈ S, ∀ l : Fin 3, w ∉ X l := by
    intro w hw l
    have hw' : w ∉ X₁ ∪ X₂ ∪ X₃ := hF (hSF hw)
    rcases hXcases l with ⟨-, f⟩ | ⟨-, f⟩ | ⟨-, f⟩ <;> rw [f]
    · exact fun h => hw' (Or.inl (Or.inl h))
    · exact fun h => hw' (Or.inl (Or.inr h))
    · exact fun h => hw' (Or.inr h)
  have hnoS : ∀ w ∈ S, ∀ l₁ l₂ : Fin 3, l₁ ≠ l₂ →
      ¬ (VertexComplete G w (X l₁) ∧ VertexComplete G w (X l₂)) := by
    rintro w hw l₁ l₂ hl ⟨h1, h2⟩
    obtain ⟨n12, n13, n23⟩ := hnotwo w (hSF hw)
    rcases hXcases l₁ with ⟨e1, f1⟩ | ⟨e1, f1⟩ | ⟨e1, f1⟩ <;>
      rcases hXcases l₂ with ⟨e2, f2⟩ | ⟨e2, f2⟩ | ⟨e2, f2⟩ <;>
      rw [f1] at h1 <;> rw [f2] at h2 <;>
      first
        | exact hl (e1.trans e2.symm)
        | exact n12 ⟨h1, h2⟩ | exact n13 ⟨h1, h2⟩ | exact n23 ⟨h1, h2⟩
        | exact n12 ⟨h2, h1⟩ | exact n13 ⟨h2, h1⟩ | exact n23 ⟨h2, h1⟩
  have hSminimal : ∀ S' : Set V, S' ⊆ S → ConnectedSet G S' →
      (∀ l : Fin 3, ∃ w ∈ S', VertexComplete G w (X l)) → S.ncard ≤ S'.ncard := by
    intro S' hsub hconn hmeet
    exact hSmin S' ⟨hsub.trans hSF, hconn, hmeet⟩
  rcases Workspace.Types.Thm244Trichotomy.minimalConnectedThreeTerminal G S
      (fun l => {w : V | VertexComplete G w (X l)}) hSconn hSmeet hnoS hSminimal with
    ⟨v, u, P, hsp⟩ | ⟨v, u, P, hsp⟩ | ⟨i, j, k, P, a, b, hsp⟩
  · exact Workspace.ProofLemmas.Thm244Case1.case1_refute
      G hG X hXdisj hXne hXanti hXcomp S v u P hsp
  · exact Workspace.Types.Thm244Case2.case2_refute
      G hG X hXdisj hXne hXanti hXcomp S hFXS v u P hsp
  · exact Workspace.Types.Thm244Case3.case3_refute
      G hG X hXdisj hXne hXanti hXcomp S hFXS hnoS i j k P a b hsp


end SPGT

end Workspace.Statements.S24
