/-  GENERATED by scripts/split_statements.py from Workspace/Statements/S21.lean -- one numbered statement
    of the paper per module.  The theorem below, its doc-comment and its
    signature are byte-identical to the source module; only the surrounding
    file was mechanically re-cut.  See PROVING_PLAN.md.  -/
import Mathlib
import Workspace.Types.Core
import Workspace.Types.Wheels
import Workspace.Types.Pseudowheels
import Workspace.Types.WheelSystems
import Workspace.Types.Classes
import Workspace.ProofLemmas.Thm211CommonNonneighbor
import Workspace.ProofLemmas.Thm211Hole
import Workspace.ProofLemmas.Thm211Wheel

/-!
# Section 21 — From wheel systems to wheels

The three numbered statements 21.1, 21.2, 21.3 of Chudnovsky–Robertson–Seymour–Thomas,
*The Strong Perfect Graph Theorem* (published/*Annals* version, printed pages
130–135).  Source of the verbatim quotations:
`paper/pdf/S21_From_wheel_systems_to_wheels.md`, `## Numbered statements`.

Section 21 introduces no defined term of its own; every notion used below already
lives in an imported module and nothing is restated here:

* `Workspace.Types.Core` — `IsPathList`, `pathLength`, `VertexComplete`,
  `VertexAnticomplete`, `Complete`, `AnticonnectedSet`;
* `Workspace.Types.Wheels` — `IsWheel` (§16's *wheel*, with rim `C` and hub `Y`);
* `Workspace.Types.Pseudowheels` — `IsPseudowheel` (§18's *pseudowheel*);
* `Workspace.Types.WheelSystems` — `IsFrame`, `IsWheelSystem`,
  `IsHubForWheelSystem`, `wheelSystemX` (`Xᵢ`), `wheelSystemA` (`Aᵢ`);
* `Workspace.Types.Classes` — `InF7`, `InF8` (the classes `F₇`, `F₈` of §1).

Encoding conventions (see `paper/spec/CONVENTIONS.md`):

* a *path* of the paper is the list `p : List V` of its vertices in order together
  with `IsPathList G p`; its length is `pathLength p = p.length - 1`, so the
  paper's `p₁,…,pₙ` are the entries of `p` and `n` is `p.length`;
* "`P` is a path in `G \ (X ∪ Y)`" is `IsPathList G p` together with
  `∀ v ∈ p, v ∉ X ∧ v ∉ Y`;
* the ends `p₁, pₙ` are pinned down by `p.head? = some p₁`,
  `p.getLast? = some pₙ`;
* the paper's 1-based `p_i` is the 0-based `p[i - 1]`; index bounds are stated as
  bounds on `p.length` so that the `getElem` side conditions are discharged
  automatically;
* "`v` has a neighbour in `S`" is `∃ a ∈ S, G.Adj v a`, and "`v` has no neighbour
  in `S`" is `VertexAnticomplete G v S`;
* "at most one member of `Y` has property `Q`" is `Set.Subsingleton {y ∈ Y | Q y}`;
* "there is a wheel in `G` with hub `Y`" is `∃ C : List V, IsWheel G C Y` — the
  hub is the *given* set `Y`, only the rim is existentially quantified;
* a wheel system is carried by a function `x : ℕ → V` together with its height
  (see the module docstring of `Workspace.Types.WheelSystems`), so the paper's
  "`x₀,…,x_{t+1}` is a wheel system with hub `Y`" is
  `IsHubForWheelSystem G z A₀ x (t + 1) Y`, which unfolds to: `x₀,…,x_{t+1}` is a
  wheel system, `Y` is a nonempty anticonnected subset of `V(G) \ (A₀ ∪ {z})`, and
  `z, x₀,…,x_t` are all `Y`-complete while `x_{t+1}` is not.

**Provenance note.**  21.2 is transcribed in its *published* form, whose ambient
hypothesis is `G ∈ F₇` together with the per-`Y` condition "there do not exist
`X, P` so that `(X, Y, P)` is a pseudowheel", and whose conclusion is the bare
"there is a wheel in `G` with hub `Y`".  (The arXiv draft instead assumes
`G ∈ F₈` and concludes a four-way disjunction; nothing from the draft is used
here.)  Likewise 21.3 is the published restatement of 19.1: it carries the guard
"if `x₀,x₁,…,x_r,x_{t+1}` is a wheel system" on the quantification over `r`, which
the draft lacks, and it does *not* conclude anything about `x_{t+1}` having a
neighbour in `A_r` and a non-neighbour in `X_r` (that clause survives only in
22.2).
-/

set_option autoImplicit false

namespace Workspace.Statements.S21

open Workspace.Types.Core Workspace.Types.Core.SPGT
open Workspace.Types.Wheels Workspace.Types.Wheels.SPGT
open Workspace.Types.Pseudowheels Workspace.Types.Pseudowheels.SPGT
open Workspace.Types.WheelSystems Workspace.Types.WheelSystems.SPGT
open Workspace.Types.Classes Workspace.Types.Classes.SPGT

namespace SPGT

variable {V : Type*} [Fintype V] [DecidableEq V]


/-- **21.1** (printed p. 130).

PAPER: *"Let `G ∈ F₇`, and let `X, Y` be disjoint nonempty anticonnected subsets
of `V(G)`, complete to each other.  Let `p₁,…,pₙ` be a path in `G \ (X ∪ Y)` of
length `≥ 4`, such that `p₁, pₙ` are `X`-complete and `p₂,…,pₙ₋₁` are not.  Suppose
that either:*

*1. `p₁, p₂, p₃` are `Y`-complete, or*

*2. there exists `i` with `1 ≤ i ≤ n-3` such that `pᵢ, pᵢ₊₁, pᵢ₊₂, pᵢ₊₃` are all
`Y`-complete, or*

*3. there exists `i` with `1 ≤ i ≤ n-3` such that `pᵢ₊₁, pᵢ₊₂` are `Y`-complete and
`pᵢ, pᵢ₊₃` are not.*

*Then there is a wheel in `G` with hub `Y`."*

Encoding notes.

* *"complete to each other"* is `SPGT.Complete G X Y` (every vertex of `X` is
  adjacent to every vertex of `Y`); by symmetry of adjacency this is the same
  condition as `SPGT.Complete G Y X`, so one of the two suffices.
* *"`p₁, pₙ` are `X`-complete and `p₂,…,pₙ₋₁` are not"* says that `p₁` and `pₙ` are
  exactly the `X`-complete vertices of `P`, and is transcribed as an *if and only
  if* over the vertices of `P`.  This is equivalent to the printed sentence
  because `P` has no repeated vertex and `p₁ ≠ pₙ` (the path has length `≥ 4`).
* The paper's `n` is `p.length`, so the range `1 ≤ i ≤ n-3` of alternatives 2 and
  3 is `1 ≤ i` and `i ≤ p.length - 3`; the 1-based `p_i` is `p[i - 1]`.
* Alternative 1 concerns the first three vertices of the path, i.e. the entries of
  `p.take 3` (a total operation, needing no index bound); since `P` has at least
  five vertices these are exactly `p₁, p₂, p₃`. -/
theorem thm_21_1 (G : SimpleGraph V) (hG : InF7 G) (X Y : Set V)
    (hXY : Disjoint X Y) (hXne : X.Nonempty) (hYne : Y.Nonempty)
    (hXanti : AnticonnectedSet G X) (hYanti : AnticonnectedSet G Y)
    (hXYcomplete : SPGT.Complete G X Y)
    (p : List V) (p₁ pₙ : V) (hp : IsPathList G p)
    (hpXY : ∀ v ∈ p, v ∉ X ∧ v ∉ Y)
    (hlen : 4 ≤ pathLength p)
    (hhead : p.head? = some p₁) (hlast : p.getLast? = some pₙ)
    (hXcomplete : ∀ v ∈ p, (VertexComplete G v X ↔ (v = p₁ ∨ v = pₙ)))
    (halt :
      (∀ v ∈ p.take 3, VertexComplete G v Y) ∨
      (∃ (i : ℕ) (_h1 : 1 ≤ i) (_h2 : i ≤ p.length - 3),
        VertexComplete G p[i - 1] Y ∧ VertexComplete G p[i] Y ∧
          VertexComplete G p[i + 1] Y ∧ VertexComplete G p[i + 2] Y) ∨
      (∃ (i : ℕ) (_h1 : 1 ≤ i) (_h2 : i ≤ p.length - 3),
        VertexComplete G p[i] Y ∧ VertexComplete G p[i + 1] Y ∧
          ¬ VertexComplete G p[i - 1] Y ∧ ¬ VertexComplete G p[i + 2] Y)) :
    ∃ C : List V, IsWheel G C Y := by
  classical
  have hn : 5 ≤ p.length := by unfold pathLength at hlen; omega
  have h0 : p[0]'(by omega) = p₁ :=
    Workspace.ProofLemmas.PathBasics.getElem_zero_of_head? hhead (by omega)
  have hnlast : p[p.length - 1]'(by omega) = pₙ :=
    Workspace.ProofLemmas.PathBasics.getElem_last_of_getLast? hlast (by omega)
  have hfirstX : VertexComplete G p[0] X :=
    (hXcomplete _ (List.getElem_mem _)).mpr (Or.inl h0)
  have hlastX : VertexComplete G p[p.length - 1] X :=
    (hXcomplete _ (List.getElem_mem _)).mpr (Or.inr hnlast)
  have hinnerX : ∀ k (hk : k < p.length), 1 ≤ k → k + 1 < p.length →
      ¬ VertexComplete G p[k] X := by
    intro k hk hk1 hkn hc
    rcases (hXcomplete _ (List.getElem_mem hk)).mp hc with he | he
    · have := hp.2.1.getElem_inj_iff.mp (he.trans h0.symm)
      omega
    · have := hp.2.1.getElem_inj_iff.mp (he.trans hnlast.symm)
      omega
  -- Use the same central pair in all three alternatives, as in the paper.
  obtain ⟨i, hi, hin, hiY, hi1Y, hcase⟩ :
      ∃ (i : ℕ) (_hi : 1 ≤ i) (_hin : i + 2 < p.length),
        VertexComplete G p[i] Y ∧ VertexComplete G p[i + 1] Y ∧
        ((i = 1 ∧ VertexComplete G p[0] Y) ∨
          (VertexComplete G p[i - 1] Y ∧ VertexComplete G p[i + 2] Y) ∨
          (¬ VertexComplete G p[i - 1] Y ∧ ¬ VertexComplete G p[i + 2] Y)) := by
    rcases halt with h | h | h
    · have htake : ∀ k (hk : k < p.length), k < 3 → VertexComplete G p[k] Y := by
        intro k hk hk3
        apply h
        have hkt : k < (p.take 3).length := by simp only [List.length_take]; omega
        simpa only [List.getElem_take] using (List.getElem_mem hkt)
      exact ⟨1, by omega, by omega, htake 1 (by omega) (by omega),
        htake 2 (by omega) (by omega), Or.inl ⟨rfl, htake 0 (by omega) (by omega)⟩⟩
    · obtain ⟨i, hi, hin, hleft, hiY, hi1Y, hright⟩ := h
      exact ⟨i, hi, by omega, hiY, hi1Y, Or.inr (Or.inl ⟨hleft, hright⟩)⟩
    · obtain ⟨i, hi, hin, hiY, hi1Y, hleft, hright⟩ := h
      exact ⟨i, hi, by omega, hiY, hi1Y, Or.inr (Or.inr ⟨hleft, hright⟩)⟩
  obtain ⟨x, hxX, hxi, hxi1⟩ :=
    Workspace.ProofLemmas.Thm211CommonNonneighbor.common_nonneighbor hG.1 hXanti hp hn
      (fun v hv => (hpXY v hv).1) hfirstX hlastX hi hin
      (hinnerX i (by omega) hi (by omega)) (hinnerX (i + 1) (by omega) (by omega) hin)
  have hxp : x ∉ p := fun hx => (hpXY x hx).1 hxX
  have hxY : VertexComplete G x Y := hXYcomplete x hxX
  have hx0 := (hfirstX x hxX).symm
  have hxlast := (hlastX x hxX).symm
  have hBerge : Berge G := hG.1.1.1.1
  obtain ⟨C, hC, hC6, hxC, hCsub, hblock⟩ :=
    Workspace.ProofLemmas.Thm211Hole.hole_through_gap hBerge hp hi hin hxp hx0 hxlast hxi hxi1
  have hCY : ∀ v ∈ C, v ∉ Y := by
    intro v hv
    rcases hCsub v hv with rfl | hvp
    · exact Set.disjoint_left.mp hXY hxX
    · exact (hpXY v hvp).2
  have hiC : p[i] ∈ C := hblock i (by omega) (by omega) (by omega)
  have hi1C : p[i + 1] ∈ C := hblock (i + 1) (by omega) (by omega) (by omega)
  have hleftC : p[i - 1] ∈ C := hblock (i - 1) (by omega) le_rfl (by omega)
  have hrightC : p[i + 2] ∈ C := hblock (i + 2) hin (by omega) le_rfl
  have hne : ∀ j k (hj : j < p.length) (hk : k < p.length), j ≠ k → p[j] ≠ p[k] :=
    fun j k hj hk hjk => Workspace.ProofLemmas.PathBasics.path_ne_of_ne_index hp hj hk hjk
  refine ⟨C, ?_⟩
  rcases hcase with ⟨rfl, h0Y⟩ | ⟨hleftY, hrightY⟩ | ⟨hleftY, hrightY⟩
  · -- The first and third edges of `x-p₁-p₂-p₃` are disjoint.
    exact ⟨⟨hC, hC6⟩, ⟨hYne, hYanti, hCY⟩, x, p[0], p[1], p[2],
      hxC, hleftC, hiC, hi1C, ⟨hx0, hxY, h0Y⟩,
      ⟨Workspace.ProofLemmas.PathBasics.path_adj_succ hp (by omega), hiY, hi1Y⟩,
      (fun he => hxp (he ▸ List.getElem_mem (show 1 < p.length by omega))),
      (fun he => hxp (he ▸ List.getElem_mem (show 2 < p.length by omega))),
      hne 0 1 (by omega) (by omega) (by omega),
      hne 0 2 (by omega) (by omega) (by omega)⟩
  · -- The first and third edges of `pᵢ-pᵢ₊₁-pᵢ₊₂-pᵢ₊₃` are disjoint.
    have hleftadj : G.Adj p[i - 1] p[i] :=
      (Workspace.ProofLemmas.PathBasics.path_adj_iff hp (by omega) (by omega)).mpr
        (Or.inl (by omega))
    exact ⟨⟨hC, hC6⟩, ⟨hYne, hYanti, hCY⟩, p[i - 1], p[i], p[i + 1], p[i + 2],
      hleftC, hiC, hi1C, hrightC, ⟨hleftadj, hleftY, hiY⟩,
      ⟨Workspace.ProofLemmas.PathBasics.path_adj_succ hp hin, hi1Y, hrightY⟩,
      hne _ _ (by omega) (by omega) (by omega),
      hne _ _ (by omega) (by omega) (by omega),
      hne _ _ (by omega) (by omega) (by omega),
      hne _ _ (by omega) (by omega) (by omega)⟩
  · -- The central complete edge is isolated among the complete edges of the rim.
    apply Workspace.ProofLemmas.Thm211Wheel.wheel_of_isolated_complete_edge hBerge hC hC6
      hYne hYanti hCY hiC hi1C hxC
      ⟨Workspace.ProofLemmas.PathBasics.path_adj_succ hp (by omega), hiY, hi1Y⟩ hxY
      (fun he => hxp (he ▸ List.getElem_mem (show i < p.length by omega)))
      (fun he => hxp (he ▸ List.getElem_mem (show i + 1 < p.length by omega)))
    intro w hw hwY
    rcases hCsub w hw with rfl | hwp
    · exact ⟨fun hadj => (hxi hadj.symm).elim, fun hadj => (hxi1 hadj.symm).elim⟩
    obtain ⟨k, hk, rfl⟩ := List.mem_iff_getElem.mp hwp
    constructor
    · intro hadj
      have hkadj := (Workspace.ProofLemmas.PathBasics.path_adj_iff hp (by omega) hk).mp hadj
      rcases hkadj with he | he
      · exact hp.2.1.getElem_inj_iff.mpr he.symm
      · have hkleft : p[k] = p[i - 1] := hp.2.1.getElem_inj_iff.mpr (by omega)
        exact (hleftY (hkleft ▸ hwY)).elim
    · intro hadj
      have hkadj := (Workspace.ProofLemmas.PathBasics.path_adj_iff hp (by omega) hk).mp hadj
      rcases hkadj with he | he
      · have hkright : p[k] = p[i + 2] := hp.2.1.getElem_inj_iff.mpr (by omega)
        exact (hrightY (hkright ▸ hwY)).elim
      · exact hp.2.1.getElem_inj_iff.mpr (by omega)


end SPGT

end Workspace.Statements.S21
