/-  GENERATED by scripts/split_statements.py from Workspace/Statements/S05.lean -- one numbered statement
    of the paper per module.  The theorem below, its doc-comment and its
    signature are byte-identical to the source module; only the surrounding
    file was mechanically re-cut.  See PROVING_PLAN.md.  -/
import Mathlib
import Workspace.Types.Core
import Workspace.Types.Tracks
import Workspace.Types.Appearances
import Workspace.Types.Decompositions
import Workspace.Types.BasicClasses
import Workspace.ProofLemmas.Thm58Setup
import Workspace.ProofLemmas.PathBasics
import Workspace.ProofLemmas.Thm58MinimalNonlocal
import Workspace.ProofLemmas.Thm58TwoNonlocalAttachments
import Workspace.ProofLemmas.Thm58MinimalFIsPath
import Workspace.ProofLemmas.Thm58SingletonCase
import Workspace.ProofLemmas.Thm58NonSingletonEndgame

/-!
# Section 5 — Small attachments to a line graph

The eight numbered statements 5.1 – 5.8 of Chudnovsky–Robertson–Seymour–Thomas,
*The Strong Perfect Graph Theorem* (published / *Annals* version; printed pages 18–28).
Every definition used here is imported, never restated:

* `Workspace.Types.Core` — `Berge`, `IsPathFrom`, `pathLength`, `ConnectedSet`, …
* `Workspace.Types.Tracks` — `IsTrackList`, `trackLength`, `trackEdges`, `IsTrackFrom`,
  `branchVertices`, `IsBranch`, `incidentEdges` (`= δ_H(v)`), `IsSubdivision`,
  `IsBipartiteSubdivision`, `IsKConnected`, `CyclicallyThreeConnected`, `DifferentBiparity`
* `Workspace.Types.Appearances` — `IsAppearance`, `Appears`, `DegenerateK4Appearance`,
  `DegenerateAppearance`, `NondegenerateAppearance`, `IsJEnlargement`, `SaturatesLineGraph`,
  `LocalForLineGraph`, `MajorForLineGraph`, `attachments`
* `Workspace.Types.Decompositions` — `AdmitsProper2Join`, `AdmitsBalancedSkewPartition`
* `Workspace.Types.BasicClasses` — `IsLineGraphOfBipartite`

## Encoding conventions specific to this section

* `K₄` is `(⊤ : SimpleGraph (Fin 4))` and `K₃,₃` is `completeBipartiteGraph (Fin 3) (Fin 3)`;
  "`A = B`" for two graphs on different vertex types is `Nonempty (A ≃g B)`.
* A track is the list `q` of its vertices in order, so `E(track) = trackEdges q`, its length
  is `trackLength q = q.length - 1`, and its ends are named by `IsTrackFrom`.  Consequently
  the paper's *"track of length ≥ k"* is the guard `k + 1 ≤ q.length`; this guard is written
  as an existential binder `(_hq : k + 1 ≤ q.length)` so that the `getElem` side conditions
  for the first edge `s(q[0], q[1])` and the last edge `s(q[q.length-2], q[q.length-1])` are
  discharged automatically.
* *"`V(J)` is the set of branch-vertices of `H`"* and *"the branches of `H` are in 1-1
  correspondence with the edges of `J`"* (printed p. 20) are used to render *"vertex of `J`"*
  as `branchVertices H` and *"edge `b₁b₂` of `J`"* as *"branch of `H` with ends `b₁, b₂`"*,
  exactly as in `Appearances.LocalForLineGraph`.  This avoids exposing the embedding
  `V(J) ⊆ V(H)` hidden inside `IsSubdivision`.
* For an appearance, `V(L(H))` is the vertex set `K ⊆ V(G)` of the induced subgraph, and the
  vertex of `G` corresponding to an edge `e` of `H` is `↑(φ ⟨e, he⟩)`, where
  `φ : H.lineGraph ≃g G.induce K` is the isomorphism carried by the appearance.
-/

set_option autoImplicit false

namespace Workspace.Statements.S05

open Workspace.Types.Core Workspace.Types.Core.SPGT
open Workspace.Types.Tracks Workspace.Types.Tracks.SPGT
open Workspace.Types.Appearances Workspace.Types.Appearances.SPGT
open Workspace.Types.Decompositions Workspace.Types.Decompositions.SPGT
open Workspace.Types.BasicClasses Workspace.Types.BasicClasses.SPGT

namespace SPGT

variable {V : Type*} [Fintype V] [DecidableEq V]


/-- **5.8** (printed p. 25)

PAPER: *"Let `G` be Berge, let `J` be a 3-connected graph, and let `L(H)` be an appearance of
`J` in `G`.  For each vertex `v` of `J`, let `N_v` be the set of edges of `H` incident with
`v`; and for each edge `uv` of `J`, let `R_uv` be the path of `L(H)` with vertex set the set
of edges of the branch of `H` between `u` and `v`.  Let `F ⊆ V(G) \ V(L(H))` be connected,
such that the set of attachments of `F` in `L(H)` is not local.  Assume that no member of `F`
is major.  Then there is a path `P` of `G` with `V(P) ⊆ F` and with ends `p₁` and `p₂`, such
that either:*

*1. there are vertices `c₁, c₂` of `H`, not in the same branch of `H`, such that for
`i = 1, 2` `pᵢ` is complete in `G` to `N_{cᵢ}`, and there are no other edges between `V(P)`
and `V(L(H))`, or*

*2. there is an edge `b₁b₂` of `J` such that one of the following holds (for `i = 1, 2`, `rᵢ`
denotes the unique vertex in `N_{bᵢ} ∩ V(R_{b₁b₂})`):*

*(a) `p₁` is adjacent in `G` to all vertices in `N_{b₁} \ {r₁}`, and `p₂` has a neighbour in
`R_{b₁b₂} \ r₁`, and every edge from `V(P)` to `V(L(H)) \ {r₁}` is either from `p₁` to
`N_{b₁} \ {r₁}`, or from `p₂` to `V(R_{b₁b₂}) \ {r₁}`, or*

*(b) for `i = 1, 2`, `pᵢ` is adjacent in `G` to all vertices in `N_{bᵢ} \ {rᵢ}`, and there are
no other edges between `V(P)` and `V(L(H))` except possibly `p₁r₁, p₂r₂`, and `P` has the same
parity as `R_{b₁b₂}`, or*

*(c) `p₁ = p₂`, and `p₁` is adjacent to all vertices in `(N_{b₁} ∪ N_{b₂}) \ {r₁, r₂}`, and
all neighbours of `p₁` in `V(L(H))` belong to `N_{b₁} ∪ N_{b₂} ∪ V(R_{b₁b₂})`, and `R_{b₁b₂}`
is even, or*

*(d) `r₁ = r₂`, and for `i = 1, 2`, `pᵢ` is adjacent in `G` to all vertices in
`N_{bᵢ} \ {rᵢ}`, and there are no other edges between `V(P)` and `V(L(H)) \ {r₁}`, and `P` is
even."*

Transcription notes.

* The appearance is given by the bipartite subdivision `H` of `J`, the vertex set `K` of the
  induced subgraph of `G`, and the isomorphism `φ : L(H) ≃g G|K` (together `hsub` and `φ` are
  `IsAppearance G J H K`).  So `V(L(H)) = K`, and the vertex of `G` corresponding to an edge
  `e` of `H` is `↑(φ ⟨e, he⟩)`.
* `N_v` is introduced inside the statement and is bound here as the parameter `N`, pinned down
  by `hN`: it is `δ_H(v)` read as a subset of `V(L(H))` and then transported into `V(G)` by
  `φ` (the paper: *"the set `N_v` is just the set `δ_H(v)`, but now we are going to think of
  it as a subset of the vertex set of `L(H)`"*).  Statement 1 applies `N` to arbitrary
  vertices `c₁, c₂` of `H`, so `N` is defined for every vertex of `H`.
* `R_{b₁b₂}` is likewise introduced inside the statement; it is bound inside alternative 2,
  where it is used, as a path `R` of `G` whose vertex set is the `φ`-image of the edge set of
  the branch `q` of `H` between `b₁` and `b₂`.  *"The unique vertex in `N_{bᵢ} ∩ V(R_{b₁b₂})`"*
  pins down `rᵢ` by `N bᵢ ∩ V(R) = {rᵢ}`.
* *"an edge `b₁b₂` of `J`"* is rendered, as everywhere in this file, as *"a branch of `H` with
  ends `b₁, b₂`"*, with `b₁, b₂` branch-vertices of `H` (`= V(J)`, printed p. 20).
* In 2(a) the paper writes the bare `R_{b₁b₂} \ r₁` once and `V(R_{b₁b₂}) \ {r₁}` a few words
  later; both are transcribed with the intended reading `V(R_{b₁b₂}) \ {r₁}`.
* *"`P` has the same parity as `R_{b₁b₂}`"* is `Even (pathLength P) ↔ Even (pathLength R)`. -/
theorem thm_5_8 (G : SimpleGraph V) (hG : Berge G)
    (m : ℕ) (J : SimpleGraph (Fin m)) (hJ : IsKConnected J 3)
    (n : ℕ) (H : SimpleGraph (Fin n)) (K : Set V)
    (hsub : IsBipartiteSubdivision J H)
    (φ : H.lineGraph ≃g G.induce K)
    (N : Fin n → Set V)
    (hN : ∀ c : Fin n, N c =
      {x : V | ∃ (e : Sym2 (Fin n)) (he : e ∈ H.edgeSet),
        e ∈ incidentEdges H c ∧ x = (↑(φ ⟨e, he⟩) : V)})
    (F : Set V) (hFK : F ⊆ Kᶜ) (hFconn : ConnectedSet G F)
    (hnotlocal : ¬ LocalForLineGraph H
      {e : Sym2 (Fin n) | ∃ he : e ∈ H.edgeSet,
        (↑(φ ⟨e, he⟩) : V) ∈ attachments G F K})
    (hnomajor : ∀ x ∈ F, ¬ MajorForLineGraph G H K φ x) :
    ∃ (P : List V) (p₁ p₂ : V), IsPathFrom G P p₁ p₂ ∧ (∀ x ∈ P, x ∈ F) ∧
      ((∃ c₁ c₂ : Fin n,
          (¬ ∃ q : List (Fin n), IsBranch H q ∧ c₁ ∈ q ∧ c₂ ∈ q) ∧
          (∀ x ∈ N c₁, G.Adj p₁ x) ∧ (∀ x ∈ N c₂, G.Adj p₂ x) ∧
          (∀ x ∈ P, ∀ y ∈ K, G.Adj x y → (x = p₁ ∧ y ∈ N c₁) ∨ (x = p₂ ∧ y ∈ N c₂))) ∨
       (∃ (b₁ b₂ : Fin n) (q : List (Fin n)) (R : List V) (r₁ r₂ : V),
          b₁ ∈ branchVertices H ∧ b₂ ∈ branchVertices H ∧
          IsBranch H q ∧ IsTrackFrom H q b₁ b₂ ∧
          IsPathList G R ∧
          {x : V | x ∈ R} =
            {x : V | ∃ (e : Sym2 (Fin n)) (he : e ∈ H.edgeSet),
              e ∈ trackEdges q ∧ x = (↑(φ ⟨e, he⟩) : V)} ∧
          N b₁ ∩ {x : V | x ∈ R} = {r₁} ∧ N b₂ ∩ {x : V | x ∈ R} = {r₂} ∧
          (((∀ x ∈ N b₁ \ {r₁}, G.Adj p₁ x) ∧
            (∃ x ∈ {y : V | y ∈ R} \ {r₁}, G.Adj p₂ x) ∧
            (∀ x ∈ P, ∀ y ∈ K, y ≠ r₁ → G.Adj x y →
              (x = p₁ ∧ y ∈ N b₁ \ {r₁}) ∨ (x = p₂ ∧ y ∈ {z : V | z ∈ R} \ {r₁}))) ∨
           ((∀ x ∈ N b₁ \ {r₁}, G.Adj p₁ x) ∧ (∀ x ∈ N b₂ \ {r₂}, G.Adj p₂ x) ∧
            (∀ x ∈ P, ∀ y ∈ K, G.Adj x y →
              (x = p₁ ∧ y ∈ N b₁ \ {r₁}) ∨ (x = p₂ ∧ y ∈ N b₂ \ {r₂}) ∨
              (x = p₁ ∧ y = r₁) ∨ (x = p₂ ∧ y = r₂)) ∧
            (Even (pathLength P) ↔ Even (pathLength R))) ∨
           (p₁ = p₂ ∧ (∀ x ∈ (N b₁ ∪ N b₂) \ {r₁, r₂}, G.Adj p₁ x) ∧
            (∀ y ∈ K, G.Adj p₁ y → y ∈ N b₁ ∪ N b₂ ∪ {z : V | z ∈ R}) ∧
            Even (pathLength R)) ∨
           (r₁ = r₂ ∧ (∀ x ∈ N b₁ \ {r₁}, G.Adj p₁ x) ∧ (∀ x ∈ N b₂ \ {r₂}, G.Adj p₂ x) ∧
            (∀ x ∈ P, ∀ y ∈ K, y ≠ r₁ → G.Adj x y →
              (x = p₁ ∧ y ∈ N b₁ \ {r₁}) ∨ (x = p₂ ∧ y ∈ N b₂ \ {r₂})) ∧
            Even (pathLength P))))) := by
  classical
  obtain ⟨F₀, hF₀F, hF₀ne, hF₀conn, hF₀notlocal, hF₀min⟩ :=
    Workspace.ProofLemmas.Thm58MinimalNonlocal.thm58MinimalNonlocal
      G m J hJ n H K hsub.1 φ F hFconn hnotlocal
  have hF₀K : F₀ ⊆ Kᶜ := hF₀F.trans hFK
  have hF₀major : ∀ x ∈ F₀, ¬ MajorForLineGraph G H K φ x :=
    fun x hx => hnomajor x (hF₀F hx)
  by_cases hsingleton : ∃ y : V, F₀ = {y}
  · obtain ⟨y, rfl⟩ := hsingleton
    have hyK : y ∉ K := hF₀K (by simp)
    obtain ⟨P, p₁, p₂, hP, hPy, hout⟩ :=
      Workspace.ProofLemmas.Thm58SingletonCase.thm58SingletonCase
        G hG m J hJ n H K hsub φ N hN y hyK hF₀notlocal
          (hF₀major y (by simp))
    exact ⟨P, p₁, p₂, hP, fun x hx => hF₀F (hPy x hx), hout⟩
  · have hF₀card : 2 ≤ F₀.ncard := by
      have hpos : 0 < F₀.ncard := (Set.ncard_pos (Set.toFinite F₀)).mpr hF₀ne
      by_contra hnot
      have hone : F₀.ncard = 1 := by omega
      obtain ⟨y, hy⟩ := Set.ncard_eq_one.mp hone
      exact hsingleton ⟨y, hy⟩
    set X : Set (Sym2 (Fin n)) :=
      {e : Sym2 (Fin n) | ∃ he : e ∈ H.edgeSet,
        (↑(φ ⟨e, he⟩) : V) ∈ attachments G F₀ K} with hX
    have hXE : X ⊆ H.edgeSet := by
      rw [hX]
      rintro e ⟨he, -⟩
      exact he
    obtain ⟨x₁, hx₁X, x₂, hx₂X, hpair⟩ :=
      Workspace.ProofLemmas.Thm58TwoNonlocalAttachments.thm58TwoNonlocalAttachments
        H ⟨m, J, hJ, hsub.1⟩ hsub.2 X hXE hF₀notlocal
    rw [hX] at hx₁X hx₂X
    obtain ⟨hx₁, hx₁att⟩ := hx₁X
    obtain ⟨hx₂, hx₂att⟩ := hx₂X
    obtain ⟨P, p₁, p₂, hP, hPF₀, -, hlocal₁, hlocal₂⟩ :=
      Workspace.ProofLemmas.Thm58MinimalFIsPath.thm58MinimalFIsPath
        G m J hJ n H K hsub φ F₀ hF₀K hF₀conn hF₀notlocal hF₀min
          x₁ x₂ hx₁ hx₂ hx₁att hx₂att hpair
    have hout :=
      Workspace.ProofLemmas.Thm58NonSingletonEndgame.thm58NonSingletonEndgame
        G hG m J hJ n H K hsub φ N hN F₀ hF₀K hF₀notlocal
          P p₁ p₂ hP hPF₀ hlocal₁ hlocal₂ hF₀card
    rcases hout with hout | hout
    · exact ⟨P, p₁, p₂, hP, fun x hx => hF₀F (by rw [← hPF₀]; exact hx), hout⟩
    · refine ⟨P.reverse, p₂, p₁, Workspace.ProofLemmas.PathBasics.isPathFrom_reverse hP,
        fun x hx => hF₀F (by rw [← hPF₀]; exact List.mem_reverse.mp hx), hout⟩


end SPGT

end Workspace.Statements.S05
