/-  GENERATED by scripts/split_statements.py from Workspace/Statements/S05.lean -- one numbered statement
    of the paper per module.  The theorem below, its doc-comment and its
    signature are byte-identical to the source module; only the surrounding
    file was mechanically re-cut.  See PROVING_PLAN.md.  -/
import Mathlib
import Workspace.Types.Core
import Workspace.Types.Tracks
import Workspace.Types.Appearances
import Workspace.Types.Decompositions
import Workspace.Types.BasicClasses
import Workspace.ProofLemmas.Thm53Assembly
import Workspace.ProofLemmas.Thm53Step1
import Workspace.ProofLemmas.NoCrossTrackBranch
import Workspace.ProofLemmas.K33SubgraphYieldsTheorem
import Workspace.ProofLemmas.CrossTrackYieldsK33
import Workspace.ProofLemmas.K33ComponentYieldsNondegenerate

/-!
# Section 5 — Small attachments to a line graph

The eight numbered statements 5.1 – 5.8 of Chudnovsky–Robertson–Seymour–Thomas,
*The Strong Perfect Graph Theorem* (published / *Annals* version; printed pages 18–28).
Every definition used here is imported, never restated:

* `Workspace.Types.Core` — `Berge`, `IsPathFrom`, `pathLength`, `ConnectedSet`, …
* `Workspace.Types.Tracks` — `IsTrackList`, `trackLength`, `trackEdges`, `IsTrackFrom`,
  `branchVertices`, `IsBranch`, `incidentEdges` (`= δ_H(v)`), `IsSubdivision`,
  `IsBipartiteSubdivision`, `IsKConnected`, `CyclicallyThreeConnected`, `DifferentBiparity`
* `Workspace.Types.Appearances` — `IsAppearance`, `Appears`, `DegenerateK4Appearance`,
  `DegenerateAppearance`, `NondegenerateAppearance`, `IsJEnlargement`, `SaturatesLineGraph`,
  `LocalForLineGraph`, `MajorForLineGraph`, `attachments`
* `Workspace.Types.Decompositions` — `AdmitsProper2Join`, `AdmitsBalancedSkewPartition`
* `Workspace.Types.BasicClasses` — `IsLineGraphOfBipartite`

## Encoding conventions specific to this section

* `K₄` is `(⊤ : SimpleGraph (Fin 4))` and `K₃,₃` is `completeBipartiteGraph (Fin 3) (Fin 3)`;
  "`A = B`" for two graphs on different vertex types is `Nonempty (A ≃g B)`.
* A track is the list `q` of its vertices in order, so `E(track) = trackEdges q`, its length
  is `trackLength q = q.length - 1`, and its ends are named by `IsTrackFrom`.  Consequently
  the paper's *"track of length ≥ k"* is the guard `k + 1 ≤ q.length`; this guard is written
  as an existential binder `(_hq : k + 1 ≤ q.length)` so that the `getElem` side conditions
  for the first edge `s(q[0], q[1])` and the last edge `s(q[q.length-2], q[q.length-1])` are
  discharged automatically.
* *"`V(J)` is the set of branch-vertices of `H`"* and *"the branches of `H` are in 1-1
  correspondence with the edges of `J`"* (printed p. 20) are used to render *"vertex of `J`"*
  as `branchVertices H` and *"edge `b₁b₂` of `J`"* as *"branch of `H` with ends `b₁, b₂`"*,
  exactly as in `Appearances.LocalForLineGraph`.  This avoids exposing the embedding
  `V(J) ⊆ V(H)` hidden inside `IsSubdivision`.
* For an appearance, `V(L(H))` is the vertex set `K ⊆ V(G)` of the induced subgraph, and the
  vertex of `G` corresponding to an edge `e` of `H` is `↑(φ ⟨e, he⟩)`, where
  `φ : H.lineGraph ≃g G.induce K` is the isomorphism carried by the appearance.
-/

set_option autoImplicit false

namespace Workspace.Statements.S05

open Workspace.Types.Core Workspace.Types.Core.SPGT
open Workspace.Types.Tracks Workspace.Types.Tracks.SPGT
open Workspace.Types.Appearances Workspace.Types.Appearances.SPGT
open Workspace.Types.Decompositions Workspace.Types.Decompositions.SPGT
open Workspace.Types.BasicClasses Workspace.Types.BasicClasses.SPGT

namespace SPGT

variable {V : Type*} [Fintype V] [DecidableEq V]


/-- **5.3** (printed p. 20)

PAPER: *"Let `H` be bipartite and cyclically 3-connected.  Then either `H = K₃,₃`, or `H` is
a subdivision of `K₄`, or `H` has a subgraph `H'` such that `H'` is a subdivision of `K₄` and
`L(H')` is nondegenerate."*

Transcription notes.

* *"a subgraph `H'` of `H`"* is a `SimpleGraph.Subgraph` of `H` — a set of vertices together
  with a set of edges among them, not necessarily induced and not necessarily proper — and
  the graph it *is* is `S.coe`.
* *"`L(H')` is nondegenerate"* is the printed-p.-18 notion for a subdivision of `K₄`, i.e.
  `NondegenerateAppearance K₄ S.coe`, which unfolds to `¬ DegenerateK4Appearance S.coe`. -/
theorem thm_5_3 {W : Type*} [Fintype W] [DecidableEq W] (H : SimpleGraph W)
    (hbip : H.IsBipartite) (hc3 : CyclicallyThreeConnected H) :
    Nonempty (H ≃g completeBipartiteGraph (Fin 3) (Fin 3)) ∨
    IsSubdivision (⊤ : SimpleGraph (Fin 4)) H ∨
    (∃ S : H.Subgraph,
      IsSubdivision (⊤ : SimpleGraph (Fin 4)) S.coe ∧
      NondegenerateAppearance (⊤ : SimpleGraph (Fin 4)) S.coe) := by
  apply Workspace.ProofLemmas.Thm53Assembly.thm_5_3_of_steps H hbip hc3
  · exact Workspace.ProofLemmas.Thm53Step1.hasK4SubdivisionSubgraph_of_cyclicallyThreeConnected
      H hc3
  · intro hbip' hc3' hdeg P Q hPlen hQlen hP hQ hdisj hPodd hQodd e11 e1n em1 emn
    by_cases hno : ∀ (R : List W) (a b : W), IsTrackFrom H R a b → a ∈ P → b ∈ Q →
        s(P[0], Q[0]) ∈ trackEdges R ∨
        s(P[0], Q[Q.length - 1]) ∈ trackEdges R ∨
        s(P[P.length - 1], Q[0]) ∈ trackEdges R ∨
        s(P[P.length - 1], Q[Q.length - 1]) ∈ trackEdges R
    · exact Or.inl
        (Workspace.ProofLemmas.NoCrossTrackBranch.isSubdivision_k4_of_no_cross_track
          hbip' hc3' P Q hPlen hQlen hP hQ hdisj hPodd hQodd e11 e1n em1 emn hno)
    · right
      push Not at hno
      obtain ⟨R, a, b, hR, ha, hb, h11, h1n, hm1, hmn⟩ := hno
      exact Workspace.Types.CrossTrackYieldsK33.crossTrackYieldsK33
        H hbip' P Q hPlen hQlen hP hQ hdisj hPodd hQodd e11 e1n em1 emn hdeg
        ⟨a, b, R, ha, hb, hR, h11, h1n, hm1, hmn⟩
  · apply Workspace.ProofLemmas.K33SubgraphYieldsTheorem.k33SubgraphYieldsTheorem_of_component H
    intro hbip' hc3' J hJ houtside
    exact Workspace.Types.K33ComponentYieldsNondegenerate.k33ComponentYieldsNondegenerate
      H hbip' hc3' J hJ houtside


end SPGT

end Workspace.Statements.S05
