/-  GENERATED by scripts/split_statements.py from Workspace/Statements/S03.lean -- one numbered statement
    of the paper per module.  The theorem below, its doc-comment and its
    signature are byte-identical to the source module; only the surrounding
    file was mechanically re-cut.  See PROVING_PLAN.md.  -/
import Mathlib
import Workspace.Types.Core
import Workspace.ProofLemmas.Thm32Setup
import Workspace.ProofLemmas.Thm32OneSided
import Workspace.ProofLemmas.Thm32Symmetry

/-!
# Section 3 — Paths and antipaths meeting

The three numbered statements 3.1, 3.2, 3.3 of Chudnovsky–Robertson–Seymour–Thomas,
*The Strong Perfect Graph Theorem* (printed pages 13–14).  Section 3 introduces no new
defined terms, so everything used here comes from `Workspace.Types.Core`.

Encoding conventions (see `paper/spec/CONVENTIONS.md`):

* a hole / antihole is the list of its vertices in cyclic order (`IsHoleList`,
  `IsAntiholeList`), and `V(C)` is `{v | v ∈ C}`;
* a path / antipath is the list of its vertices in order (`IsPathList`,
  `IsAntipathList`), with named ends via `IsPathFrom` / `IsAntipathFrom`;
* a path `p₁-⋯-p_m` is a list `p` with `p.length = m`, so the paper's `p_i` is `p[i-1]`;
  consequently `{p_1,…,p_{s-1}} = p.take (s-1)`, `{p_{s+2},…,p_m} = p.drop (s+1)`, and a
  window `{p_{s-2},…,p_{s+2}}` is `(p.drop (s-3)).take 5`.
-/

namespace Workspace.Statements.S03

open Workspace.Types.Core
open Workspace.Types.Core.SPGT

namespace SPGT

variable {V : Type*} [Fintype V] [DecidableEq V]


/-- **3.2** (printed p. 13)

PAPER: *"Let `p₁-⋯-p_m` be a path in a Berge graph `G`.  Let `2 ≤ s ≤ m-2`, and let
`p_s-q₁-⋯-q_n-p_{s+1}` be an antipath, where `n ≥ 2` is odd.  Assume that each of
`q₁,…,q_n` has a neighbour in `{p₁,…,p_{s-1}}` and a neighbour in `{p_{s+2},…,p_m}`.
Then either:*

*• `s ≥ 3` and the only nonedges between `{p_{s-2},p_{s-1},p_s,p_{s+1},p_{s+2}}` and
`{q₁,…,q_n}` are `p_{s-1}q_n`, `p_sq₁`, `p_{s+1}q_n`, or*

*• `s ≤ m-3` and the only nonedges between `{p_{s-1},p_s,p_{s+1},p_{s+2},p_{s+3}}` and
`{q₁,…,q_n}` are `p_sq₁`, `p_{s+1}q_n`, `p_{s+2}q₁`."*

The hypothesis "`n ≥ 2` is odd" is transcribed exactly as printed, as the two conjuncts
`2 ≤ n` and `Odd n` (which together say `n ≥ 3` is odd).

Lists are `0`-indexed, so the paper's `p_i` is `p[i-1]` and its `q_j` is `q[j-1]`; in
particular `p_s = p[s-1]`, `p_{s+1} = p[s]`, `q₁ = q[0]` and `q_n = q[n-1]`.  The two
five-vertex windows `{p_{s-2},…,p_{s+2}}` and `{p_{s-1},…,p_{s+3}}` are
`(p.drop (s-3)).take 5` and `(p.drop (s-2)).take 5` respectively (each guarded by the
side condition `3 ≤ s`, resp. `s ≤ m-3`, of its own alternative).  "The only nonedges
between `X` and `Y` are `e₁, e₂, e₃`" is rendered as: for `x ∈ X` and `y ∈ Y`, `xy` is a
nonedge **iff** the pair `(x,y)` is one of the three listed pairs. -/
theorem thm_3_2 (G : SimpleGraph V) (hG : Berge G) (m n s : ℕ) (p q : List V)
    (hp : IsPathList G p) (hpm : p.length = m)
    (hs1 : 2 ≤ s) (hs2 : s ≤ m - 2)
    (hqn : q.length = n) (hn2 : 2 ≤ n) (hnodd : Odd n)
    (hQ : IsAntipathFrom G (p[s - 1] :: (q ++ [p[s]])) p[s - 1] p[s])
    (hqleft : ∀ x ∈ q, ∃ y ∈ p.take (s - 1), G.Adj x y)
    (hqright : ∀ x ∈ q, ∃ y ∈ p.drop (s + 1), G.Adj x y) :
    (3 ≤ s ∧ ∀ x ∈ (p.drop (s - 3)).take 5, ∀ y ∈ q,
        (¬ G.Adj x y ↔
          (x = p[s - 2] ∧ y = q[n - 1]) ∨ (x = p[s - 1] ∧ y = q[0]) ∨
            (x = p[s] ∧ y = q[n - 1]))) ∨
    (s ≤ m - 3 ∧ ∀ x ∈ (p.drop (s - 2)).take 5, ∀ y ∈ q,
        (¬ G.Adj x y ↔
          (x = p[s - 1] ∧ y = q[0]) ∨ (x = p[s] ∧ y = q[n - 1]) ∨
            (x = p[s + 1] ∧ y = q[0]))) := by
  classical
  rcases Workspace.ProofLemmas.Thm32Setup.initial_configuration
    G hG m n s p q hp hpm hs1 hs2 hqn hn2 hnodd hQ hqleft hqright with hleft | hright
  · obtain ⟨u, hu, v, hv, huv, hpath⟩ := hleft
    exact Or.inl (Workspace.ProofLemmas.Thm32OneSided.left_pattern
      G hG m n s p q hp hpm hs1 hs2 hqn hn2 hnodd hQ hqleft hqright
        u hu v hv huv hpath)
  · obtain ⟨w, hw, x, hx, hwx, hpath⟩ := hright
    exact Or.inr (Workspace.ProofLemmas.Thm32Symmetry.right_pattern
      G hG m n s p q hp hpm hs1 hs2 hqn hn2 hnodd hQ hqleft hqright
        w hw x hx hwx hpath)


end SPGT

end Workspace.Statements.S03
