/-  GENERATED by scripts/split_statements.py from Workspace/Statements/S03.lean -- one numbered statement
    of the paper per module.  The theorem below, its doc-comment and its
    signature are byte-identical to the source module; only the surrounding
    file was mechanically re-cut.  See PROVING_PLAN.md.  -/
import Mathlib
import Workspace.Types.Core
import Workspace.Statements.S02.Thm_2_2
import Workspace.ProofLemmas.PathBasics
import Workspace.ProofLemmas.PathAttach
import Workspace.ProofLemmas.PrismBasics
import Workspace.ProofLemmas.HoleBasics
import Workspace.ProofLemmas.InducedPathExtraction
import Workspace.ProofLemmas.OddWheelArc
import Workspace.ProofLemmas.HoleArithmetic

set_option autoImplicit false
set_option linter.unusedSectionVars false
set_option linter.unusedVariables false
set_option maxHeartbeats 2000000

/-!
# Section 3 — Paths and antipaths meeting

The three numbered statements 3.1, 3.2, 3.3 of Chudnovsky–Robertson–Seymour–Thomas,
*The Strong Perfect Graph Theorem* (printed pages 13–14).  Section 3 introduces no new
defined terms, so everything used here comes from `Workspace.Types.Core`.

Encoding conventions (see `paper/spec/CONVENTIONS.md`):

* a hole / antihole is the list of its vertices in cyclic order (`IsHoleList`,
  `IsAntiholeList`), and `V(C)` is `{v | v ∈ C}`;
* a path / antipath is the list of its vertices in order (`IsPathList`,
  `IsAntipathList`), with named ends via `IsPathFrom` / `IsAntipathFrom`;
* a path `p₁-⋯-p_m` is a list `p` with `p.length = m`, so the paper's `p_i` is `p[i-1]`;
  consequently `{p_1,…,p_{s-1}} = p.take (s-1)`, `{p_{s+2},…,p_m} = p.drop (s+1)`, and a
  window `{p_{s-2},…,p_{s+2}}` is `(p.drop (s-3)).take 5`.
-/

namespace Workspace.Statements.S03

open Workspace.Types.Core
open Workspace.Types.Core.SPGT

namespace SPGT

variable {V : Type*} [Fintype V] [DecidableEq V]

open Workspace.ProofLemmas

/-! ### The two routine consequences used in the printed proof -/

/-- If the ends of a path of length at least two are `X`-complete and no interior
vertex is `X`-complete, then no edge of the path is `X`-complete. -/
private theorem no_complete_edge_of_no_complete_interior {G : SimpleGraph V} {X : Set V}
    {P : List V} {u v : V} (hP : IsPathFrom G P u v) (hlen : 2 ≤ pathLength P)
    (hint : ∀ w ∈ SPGT.interior P, ¬ VertexComplete G w X) :
    ¬ ∃ a ∈ P, ∃ b ∈ P, EdgeComplete G X a b := by
  rintro ⟨a, ha, b, hb, hab, haX, hbX⟩
  obtain ⟨i, hi, rfl⟩ := List.mem_iff_getElem.mp ha
  obtain ⟨j, hj, rfl⟩ := List.mem_iff_getElem.mp hb
  have hlenP : 3 ≤ P.length := by
    rw [pathLength] at hlen
    omega
  rcases (PathBasics.path_adj_iff hP.1 hi hj).mp hab with hij | hji
  · by_cases hi0 : i = 0
    · apply hint (P[j]'hj)
        (PathBasics.getElem_mem_interior hP.1 hj (by omega) (by omega)) hbX
    · apply hint (P[i]'hi)
        (PathBasics.getElem_mem_interior hP.1 hi (by omega) (by omega)) haX
  · by_cases hj0 : j = 0
    · apply hint (P[i]'hi)
        (PathBasics.getElem_mem_interior hP.1 hi (by omega) (by omega)) haX
    · apply hint (P[j]'hj)
        (PathBasics.getElem_mem_interior hP.1 hj (by omega) (by omega)) hbX

/-- The exact form in which the proof repeatedly applies 2.2. -/
private theorem even_path_of_complete_ends {G : SimpleGraph V} (hG : Berge G) {X : Set V}
    (hX : AnticonnectedSet G X) {P : List V} {u v z : V}
    (hP : IsPathFrom G P u v) (hPX : ∀ w ∈ P, w ∉ X)
    (hlen : 2 ≤ pathLength P) (huX : VertexComplete G u X)
    (hvX : VertexComplete G v X)
    (hint : ∀ w ∈ SPGT.interior P, ¬ VertexComplete G w X)
    (hzX : VertexComplete G z X)
    (hzint : ∀ w ∈ SPGT.interior P, ¬ G.Adj z w) :
    Even (pathLength P) := by
  rcases Nat.even_or_odd (pathLength P) with heven | hodd
  · exact heven
  · obtain ⟨w, hw, hzw⟩ := Workspace.Statements.S02.SPGT.thm_2_2
      G hG X hX P u v hP hPX hodd huX hvX
        (no_complete_edge_of_no_complete_interior hP hlen hint) z hzX
    exact (hzint w hw hzw).elim

private theorem not_adj_of_compl_adj {G : SimpleGraph V} {u v : V} (h : Gᶜ.Adj u v) :
    ¬ G.Adj u v := by
  rw [SimpleGraph.compl_adj] at h
  exact h.2

/-- An odd antipath with a vertex attached in the complement at both ends closes
to an odd antihole. -/
private theorem odd_antihole_absurd {G : SimpleGraph V} (hG : Berge G)
    {R : List V} {u v w : V} (hR : IsAntipathFrom G R u v)
    (hlen : 2 ≤ pathLength R) (hwune : w ≠ u) (hwu : ¬ G.Adj w u)
    (hwvne : w ≠ v) (hwv : ¬ G.Adj w v) (hwR : w ∉ R)
    (hwint : ∀ y ∈ SPGT.interior R, G.Adj w y)
    (hodd : Odd (pathLength R)) : False := by
  have hhole : IsHoleList Gᶜ (w :: R) :=
    PrismBasics.isHoleList_of_path_add_vertex (G := Gᶜ) hR hlen
      (by rw [SimpleGraph.compl_adj]; exact ⟨hwune, hwu⟩)
      (by rw [SimpleGraph.compl_adj]; exact ⟨hwvne, hwv⟩) hwR
      (fun y hy hc => not_adj_of_compl_adj hc (hwint y hy))
  have heven := hG.2 _ hhole
  rw [PrismBasics.holeLength_cons _ (PathBasics.path_ne_nil hR.1)] at heven
  obtain ⟨k, hk⟩ := heven
  obtain ⟨j, hj⟩ := hodd
  omega

/-- An even antipath with one additional complement-edge at either end closes
to an odd antihole. -/
private theorem odd_antihole_absurd_two {G : SimpleGraph V} (hG : Berge G)
    {R : List V} {u v s t : V} (hR : IsAntipathFrom G R u v)
    (hlen : 1 ≤ pathLength R)
    (hsune : s ≠ u) (hsu : ¬ G.Adj s u)
    (htvne : t ≠ v) (htv : ¬ G.Adj t v)
    (hstne : s ≠ t) (hst : ¬ G.Adj s t)
    (hsR : s ∉ R) (htR : t ∉ R)
    (hsv : G.Adj s v) (htu : G.Adj t u)
    (hsint : ∀ y ∈ SPGT.interior R, G.Adj s y)
    (htint : ∀ y ∈ SPGT.interior R, G.Adj t y)
    (hpar : Even (pathLength R)) : False := by
  have hhole : IsHoleList Gᶜ (t :: s :: R) :=
    PrismBasics.isHoleList_of_path_add_two_vertices (G := Gᶜ) hR hlen
      (by rw [SimpleGraph.compl_adj]; exact ⟨hsune, hsu⟩)
      (by rw [SimpleGraph.compl_adj]; exact ⟨htvne, htv⟩)
      (by rw [SimpleGraph.compl_adj]; exact ⟨hstne, hst⟩) hsR htR
      (fun hc => not_adj_of_compl_adj hc hsv)
      (fun hc => not_adj_of_compl_adj hc htu)
      (fun y hy hc => not_adj_of_compl_adj hc (hsint y hy))
      (fun y hy hc => not_adj_of_compl_adj hc (htint y hy))
  have heven := hG.2 _ hhole
  rw [PrismBasics.holeLength_cons_cons _ _ (PathBasics.path_ne_nil hR.1)] at heven
  obtain ⟨k, hk⟩ := heven
  obtain ⟨j, hj⟩ := hpar
  omega


/-- **3.3** (printed p. 13)

PAPER: *"Let `G` be Berge, let `C` be a hole in `G` of length ≥ 6, with vertices
`p₁,…,p_m` in order, and let `Q` be an antipath with vertices `p₁,q₁,…,q_n,p₂`, with
length ≥ 4 and even.  Let `z ∈ V(G)`, complete to `V(Q)` and with no neighbours among
`p₃,…,p_m`.  There is at most one vertex in `{p₃,…,p_m}` complete to either
`{q₁,…,q_{n-1}}` or `{q₂,…,q_n}`, and any such vertex is one of `p₃, p_m`."*

The hole is the list `C` of its vertices in cyclic order; naming its first three vertices
`p₁, p₂, p₃` is just the decomposition `C = p₁ :: p₂ :: p₃ :: rest` (always available since
`C` has length ≥ 6), `p_m` is the last vertex of `C`, and `{p₃,…,p_m}` is `C.drop 2`.
The antipath `Q` has interior list `q = [q₁,…,q_n]`, so `{q₁,…,q_{n-1}} = q.dropLast` and
`{q₂,…,q_n} = q.tail`, and `V(Q) = {v | v ∈ Q}`.  The conclusion is the conjunction of
"at most one such vertex" and "any such vertex is `p₃` or `p_m`". -/
theorem thm_3_3 (G : SimpleGraph V) (hG : Berge G)
    (C : List V) (p₁ p₂ p₃ pm : V) (rest : List V)
    (hC : IsHoleList G C) (hC6 : 6 ≤ holeLength C)
    (hCdef : C = p₁ :: p₂ :: p₃ :: rest) (hpm : C.getLast? = some pm)
    (q Q : List V) (hQdef : Q = p₁ :: (q ++ [p₂]))
    (hQanti : IsAntipathFrom G Q p₁ p₂)
    (hQlen : 4 ≤ pathLength Q) (hQeven : Even (pathLength Q))
    (z : V) (hzQ : VertexComplete G z {v : V | v ∈ Q})
    (hzC : VertexAnticomplete G z {v : V | v ∈ C.drop 2}) :
    (∀ x ∈ C.drop 2, ∀ y ∈ C.drop 2,
        (VertexComplete G x {v : V | v ∈ q.dropLast} ∨
          VertexComplete G x {v : V | v ∈ q.tail}) →
        (VertexComplete G y {v : V | v ∈ q.dropLast} ∨
          VertexComplete G y {v : V | v ∈ q.tail}) → x = y) ∧
    (∀ x ∈ C.drop 2,
        (VertexComplete G x {v : V | v ∈ q.dropLast} ∨
          VertexComplete G x {v : V | v ∈ q.tail}) → x = p₃ ∨ x = pm) := by
  classical
  set m : ℕ := C.length
  set n : ℕ := q.length
  have hCm : C.length = m := rfl
  have hQn : Q.length = n + 2 := by simp [hQdef, n]
  have hm6 : 6 ≤ m := by simpa [holeLength, hCm] using hC6
  have hn3 : 3 ≤ n := by
    rw [pathLength, hQn] at hQlen
    omega
  have hnodd : Odd n := by
    have hpl : pathLength Q = n + 1 := by rw [pathLength, hQn]; omega
    rw [hpl] at hQeven
    obtain ⟨k, hk⟩ := hQeven
    exact ⟨k - 1, by omega⟩
  have hmeven : Even m := by
    have := hG.1 C hC
    simpa [holeLength, hCm] using this

  ---------------------------------------------------------------------------
  -- The rim, indexed from `p₁`.
  ---------------------------------------------------------------------------
  have hmpos : 0 < C.length := by omega
  obtain ⟨D, hD⟩ := OddWheelArc.rim_exists (C := C) hmpos 0
  have hDeq : ∀ (t : ℕ) (ht : t < C.length), C[t]'ht = D t := by
    intro t ht
    rw [← OddWheelArc.rim_eq_getElem hmpos hD t]
    exact HoleArithmetic.getElem_congr_idx C ht (Nat.mod_lt _ hmpos)
      (by rw [Nat.zero_add, Nat.mod_eq_of_lt ht])
  have radj : ∀ {a b : ℕ}, a < m → b < m →
      (G.Adj (D a) (D b) ↔
        (b = a + 1 ∨ a = b + 1 ∨ (a = 0 ∧ b = m - 1) ∨
          (b = 0 ∧ a = m - 1))) :=
    fun {a b} ha hb => OddWheelArc.rim_adj hC hmpos hD hCm ha hb
  have rne : ∀ {a b : ℕ}, a < m → b < m → a ≠ b → D a ≠ D b :=
    fun {a b} ha hb hab => OddWheelArc.rim_ne hC hmpos hD hCm ha hb hab
  have rmem : ∀ t : ℕ, D t ∈ C := OddWheelArc.rim_mem hmpos hD
  have rsurj : ∀ {w : V}, w ∈ C → ∃ t, t < m ∧ w = D t :=
    fun {w} hw => OddWheelArc.rim_surj hC hmpos hD hCm hw
  have hD0 : D 0 = p₁ := by
    exact (hDeq 0 (by omega)).symm.trans (by simp [hCdef])
  have hD1 : D 1 = p₂ := by
    exact (hDeq 1 (by omega)).symm.trans (by simp [hCdef])
  have hD2 : D 2 = p₃ := by
    exact (hDeq 2 (by omega)).symm.trans (by simp [hCdef])
  have hDm : D (m - 1) = pm := by
    rw [← hDeq (m - 1) (by omega)]
    exact PathBasics.getElem_last_of_getLast? hpm (by omega)
  have hDmod0 : D m = D 0 :=
    OddWheelArc.rim_congr hC hD
      (show m % C.length = 0 % C.length by rw [hCm]; simp)
  have hdrop : ∀ w : V, w ∈ C.drop 2 ↔ ∃ t, 2 ≤ t ∧ t < m ∧ w = D t := by
    intro w
    constructor
    · intro hw
      obtain ⟨j, hj, hje⟩ := List.getElem_of_mem hw
      rw [List.length_drop] at hj
      refine ⟨2 + j, by omega, by omega, ?_⟩
      rw [← hje, List.getElem_drop]
      exact (hDeq (2 + j) (by omega)).symm ▸ rfl
    · rintro ⟨t, ht2, htm, rfl⟩
      have hjm : t - 2 < (C.drop 2).length := by rw [List.length_drop]; omega
      have he : (C.drop 2)[t - 2]'hjm = D t := by
        rw [List.getElem_drop]
        rw [HoleArithmetic.getElem_congr_idx C (by omega) (show t < C.length by omega)
          (show 2 + (t - 2) = t by omega)]
        exact hDeq t (by omega)
      rw [← he]
      exact List.getElem_mem hjm

  ---------------------------------------------------------------------------
  -- The antipath `p₁-q₁-⋯-qₙ-p₂` and its two truncated interiors.
  ---------------------------------------------------------------------------
  have hQp : IsPathFrom Gᶜ Q (D 0) (D 1) := by
    rw [hD0, hD1]
    exact hQanti
  have hQpos : 0 < Q.length := PathBasics.path_length_pos hQp.1
  have hQ0 : Q[0]'(by omega) = D 0 :=
    PathBasics.getElem_zero_of_head? hQp.2.1 hQpos
  have hQlast : Q[n + 1]'(by omega) = D 1 := by
    have h := PathBasics.getElem_last_of_getLast? hQp.2.2 hQpos
    rw [HoleArithmetic.getElem_congr_idx Q (show n + 1 < Q.length by omega)
      (show Q.length - 1 < Q.length by omega) (by omega)]
    exact h
  have hQadj : ∀ (i j : ℕ) (hi : i < Q.length) (hj : j < Q.length),
      (Gᶜ.Adj (Q[i]'hi) (Q[j]'hj) ↔ (i + 1 = j ∨ j + 1 = i)) := hQp.1.2.2
  have hQne : ∀ (i j : ℕ) (hi : i < Q.length) (hj : j < Q.length), i ≠ j →
      (Q[i]'hi) ≠ (Q[j]'hj) :=
    fun i j hi hj hij => PathBasics.path_ne_of_ne_index hQp.1 hi hj hij
  have hQGadj : ∀ (i j : ℕ) (hi : i < Q.length) (hj : j < Q.length), i ≠ j →
      i + 1 ≠ j → j + 1 ≠ i → G.Adj (Q[i]'hi) (Q[j]'hj) := by
    intro i j hi hj hij h1 h2
    by_contra hc
    exact absurd ((hQadj i j hi hj).mp
      (by rw [SimpleGraph.compl_adj]; exact ⟨hQne i j hi hj hij, hc⟩)) (by omega)
  have hQnotGadj : ∀ (i j : ℕ) (hi : i < Q.length) (hj : j < Q.length),
      (i + 1 = j ∨ j + 1 = i) → ¬ G.Adj (Q[i]'hi) (Q[j]'hj) := by
    intro i j hi hj hc
    exact not_adj_of_compl_adj ((hQadj i j hi hj).mpr hc)
  have hinter : SPGT.interior Q = q := by simp [SPGT.interior, hQdef]
  have hqsget : ∀ (j : ℕ) (hj : j < n), q[j]'hj = Q[j + 1]'(by omega) := by
    intro j hj
    simpa only [hQdef, List.getElem_cons_succ] using
      (List.getElem_append_left' hj [p₂])
  have hZ1 : ∀ x : V, x ∈ q.dropLast ↔
      ∃ (i : ℕ) (hi : i < Q.length), 1 ≤ i ∧ i + 1 ≤ n ∧ Q[i]'hi = x := by
    intro x
    constructor
    · intro hx
      obtain ⟨j, hj, hje⟩ := List.getElem_of_mem hx
      rw [List.length_dropLast] at hj
      refine ⟨j + 1, by omega, by omega, by omega, ?_⟩
      rw [← hje, List.getElem_dropLast, hqsget j (by omega)]
    · rintro ⟨i, hi, h1, h2, rfl⟩
      have hj : i - 1 < q.dropLast.length := by rw [List.length_dropLast]; omega
      have he : q.dropLast[i - 1]'hj = Q[i]'hi := by
        rw [List.getElem_dropLast, hqsget (i - 1) (by omega)]
        exact HoleArithmetic.getElem_congr_idx Q (by omega) hi (by omega)
      rw [← he]
      exact List.getElem_mem hj
  have hZ2 : ∀ x : V, x ∈ q.tail ↔
      ∃ (i : ℕ) (hi : i < Q.length), 2 ≤ i ∧ i ≤ n ∧ Q[i]'hi = x := by
    intro x
    constructor
    · intro hx
      obtain ⟨j, hj, hje⟩ := List.getElem_of_mem hx
      rw [List.length_tail] at hj
      refine ⟨j + 2, by omega, by omega, by omega, ?_⟩
      rw [← hje, List.getElem_tail, hqsget (j + 1) (by omega)]
    · rintro ⟨i, hi, h1, h2, rfl⟩
      have hj : i - 2 < q.tail.length := by rw [List.length_tail]; omega
      have he : q.tail[i - 2]'hj = Q[i]'hi := by
        rw [List.getElem_tail, hqsget (i - 2 + 1) (by omega)]
        exact HoleArithmetic.getElem_congr_idx Q (by omega) hi (by omega)
      rw [← he]
      exact List.getElem_mem hj
  have hZ0 : ∀ x : V, x ∈ q ↔
      ∃ (i : ℕ) (hi : i < Q.length), 1 ≤ i ∧ i ≤ n ∧ Q[i]'hi = x := by
    intro x
    constructor
    · intro hx
      obtain ⟨j, hj, hje⟩ := List.getElem_of_mem hx
      exact ⟨j + 1, by omega, by omega, by omega, by rw [← hje, hqsget j (by omega)]⟩
    · rintro ⟨i, hi, h1, h2, rfl⟩
      have hj : i - 1 < q.length := by omega
      have he : q[i - 1]'hj = Q[i]'hi := by
        rw [hqsget (i - 1) (by omega)]
        exact HoleArithmetic.getElem_congr_idx Q (by omega) hi (by omega)
      rw [← he]
      exact List.getElem_mem hj

  -- Every `qᵢ` misses the hole: it sees `z`, whereas every rim vertex after
  -- `p₂` misses `z`; the first two rim vertices are excluded by nodupness of `Q`.
  have hQC : ∀ (k : ℕ) (hk : k < Q.length), 1 ≤ k → k ≤ n → Q[k]'hk ∉ C := by
    intro k hk hk1 hkn hkC
    obtain ⟨t, htm, hteq⟩ := rsurj hkC
    have ht0 : t ≠ 0 := by
      intro ht
      subst ht
      exact hQne k 0 hk (by omega) (by omega) (by rw [hteq, hQ0])
    have ht1 : t ≠ 1 := by
      intro ht
      subst ht
      exact hQne k (n + 1) hk (by omega) (by omega) (by rw [hteq, hQlast])
    have hkdrop : Q[k]'hk ∈ C.drop 2 :=
      (hdrop _).mpr ⟨t, by omega, htm, hteq⟩
    exact hzC _ hkdrop (hzQ _ (List.getElem_mem hk))
  have hZ1C : ∀ y ∈ {x : V | x ∈ q.dropLast}, y ∉ C := by
    intro y hy
    obtain ⟨k, hk, h1, h2, rfl⟩ := (hZ1 y).mp hy
    exact hQC k hk h1 (by omega)
  have hZ2C : ∀ y ∈ {x : V | x ∈ q.tail}, y ∉ C := by
    intro y hy
    obtain ⟨k, hk, h1, h2, rfl⟩ := (hZ2 y).mp hy
    exact hQC k hk (by omega) h2
  have hZ1anti : AnticonnectedSet G {x : V | x ∈ q.dropLast} := by
    have hset : {x : V | x ∈ q.dropLast} =
        {x : V | x ∈ (Q.drop 1).take (n - 1 - 1 + 1)} := by
      ext y
      simp only [Set.mem_setOf_eq]
      rw [hZ1 y, PathBasics.mem_slice_iff Q (show 1 ≤ n - 1 by omega)
        (show n - 1 < Q.length by omega)]
      constructor
      · rintro ⟨i, hi, h1, h2, rfl⟩
        exact ⟨i, hi, h1, by omega, rfl⟩
      · rintro ⟨i, hi, h1, h2, rfl⟩
        exact ⟨i, hi, h1, by omega, rfl⟩
    rw [hset]
    exact InducedPathExtraction.anticonnectedSet_setOf_mem_of_isAntipathList
      (PathBasics.isPathList_slice hQp.1 (show 1 < n - 1 by omega)
        (show n - 1 < Q.length by omega))
  have hZ2anti : AnticonnectedSet G {x : V | x ∈ q.tail} := by
    have hset : {x : V | x ∈ q.tail} =
        {x : V | x ∈ (Q.drop 2).take (n - 2 + 1)} := by
      ext y
      simp only [Set.mem_setOf_eq]
      rw [hZ2 y, PathBasics.mem_slice_iff Q (show 2 ≤ n by omega)
        (show n < Q.length by omega)]
    rw [hset]
    exact InducedPathExtraction.anticonnectedSet_setOf_mem_of_isAntipathList
      (PathBasics.isPathList_slice hQp.1 (show 2 < n by omega)
        (show n < Q.length by omega))
  have hVC1 : ∀ w : V, VertexComplete G w {x : V | x ∈ q.dropLast} ↔
      ∀ (i : ℕ) (hi : i < Q.length), 1 ≤ i → i + 1 ≤ n → G.Adj w (Q[i]'hi) := by
    intro w
    constructor
    · intro h i hi h1 h2
      exact h _ ((hZ1 _).mpr ⟨i, hi, h1, h2, rfl⟩)
    · intro h y hy
      obtain ⟨i, hi, h1, h2, rfl⟩ := (hZ1 y).mp hy
      exact h i hi h1 h2
  have hVC2 : ∀ w : V, VertexComplete G w {x : V | x ∈ q.tail} ↔
      ∀ (i : ℕ) (hi : i < Q.length), 2 ≤ i → i ≤ n → G.Adj w (Q[i]'hi) := by
    intro w
    constructor
    · intro h i hi h1 h2
      exact h _ ((hZ2 _).mpr ⟨i, hi, h1, h2, rfl⟩)
    · intro h y hy
      obtain ⟨i, hi, h1, h2, rfl⟩ := (hZ2 y).mp hy
      exact h i hi h1 h2
  have hp1adj : ∀ (k : ℕ) (hk : k < Q.length), 2 ≤ k → G.Adj (D 0) (Q[k]'hk) := by
    intro k hk h2
    rw [← hQ0]
    exact hQGadj 0 k (by omega) hk (by omega) (by omega) (by omega)
  have hp2adj : ∀ (k : ℕ) (hk : k < Q.length), k + 1 ≤ n →
      G.Adj (D 1) (Q[k]'hk) := by
    intro k hk h2
    rw [← hQlast]
    exact hQGadj (n + 1) k (by omega) hk (by omega) (by omega) (by omega)
  have hp2VC1 : VertexComplete G (D 1) {x : V | x ∈ q.dropLast} :=
    (hVC1 (D 1)).mpr (fun k hk _ h2 => hp2adj k hk h2)
  have hp1VC2 : VertexComplete G (D 0) {x : V | x ∈ q.tail} :=
    (hVC2 (D 0)).mpr (fun k hk h1 _ => hp1adj k hk h1)
  have hzVC1 : VertexComplete G z {x : V | x ∈ q.dropLast} := by
    intro y hy
    obtain ⟨i, hi, -, -, rfl⟩ := (hZ1 y).mp hy
    exact hzQ _ (List.getElem_mem hi)
  have hzVC2 : VertexComplete G z {x : V | x ∈ q.tail} := by
    intro y hy
    obtain ⟨i, hi, -, -, rfl⟩ := (hZ2 y).mp hy
    exact hzQ _ (List.getElem_mem hi)
  have hZ0C : ∀ y ∈ {x : V | x ∈ q}, y ∉ C := by
    intro y hy
    obtain ⟨i, hi, h1, h2, rfl⟩ := (hZ0 y).mp hy
    exact hQC i hi h1 h2
  have hZ0anti : AnticonnectedSet G {x : V | x ∈ q} := by
    have hset : {x : V | x ∈ q} = {x : V | x ∈ (Q.drop 1).take (n - 1 + 1)} := by
      ext y
      simp only [Set.mem_setOf_eq]
      rw [hZ0 y, PathBasics.mem_slice_iff Q (show 1 ≤ n by omega)
        (show n < Q.length by omega)]
    rw [hset]
    exact InducedPathExtraction.anticonnectedSet_setOf_mem_of_isAntipathList
      (PathBasics.isPathList_slice hQp.1 (show 1 < n by omega) (show n < Q.length by omega))
  have hbothVC0 : ∀ w : V,
      VertexComplete G w {x : V | x ∈ q.dropLast} →
      VertexComplete G w {x : V | x ∈ q.tail} →
      VertexComplete G w {x : V | x ∈ q} := by
    intro w hw1 hw2 y hy
    obtain ⟨i, hi, h1, h2, rfl⟩ := (hZ0 y).mp hy
    rcases Nat.lt_or_ge (i + 1) (n + 1) with h | h
    · exact (hVC1 _).mp hw1 i hi h1 (by omega)
    · exact (hVC2 _).mp hw2 i hi (by omega) h2
  have hzVC0 : VertexComplete G z {x : V | x ∈ q} := by
    intro y hy
    obtain ⟨i, hi, -, -, rfl⟩ := (hZ0 y).mp hy
    exact hzQ _ (List.getElem_mem hi)
  have hp2nVC0 : ¬ VertexComplete G (D 1) {x : V | x ∈ q} := by
    intro hc
    exact hQnotGadj (n + 1) n (by omega) (by omega) (Or.inr rfl)
      (by rw [hQlast]; exact hc _ ((hZ0 _).mpr ⟨n, by omega, by omega, by omega, rfl⟩))
  have hp1nVC0 : ¬ VertexComplete G (D 0) {x : V | x ∈ q} := by
    intro hc
    exact hQnotGadj 0 1 (by omega) (by omega) (Or.inl rfl)
      (by rw [hQ0]; exact hc _ ((hZ0 _).mpr ⟨1, by omega, by omega, by omega, rfl⟩))
  have hznotC : z ∉ C := by
    intro hzmem
    obtain ⟨t, htm, rfl⟩ := rsurj hzmem
    have hz0 : G.Adj (D t) (D 0) := hzQ _ (by rw [← hQ0]; exact List.getElem_mem (by omega))
    have hz1 : G.Adj (D t) (D 1) := hzQ _ (by rw [← hQlast]; exact List.getElem_mem (by omega))
    have h0 := (radj htm (show 0 < m by omega)).mp hz0
    have h1 := (radj htm (show 1 < m by omega)).mp hz1
    omega

  -- 2.2 along any non-wrapping rim arc.  The hypotheses explicitly expose
  -- the two paper conditions that vary from one application to the next.
  have hRRarc : ∀ (Z : Set V), (∀ y ∈ Z, y ∉ C) → AnticonnectedSet G Z →
      VertexComplete G z Z → ∀ a b : ℕ, a < b → b - a + 2 ≤ m → 2 ≤ b - a →
      VertexComplete G (D a) Z → VertexComplete G (D b) Z →
      (∀ w ∈ SPGT.interior (OddWheelArc.arc C 0 a b), ¬ VertexComplete G w Z) →
      (∀ w ∈ SPGT.interior (OddWheelArc.arc C 0 a b), ¬ G.Adj z w) →
      Even (b - a) := by
    intro Z hZC hZanti hzZ a b hab hlen hlen2 haZ hbZ hint hzint
    have hP : IsPathFrom G (OddWheelArc.arc C 0 a b) (D a) (D b) :=
      OddWheelArc.arc_isPathFrom hC hmpos hD hCm hab hlen
    have hplen : pathLength (OddWheelArc.arc C 0 a b) = b - a := by
      rw [pathLength, OddWheelArc.arc_length C 0 a b (by omega)]
      omega
    have hPout : ∀ w ∈ OddWheelArc.arc C 0 a b, w ∉ Z := by
      intro w hw hwZ
      exact hZC w hwZ (HoleBasics.mem_rotate_iff.mp (List.mem_of_mem_take hw))
    rw [← hplen]
    exact even_path_of_complete_ends hG hZanti hP hPout (by omega) haZ hbZ hint hzZ hzint
  have hRRarcIndex : ∀ (Z : Set V), (∀ y ∈ Z, y ∉ C) → AnticonnectedSet G Z →
      VertexComplete G z Z → ∀ a b : ℕ, a < b → b - a + 2 ≤ m → 2 ≤ b - a →
      VertexComplete G (D a) Z → VertexComplete G (D b) Z →
      (∀ s, a < s → s < b → ¬ VertexComplete G (D s) Z) →
      (∀ s, a < s → s < b → ¬ G.Adj z (D s)) → Even (b - a) := by
    intro Z hZC hZanti hzZ a b hab hlen hlen2 haZ hbZ hint hzint
    apply hRRarc Z hZC hZanti hzZ a b hab hlen hlen2 haZ hbZ
    · intro w hw
      have hP : IsPathFrom G (OddWheelArc.arc C 0 a b) (D a) (D b) :=
        OddWheelArc.arc_isPathFrom hC hmpos hD hCm hab hlen
      have hwi := (PathBasics.mem_interior_iff_of_pathFrom hP).mp hw
      obtain ⟨s, hsa, hsb, rfl⟩ :=
        (OddWheelArc.arc_mem_iff hC hmpos hD hCm (le_of_lt hab) (by omega)).mp hwi.1
      exact hint s (by by_contra hc; exact hwi.2.1 (by rw [show s = a by omega]))
        (by by_contra hc; exact hwi.2.2 (by rw [show s = b by omega]))
    · intro w hw
      have hP : IsPathFrom G (OddWheelArc.arc C 0 a b) (D a) (D b) :=
        OddWheelArc.arc_isPathFrom hC hmpos hD hCm hab hlen
      have hwi := (PathBasics.mem_interior_iff_of_pathFrom hP).mp hw
      obtain ⟨s, hsa, hsb, rfl⟩ :=
        (OddWheelArc.arc_mem_iff hC hmpos hD hCm (le_of_lt hab) (by omega)).mp hwi.1
      exact hzint s (by by_contra hc; exact hwi.2.1 (by rw [show s = a by omega]))
        (by by_contra hc; exact hwi.2.2 (by rw [show s = b by omega]))

  ---------------------------------------------------------------------------
  -- Claim (1): `Y₁ ⊆ Y₂ ∪ {p_m}` and `Y₂ ⊆ Y₁ ∪ {p₃}`.
  ---------------------------------------------------------------------------
  have hcl1 : ∀ t, 2 ≤ t → t < m →
      VertexComplete G (D t) {x : V | x ∈ q.dropLast} →
      (VertexComplete G (D t) {x : V | x ∈ q.tail} ∨ t = m - 1) := by
    intro t ht2 htm ht1
    by_contra hcon
    push Not at hcon
    obtain ⟨hnot2, htne⟩ := hcon
    have hqn : ¬ G.Adj (D t) (Q[n]'(by omega)) := by
      intro hadj
      refine hnot2 ((hVC2 _).mpr ?_)
      intro k hk hk2 hkn
      rcases Nat.lt_or_ge (k + 1) (n + 1) with h | h
      · exact (hVC1 _).mp ht1 k hk (by omega) (by omega)
      · rw [HoleArithmetic.getElem_congr_idx Q hk (show n < Q.length by omega) (by omega)]
        exact hadj
    have hslice : IsAntipathFrom G ((Q.drop 0).take (n - 0 + 1))
        (Q[0]'(by omega)) (Q[n]'(by omega)) :=
      PathBasics.isPathFrom_slice hQp.1 (show 0 < n by omega) (show n < Q.length by omega)
    have hsl : pathLength ((Q.drop 0).take (n - 0 + 1)) = n := by
      rw [pathLength, PathBasics.length_slice Q (show (0 : ℕ) ≤ n by omega)
        (show n < Q.length by omega)]
      omega
    refine odd_antihole_absurd hG hslice (by omega) ?_ ?_ ?_ hqn ?_ ?_ ?_
    · rw [hQ0]
      exact rne (by omega) (by omega) (by omega)
    · rw [hQ0]
      intro hadj
      have := (radj htm (show 0 < m by omega)).mp hadj
      omega
    · exact fun he => hQC n (by omega) (by omega) (by omega) (he ▸ rmem t)
    · intro hmem
      obtain ⟨k, hk, hk0, hkn, hke⟩ :=
        (PathBasics.mem_slice_iff Q (show (0 : ℕ) ≤ n by omega)
          (show n < Q.length by omega)).mp hmem
      rcases Nat.lt_or_ge k 1 with h | h
      · have he : Q[0]'(by omega) = D t := by
          rw [← hke]
          exact HoleArithmetic.getElem_congr_idx Q (by omega) hk (by omega)
        rw [hQ0] at he
        exact rne (by omega) htm (by omega) he
      · exact hQC k hk h hkn (hke ▸ rmem t)
    · intro y hy
      obtain ⟨k, hk, hk0, hkn, rfl⟩ :=
        (PathBasics.mem_interior_slice_iff hQp.1 (show 0 < n by omega)
          (show n < Q.length by omega)).mp hy
      exact (hVC1 _).mp ht1 k hk (by omega) (by omega)
    · rw [hsl]
      exact hnodd
  have hcl2 : ∀ t, 2 ≤ t → t < m →
      VertexComplete G (D t) {x : V | x ∈ q.tail} →
      (VertexComplete G (D t) {x : V | x ∈ q.dropLast} ∨ t = 2) := by
    intro t ht2 htm ht2c
    by_contra hcon
    push Not at hcon
    obtain ⟨hnot1, htne⟩ := hcon
    have hq1 : ¬ G.Adj (D t) (Q[1]'(by omega)) := by
      intro hadj
      refine hnot1 ((hVC1 _).mpr ?_)
      intro k hk hk1 hkn
      rcases Nat.lt_or_ge k 2 with h | h
      · rw [HoleArithmetic.getElem_congr_idx Q hk (show 1 < Q.length by omega) (by omega)]
        exact hadj
      · exact (hVC2 _).mp ht2c k hk (by omega) (by omega)
    have hslice : IsAntipathFrom G ((Q.drop 1).take (n + 1 - 1 + 1))
        (Q[1]'(by omega)) (Q[n + 1]'(by omega)) :=
      PathBasics.isPathFrom_slice hQp.1 (show 1 < n + 1 by omega)
        (show n + 1 < Q.length by omega)
    have hsl : pathLength ((Q.drop 1).take (n + 1 - 1 + 1)) = n := by
      rw [pathLength, PathBasics.length_slice Q (show (1 : ℕ) ≤ n + 1 by omega)
        (show n + 1 < Q.length by omega)]
      omega
    refine odd_antihole_absurd hG hslice (by omega) ?_ hq1 ?_ ?_ ?_ ?_ ?_
    · exact fun he => hQC 1 (by omega) (by omega) (by omega) (he ▸ rmem t)
    · rw [hQlast]
      exact rne (a := t) (b := 1) htm (by omega) (by omega)
    · rw [hQlast]
      intro hadj
      have := (radj htm (show 1 < m by omega)).mp hadj
      omega
    · intro hmem
      obtain ⟨k, hk, hk0, hkn, hke⟩ :=
        (PathBasics.mem_slice_iff Q (show (1 : ℕ) ≤ n + 1 by omega)
          (show n + 1 < Q.length by omega)).mp hmem
      rcases Nat.lt_or_ge k (n + 1) with h | h
      · exact hQC k hk hk0 (by omega) (hke ▸ rmem t)
      · have he : Q[n + 1]'(by omega) = D t := by
          rw [← hke]
          exact HoleArithmetic.getElem_congr_idx Q (by omega) hk (by omega)
        rw [hQlast] at he
        exact rne (by omega) htm (by omega) he
    · intro y hy
      obtain ⟨k, hk, hk0, hkn, rfl⟩ :=
        (PathBasics.mem_interior_slice_iff hQp.1 (show 1 < n + 1 by omega)
          (show n + 1 < Q.length by omega)).mp hy
      exact (hVC2 _).mp ht2c k hk (by omega) (by omega)
    · rw [hsl]
      exact hnodd

  ---------------------------------------------------------------------------
  -- The two antiholes used after Claims (1) and (2).
  ---------------------------------------------------------------------------
  have hnotQ : ∀ (w : ℕ), 2 ≤ w → w < m → D w ∉ Q := by
    intro w hw2 hwm hmem
    obtain ⟨k, hk, hke⟩ := List.getElem_of_mem hmem
    rcases Nat.lt_or_ge k 1 with h | h
    · have he : Q[0]'(by omega) = D w := by
        rw [← hke]
        exact HoleArithmetic.getElem_congr_idx Q (by omega) hk (by omega)
      rw [hQ0] at he
      exact rne (by omega) hwm (by omega) he
    rcases Nat.lt_or_ge k (n + 1) with h' | h'
    · exact hQC k hk h (by omega) (hke ▸ rmem w)
    · have he : Q[n + 1]'(by omega) = D w := by
        rw [← hke]
        exact HoleArithmetic.getElem_congr_idx Q (by omega) hk (by omega)
      rw [hQlast] at he
      exact rne (by omega) hwm (by omega) he
  have hnotboth : ¬ ((VertexComplete G (D 2) {x : V | x ∈ q.dropLast} ∧
        VertexComplete G (D 2) {x : V | x ∈ q.tail}) ∧
      (VertexComplete G (D (m - 1)) {x : V | x ∈ q.dropLast} ∧
        VertexComplete G (D (m - 1)) {x : V | x ∈ q.tail})) := by
    rintro ⟨⟨h21, h22⟩, hm1, hm2⟩
    have hall2 : ∀ (k : ℕ) (hk : k < Q.length), 1 ≤ k → k ≤ n →
        G.Adj (D 2) (Q[k]'hk) := by
      intro k hk h1 h2
      rcases Nat.lt_or_ge (k + 1) (n + 1) with h | h
      · exact (hVC1 _).mp h21 k hk h1 (by omega)
      · exact (hVC2 _).mp h22 k hk (by omega) h2
    have hallm : ∀ (k : ℕ) (hk : k < Q.length), 1 ≤ k → k ≤ n →
        G.Adj (D (m - 1)) (Q[k]'hk) := by
      intro k hk h1 h2
      rcases Nat.lt_or_ge (k + 1) (n + 1) with h | h
      · exact (hVC1 _).mp hm1 k hk h1 (by omega)
      · exact (hVC2 _).mp hm2 k hk (by omega) h2
    refine odd_antihole_absurd_two hG hQp (by omega) ?_ ?_ ?_ ?_ ?_ ?_
      (hnotQ 2 (by omega) (by omega)) (hnotQ (m - 1) (by omega) (by omega))
      ?_ ?_ ?_ ?_ hQeven
    · exact rne (by omega) (by omega) (by omega)
    · intro hadj
      have := (radj (show 2 < m by omega) (show 0 < m by omega)).mp hadj
      omega
    · exact rne (by omega) (by omega) (by omega)
    · intro hadj
      have := (radj (show m - 1 < m by omega) (show 1 < m by omega)).mp hadj
      omega
    · exact rne (by omega) (by omega) (by omega)
    · intro hadj
      have := (radj (show 2 < m by omega) (show m - 1 < m by omega)).mp hadj
      omega
    · exact (radj (show 2 < m by omega) (show 1 < m by omega)).mpr
        (Or.inr (Or.inl rfl))
    · exact (radj (show m - 1 < m by omega) (show 0 < m by omega)).mpr
        (Or.inr (Or.inr (Or.inr ⟨rfl, rfl⟩)))
    · intro y hy
      rw [hinter] at hy
      obtain ⟨k, hk, hk1, hkn, rfl⟩ := (hZ0 y).mp hy
      exact hall2 k hk hk1 hkn
    · intro y hy
      rw [hinter] at hy
      obtain ⟨k, hk, hk1, hkn, rfl⟩ := (hZ0 y).mp hy
      exact hallm k hk hk1 hkn

  have hantiK : VertexComplete G (D 2) {x : V | x ∈ q.tail} →
      ¬ VertexComplete G (D 2) {x : V | x ∈ q.dropLast} →
      VertexComplete G (D (m - 1)) {x : V | x ∈ q.dropLast} →
      ¬ VertexComplete G (D (m - 1)) {x : V | x ∈ q.tail} → False := by
    intro h2VC2 h2nVC1 hmVC1 hmnVC2
    have hnq1 : ¬ G.Adj (D 2) (Q[1]'(by omega)) := by
      intro hadj
      refine h2nVC1 ((hVC1 _).mpr ?_)
      intro k hk hk1 hkn
      rcases Nat.lt_or_ge k 2 with h | h
      · rw [HoleArithmetic.getElem_congr_idx Q hk (show 1 < Q.length by omega) (by omega)]
        exact hadj
      · exact (hVC2 _).mp h2VC2 k hk (by omega) (by omega)
    have hnqn : ¬ G.Adj (D (m - 1)) (Q[n]'(by omega)) := by
      intro hadj
      refine hmnVC2 ((hVC2 _).mpr ?_)
      intro k hk hk2 hkn
      rcases Nat.lt_or_ge (k + 1) (n + 1) with h | h
      · exact (hVC1 _).mp hmVC1 k hk (by omega) (by omega)
      · rw [HoleArithmetic.getElem_congr_idx Q hk (show n < Q.length by omega) (by omega)]
        exact hadj
    have hslice : IsAntipathFrom G ((Q.drop 1).take (n - 1 + 1))
        (Q[1]'(by omega)) (Q[n]'(by omega)) :=
      PathBasics.isPathFrom_slice hQp.1 (show 1 < n by omega) (show n < Q.length by omega)
    have hsl : pathLength ((Q.drop 1).take (n - 1 + 1)) = n - 1 := by
      rw [pathLength, PathBasics.length_slice Q (show (1 : ℕ) ≤ n by omega)
        (show n < Q.length by omega)]
      omega
    have hmem : ∀ y : V, y ∈ (Q.drop 1).take (n - 1 + 1) →
        ∃ (k : ℕ) (hk : k < Q.length), 1 ≤ k ∧ k ≤ n ∧ Q[k]'hk = y :=
      fun y hy => (PathBasics.mem_slice_iff Q (show (1 : ℕ) ≤ n by omega)
        (show n < Q.length by omega)).mp hy
    refine odd_antihole_absurd_two hG hslice (by omega) ?_ hnq1 ?_ hnqn ?_ ?_ ?_ ?_
      ?_ ?_ ?_ ?_ ?_
    · exact fun he => hQC 1 (by omega) (by omega) (by omega) (he ▸ rmem 2)
    · exact fun he => hQC n (by omega) (by omega) (by omega) (he ▸ rmem (m - 1))
    · exact rne (by omega) (by omega) (by omega)
    · intro hadj
      have := (radj (show 2 < m by omega) (show m - 1 < m by omega)).mp hadj
      omega
    · intro hmQ
      obtain ⟨k, hk, hk1, hkn, hke⟩ := hmem _ hmQ
      exact hQC k hk hk1 hkn (hke ▸ rmem 2)
    · intro hmQ
      obtain ⟨k, hk, hk1, hkn, hke⟩ := hmem _ hmQ
      exact hQC k hk hk1 hkn (hke ▸ rmem (m - 1))
    · exact (hVC2 _).mp h2VC2 n (by omega) (by omega) (by omega)
    · exact (hVC1 _).mp hmVC1 1 (by omega) (by omega) (by omega)
    · intro y hy
      obtain ⟨k, hk, hk1, hkn, rfl⟩ :=
        (PathBasics.mem_interior_slice_iff hQp.1 (show 1 < n by omega)
          (show n < Q.length by omega)).mp hy
      exact (hVC2 _).mp h2VC2 k hk (by omega) (by omega)
    · intro y hy
      obtain ⟨k, hk, hk1, hkn, rfl⟩ :=
        (PathBasics.mem_interior_slice_iff hQp.1 (show 1 < n by omega)
          (show n < Q.length by omega)).mp hy
      exact (hVC1 _).mp hmVC1 k hk (by omega) (by omega)
    · rw [hsl]
      obtain ⟨k, hk⟩ := hnodd
      exact ⟨k, by omega⟩

  ---------------------------------------------------------------------------
  -- Claim (2), first half: a `Y₁` vertex before `p_m` forces `p₃ ∈ Y₁ ∩ Y₂`.
  ---------------------------------------------------------------------------
  have hcl3 : (∃ t, 2 ≤ t ∧ t + 2 ≤ m ∧
        VertexComplete G (D t) {x : V | x ∈ q.dropLast}) →
      (VertexComplete G (D 2) {x : V | x ∈ q.dropLast} ∧
        VertexComplete G (D 2) {x : V | x ∈ q.tail}) := by
    intro hex
    obtain ⟨tt, ⟨htt2, httm, httVC1⟩, httmin⟩ :
        ∃ tt, (2 ≤ tt ∧ tt + 2 ≤ m ∧
            VertexComplete G (D tt) {x : V | x ∈ q.dropLast}) ∧
          ∀ s, s < tt → ¬ (2 ≤ s ∧ s + 2 ≤ m ∧
            VertexComplete G (D s) {x : V | x ∈ q.dropLast}) :=
      ⟨Nat.find hex, Nat.find_spec hex, fun s hs => Nat.find_min hex hs⟩
    have httVC2 : VertexComplete G (D tt) {x : V | x ∈ q.tail} := by
      rcases hcl1 tt htt2 (by omega) httVC1 with h | h
      · exact h
      · omega
    by_cases htteq : tt = 2
    · rw [htteq] at httVC1 httVC2
      exact ⟨httVC1, httVC2⟩
    exfalso
    have htt3 : 3 ≤ tt := by omega
    -- The path `p₂-⋯-pᵢ` must be even, so the zero-based index `tt` is odd.
    have httodd : Odd tt := by
      have heven := hRRarcIndex {x : V | x ∈ q.dropLast} hZ1C hZ1anti hzVC1
        1 tt (by omega) (by omega) (by omega) hp2VC1 httVC1
        (fun s hs1 hst hs => httmin s hst ⟨by omega, by omega, hs⟩)
        (fun s hs1 hst => hzC _ ((hdrop _).mpr ⟨s, by omega, by omega, rfl⟩))
      obtain ⟨k, hk⟩ := heven
      exact ⟨k, by omega⟩
    -- On the other side, `pᵢ-⋯-p_m-p₁` is odd.  Thus 2.2 forces an
    -- interior `Y₂` vertex.
    obtain ⟨s0, hs0t, hs0m, hs0VC2⟩ : ∃ s, tt < s ∧ s < m ∧
        VertexComplete G (D s) {x : V | x ∈ q.tail} := by
      by_contra hcon
      push Not at hcon
      have heven := hRRarcIndex {x : V | x ∈ q.tail} hZ2C hZ2anti hzVC2
        tt m (by omega) (by omega) (by omega) httVC2
        (by rw [hDmod0]; exact hp1VC2)
        (fun s hs1 hs2 => hcon s hs1 hs2)
        (fun s hs1 hs2 => hzC _ ((hdrop _).mpr ⟨s, by omega, hs2, rfl⟩))
      obtain ⟨a, ha⟩ := heven
      obtain ⟨b, hb⟩ := hmeven
      obtain ⟨c, hc⟩ := httodd
      omega
    have hs0VC1 : VertexComplete G (D s0) {x : V | x ∈ q.dropLast} := by
      rcases hcl2 s0 (by omega) hs0m hs0VC2 with h | h
      · exact h
      · omega

    -- Finally apply 2.2 to `z-p₂-⋯-pᵢ`, with the full set of `q`'s.
    let A : List V := OddWheelArc.arc C 0 1 tt
    have hA : IsPathFrom G A (D 1) (D tt) := by
      dsimp [A]
      exact OddWheelArc.arc_isPathFrom hC hmpos hD hCm (by omega) (by omega)
    have hAlen : A.length = tt := by
      dsimp [A]
      rw [OddWheelArc.arc_length C 0 1 tt (by omega)]
      omega
    have hzD1 : G.Adj z (D 1) :=
      hzQ _ (by rw [← hQlast]; exact List.getElem_mem (by omega))
    have hzA : z ∉ A := by
      intro hzmem
      exact hznotC (HoleBasics.mem_rotate_iff.mp (List.mem_of_mem_take hzmem))
    have hzother : ∀ x ∈ A, x ≠ D 1 → ¬ G.Adj z x := by
      intro x hx hx1
      obtain ⟨s, hs1, hst, rfl⟩ :=
        (OddWheelArc.arc_mem_iff hC hmpos hD hCm (show 1 ≤ tt by omega)
          (by omega)).mp hx
      have hsne : s ≠ 1 := fun hs => hx1 (by rw [hs])
      exact hzC _ ((hdrop _).mpr ⟨s, by omega, by omega, rfl⟩)
    have hP : IsPathFrom G (z :: A) z (D tt) :=
      PathAttach.isPathFrom_cons hA hzD1 hzA hzother
    have hPlen : pathLength (z :: A) = tt := by
      rw [pathLength]
      simp only [List.length_cons, hAlen]
      omega
    have hPout : ∀ w ∈ z :: A, w ∉ {x : V | x ∈ q} := by
      intro w hw hwq
      rcases List.mem_cons.mp hw with hwz | hwA
      · subst w
        exact G.irrefl (hzVC0 _ hwq)
      · exact hZ0C w hwq (HoleBasics.mem_rotate_iff.mp (List.mem_of_mem_take hwA))
    have hPint : ∀ w ∈ SPGT.interior (z :: A),
        ¬ VertexComplete G w {x : V | x ∈ q} := by
      intro w hw hw0
      have hwi := (PathBasics.mem_interior_iff_of_pathFrom hP).mp hw
      have hwA : w ∈ A := by
        rcases List.mem_cons.mp hwi.1 with hwz | hwA
        · exact absurd hwz hwi.2.1
        · exact hwA
      obtain ⟨s, hs1, hst, rfl⟩ :=
        (OddWheelArc.arc_mem_iff hC hmpos hD hCm (show 1 ≤ tt by omega)
          (by omega)).mp hwA
      have hslt : s < tt := by
        by_contra hc
        have hseq : s = tt := by omega
        exact hwi.2.2 (by rw [hseq])
      by_cases hse : s = 1
      · rw [hse] at hw0
        exact hp2nVC0 hw0
      · have hsVC1 : VertexComplete G (D s) {x : V | x ∈ q.dropLast} := by
          intro y hy
          exact hw0 y (List.mem_of_mem_dropLast hy)
        exact httmin s hslt ⟨by omega, by omega, hsVC1⟩
    have hs0VC0 : VertexComplete G (D s0) {x : V | x ∈ q} :=
      hbothVC0 _ hs0VC1 hs0VC2
    have hs0anti : ∀ w ∈ SPGT.interior (z :: A), ¬ G.Adj (D s0) w := by
      intro w hw hadj
      have hwi := (PathBasics.mem_interior_iff_of_pathFrom hP).mp hw
      have hwA : w ∈ A := by
        rcases List.mem_cons.mp hwi.1 with hwz | hwA
        · exact absurd hwz hwi.2.1
        · exact hwA
      obtain ⟨s, hs1, hst, rfl⟩ :=
        (OddWheelArc.arc_mem_iff hC hmpos hD hCm (show 1 ≤ tt by omega)
          (by omega)).mp hwA
      have hslt : s < tt := by
        by_contra hc
        have hseq : s = tt := by omega
        exact hwi.2.2 (by rw [hseq])
      have := (radj hs0m (show s < m by omega)).mp hadj
      omega
    have heven := even_path_of_complete_ends (z := D s0) hG hZ0anti hP hPout
      (by rw [hPlen]; omega) hzVC0 (hbothVC0 _ httVC1 httVC2) hPint hs0VC0 hs0anti
    rw [hPlen] at heven
    exact (Nat.not_even_iff_odd.mpr httodd heven).elim

  ---------------------------------------------------------------------------
  -- Claim (2), mirrored: a `Y₂` vertex after `p₃` forces
  -- `p_m ∈ Y₁ ∩ Y₂`.
  ---------------------------------------------------------------------------
  have hcl4 : (∃ t, 3 ≤ t ∧ t < m ∧
        VertexComplete G (D t) {x : V | x ∈ q.tail}) →
      (VertexComplete G (D (m - 1)) {x : V | x ∈ q.dropLast} ∧
        VertexComplete G (D (m - 1)) {x : V | x ∈ q.tail}) := by
    intro hex
    obtain ⟨t0, ht03, ht0m, ht0VC2⟩ := hex
    let S : Finset ℕ := (Finset.range m).filter (fun j =>
      3 ≤ j ∧ j < m ∧ VertexComplete G (D j) {x : V | x ∈ q.tail})
    have hmemS : ∀ j : ℕ, j ∈ S ↔
        (j < m ∧ 3 ≤ j ∧ j < m ∧
          VertexComplete G (D j) {x : V | x ∈ q.tail}) := by
      intro j
      simp [S]
    have ht0S : t0 ∈ S := (hmemS t0).mpr ⟨ht0m, ht03, ht0m, ht0VC2⟩
    have hSne : S.Nonempty := ⟨t0, ht0S⟩
    let tt : ℕ := S.max' hSne
    have httS : tt ∈ S := by exact Finset.max'_mem S hSne
    have htt3 : 3 ≤ tt := ((hmemS tt).mp httS).2.1
    have httm : tt < m := ((hmemS tt).mp httS).2.2.1
    have httVC2 : VertexComplete G (D tt) {x : V | x ∈ q.tail} :=
      ((hmemS tt).mp httS).2.2.2
    have httmax : ∀ s, tt < s → s < m →
        ¬ VertexComplete G (D s) {x : V | x ∈ q.tail} := by
      intro s hts hsm hsVC
      have hsS : s ∈ S := (hmemS s).mpr ⟨hsm, by omega, hsm, hsVC⟩
      exact (not_lt_of_ge (Finset.le_max' S s hsS)) hts
    have httVC1 : VertexComplete G (D tt) {x : V | x ∈ q.dropLast} := by
      rcases hcl2 tt (by omega) httm httVC2 with h | h
      · exact h
      · omega
    by_cases htteq : tt = m - 1
    · rw [htteq] at httVC1 httVC2
      exact ⟨httVC1, httVC2⟩
    exfalso
    have httlt : tt < m - 1 := by omega
    -- The final rim arc is even; since the hole is even, `tt` is even.
    have htteven : Even tt := by
      have htailEven := hRRarcIndex {x : V | x ∈ q.tail} hZ2C hZ2anti hzVC2
        tt m (by omega) (by omega) (by omega) httVC2
        (by rw [hDmod0]; exact hp1VC2)
        (fun s hs1 hs2 => httmax s hs1 hs2)
        (fun s hs1 hs2 => hzC _ ((hdrop _).mpr ⟨s, by omega, hs2, rfl⟩))
      obtain ⟨a, ha⟩ := htailEven
      obtain ⟨b, hb⟩ := hmeven
      exact ⟨b - a, by omega⟩
    -- The odd path `p₂-⋯-pᵢ` contains an internal `Y₁` vertex.
    obtain ⟨s0, hs01, hs0t, hs0VC1⟩ : ∃ s, 1 < s ∧ s < tt ∧
        VertexComplete G (D s) {x : V | x ∈ q.dropLast} := by
      by_contra hcon
      push Not at hcon
      have heven := hRRarcIndex {x : V | x ∈ q.dropLast} hZ1C hZ1anti hzVC1
        1 tt (by omega) (by omega) (by omega) hp2VC1 httVC1
        (fun s hs1 hs2 => hcon s hs1 hs2)
        (fun s hs1 hs2 => hzC _ ((hdrop _).mpr ⟨s, by omega, by omega, rfl⟩))
      obtain ⟨a, ha⟩ := heven
      obtain ⟨b, hb⟩ := htteven
      omega
    have hs0VC2 : VertexComplete G (D s0) {x : V | x ∈ q.tail} := by
      rcases hcl1 s0 (by omega) (by omega) hs0VC1 with h | h
      · exact h
      · omega

    -- Mirror the last 2.2 application, on `z-p₁-p_m-⋯-pᵢ`.
    let A : List V := (OddWheelArc.arc C 0 tt m).reverse
    have hA : IsPathFrom G A (D 0) (D tt) := by
      dsimp [A]
      have h := OddWheelArc.arc_rev_isPathFrom hC hmpos hD hCm
        (show tt ≤ m by omega) (by omega)
      rw [hDmod0] at h
      exact h
    have hAlen : A.length = m - tt + 1 := by
      dsimp [A]
      rw [List.length_reverse, OddWheelArc.arc_length C 0 tt m (by omega)]
    have hzD0 : G.Adj z (D 0) :=
      hzQ _ (by rw [← hQ0]; exact List.getElem_mem (by omega))
    have hzA : z ∉ A := by
      intro hzmem
      exact hznotC (HoleBasics.mem_rotate_iff.mp
        (List.mem_of_mem_take (List.mem_reverse.mp hzmem)))
    have hzother : ∀ x ∈ A, x ≠ D 0 → ¬ G.Adj z x := by
      intro x hx hx0
      obtain ⟨s, hts, hsm, rfl⟩ :=
        (OddWheelArc.arc_mem_iff hC hmpos hD hCm (show tt ≤ m by omega)
          (by omega)).mp (List.mem_reverse.mp hx)
      have hsne : s ≠ m := fun hs => hx0 (by rw [hs, hDmod0])
      exact hzC _ ((hdrop _).mpr ⟨s, by omega, by omega, rfl⟩)
    have hP : IsPathFrom G (z :: A) z (D tt) :=
      PathAttach.isPathFrom_cons hA hzD0 hzA hzother
    have hPlen : pathLength (z :: A) = m - tt + 1 := by
      rw [pathLength]
      simp only [List.length_cons, hAlen]
      omega
    have hPout : ∀ w ∈ z :: A, w ∉ {x : V | x ∈ q} := by
      intro w hw hwq
      rcases List.mem_cons.mp hw with hwz | hwA
      · subst w
        exact G.irrefl (hzVC0 _ hwq)
      · exact hZ0C w hwq (HoleBasics.mem_rotate_iff.mp
          (List.mem_of_mem_take (List.mem_reverse.mp hwA)))
    have hPint : ∀ w ∈ SPGT.interior (z :: A),
        ¬ VertexComplete G w {x : V | x ∈ q} := by
      intro w hw hw0
      have hwi := (PathBasics.mem_interior_iff_of_pathFrom hP).mp hw
      have hwA : w ∈ A := by
        rcases List.mem_cons.mp hwi.1 with hwz | hwA
        · exact absurd hwz hwi.2.1
        · exact hwA
      obtain ⟨s, hts, hsm, rfl⟩ :=
        (OddWheelArc.arc_mem_iff hC hmpos hD hCm (show tt ≤ m by omega)
          (by omega)).mp (List.mem_reverse.mp hwA)
      have hsne : s ≠ tt := fun hs => hwi.2.2 (by rw [hs])
      by_cases hse : s = m
      · rw [hse, hDmod0] at hw0
        exact hp1nVC0 hw0
      · have hsVC2 : VertexComplete G (D s) {x : V | x ∈ q.tail} := by
          intro y hy
          exact hw0 y (List.mem_of_mem_tail hy)
        exact httmax s (by omega) (by omega) hsVC2
    have hs0VC0 : VertexComplete G (D s0) {x : V | x ∈ q} :=
      hbothVC0 _ hs0VC1 hs0VC2
    have hs0anti : ∀ w ∈ SPGT.interior (z :: A), ¬ G.Adj (D s0) w := by
      intro w hw hadj
      have hwi := (PathBasics.mem_interior_iff_of_pathFrom hP).mp hw
      have hwA : w ∈ A := by
        rcases List.mem_cons.mp hwi.1 with hwz | hwA
        · exact absurd hwz hwi.2.1
        · exact hwA
      obtain ⟨s, hts, hsm, rfl⟩ :=
        (OddWheelArc.arc_mem_iff hC hmpos hD hCm (show tt ≤ m by omega)
          (by omega)).mp (List.mem_reverse.mp hwA)
      have hsne : s ≠ tt := fun hs => hwi.2.2 (by rw [hs])
      by_cases hse : s = m
      · rw [hse, hDmod0] at hadj
        have := (radj (show s0 < m by omega) (show 0 < m by omega)).mp hadj
        omega
      · have := (radj (show s0 < m by omega) (show s < m by omega)).mp hadj
        omega
    have heven := even_path_of_complete_ends (z := D s0) hG hZ0anti hP hPout
      (by rw [hPlen]; omega) hzVC0 (hbothVC0 _ httVC1 httVC2) hPint hs0VC0 hs0anti
    rw [hPlen] at heven
    obtain ⟨a, ha⟩ := heven
    obtain ⟨b, hb⟩ := hmeven
    obtain ⟨c, hc⟩ := htteven
    omega

  ---------------------------------------------------------------------------
  -- The last paragraph of the paper.
  ---------------------------------------------------------------------------
  have final :
      (∀ t, 2 ≤ t → t < m →
        (VertexComplete G (D t) {x : V | x ∈ q.dropLast} ∨
          VertexComplete G (D t) {x : V | x ∈ q.tail}) →
        (t = 2 ∨ t = m - 1)) ∧
      ¬ ((VertexComplete G (D 2) {x : V | x ∈ q.dropLast} ∨
            VertexComplete G (D 2) {x : V | x ∈ q.tail}) ∧
          (VertexComplete G (D (m - 1)) {x : V | x ∈ q.dropLast} ∨
            VertexComplete G (D (m - 1)) {x : V | x ∈ q.tail})) := by
    by_cases hA : VertexComplete G (D 2) {x : V | x ∈ q.dropLast} ∧
        VertexComplete G (D 2) {x : V | x ∈ q.tail}
    · have hB : ¬ (VertexComplete G (D (m - 1)) {x : V | x ∈ q.dropLast} ∧
          VertexComplete G (D (m - 1)) {x : V | x ∈ q.tail}) :=
        fun h => hnotboth ⟨hA, h⟩
      have hno2 : ∀ t, 3 ≤ t → t < m →
          ¬ VertexComplete G (D t) {x : V | x ∈ q.tail} :=
        fun t ht3 htm ht => hB (hcl4 ⟨t, ht3, htm, ht⟩)
      constructor
      · intro t ht2 htm ht
        rcases ht with ht1 | ht2c
        · rcases hcl1 t ht2 htm ht1 with ht2' | hlast
          · exact Or.inl (by by_contra hne; exact hno2 t (by omega) htm ht2')
          · exact Or.inr hlast
        · exact Or.inl (by by_contra hne; exact hno2 t (by omega) htm ht2c)
      · rintro ⟨hP2, hPm⟩
        have hmVC1 : VertexComplete G (D (m - 1)) {x : V | x ∈ q.dropLast} := by
          rcases hPm with h | h
          · exact h
          · exact absurd h (hno2 (m - 1) (by omega) (by omega))
        have heven := hRRarcIndex {x : V | x ∈ q.dropLast} hZ1C hZ1anti hzVC1
          2 (m - 1) (by omega) (by omega) (by omega) hA.1 hmVC1
          (fun s hs1 hs2 hs => by
            rcases hcl1 s (by omega) (by omega) hs with hs' | hs'
            · exact hno2 s (by omega) (by omega) hs'
            · omega)
          (fun s hs1 hs2 => hzC _ ((hdrop _).mpr ⟨s, by omega, by omega, rfl⟩))
        obtain ⟨a, ha⟩ := heven
        obtain ⟨b, hb⟩ := hmeven
        omega
    · have hno1 : ∀ t, 2 ≤ t → t + 2 ≤ m →
          ¬ VertexComplete G (D t) {x : V | x ∈ q.dropLast} :=
        fun t ht2 htm ht => hA (hcl3 ⟨t, ht2, htm, ht⟩)
      constructor
      · intro t ht2 htm ht
        rcases ht with ht1 | ht2c
        · exact Or.inr (by by_contra hne; exact hno1 t ht2 (by omega) ht1)
        · rcases hcl2 t ht2 htm ht2c with ht1 | htfirst
          · exact Or.inr (by by_contra hne; exact hno1 t ht2 (by omega) ht1)
          · exact Or.inl htfirst
      · rintro ⟨hP2, hPm⟩
        have h2VC2 : VertexComplete G (D 2) {x : V | x ∈ q.tail} := by
          rcases hP2 with h | h
          · exact absurd h (hno1 2 (by omega) (by omega))
          · exact h
        have h2nVC1 : ¬ VertexComplete G (D 2) {x : V | x ∈ q.dropLast} :=
          hno1 2 (by omega) (by omega)
        have hmVC1 : VertexComplete G (D (m - 1)) {x : V | x ∈ q.dropLast} := by
          rcases hPm with h | h
          · exact h
          · rcases hcl2 (m - 1) (by omega) (by omega) h with h' | h'
            · exact h'
            · omega
        have hmnVC2 : ¬ VertexComplete G (D (m - 1)) {x : V | x ∈ q.tail} := by
          intro hmVC2
          have heven := hRRarcIndex {x : V | x ∈ q.tail} hZ2C hZ2anti hzVC2
            2 (m - 1) (by omega) (by omega) (by omega) h2VC2 hmVC2
            (fun s hs1 hs2 hs => by
              rcases hcl2 s (by omega) (by omega) hs with hs' | hs'
              · exact hno1 s (by omega) (by omega) hs'
              · omega)
            (fun s hs1 hs2 => hzC _ ((hdrop _).mpr ⟨s, by omega, by omega, rfl⟩))
          obtain ⟨a, ha⟩ := heven
          obtain ⟨b, hb⟩ := hmeven
          omega
        exact hantiK h2VC2 h2nVC1 hmVC1 hmnVC2

  obtain ⟨hmain, hmain2⟩ := final
  constructor
  · intro x hxC y hyC hx hy
    obtain ⟨t, ht2, htm, rfl⟩ := (hdrop x).mp hxC
    obtain ⟨s, hs2, hsm, rfl⟩ := (hdrop y).mp hyC
    rcases hmain t ht2 htm hx with ht | ht <;>
      rcases hmain s hs2 hsm hy with hs | hs
    · rw [ht, hs]
    · exact (hmain2 ⟨ht ▸ hx, hs ▸ hy⟩).elim
    · exact (hmain2 ⟨hs ▸ hy, ht ▸ hx⟩).elim
    · rw [ht, hs]
  · intro x hxC hx
    obtain ⟨t, ht2, htm, rfl⟩ := (hdrop x).mp hxC
    rcases hmain t ht2 htm hx with ht | ht
    · rw [ht]
      exact Or.inl hD2
    · rw [ht]
      exact Or.inr hDm


end SPGT

end Workspace.Statements.S03
