/-  GENERATED by scripts/split_statements.py from Workspace/Statements/S18.lean -- one numbered statement
    of the paper per module.  The theorem below, its doc-comment and its
    signature are byte-identical to the source module; only the surrounding
    file was mechanically re-cut.  See PROVING_PLAN.md.  -/
import Mathlib
import Workspace.Types.Core
import Workspace.Types.Tracks
import Workspace.Types.Appearances
import Workspace.Types.Pseudowheels
import Workspace.Types.Decompositions
import Workspace.Types.LongOddPrism
import Workspace.Types.Classes
import Workspace.ProofLemmas.Thm183Assembly

/-!
# Section 18 — Pseudowheels

The seven numbered statements 18.1 … 18.7 of Chudnovsky–Robertson–Seymour–Thomas,
*The Strong Perfect Graph Theorem* (published/Annals version, printed pages
109–116).  Source of the verbatim quotations: `paper/pdf/S18_Pseudowheels.md`,
`## Numbered statements`.

Every defined term used here already lives in an imported module; nothing is
restated:

* `Workspace.Types.Core` — `IsPathList`, `IsPathFrom`, `IsAntipathFrom`,
  `pathLength`, `SPGT.interior`, `VertexComplete`, `EdgeComplete`, `Complete`,
  `ConnectedSet`, `AnticonnectedSet`;
* `Workspace.Types.Tracks` — `IsTrackList` (§5's *track*: a **subgraph**, not
  necessarily induced), used in 18.1;
* `Workspace.Types.Appearances` — `attachments` (§5's *attachment*), used in 18.6;
* `Workspace.Types.Pseudowheels` — `IsPseudowheel`, `OptimalPseudowheel`;
* `Workspace.Types.Decompositions` — `AdmitsBalancedSkewPartition`;
* `Workspace.Types.LongOddPrism` — `Recalcitrant` (§13);
* `Workspace.Types.Classes` — `InF7`, `InF8` (the classes `F₇`, `F₈` of §1).

Encoding conventions (see `paper/spec/CONVENTIONS.md`):

* a *path* of the paper is the list `p : List V` of its vertices in order,
  together with `IsPathList G p`; its length is `pathLength p`, its interior is
  `SPGT.interior p` (always qualified — a bare `interior` is Mathlib's topological
  one), and `V(P)` is `{w : V | w ∈ p}`.  The paper's `n` is `p.length`;
* "`P` is a path of `G \ (X ∪ Y)`" is `IsPathList G p ∧ ∀ w ∈ p, w ∉ X ∪ Y`;
* **a subpath** of a path `P` is a contiguous block of the list, `q <:+: p`
  (`List.IsInfix`), which is automatically a path of `G` when it is non-null,
  since `P` is induced;
* **the number of `X`-complete edges of `P`.**  Paths of the paper are induced, so
  the edges of `P` are exactly the adjacent pairs of vertices of `P`, and their
  number is
  `{e : Sym2 V | ∃ u ∈ p, ∃ v ∈ p, e = s(u, v) ∧ EdgeComplete G X u v}.ncard` —
  a set of *unordered* pairs, so each edge is counted exactly once (the
  convention already used in `Workspace.Statements.S02`);
* the paper's `pₙ₋₁`, `pₙ₋₂` are written `pn1`, `pn2` (the subscript minus `₋` is
  not a Lean identifier character), pinned down by `p.dropLast.getLast?` and
  `p.dropLast.dropLast.getLast?`;
* "have the same parity" is `a % 2 = b % 2`.
-/

set_option autoImplicit false

namespace Workspace.Statements.S18

open Workspace.Types.Core Workspace.Types.Core.SPGT
open Workspace.Types.Tracks Workspace.Types.Tracks.SPGT
open Workspace.Types.Appearances Workspace.Types.Appearances.SPGT
open Workspace.Types.Pseudowheels Workspace.Types.Pseudowheels.SPGT
open Workspace.Types.Decompositions Workspace.Types.Decompositions.SPGT
open Workspace.Types.LongOddPrism Workspace.Types.LongOddPrism.SPGT
open Workspace.Types.Classes Workspace.Types.Classes.SPGT

namespace SPGT

variable {V : Type*} [Fintype V] [DecidableEq V]


/-- **18.3** (printed p. 110).

PAPER: *"Let `G ∈ F₇`, and let `X,Y` be disjoint nonempty anticonnected subsets of
`V(G)`, complete to each other.  Let `P` be a path `p₁`-`⋯`-`pₙ` of `G \ (X ∪ Y)`,
where `n ≥ 5`, such that `p₁,pₙ` are the only `X`-complete vertices of `P`.  Then
`P` has even length.  Assume that at least two vertices of `P` are `Y`-complete,
and let `P'` be a maximal subpath of `P` such that none of its internal vertices
are `Y`-complete.  Then the length of `P'` has the same parity as the number of
ends of `P'` that belong to `{p₁,pₙ}` and are not `Y`-complete.  Moreover, the
number of `Y`-complete edges of `P` has the same parity as the number of elements
of `{p₁,pₙ}` that are `Y`-complete."*

(Introduced by: *"We need the following extension of 2.3."*)

Encoding notes.

* The statement has three conclusions.  The first, *"`P` has even length"*, is
  unconditional.  The other two live under the sentence *"Assume that at least two
  vertices of `P` are `Y`-complete"*, whose scope extends through the closing
  *"Moreover …"* sentence; they are therefore the two conjuncts of an implication.
* *"a maximal subpath `P'` of `P` such that none of its internal vertices are
  `Y`-complete"* is universally quantified: `q` is a contiguous block of `p`
  (`q <:+: p`), it is a path with ends `a,b` (`IsPathFrom G q a b`), no vertex of
  `SPGT.interior q` is `Y`-complete, and `q` is maximal — every contiguous block
  `r` of `p` with the same property that contains `q` equals `q`.
* *"the number of ends of `P'` that belong to `{p₁,pₙ}` and are not `Y`-complete"*
  is the cardinality of `{w | (w = a ∨ w = b) ∧ (w = p₁ ∨ w = pₙ) ∧ ¬ w is
  Y-complete}`; taking a *set* of vertices makes a length-`0` subpath (where
  `a = b`) count once, as it should.
* For the edge-counting convention see the module docstring.

**ERRATUM (see `FIXES.md` §F7).**  The printed sentence

> *"let `P'` be a maximal subpath of `P` such that none of its internal vertices are
> `Y`-complete.  Then the length of `P'` has the same parity as the number of ends of `P'` that
> belong to `{p₁,pₙ}` and are not `Y`-complete."*

is **false as printed**, for lines of length `1`.  If `pᵢpᵢ₊₁` is a `Y`-complete edge of `P`
with `1 < i` and `i + 1 < n`, then `q = pᵢ-pᵢ₊₁` is a maximal subpath with no `Y`-complete
internal vertex (it has no internal vertex at all, and neither one-step extension is admissible,
since it would make `pᵢ` resp. `pᵢ₊₁` an internal `Y`-complete vertex).  Its length is `1`,
while the number of its ends that lie in `{p₁,pₙ}` **and are not `Y`-complete** is `0` — both
its ends are `Y`-complete.  The printed claim would read `1 ≡ 0 (mod 2)`.  Read literally it
forces `P` to have no `Y`-complete edge at all, contradicting 18.3's own closing paragraph
(*"`y` … the number of `Y`-complete edges in `P`"*) and 18.4 (*"`P` contains an odd number, at
least 3, of `Y`-complete edges"*).  The machine-checked refutation is
`ProofAttempts/thm_18_3/Claim2_Refutation.lean`.

The missing side condition is supplied by the paper's own proof, which carries it throughout:

> *"Let `P'` be a line of length `≥ 2`, and assume first that both ends of `P'` are
> `Y`-complete."*

and whose recap of the case analysis reads *"a line has odd length if and only if **either it
has length 1**, or one of its ends is one of `p₁, pₙ` and is not `Y`-complete."*  The second
conjunct below therefore carries the extra hypothesis `2 ≤ pathLength q`, which is exactly the
scope of the printed argument.  Conjuncts 1 and 3 are untouched; the closing counting paragraph
of 18.3 — and hence 18.4, the only consumer — uses the length-`1` case through its own recap,
not through this conjunct. -/
theorem thm_18_3 (G : SimpleGraph V) (hG : InF7 G) (X Y : Set V)
    (hXY : Disjoint X Y) (hXne : X.Nonempty) (hYne : Y.Nonempty)
    (hXa : AnticonnectedSet G X) (hYa : AnticonnectedSet G Y)
    (hcompl : Complete G X Y)
    (p : List V) (p₁ pₙ : V) (hp : IsPathList G p)
    (hpXY : ∀ w ∈ p, w ∉ X ∪ Y) (hn : 5 ≤ p.length)
    (hhead : p.head? = some p₁) (hlast : p.getLast? = some pₙ)
    (hXuniq : ∀ w ∈ p, (VertexComplete G w X ↔ (w = p₁ ∨ w = pₙ))) :
    Even (pathLength p) ∧
    (2 ≤ {w : V | w ∈ p ∧ VertexComplete G w Y}.ncard →
      ((∀ (q : List V) (a b : V), q <:+: p → IsPathFrom G q a b →
          (∀ w ∈ SPGT.interior q, ¬ VertexComplete G w Y) →
          (∀ r : List V, r <:+: p →
            (∀ w ∈ SPGT.interior r, ¬ VertexComplete G w Y) → q <:+: r → r = q) →
          2 ≤ pathLength q →
          pathLength q % 2 =
            {w : V | (w = a ∨ w = b) ∧ (w = p₁ ∨ w = pₙ) ∧
              ¬ VertexComplete G w Y}.ncard % 2) ∧
        {e : Sym2 V | ∃ u ∈ p, ∃ v ∈ p, e = s(u, v) ∧ EdgeComplete G Y u v}.ncard % 2 =
          {w : V | (w = p₁ ∨ w = pₙ) ∧ VertexComplete G w Y}.ncard % 2)) := by
  -- The printed proof is reproduced, step for step, in the `Thm183*` modules:
  -- *"it follows that `P` has even length, by 13.6"* — `Thm183EvenLength`;
  -- *"assume first that both ends of `P'` are `Y`-complete … `P'` has even length"* —
  -- `Thm183LineEvenCase`;
  -- *"an end of `P'` is not `Y`-complete … Consequently `P'` is odd"* —
  -- `Thm183LineOddCase` and `Thm183Lines.line_odd_of_first_end_not_YComplete`;
  -- *"the number of odd lines equals `y + z` … so `y, z` have the same parity"* —
  -- `Thm183Lines.yEdges_parity` (via `Thm183LineCounting`, `Thm183EdgeCount`).
  exact Workspace.ProofLemmas.Thm183Assembly.thm_18_3_full G hG X Y hXY hXne hYne hXa hYa
    hcompl p p₁ pₙ hp hpXY hn hhead hlast hXuniq


end SPGT

end Workspace.Statements.S18
