/-  GENERATED by scripts/split_statements.py from Workspace/Statements/S18.lean -- one numbered statement
    of the paper per module.  The theorem below, its doc-comment and its
    signature are byte-identical to the source module; only the surrounding
    file was mechanically re-cut.  See PROVING_PLAN.md.  -/
import Mathlib
import Workspace.Types.Core
import Workspace.Types.Tracks
import Workspace.Types.Appearances
import Workspace.Types.Pseudowheels
import Workspace.Types.Decompositions
import Workspace.Types.LongOddPrism
import Workspace.Types.Classes
import Workspace.Statements.S02.Thm_2_3
import Workspace.Statements.S13.Thm_13_6
import Workspace.Statements.S13.Thm_13_7
import Workspace.ProofLemmas.PathBasics
import Workspace.ProofLemmas.PathGlue
import Workspace.ProofLemmas.InducedPathExtraction
import Workspace.ProofLemmas.AntiholeCompletion
import Workspace.ProofLemmas.Thm182MaxIndex
import Workspace.ProofLemmas.Thm182EdgeSetTake
import Workspace.ProofLemmas.Thm182DropLastIndex

/-!
# Section 18 — Pseudowheels

The seven numbered statements 18.1 … 18.7 of Chudnovsky–Robertson–Seymour–Thomas,
*The Strong Perfect Graph Theorem* (published/Annals version, printed pages
109–116).  Source of the verbatim quotations: `paper/pdf/S18_Pseudowheels.md`,
`## Numbered statements`.

Every defined term used here already lives in an imported module; nothing is
restated:

* `Workspace.Types.Core` — `IsPathList`, `IsPathFrom`, `IsAntipathFrom`,
  `pathLength`, `SPGT.interior`, `VertexComplete`, `EdgeComplete`, `Complete`,
  `ConnectedSet`, `AnticonnectedSet`;
* `Workspace.Types.Tracks` — `IsTrackList` (§5's *track*: a **subgraph**, not
  necessarily induced), used in 18.1;
* `Workspace.Types.Appearances` — `attachments` (§5's *attachment*), used in 18.6;
* `Workspace.Types.Pseudowheels` — `IsPseudowheel`, `OptimalPseudowheel`;
* `Workspace.Types.Decompositions` — `AdmitsBalancedSkewPartition`;
* `Workspace.Types.LongOddPrism` — `Recalcitrant` (§13);
* `Workspace.Types.Classes` — `InF7`, `InF8` (the classes `F₇`, `F₈` of §1).

Encoding conventions (see `paper/spec/CONVENTIONS.md`):

* a *path* of the paper is the list `p : List V` of its vertices in order,
  together with `IsPathList G p`; its length is `pathLength p`, its interior is
  `SPGT.interior p` (always qualified — a bare `interior` is Mathlib's topological
  one), and `V(P)` is `{w : V | w ∈ p}`.  The paper's `n` is `p.length`;
* "`P` is a path of `G \ (X ∪ Y)`" is `IsPathList G p ∧ ∀ w ∈ p, w ∉ X ∪ Y`;
* **a subpath** of a path `P` is a contiguous block of the list, `q <:+: p`
  (`List.IsInfix`), which is automatically a path of `G` when it is non-null,
  since `P` is induced;
* **the number of `X`-complete edges of `P`.**  Paths of the paper are induced, so
  the edges of `P` are exactly the adjacent pairs of vertices of `P`, and their
  number is
  `{e : Sym2 V | ∃ u ∈ p, ∃ v ∈ p, e = s(u, v) ∧ EdgeComplete G X u v}.ncard` —
  a set of *unordered* pairs, so each edge is counted exactly once (the
  convention already used in `Workspace.Statements.S02`);
* the paper's `pₙ₋₁`, `pₙ₋₂` are written `pn1`, `pn2` (the subscript minus `₋` is
  not a Lean identifier character), pinned down by `p.dropLast.getLast?` and
  `p.dropLast.dropLast.getLast?`;
* "have the same parity" is `a % 2 = b % 2`.
-/

set_option autoImplicit false

namespace Workspace.Statements.S18

open Workspace.Types.Core Workspace.Types.Core.SPGT
open Workspace.Types.Tracks Workspace.Types.Tracks.SPGT
open Workspace.Types.Appearances Workspace.Types.Appearances.SPGT
open Workspace.Types.Pseudowheels Workspace.Types.Pseudowheels.SPGT
open Workspace.Types.Decompositions Workspace.Types.Decompositions.SPGT
open Workspace.Types.LongOddPrism Workspace.Types.LongOddPrism.SPGT
open Workspace.Types.Classes Workspace.Types.Classes.SPGT

namespace SPGT

variable {V : Type*} [Fintype V] [DecidableEq V]


/-- **18.2** (printed p. 110).

PAPER: *"Let `G ∈ F₇`, and let `X,Y` be disjoint nonempty anticonnected subsets of
`V(G)`, complete to each other.  Let `P` be a path in `G` with even length `> 0`,
with vertices `p₁,…,pₙ` in order, such that `p₁` is `X`-complete, `pₙ` is not
`X`-complete and `pₙ` is the unique `Y`-complete vertex of `P`.  Suppose that
there is a `Y`-complete vertex in `G` nonadjacent to both `pₙ₋₁,pₙ₋₂`.  Then
either:*

* *there is an odd number of `X`-complete edges in `P`, or*

* *`n = 3` and there is an odd antipath joining `pₙ₋₁` and `pₙ` with interior in
  `X`."*

(Introduced by: *"There is a reformulation of 13.7 that we sometimes need:"*)

Encoding notes.

* `P` is a path **in `G`** here — the paper does *not* write "in `G \ (X ∪ Y)`" in
  this statement, and that is transcribed as printed.
* Even length `> 0` forces `n ≥ 3`, so `pₙ₋₁` and `pₙ₋₂` exist; they are `pn1` and
  `pn2`.
* *"`n = 3`"* is `p.length = 3` (`n` is the number of vertices). -/
theorem thm_18_2 (G : SimpleGraph V) (hG : InF7 G) (X Y : Set V)
    (hXY : Disjoint X Y) (hXne : X.Nonempty) (hYne : Y.Nonempty)
    (hXa : AnticonnectedSet G X) (hYa : AnticonnectedSet G Y)
    (hcompl : Complete G X Y)
    (p : List V) (p₁ pn2 pn1 pₙ : V) (hp : IsPathList G p)
    (heven : Even (pathLength p)) (hpos : 0 < pathLength p)
    (hhead : p.head? = some p₁) (hlast : p.getLast? = some pₙ)
    (hlast1 : p.dropLast.getLast? = some pn1)
    (hlast2 : p.dropLast.dropLast.getLast? = some pn2)
    (hp₁X : VertexComplete G p₁ X) (hpₙX : ¬ VertexComplete G pₙ X)
    (hYuniq : ∀ w ∈ p, (VertexComplete G w Y ↔ w = pₙ))
    (hvy : ∃ v : V, VertexComplete G v Y ∧ ¬ G.Adj v pn1 ∧ ¬ G.Adj v pn2) :
    Odd {e : Sym2 V | ∃ u ∈ p, ∃ v ∈ p, e = s(u, v) ∧ EdgeComplete G X u v}.ncard ∨
    (p.length = 3 ∧ ∃ q : List V, IsAntipathFrom G q pn1 pₙ ∧ Odd (pathLength q) ∧
      ∀ w ∈ SPGT.interior q, w ∈ X) := by
  classical
  let E : Set (Sym2 V) :=
    {e : Sym2 V | ∃ u ∈ p, ∃ v ∈ p, e = s(u, v) ∧ EdgeComplete G X u v}
  by_cases hEodd : Odd E.ncard
  · exact Or.inl hEodd
  right
  have hBerge : Berge G := hG.1.1.1.1
  have hF5 : InF5 G := hG.1.1
  have hplen : pathLength p = p.length - 1 :=
    Workspace.ProofLemmas.PathBasics.pathLength_eq p
  have hplen2 : 2 ≤ pathLength p := by
    obtain ⟨k, hk⟩ := heven
    omega
  have hlen3 : 3 ≤ p.length := by omega
  have h0lt : 0 < p.length := by omega
  have hnlt : p.length - 1 < p.length := by omega
  have hp0 : p[0]'h0lt = p₁ :=
    Workspace.ProofLemmas.PathBasics.getElem_zero_of_head? hhead h0lt
  have hpLast : p[p.length - 1]'hnlt = pₙ :=
    Workspace.ProofLemmas.PathBasics.getElem_last_of_getLast? hlast h0lt
  have hp₁mem : p₁ ∈ p := Workspace.ProofLemmas.PathBasics.head_mem hhead
  have hpₙmem : pₙ ∈ p := Workspace.ProofLemmas.PathBasics.getLast_mem hlast
  have hendsNotAdj : ¬ G.Adj p₁ pₙ := by
    rw [← hp0, ← hpLast]
    exact Workspace.ProofLemmas.PathBasics.path_ends_not_adj hp hlen3
  have hpX : ∀ w ∈ p, w ∉ X := by
    intro w hw hwX
    have hwY : VertexComplete G w Y := hcompl w hwX
    have hwn : w = pₙ := (hYuniq w hw).mp hwY
    exact hendsNotAdj (hwn ▸ hp₁X w hwX)
  have h0X : VertexComplete G (p[0]'h0lt) X := by simpa [hp0] using hp₁X
  obtain ⟨m, hm, hmX, hmax⟩ :=
    Workspace.ProofLemmas.Thm182MaxIndex.exists_max_complete_index G X p h0lt h0X
  have hmlast : m < p.length - 1 := by
    have hmle : m ≤ p.length - 1 := by omega
    by_contra hnot
    have hmeq : m = p.length - 1 := by omega
    apply hpₙX
    have heq : p[m]'hm = pₙ := by
      rw [← hpLast]
      congr
    exact heq ▸ hmX
  have hEeven : Even E.ncard := Nat.not_odd_iff_even.mp hEodd
  have hEeq : E =
      {e : Sym2 V | ∃ u ∈ p.take (m + 1), ∃ v ∈ p.take (m + 1),
        e = s(u, v) ∧ EdgeComplete G X u v} := by
    exact Workspace.ProofLemmas.Thm182EdgeSetTake.xed_eq_take G X p m hm hmax
  have hprefixEven : Even
      {e : Sym2 V | ∃ u ∈ p.take (m + 1), ∃ v ∈ p.take (m + 1),
        e = s(u, v) ∧ EdgeComplete G X u v}.ncard := by
    rw [← hEeq]
    exact hEeven
  rcases Nat.even_or_odd m with hmEven | hmOdd
  · -- The last `X`-complete vertex has odd paper-index.  Apply 13.7 to the tail.
    let t : List V := (p.drop m).take ((p.length - 1) - m + 1)
    have htFrom₀ := Workspace.ProofLemmas.PathBasics.isPathFrom_slice hp hmlast hnlt
    have htFrom : IsPathFrom G t (p[m]'hm) pₙ := by
      simpa [t, hpLast] using htFrom₀
    have htlen : t.length = (p.length - 1) - m + 1 := by
      exact Workspace.ProofLemmas.PathBasics.length_slice p (le_of_lt hmlast) hnlt
    have htplen : pathLength t = pathLength p - m := by
      rw [Workspace.ProofLemmas.PathBasics.pathLength_eq, htlen, hplen]
      omega
    have hteven : Even (pathLength t) := by
      rw [Nat.even_iff] at heven hmEven ⊢
      rw [htplen]
      omega
    have htpos : 0 < pathLength t := by rw [htplen]; omega
    have htXuniq : ∀ u ∈ t, (VertexComplete G u X ↔ u = p[m]'hm) := by
      intro u hu
      obtain ⟨k, hk, hmk, hklast, hku⟩ :=
        (Workspace.ProofLemmas.PathBasics.mem_slice_iff p (le_of_lt hmlast) hnlt).mp hu
      constructor
      · intro huX
        have hkm : k ≤ m := hmax k hk (hku ▸ huX)
        have hkeq : k = m := by omega
        subst k
        exact hku.symm
      · intro hueq
        rw [hueq]
        exact hmX
    have htYuniq : ∀ u ∈ t, (VertexComplete G u Y ↔ u = pₙ) := by
      intro u hu
      apply hYuniq u
      exact List.drop_subset _ _ (List.take_subset _ _ hu)
    have h137 := _root_.Workspace.Statements.S13.SPGT.thm_13_7 G hF5 X Y hXY hXne hYne
        hXa hYa hcompl t (p[m]'hm) pₙ htFrom.1 hteven htpos htFrom.2.1 htFrom.2.2
        htXuniq htYuniq
    rcases h137 with ⟨htwo, hrest⟩
    rcases hrest with ⟨c, htshape, hrest⟩
    rcases hrest with ⟨Q, R, hQrest, hRrest, hxor⟩
    rcases hQrest with ⟨hQ, hQint⟩
    rcases hRrest with ⟨hR, hRint⟩
    have hmidx : m = p.length - 3 := by rw [htplen] at htwo; omega
    have hpn2idx : p[p.length - 3]'(by omega) = pn2 := by
      have h := hlast2
      rw [Workspace.ProofLemmas.Thm182DropLastIndex.dropLast_dropLast_getLast?_eq p hlen3]
        at h
      exact Option.some.inj h
    have hpn1idx : p[p.length - 2]'(by omega) = pn1 := by
      have h := hlast1
      rw [Workspace.ProofLemmas.Thm182DropLastIndex.dropLast_getLast?_eq p (by omega)] at h
      exact Option.some.inj h
    have hpm : p[m]'hm = pn2 := by
      rw [← hpn2idx]
      congr
    have h1t : 1 < t.length := by rw [htlen]; omega
    have hcidx : c = p[p.length - 2]'(by omega) := by
      have hget : t[1]'h1t = p[p.length - 2]'(by omega) :=
        Workspace.ProofLemmas.PathBasics.getElem_slice' p h1t (by omega) (by omega)
      simpa [htshape] using hget
    have hc : c = pn1 := hcidx.trans hpn1idx
    have hQ' : IsAntipathFrom G Q pn1 pₙ := by simpa [hc] using hQ
    have hR' : IsAntipathFrom G R pn2 pn1 := by simpa [hpm, hc] using hR
    have hadj21 : G.Adj pn2 pn1 := by
      rw [← hpn2idx, ← hpn1idx]
      convert Workspace.ProofLemmas.PathBasics.path_adj_succ hp (i := p.length - 3) (by omega)
        using 1 <;> congr <;> omega
    obtain ⟨v, hvY, hvn1, hvn2⟩ := hvy
    have hvne2 : v ≠ pn2 := by
      intro h
      subst v
      exact hvn1 hadj21
    have hvne1 : v ≠ pn1 := by
      intro h
      subst v
      exact hvn2 hadj21.symm
    have hReven : Even (pathLength R) :=
      Workspace.ProofLemmas.AntiholeCompletion.even_pathLength_of_witness hBerge
        hadj21 hvY hvn2 hvn1 hvne2 hvne1 hR' hRint
    have hQodd : Odd (pathLength Q) := by
      rcases hxor with ⟨hQo, -⟩ | ⟨hRo, -⟩
      · exact hQo
      · rw [Nat.even_iff] at hReven
        rw [Nat.odd_iff] at hRo
        omega
    have hlenEq : p.length = 3 := by
      by_contra hne
      have hlen4 : 4 ≤ p.length := by omega
      have hadj1n : G.Adj pn1 pₙ := by
        rw [← hpn1idx, ← hpLast]
        convert Workspace.ProofLemmas.PathBasics.path_adj_succ hp (i := p.length - 2) (by omega)
          using 1 <;> congr <;> omega
      have hp1n1 : ¬ G.Adj p₁ pn1 := by
        rw [← hp0, ← hpn1idx]
        exact Workspace.ProofLemmas.PathBasics.path_not_adj_of_gap hp (by omega) (by omega)
          (by omega) (by omega)
      have hp1n : ¬ G.Adj p₁ pₙ := hendsNotAdj
      have hp1ne1 : p₁ ≠ pn1 := by
        rw [← hp0, ← hpn1idx]
        exact Workspace.ProofLemmas.PathBasics.path_ne_of_ne_index hp (by omega) (by omega)
          (by omega)
      have hp1nen : p₁ ≠ pₙ := by
        rw [← hp0, ← hpLast]
        exact Workspace.ProofLemmas.PathBasics.path_ne_of_ne_index hp (by omega) (by omega)
          (by omega)
      have hQeven : Even (pathLength Q) :=
        Workspace.ProofLemmas.AntiholeCompletion.even_pathLength_of_witness hBerge
          hadj1n hp₁X hp1n1 hp1n hp1ne1 hp1nen hQ' hQint
      rw [Nat.even_iff] at hQeven
      rw [Nat.odd_iff] at hQodd
      omega
    exact ⟨hlenEq, Q, hQ', hQodd, hQint⟩
  · -- The contrary parity yields the odd-prefix case of the printed proof.
    exfalso
    have hmpos : 0 < m := by
      rw [Nat.odd_iff] at hmOdd
      omega
    let q : List V := p.take (m + 1)
    have hqFrom₀ := Workspace.ProofLemmas.PathBasics.isPathFrom_slice hp hmpos hm
    have hqFrom : IsPathFrom G q p₁ (p[m]'hm) := by
      simpa [q, hp0] using hqFrom₀
    have hqlen : q.length = m + 1 := by simp [q]; omega
    have hqplen : pathLength q = m := by
      rw [Workspace.ProofLemmas.PathBasics.pathLength_eq, hqlen]
      omega
    have hqodd : Odd (pathLength q) := by simpa [hqplen] using hmOdd
    have hqpar :=
      (_root_.Workspace.Statements.S02.SPGT.thm_2_3 G hBerge X hXa p (Or.inl hp) hpX).1
        q p₁ (p[m]'hm)
        (Or.inl ⟨hp, (List.take_prefix (m + 1) p).isInfix⟩) hqFrom hp₁X hmX
    have honly : ∀ w ∈ p, VertexComplete G w X → w = p₁ ∨ w = p[m]'hm := by
      rcases hqpar with hpar | honly
      · have hpreMod :
            {e : Sym2 V | ∃ u ∈ q, ∃ v ∈ q,
              e = s(u, v) ∧ EdgeComplete G X u v}.ncard % 2 = 0 := by
          simpa [q] using Nat.even_iff.mp hprefixEven
        have hqMod : pathLength q % 2 = 1 := Nat.odd_iff.mp hqodd
        exfalso
        simpa [q] using (show False by omega)
      · exact honly
    have hXsub : X ⊆ {v : V | v ∈ q}ᶜ := by
      intro x hx hxq
      exact hpX x (List.take_subset _ _ hxq) hx
    rcases _root_.Workspace.Statements.S13.SPGT.thm_13_6 G hF5 q p₁ (p[m]'hm)
        hqFrom hqodd X hXsub hXa hp₁X hmX with hedge | hshort
    · obtain ⟨u, huq, v, hvq, hEdge⟩ := hedge
      have hup : u ∈ p := List.take_subset _ _ huq
      have hvp : v ∈ p := List.take_subset _ _ hvq
      have hadjEnds : G.Adj p₁ (p[m]'hm) := by
        rcases honly u hup hEdge.2.1 with hu | hu <;>
          rcases honly v hvp hEdge.2.2 with hv | hv
        · rw [hu, hv] at hEdge
          exact False.elim (G.irrefl hEdge.1)
        · simpa [hu, hv] using hEdge.1
        · simpa [hu, hv] using hEdge.1.symm
        · rw [hu, hv] at hEdge
          exact False.elim (G.irrefl hEdge.1)
      have hset :
          {e : Sym2 V | ∃ a ∈ q, ∃ b ∈ q,
            e = s(a, b) ∧ EdgeComplete G X a b} = {s(p₁, p[m]'hm)} := by
        ext e
        constructor
        · rintro ⟨a, haq, b, hbq, rfl, hEc⟩
          simp only [Set.mem_singleton_iff]
          have hap : a ∈ p := List.take_subset _ _ haq
          have hbp : b ∈ p := List.take_subset _ _ hbq
          rcases honly a hap hEc.2.1 with ha | ha <;>
            rcases honly b hbp hEc.2.2 with hb | hb
          · rw [ha, hb] at hEc
            exact False.elim (G.irrefl hEc.1)
          · simp [ha, hb]
          · simpa [ha, hb] using Sym2.eq_swap (p₁, p[m]'hm)
          · rw [ha, hb] at hEc
            exact False.elim (G.irrefl hEc.1)
        · intro he
          simp only [Set.mem_singleton_iff] at he
          subst e
          exact ⟨p₁, (Workspace.ProofLemmas.PathBasics.isPathFrom_ends_mem hqFrom).1,
            p[m]'hm, (Workspace.ProofLemmas.PathBasics.isPathFrom_ends_mem hqFrom).2,
            rfl, hadjEnds, hp₁X, hmX⟩
      have hbad : Even (1 : ℕ) := by
        rw [← Set.ncard_singleton (s(p₁, p[m]'hm)), ← hset]
        simpa [q] using hprefixEven
      norm_num [Nat.even_iff] at hbad
    · obtain ⟨hq3, c, d, hinter, Q, hQ, hQodd, hQint⟩ := hshort
      have hm3 : m = 3 := by rw [hqplen] at hq3; omega
      have hlen5 : 5 ≤ p.length := by omega
      have hq4 : q.length = 4 := by omega
      obtain ⟨a, b, c', d', hshape⟩ :=
        Workspace.ProofLemmas.PathGlue.length_eq_four hq4
      have hinter' : [b, c'] = [c, d] := by
        rw [hshape] at hinter
        simpa [SPGT.interior] using hinter
      have hbc : b = c := by simpa using congrArg List.head? hinter'
      have hcd : c' = d := by
        have := congrArg List.tail hinter'
        simpa using this
      have hbidx : b = p[1]'(by omega) := by
        have hget : q[1]'(by omega) = p[1]'(by omega) := by simp [q]
        simpa [hshape] using hget
      have hcidx : c' = p[2]'(by omega) := by
        have hget : q[2]'(by omega) = p[2]'(by omega) := by simp [q]
        simpa [hshape] using hget
      have hc : c = p[1]'(by omega) := hbc.symm.trans hbidx
      have hd : d = p[2]'(by omega) := hcd.symm.trans hcidx
      have hcp : c ∈ p := by rw [hc]; exact List.getElem_mem (by omega)
      have hdp : d ∈ p := by rw [hd]; exact List.getElem_mem (by omega)
      have hcX : c ∉ X := hpX c hcp
      have hdX : d ∉ X := hpX d hdp
      have hcY : c ∉ Y := by
        intro hcy
        have hccomp : VertexComplete G c X := fun x hx => (hcompl x hx c hcy).symm
        rcases honly c hcp hccomp with h | h
        · rw [hc, ← hp0] at h
          exact Workspace.ProofLemmas.PathBasics.path_ne_of_ne_index hp (by omega) (by omega)
            (by omega) h.symm
        · rw [hc] at h
          exact Workspace.ProofLemmas.PathBasics.path_ne_of_ne_index hp (by omega) hm
            (by omega) h
      have hdY : d ∉ Y := by
        intro hdy
        have hdcomp : VertexComplete G d X := fun x hx => (hcompl x hx d hdy).symm
        rcases honly d hdp hdcomp with h | h
        · rw [hd, ← hp0] at h
          exact Workspace.ProofLemmas.PathBasics.path_ne_of_ne_index hp (by omega) (by omega)
            (by omega) h.symm
        · rw [hd] at h
          exact Workspace.ProofLemmas.PathBasics.path_ne_of_ne_index hp (by omega) hm
            (by omega) h
      have hcNotComplete : ¬ VertexComplete G c Y := by
        intro h
        have := (hYuniq c hcp).mp h
        rw [hc, ← hpLast] at this
        exact Workspace.ProofLemmas.PathBasics.path_ne_of_ne_index hp (by omega) (by omega)
          (by omega) this
      have hdNotComplete : ¬ VertexComplete G d Y := by
        intro h
        have := (hYuniq d hdp).mp h
        rw [hd, ← hpLast] at this
        exact Workspace.ProofLemmas.PathBasics.path_ne_of_ne_index hp (by omega) (by omega)
          (by omega) this
      have hcMiss : ∃ y ∈ Y, ¬ G.Adj c y := by
        by_contra h
        push Not at h
        exact hcNotComplete h
      have hdMiss : ∃ y ∈ Y, ¬ G.Adj d y := by
        by_contra h
        push Not at h
        exact hdNotComplete h
      obtain ⟨R, hR, hRint⟩ :=
        Workspace.ProofLemmas.InducedPathExtraction.exists_antipath_interior_in hYa
          hcY hdY hcMiss hdMiss
      have hadjcd : G.Adj c d := by
        rw [hc, hd]
        exact Workspace.ProofLemmas.PathBasics.path_adj_succ hp (i := 1) (by omega)
      have hpₙY : VertexComplete G pₙ Y := (hYuniq pₙ hpₙmem).mpr rfl
      have hpₙc : ¬ G.Adj pₙ c := by
        rw [hc, ← hpLast]
        exact Workspace.ProofLemmas.PathBasics.path_not_adj_of_gap hp (by omega) (by omega)
          (by omega) (by omega)
      have hpₙd : ¬ G.Adj pₙ d := by
        rw [hd, ← hpLast]
        exact Workspace.ProofLemmas.PathBasics.path_not_adj_of_gap hp (by omega) (by omega)
          (by omega) (by omega)
      have hpₙnec : pₙ ≠ c := by
        rw [hc, ← hpLast]
        exact Workspace.ProofLemmas.PathBasics.path_ne_of_ne_index hp (by omega) (by omega)
          (by omega)
      have hpₙned : pₙ ≠ d := by
        rw [hd, ← hpLast]
        exact Workspace.ProofLemmas.PathBasics.path_ne_of_ne_index hp (by omega) (by omega)
          (by omega)
      have hReven : Even (pathLength R) :=
        Workspace.ProofLemmas.AntiholeCompletion.even_pathLength_of_witness hBerge
          hadjcd hpₙY hpₙc hpₙd hpₙnec hpₙned hR hRint
      have hsumEven : Even (pathLength R + pathLength Q) :=
        Workspace.ProofLemmas.AntiholeCompletion.even_add_pathLength_of_two_antipaths hBerge
          hXY hcompl hadjcd hcX hdX hcY hdY hR hRint hQ hQint
      rw [Nat.even_iff] at hReven hsumEven
      rw [Nat.odd_iff] at hQodd
      omega


end SPGT

end Workspace.Statements.S18
