/-  GENERATED by scripts/split_statements.py from Workspace/Statements/S18.lean -- one numbered statement
    of the paper per module.  The theorem below, its doc-comment and its
    signature are byte-identical to the source module; only the surrounding
    file was mechanically re-cut.  See PROVING_PLAN.md.  -/
import Mathlib
import Workspace.Types.Core
import Workspace.Types.Tracks
import Workspace.Types.Appearances
import Workspace.Types.Pseudowheels
import Workspace.Types.Decompositions
import Workspace.Types.LongOddPrism
import Workspace.Types.Classes
import Workspace.ProofLemmas.Thm185Singleton

/-!
# Section 18 — Pseudowheels

The seven numbered statements 18.1 … 18.7 of Chudnovsky–Robertson–Seymour–Thomas,
*The Strong Perfect Graph Theorem* (published/Annals version, printed pages
109–116).  Source of the verbatim quotations: `paper/pdf/S18_Pseudowheels.md`,
`## Numbered statements`.

Every defined term used here already lives in an imported module; nothing is
restated:

* `Workspace.Types.Core` — `IsPathList`, `IsPathFrom`, `IsAntipathFrom`,
  `pathLength`, `SPGT.interior`, `VertexComplete`, `EdgeComplete`, `Complete`,
  `ConnectedSet`, `AnticonnectedSet`;
* `Workspace.Types.Tracks` — `IsTrackList` (§5's *track*: a **subgraph**, not
  necessarily induced), used in 18.1;
* `Workspace.Types.Appearances` — `attachments` (§5's *attachment*), used in 18.6;
* `Workspace.Types.Pseudowheels` — `IsPseudowheel`, `OptimalPseudowheel`;
* `Workspace.Types.Decompositions` — `AdmitsBalancedSkewPartition`;
* `Workspace.Types.LongOddPrism` — `Recalcitrant` (§13);
* `Workspace.Types.Classes` — `InF7`, `InF8` (the classes `F₇`, `F₈` of §1).

Encoding conventions (see `paper/spec/CONVENTIONS.md`):

* a *path* of the paper is the list `p : List V` of its vertices in order,
  together with `IsPathList G p`; its length is `pathLength p`, its interior is
  `SPGT.interior p` (always qualified — a bare `interior` is Mathlib's topological
  one), and `V(P)` is `{w : V | w ∈ p}`.  The paper's `n` is `p.length`;
* "`P` is a path of `G \ (X ∪ Y)`" is `IsPathList G p ∧ ∀ w ∈ p, w ∉ X ∪ Y`;
* **a subpath** of a path `P` is a contiguous block of the list, `q <:+: p`
  (`List.IsInfix`), which is automatically a path of `G` when it is non-null,
  since `P` is induced;
* **the number of `X`-complete edges of `P`.**  Paths of the paper are induced, so
  the edges of `P` are exactly the adjacent pairs of vertices of `P`, and their
  number is
  `{e : Sym2 V | ∃ u ∈ p, ∃ v ∈ p, e = s(u, v) ∧ EdgeComplete G X u v}.ncard` —
  a set of *unordered* pairs, so each edge is counted exactly once (the
  convention already used in `Workspace.Statements.S02`);
* the paper's `pₙ₋₁`, `pₙ₋₂` are written `pn1`, `pn2` (the subscript minus `₋` is
  not a Lean identifier character), pinned down by `p.dropLast.getLast?` and
  `p.dropLast.dropLast.getLast?`;
* "have the same parity" is `a % 2 = b % 2`.
-/

set_option autoImplicit false

namespace Workspace.Statements.S18

open Workspace.Types.Core Workspace.Types.Core.SPGT
open Workspace.Types.Tracks Workspace.Types.Tracks.SPGT
open Workspace.Types.Appearances Workspace.Types.Appearances.SPGT
open Workspace.Types.Pseudowheels Workspace.Types.Pseudowheels.SPGT
open Workspace.Types.Decompositions Workspace.Types.Decompositions.SPGT
open Workspace.Types.LongOddPrism Workspace.Types.LongOddPrism.SPGT
open Workspace.Types.Classes Workspace.Types.Classes.SPGT

namespace SPGT

variable {V : Type*} [Fintype V] [DecidableEq V]


/-- **18.5** (printed p. 111).

PAPER: *"Let `G ∈ F₇`, and let `(X,Y,P)` be an optimal pseudowheel in `G`, where
`P` is `p₁`-`⋯`-`pₙ`.  Let `v ∈ V(G) \ (X ∪ Y ∪ V(P))`, not `Y`-complete.  Then
there is a subpath `P'` of `P` such that*

* *`V(P')` contains all the neighbours of `v` in `P`,*

* *there is no `Y`-complete vertex in the interior of `P'`, and*

* *if `v` is `X`-complete, then either `V(P') = {p₁}`, or `pₙ ∈ V(P')`."*

Encoding notes.

* `p₁` and `pₙ` are the first and last vertices of `P`, named by `hhead`/`hlast`.
* *"a subpath `P'` of `P`"* is a contiguous block `q <:+: P` which is a path
  (`IsPathList G q`, so in particular non-null — the empty list is not a path of
  the paper). -/
theorem thm_18_5 (G : SimpleGraph V) (hG : InF7 G) (X Y : Set V) (P : List V)
    (p₁ pₙ : V) (hopt : OptimalPseudowheel G X Y P)
    (hhead : P.head? = some p₁) (hlast : P.getLast? = some pₙ)
    (v : V) (hvXY : v ∉ X ∪ Y) (hvP : v ∉ P) (hvY : ¬ VertexComplete G v Y) :
    ∃ q : List V, IsPathList G q ∧ q <:+: P ∧
      (∀ w ∈ P, G.Adj v w → w ∈ q) ∧
      (∀ w ∈ SPGT.interior q, ¬ VertexComplete G w Y) ∧
      (VertexComplete G v X → ({w : V | w ∈ q} = {p₁} ∨ pₙ ∈ q)) := by
  exact Scratch186Singleton.singleton_good G hG X Y P p₁ pₙ v hopt hhead hlast
    hvXY hvP hvY


end SPGT

end Workspace.Statements.S18
